monitor.stream-restore.rules = [
  {
    matches = [
      {
        application.name = "Firefox"
      }
    ]
    actions = {
      update-props = {
        module-stream-restore.id = "sink-input-by-application-name:Firefox"
      }
    }
  }
]
