---
- name: 'gak_qbittorrent: Ensure application state mount directories exist'
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ gak_qbittorrent_dir }}'
    - '{{ gak_qbittorrent_dir }}/config'
  tags: ['gak-qbittorrent-config']

- name: 'gak_qbittorrent: Deploy the Compose project'
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: '{{ gak_qbittorrent_dir }}/compose.yaml'
    mode: '0644'
  tags: ['gak-qbittorrent-config', 'gak-compose-config']
