#+TITLE: SSH config & setup
* User config
:PROPERTIES:
:header-args:conf: :tangle ~/.ssh/config :tangle-mode o600
:CUSTOM_ID: orgid-npmhvi
:END:

- [[https://stackoverflow.com/questions/3466626/how-to-permanently-add-a-private-key-with-ssh-add-on-ubuntu/4246809#4246809][How to permanently add a private key with ssh-add on Ubuntu? - Stack Overflow]]
  # [2022-04-07 Thu 22:59:01]
- [[https://chat.openai.com/share/fdc72cef-2d5c-4517-8368-6df37615ef90][Auto-add SSH key - ChatGPT]]

#+begin_src conf
Host alarm
     User alarm
     Port 1111
     Hostname alarm # resolved by /etc/hosts
     IdentityFile ~/.ssh/local2alarm

Host *
     ServerAliveInterval 5
     AddKeysToAgent yes # man ssh_config | sed -n '/AddKeysToAgent/,/^$/p'

Host aur.archlinux.org
     IdentityFile ~/.ssh/aur
     User aur

Host codeberg.org
     IdentityFile ~/.ssh/git-upstream-winr58
     IdentityFile ~/.ssh/git-dotfiles

Host github.com
     IdentityFile ~/.ssh/github
     IdentityFile ~/.ssh/git-upstream-push

# # Arch WSL
# Host localhost
#      User lobo
#      IdentityFile ~/.ssh/id_ed25519
#+end_src

* ~/etc/ssh/sshd_config.d/~
:PROPERTIES:
:tangle-dir: /sudo::/etc/ssh/sshd_config.d
:header-args: :cache yes
:END:
- [[https://linuxconfig.org/how-to-change-ssh-port-on-linux][How to change SSH port on Linux - Linux Tutorials - Learn Linux Configuration]]
  # [2022-04-02 Sat 14:21:35]
- [[https://www.cyberciti.biz/faq/how-to-disable-ssh-password-login-on-linux/][How to disable ssh password login on Linux to increase security - nixCraft]]
  # [2022-12-22 Thu 13:56:27 -03]

** 50-disable-password-and-root.conf

This is the sshd server system-wide configuration file.  See
=sshd_config(5)= for more information.
#+begin_src conf :tangle (tdir "/50-disable-password-and-root-login.conf") :cache yes
PermitRootLogin no
PasswordAuthentication no
ChallengeResponseAuthentication no
#+end_src

** 50-port.conf
# #TODO-privacy-garantism
#+begin_src conf :tangle (tdir "/50-port.conf") :cache yes
Port 1111
#+end_src

* Notes
** SSH login without password
- See
  + [[https://www.pragmaticlinux.com/2021/05/configure-ssh-for-login-without-a-password/][Configure SSH for login without a password - PragmaticLinux]]
# [2022-04-07 Thu 01:31:09]

Generate private/public key pair on local PC.
#+begin_src shell
cd ~/.ssh
# Enter a filename and optionally a passphrase
ssh-keygen
# I gave the filename of 'id_rsa_alarm'
#+end_src

Add the private key to keyring
#+begin_src shell
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa_alarm
#+end_src
- or set a host to a private key file using the config file, see
  [[#orgid-npmhvi][User config]].

- *NOTE*: If the error "=hostname@ip: Permission denied (publickey).=" is given, add
  the private key to the keyring again by repeating the previous step.

Then use the helper program to copy to destination server
#+begin_src shell
ssh-copy-id -i id_rsa_alarm.pub -p 1111 alarm@alarm
#+end_src
*** Allow SSH onto the local PC / Reverse allow
Likewise, to allow SSh access but 'in reverse', add the public key from the
origin to the local PC using the =authorized_keys=:
: ~/.ssh/authorized_keys
# [2022-12-24 Sat 19:51:36 -03]

*** Security
[[https://www.pragmaticlinux.com/2021/05/configure-ssh-for-login-without-a-password/][Further on the same article]] there are some settings to be changed on
the =/etc/ssh/sshd_config= file.
#+begin_example
PermitRootLogin no
PasswordAuthentication no
ChallengeResponseAuthentication no
#+end_example
This makes ssh connections only work via keys previously
authorized. An extra configuration change might also be changing the
port to a non-standard one with e.g. =Port 1234=. Make sure to provide
the custom port when connecting via the command line with =-p 1234= or
via =Port 1234= under a host definition in =~/.ssh/config=.

** How to use SSH with GitHub
See [[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key][Generating a new SSH key and adding it to the ssh-agent - GitHub Docs]]

On Linux, run:

: ssh-keygen -t ed25519 -C "your_email@example.com"

on the prompt "=Enter a file in which to save the key[...]=" to change the
default name, the full path needs to be given, if not it will be placed in the
current directory. The generated files are two: One private key file, without
extension; and one public key file, with the extension "=.pub=", e.g.:
=generated-key-file= and =generated-key-file.pub=

The location of the generated files don't really matter but
it is good convention, and safer, to keep them in the directory "=~/.ssh=",
with it having octal permissions of =700=; the private key file =600= and
=644= for the public key files. Like so:
#+begin_example shell
$ stat -c "%a %n" ~/.ssh
700 /home/user/.ssh
$ stat -c "%a %n" ~/.ssh/*
600 /home/user/.ssh/config
600 /home/user/.ssh/ed25519
644 /home/user/.ssh/ed25519.pub
600 /home/user/.ssh/generated-key-file
644 /home/user/.ssh/generated-key-file.pub
600 /home/user/.ssh/id_rsa_host
644 /home/user/.ssh/id_rsa_host.pub
600 /home/user/.ssh/known_hosts
600 /home/user/.ssh/known_hosts.old
#+end_example
- See
  + [[https://askubuntu.com/questions/152001/how-can-i-get-octal-file-permissions-from-command-line/152003#152003][How can I get octal file permissions from command line? - Ask Ubuntu]]
  + [[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent][Generating a new SSH key and adding it to the ssh-agent - GitHub Docs]]

As described in [[*SSH login without password][SSH login without password#Add the private key to keyring]]
The following two steps are required for using the ssh keys without password:
To start =ssh-agent=:
: eval "$(ssh-agent -s)"

and to add a specific private key to keyring:
: ssh-add ~/.ssh/generated-key-file
where =generated-key-file= is a chosen filename from =ssh-keygen=.
# [2022-11-08 Tue 19:20:51 -03]

Now, for it to work on GitHub the public key have to be registered there:
Go to https://github.com/settings/ssh/new

Give it a Title, it has identification purposes only;
Copy the contents of =generated-key-file.pub= and paste it in the "Key" field;
Confirm with "Add SSH Key".

Now, commands like
: git clone git@github.com:USERNAME/REPO.git
should work.
# [2022-11-08 Tue 19:25:03 -03]
