#!/usr/bin/env sh
command -v jaq > /dev/null &&
    alias jq=jaq
# jaq is a faster jq clone

# if [`jq' is not alias] AND [`jq' not found] = fail
! alias jq > /dev/null && ! command -v jq > /dev/null &&
    notify-send -a hypr-workspace script \
                'jaq/jq not found' \
                'Install jaq (or jq)' &&
    exit 1

hyprctl activewindow -j | jq --raw-output .title

# shellcheck disable=SC2016
socat -u UNIX-CONNECT:/tmp/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock - |
    stdbuf -o0 grep '^activewindow>>' |
    stdbuf -o0 awk -F '>>|,' '{print $3}'
