#!/usr/bin/env sh
# tested on a dual-monitor setup, may not work with different ones

command -v jaq > /dev/null &&
    alias jq=jaq
# jaq is a faster jq clone

# if [`jq' is not alias] AND [`jq' not found] = fail
! alias jq > /dev/null && ! command -v jq > /dev/null &&
    notify-send -a hypr-workspace script \
                'jaq/jq not found' \
                'Install jaq (or jq)' &&
    exit 1

active_focused_ws() {
    hyprctl monitors -j | jq -r ".[] | select(.focused == $1).activeWorkspace.id"
}

json_out_format() {
    printf '{"focused":"%s","unfocused":"%s"}\n' "$1" "$2"
}

json_out_format "$(active_focused_ws true)" "$(active_focused_ws false)"

socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR}"/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock - |
    stdbuf -o0 awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}'
