#!/usr/bin/env sh
unset __usingjaq

command -v jaq > /dev/null &&
    alias jq=jaq &&
    __usingjaq=t
# jaq is a faster jq clone

# if [`jq' is not alias] AND [`jq' not found] = fail
! alias jq > /dev/null && ! command -v jq > /dev/null &&
    notify-send -a hypr-workspace script \
                'jaq/jq not found' \
                'Install jaq (or jq)' &&
    exit 1

spacesJq (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    seq 1 10 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spacesJaq() {
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jaq 'map({key: .id | tostring, value: .windows}) | from_entries')
    seq 1 10 | jaq --arg windows "${WORKSPACE_WINDOWS}" --slurp --color never -c 'map(tostring) | map({id: ., windows: (($windows | fromjson)[.]//0)})'
}

if [ -n "${__usingjaq}" ]; then
    alias spaces=spacesJaq
else
    alias spaces=spacesJq
fi

spaces

socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR}"/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock - |
    while read -r _; do
        spaces
    done
