# [[file:../darkman/README.org::*Making Darkman portal implementation work on minimal setups][Making Darkman portal implementation work on minimal setups:2]]
[preferred]
default=gtk
org.freedesktop.impl.portal.Settings=darkman
# Making Darkman portal implementation work on minimal setups:2 ends here
