---
# Quadlet directories
- name: Ensure Quadlet systemd directory exists for aiagent
  tags: [aiagent_user]
  ansible.builtin.file:
    path: "/home/{{ aiagent_name }}/.config/containers/systemd"
    state: directory
    owner: "{{ aiagent_name }}"
    group: "{{ aiagent_name }}"
    mode: "0750"
  become: true

- name: Deploy aiagent_container tree
  tags: [aiagent_user]
  ansible.builtin.copy:
    src: aiagent_container/
    dest: "/home/{{ aiagent_name }}/aiagent_container/"
    owner: "{{ aiagent_name }}"
    group: "{{ aiagent_name }}"
    mode: "0640"
  become: true

- name: Ensure aiagent_container source directories exist for aiagent
  tags: [aiagent_user]
  ansible.builtin.file:
    path: "/home/{{ aiagent_name }}/aiagent_container/{{ item }}"
    state: directory
    owner: "{{ aiagent_name }}"
    group: "{{ aiagent_name }}"
    mode: "0750"
  loop: "{{ aiagent_container_dirs }}"
  become: true

- name: Deploy Quadlets tree
  tags: [aiagent_user]
  ansible.builtin.copy:
    src: containers/systemd/
    dest: "/home/{{ aiagent_name }}/.config/containers/systemd/"
    owner: "{{ aiagent_name }}"
    group: "{{ aiagent_name }}"
    mode: "0640"
  become: true
  notify: Reload aiagent quadlets

- name: Ensure systemd user unit directory exists for aiagent
  tags: [aiagent_user]
  ansible.builtin.file:
    path: "/home/{{ aiagent_name }}/.config/systemd/user"
    state: directory
    owner: "{{ aiagent_name }}"
    group: "{{ aiagent_name }}"
    mode: "0750"
  become: true

- name: Deploy aiagent systemd user units
  tags: [aiagent_user]
  ansible.builtin.copy:
    src: systemd/user/
    dest: "/home/{{ aiagent_name }}/.config/systemd/user/"
    owner: "{{ aiagent_name }}"
    group: "{{ aiagent_name }}"
    mode: "0640"
  become: true
  notify: Reload aiagent quadlets

- name: Deploy bashrc.d tree
  tags: [aiagent_user]
  ansible.builtin.copy:
    src: bashrc.d/
    dest: "/home/{{ aiagent_name }}/aiagent_container/bashrc.d/"
    owner: "{{ aiagent_name }}"
    group: "{{ aiagent_name }}"
    mode: "0640"
  become: true

- name: Deploy init.d tree
  tags: [aiagent_user]
  ansible.builtin.copy:
    src: init.d/
    dest: "/home/{{ aiagent_name }}/aiagent_container/init.d/"
    owner: "{{ aiagent_name }}"
    group: "{{ aiagent_name }}"
    # needs to be executable so when the target user bind mounts the files here
    # to inside a container it can be executed.
    mode: "0700"
  become: true
