if [[ $TERM == "dumb" ]] || [[ -n $INSIDE_EMACS ]]; then
    # NOTE: set this on BOTH `.zshrc' AND `.zshenv'
    unsetopt zle
    PS1='$ '
    export HISTFILE=$HOME/.tramp_history
    return
fi

[[ -n $DEBUG ]] && set -x

[[ $- != *i* ]] && return

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
[[ -r "$XDG_CONFIG_HOME"/shell/profile ]] &&
    source "$XDG_CONFIG_HOME"/shell/profile

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# generated by powerlevel10k theme:
# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f "${ZDOTDIR}"/.p10k.zsh ]] || source "${ZDOTDIR}"/.p10k.zsh

autoload -U colors && colors
[[ -z $DEBUG ]] && [[ -s "/etc/grc.zsh" ]] && source /etc/grc.zsh

# use if check rather than <(..) redirection to save some startup ms
LS_COLORS_ENV_FILE=${XDG_DATA_HOME}/LS_COLORS_ENV
if [[ ! -s ${LS_COLORS_ENV_FILE} ]]; then
    dircolors > "${LS_COLORS_ENV_FILE}"
    source "${LS_COLORS_ENV_FILE}"
else
    source "${LS_COLORS_ENV_FILE}"
fi
# source <(dircolors)

unsetopt beep
bindkey -e # set emacs mode
setopt autocd extendedglob nomatch notify

zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

[[ -z $DEBUG ]] && source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
[[ -z $DEBUG ]] && source "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
[[ -z $DEBUG ]] && source "/usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"

source "$XDG_CONFIG_HOME/shell/aliases"

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

AUTOSUGGESTION_ACCEPT_RIGHT_ARROW=1

#bindkey '^I'   complete-word       # tab          | complete
bindkey '^[[Z'  forward-word  # shift + tab  | autosuggest
# ctrl-left and ctrl-right
bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
# ctrl-bs and ctrl-del
bindkey "\e[3;5~" kill-word
bindkey "\C-_"    backward-kill-word
# del, home and end
bindkey "\e[3~" delete-char
bindkey "\e[H"  beginning-of-line
bindkey "\e[F"  end-of-line
# alt-bs
bindkey "\e\d"  undo
# ctrl+e
bindkey "^E"    end-of-line
bindkey "^F"    autosuggest-fetch

bindkey -e '' undo
bindkey -e 'd' kill-word

# search
# bindkey '' up-line-or-search
# bindkey '' down-line-or-search

bindkey "^S" history-incremental-search-backward
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# https://stackoverflow.com/questions/26409337/inserting-a-newline-in-a-multiline-zsh-command-pulled-from-history/26461450#26461450
# bindkey '^M'   accept-line # vterm fix
bindkey '^[^M' self-insert-unmeta # Insert newline without accepting the command

# `'^J' as self-insert-unmeta' conflicts with Emacs vterm, so only set
# it outside.
if [[ ! $INSIDE_EMACS == vterm ]] || [[ -z $EMACS_VTERM_PATH ]]; then
    bindkey '^J' self-insert-unmeta
fi

bindkey '^H'   backward-kill-word
bindkey '^F'   forward-char

current_clip() {
    selfSessionType=$( loginctl show-session self -p Type | awk -F'=' '{print $2}' )
    if [ "${selfSessionType}" = wayland ]; then
        ## Wayland
        export clipCopy=wl-copy
        export clipPaste=wl-paste
    else
        ## Xorg
        export clipCopy=(xclip -r -i -t UTF8_STRING -selection clip)
        export clipPaste=(xclip -o -selection clip \</dev/null)
    fi
}

xw-clip-kill-region () {
    zle copy-region-as-kill
    printf '%s' "$CUTBUFFER" | ${clipCopy}
}
zle -N xw-clip-kill-region

xw-clip-kill-region () {
    zle kill-region
    printf '%s' "$CUTBUFFER" | ${clipCopy}
}
zle -N xw-clip-kill-region

xw-clip-kill-line () {
    zle kill-line
    printf '%s' "$CUTBUFFER" | ${clipCopy}
}
zle -N xw-clip-kill-line

xw-clip-yank () {
    CUTBUFFER=$( ${clipPaste} )
    zle yank
}
zle -N xw-clip-yank

x-wayland-bindkeys() {
    bindkey -e '^[w' xw-clip-kill-region
    bindkey -e '^W' xw-clip-kill-region
    bindkey -e '^Y' xw-clip-yank
    bindkey -e '^K' xw-clip-kill-line
}

tty-clipboard-binkeys-emacs() {
    bindkey -e '^[w' copy-region-as-kill
    bindkey -e '^W' kill-region
    bindkey -e '^Y' yank
    bindkey -e '^K' kill-line
}
current_clip

if [[ -n $WAYLAND_DISPLAY ]]; then
    x-wayland-bindkeys
elif [[ -n $DISPLAY ]] && [[ -z $WAYLAND_DISPLAY ]]; then
    x-wayland-bindkeys
else
    tty-clipboard-binkeys-emacs
fi

bindkey -r '^[x' # execute-named-cmd

# remap default ctrl + c (interrupt)
stty intr '^G' <$TTY >$TTY

set -o ignoreeof

[[ -r ${TTY:-} && -w ${TTY:-} && $+commands[stty] == 1 ]] &&
    stty -ixon <$TTY >$TTY

# Disable lack-of-newline percentile symbol https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol/167600#167600
unsetopt PROMPT_SP
# https://www.cassey.dev/til/2020-11-09-zsh-percent-signs/
# https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol
# export PROMPT_EOL_MARK=''

function is_command() {
    command -v "$1" &> /dev/null && return 0
    return 1
}

localFPATH="${XDG_DATA_HOME}"/zsh/functions
mkdir -p "$localFPATH"
fpath+="$localFPATH"

function is_user_fpath_file() {
    if [[ -f ${localFPATH%/}/$1 ]]; then
        return 0
    else
        return 1
    fi
}

function download_to_user_fpath() {
    if is_user_fpath_file "$1"; then
        return 0
    else
        printf 'Downloading "%s" to "%s"\nSource: %s\n\n' "$1" "$localFPATH"/"$1" "$2"
        curl -sL -o "$localFPATH"/"$1" "$2"
    fi
}

download_to_user_fpath delsel-mode 'https://raw.githubusercontent.com/knu/zsh-delsel-mode/master/delsel-mode'
# then autoload it
autoload -Uz delsel-mode
delsel-mode

autoload -U +X bashcompinit && bashcompinit

is_command git &&
    download_to_user_fpath _git 'https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh'

is_command stack && {
    is_user_fpath_file "$1" ||
        stack --bash-completion-script `which stack` > "$localFPATH"/_stack
}

# The following lines were added (generated) by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' matcher-list '+' 'l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:]}={[:upper:]} r:|[._-]=** r:|=**'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle :compinstall filename "$ZDOTDIR/.zshrc"

# autoload -Uz compinit && compinit
_comp_options+=(globdots) # Include hidden files.
# End of lines added by compinstall

shellCompletionDir=${XDG_DATA_HOME}/shell-completion
[[ -d ${shellCompletionDir}/zsh ]] && fpath+=${shellCompletionDir}/zsh

autoload -Uz compinit && compinit

[[ -d ${shellCompletionDir}/bash ]] &&
    for file in $(find "${shellCompletionDir}"/bash/* -type f); do
        [[ -f ${file} ]] && source "${file}"
    done

[[ -d ${XDG_STATE_HOME}/zsh ]] || mkdir -p "${XDG_STATE_HOME}"/zsh
export HISTFILE=$XDG_STATE_HOME/zsh/history
export HISTSIZE=10000000
export SAVEHIST=10000000

setopt histignorealldups

eval "$(atuin init zsh)"

eval "$(zoxide init zsh)"

alias cd=z
alias c=z

# source_check() {
#     [ -r "$1" ] &&
#         . "$1"
# }

# source_check "$XDG_CONFIG_HOME"/shell/nnn-setup.bash
# source_check "$XDG_CONFIG_HOME"/shell/ghcup-setup.sh

__setupModulesDir=$XDG_CONFIG_HOME/shell/setup-modules
if test -d "${__setupModulesDir}"; then
    for module in "${__setupModulesDir}"/*.sh \
                  "${__setupModulesDir}"/*.bash; do
        test -r "$module" && . "$module"
    done
    unset module
fi
unset __setupModulesDir
