#+title: Shell configurations
#+description: General configuration defaults for all used shells.

- Basic shell references:
  + [[https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html][3.5.3 Shell Parameter Expansion]]
  + [[https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html][3.4.2 Special Parameters]]
  + [[https://www.computerhope.com/jargon/p/positional-parameter.htm][What is a Positional Parameter? - Computer Hope]]

* =aliases=: Shell aliases
:PROPERTIES:
:header-args:shell: :tangle ~/.config/shell/aliases :mkdirp yes :tangle-mode o644 :shebang #!/usr/bin/echo 'This is a source only file.'
:END:

[[https://www.youtube.com/watch?v=4v4Mcncvsac][Shell Aliases Every Linux User Needs - YouTube]]

** Pacman & Paru
#+begin_src shell
alias pac='sudo /usr/bin/pacman -S'
alias pacss='/usr/bin/pacman -Ss'
alias pacssq='/usr/bin/pacman -Ssq'
alias pacsyu='sudo /usr/bin/pacman -Syu'
alias paruss='paru -Ss'
alias pacrcsn='sudo /usr/bin/pacman -Rcsn'
alias pacrsn='sudo /usr/bin/pacman -Rsn'
alias pacrcn='sudo /usr/bin/pacman -Rcn'
alias update='pacsyu; paru'
alias pacqs='/usr/bin/pacman -Qs'
alias pacqi='/usr/bin/pacman -Qi'
alias pacsi='/usr/bin/pacman -Si'
alias parusi='paru -Si'
alias pacqo='/usr/bin/pacman -Qo'
alias pacqi='/usr/bin/pacman -Qi'
alias pacf='/usr/bin/pacman -F'
alias pacfy='/usr/bin/pacman -Fy'
#+end_src

** Systemd
#+begin_src shell
alias sd="systemctl"
alias sdu="systemctl --user"
alias suspend='systemctl suspend'
alias cdsd='cd /etc/systemd/system'
alias cdsdu='cd "$XDG_CONFIG_HOME"/systemd/user'
#+end_src

** sudo vs doas
# doas not worth on arch + emacs :c
#+begin_src shell
# alias sudo='doas'
alias doas=sudo
#+end_src

** Launchers
#+begin_src shell
if command -v cpg > /dev/null && command -v mvg > /dev/null; then
    alias cp="cpg -vi --progress-bar"
    alias mv="mvg -vi --progress-bar"
else
    alias cp="cp -vi"
    alias mv="mv -vi"
fi

alias e="$EDITOR"
alias re="sudo $EDITOR"
alias a="aria2c"
alias f="fzf"
alias c="bat"
alias b="bat"
#+end_src

** Navigation & listing
#+begin_src shell
alias l='eza -lag --color=auto --group-directories-first --time-style long-iso'
alias lt='l -T'
# alias cd-file-manager-actions="cd ~/.local/share/file-manager/actions"
alias cdc='cd "$XDG_CONFIG_HOME"'
alias cds='cd "$XDG_DATA_HOME"'
alias cdcc='cd "$XDG_CACHE_HOME"'
alias cdst='cd "$XDG_STATE_HOME"'
alias cdconf='cd "$XDG_CONFIG_HOME"'
alias cdshare='cd "$XDG_DATA_HOME"'
alias cdcache='cd "$XDG_CACHE_HOME"'
alias cdstate='cd "$XDG_STATE_HOME"'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
# no one should have that many children hehe


#+end_src

** Directory
#+begin_src shell
alias mkdir='mkdir -pv'
#+end_src

** Git
- See
  + [[https://www.ackama.com/what-we-think/the-best-way-to-store-your-dotfiles-a-bare-git-repository-explained/][The best way to store your dotfiles: A bare Git repository **EXPLAINED** - Ackama]]
    /(best article)/.
  + [[https://www.youtube.com/watch?v=tBoLDpTWVOM][Git Bare Repository - A Better Way To Manage Dotfiles]]
#+begin_src shell
alias dot='git --git-dir="$HOME/.local/dotfiles.git" --work-tree="$HOME"'
#+end_src

** SSH
#+begin_src shell
alias alarm='ssh -p 1111 alarm@alarm'
#+end_src

** Archives & Compressed files
#+begin_src shell
alias pc='patool create'
alias pe='patool extract'
alias px='patool extract'
alias pl='patool list'
alias xs='xtosubdir'
#+end_src

** Root commands without password
# commands that require permissions from the =/etc/sudoers= file.
Commands to be runned as root configured not to ask for password.

#+begin_src shell
alias rgboff='sudo openrgb --device 0 -m off; sudo openrgb --device 1 -m off;'
#+end_src

** Tools & Utilities
*** Xorg
# wayland lul # [2023-09-22 Fri 12:46:26 -03]
#+begin_src shell
alias gamma1='xrandr --output HDMI1 --gamma 1'
alias gamma1.2='xrandr --output HDMI1 --gamma 1.222'
alias gamma2='xrandr --output HDMI1 --gamma 1.222'
alias monitors-setup-alias='nvidia-settings --assign CurrentMetaMode="DPY-1: 2560x1440_165 @2560x1440 +0+0 {ViewPortIn=2560x1440, ViewPortOut=2560x1440+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DPY-3: 2560x1440_60 @2560x1440 +2560+0 {ViewPortIn=2560x1440, ViewPortOut=2560x1440+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"'
#+end_src

*** Monitor controls
"=brightness=" is an AUR script. See [[file:~/org/arch-linux.org::#orgid-jpxivm][Change brightness from the command-line]].
#+begin_src shell
alias b10='brightness 10'
alias b30='brightness 30'
alias b100='brightness 100'
#+end_src

* =profile=: Shell environment variables & user-login configuration
:PROPERTIES:
:header-args:shell: :tangle ~/.config/shell/profile :tangle-mode o644 :shebang #!/usr/bin/echo 'This is a source only file.'
:END:

# User defined variables are in lowerCamelCase.

** XDG Standard enviroment variables

For the XDG standard, the only less conventional one is
=XDG_STATE_HOME=, and =XDG_BIN_HOME= is /not/ a part of the specification
but commonly used.
# as of # [2022-11-30 Wed 16:41:29 -03].
- See
  + [[https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html][XDG Base Directory Specification]]
  + [[https://stackoverflow.com/questions/25897836/where-should-i-write-a-user-specific-log-file-to-and-be-xdg-base-directory-comp/27965014#27965014][Where should I write a user specific log file to (and be XDG base directory compatible) - Stack Overflow]].

#+begin_src shell
export XDG_CACHE_HOME="$HOME/.local/cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_BIN_HOME="$HOME/.local/bin"
#+end_src

** Additional PATH directories
Source helper functions, specifically =append_path=.
#+begin_src shell
source "$XDG_CONFIG_HOME/shell/functions"
#+end_src

More PATH directories
#+begin_src shell
append_path "$XDG_BIN_HOME"
#+end_src

See [[https://github.com/LukeSmithxyz/voidrice/blob/284b1078cb6231863244a1355dd08cd81be279a6/.config/shell/profile#L9][voidrice/profile at master · LukeSmithxyz/voidrice#L9]].
Putting the directories in =XDG_BIN_HOME= /after/ PATH to make already present
executables, e.g. from =/usr/bin=, take precedence.
#+begin_src shell
find_subdirs_xdg_bin_home_colon_sep() {
    [ -d "$XDG_BIN_HOME" ] &&
        find "$XDG_BIN_HOME" \
             -mindepth 1 \
             -maxdepth 1 \
             -type d \
             -not -name '.*' \
             -printf %p:
}
#+end_src
- where
  + =-not -name '.*'= is to exclude directories (=-type d=) beggining with =.= (dot).
  + =-mindepth 1= prevents the target directory =$XDG_BIN_HOME= itself from being included.
    * See https://stackoverflow.com/a/13525005
  + =-maxdepth 1= includes only first-level subdirectories of =$XDG_BIN_HOME=.

- Now:
  + Get the output of =find_subdirs_xdg_bin_home_colon_sep=;
  + save it in a local variable (POSIX-style);
  + remove any =:= at the end of it while appending to path with
    =append_path=.
  + =unset= the local variable for good measure.
#+begin_src shell
[ -d "$XDG_BIN_HOME" ] && {
    _xdg_bin_home_dirs=$(find_subdirs_xdg_bin_home_colon_sep)
    append_path "${_xdg_bin_home_dirs%:}"
    unset _xdg_bin_home_dirs
}
#+end_src

# This came here because in earlier versions of this config when
# adding subdirectories of XDG_BIN_HOME to PATH `-mindepth 1' wasn't
# being used in find, leading to duplicates being added to PATH. But
# leave it here just because it's redundant.
# [2024-02-24 Sat 22:19:41 -03] @ak
Remove duplicated from PATH without changing the order:
See [[https://superuser.com/questions/449636/path-is-filled-with-duplicates/1321712#1321712][bash - $PATH is filled with duplicates - Super User]]
#+begin_src shell
PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"
#+end_src

Finally, export PATH:
#+begin_src shell
export PATH
#+end_src

** Defending Home
based on:
- [[https://lobste.rs/s/3wntbx/practical_self_defense_against_scourge][Practical Self-Defense against the Scourge of Dot-Files | Lobsters]]
- https://github.com/BrodieRobertson/dotfiles/blob/master/.zshenv
- [[https://wiki.archlinux.org/title/XDG_Base_Directory][XDG Base Directory - ArchWiki]]
- [[https://github.com/b3nj5m1n/xdg-ninja][b3nj5m1n/xdg-ninja: A shell script which checks your $HOME for unwanted files and directories.]]
#+begin_src shell
export XAUTHORITY="$XDG_DATA_HOME"/xorg/Xauthority
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
export GEM_PATH="$XDG_DATA_HOME/ruby/gems"
export GEM_SPEC_CACHE="$XDG_DATA_HOME/ruby/specs"
#+end_src

NOTE: setting =GEM_HOME= now causes issues, in special the error:
#+begin_example
/usr/lib/ruby/3.0.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem gemname (>= 0.a) with executable asciidoctor (Gem::GemNotFoundException)
      from /usr/lib/ruby/3.0.0/rubygems.rb:284:in `activate_bin_path'
      from /usr/bin/asciidoctor:25:in `<main>'
#+end_example
: export GEM_HOME="$XDG_DATA_HOME/ruby/gems"

#+begin_src shell -r
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"
#export MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
#export VIMINIT=":set runtimepath+=$XDG_CACHE_HOME/vim|:source $MYVIMRC"
#export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME/nv-gl-shader-cache"
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo

export LESSHISTFILE="$XDG_STATE_HOME"/less/history
export GRIPHOME="$XDG_CONFIG_HOME/grip"
export PKG_CACHE_PATH="$XDG_CACHE_HOME/pkg" # https://github.com/vercel/pkg/issues/537
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine
export MAIL="$XDG_DATA_HOME"/mail # Mailutils
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages # dotNet
# ~/.slime: https://github.com/slime/slime/issues/610
export KERAS_HOME="$XDG_DATA_HOME/keras" # don't seem to work but whatever :c [2022-03-29 Tue 21:46:37 ] https://github.com/tensorflow/tensorflow/issues/38831 and https://github.com/keras-team/keras/issues/11923
export UNISON="$XDG_DATA_HOME"/unison
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
export IPYTHONDIR="${XDG_CONFIG_HOME}"/ipython
export ANDROID_HOME=${XDG_DATA_HOME}/android
alias adb='HOME="$XDG_DATA_HOME"/android adb'
export CUDA_CACHE_PATH=${XDG_CACHE_HOME}/nv
alias dosbox=dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox.conf
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
alias nvidia-settings='mkdir -p "${XDG_CONFIG_HOME}"/nvidia && nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings'
# https://github.com/ansible/ansible/commit/d7fbde4ea9db6cc44e81c39d699595330f4fa3c6
export ANSIBLE_HOME=${XDG_DATA_HOME}/ansible
export RUSTUP_HOME=${XDG_DATA_HOME}/rustup
alias wget="wget --hsts-file=${XDG_DATA_HOME}/wget-hsts"
export CALCHISTFILE=${XDG_CACHE_HOME}/calc_history
export RANDFILE=${XDG_CACHE_HOME}/rnd
export SQLITE_HISTORY=${XDG_CACHE_HOME}/sqlite_history
#+end_src

** Default Apps
Commands
#+begin_src shell
#export READER="zatura"
export GIT_EDITOR=emacsclient
export ALTERNATE_EDITOR=emacs
export EDITOR=emacsclient
export VISUAL=emacsclient
export TERMINAL=alacritty
export BROWSER=firefox
export VIDEO=mpv
export IMAGE=qimgv
export OPENER=launch
export PAGER=bat
export WM=Hyprland
#+end_src

** Import environment variables from systemd
- See
  [[https://github.com/systemd/systemd/issues/17180#issuecomment-723856129][systemd ignores $HOME/.config/environment.d/envvars.conf file · Issue #17180 · systemd/systemd]]
  [[https://curiouscoding.nl/linux/environment-variables/][Environment variables done once · CuriousCoding]]
  # [2023-02-19 Sun 03:28:04 -03]
  [[https://wiki.archlinux.org/title/Environment_variables#:~:text=use systemd-environment-d-generator(8) to generate environment%2C][Environment variables - ArchWiki]]
  # [2023-04-07 Fri 05:58:58 -03]

Install =run-parts= to run all scripts within a directory.

The check is to make sure the =30-systemd-environment-d-generator=
program doesn't return an empty result, from having an empty or
inexistent =environment.d= directory.
#+begin_src shell
ps -p 1 -o comm= | grep -q systemd &&
    [ "$(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator | wc -l)" != 0 ] &&
    export $(run-parts /usr/lib/systemd/user-environment-generators/ | xargs)
#+end_src
Here, =xargs= separates the output of the scripts into a space-separated
list of arguments.

#+begin_src shell
# check for duplicates in the PATH again
PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"
#+end_src

** NVIDIA hardware acceleration
#+begin_src shell
export MOZ_DISABLE_RDD_SANDBOX=1
export NVD_BACKEND=direct
#+end_src
# export LIBVA_DRIVER_NAME=nvidia
# this can be disabled to not use video decoding per
# command. e.g. 'LIBVA_DRIVER_NAME= firefox'

# idk anything else but this just worked # [2023-03-23 Thu 18:20:00 -03]
# ####
# ## X11 only
# export MOZ_X11_EGL=1 # this doesn't seem to work but `gfx.x11-egl.force-enabled = true' does

# export MOZ_DRM_DEVICE=/dev/dri/renderD128 # testing not necessary with `libva-nvidia-driver' [AUR]
# apparently this is all firefox need, testing # [2023-03-23 Thu 18:35:16 -03]
# ps: for X11, testing wayland # [2023-03-31 Fri 08:19:39 -03]

# ## Wayland only
# moved these to built-in window manager's enviroment variables,
# e.g. `env' keyword in Hyprland.
# export EGL_PLATFORM=wayland # unset this when on X11
# export MOZ_ENABLE_WAYLAND=1 # necessary otherwise Firefox will only try X11


** Program specific settings
*** LSP
[[https://emacs-lsp.github.io/lsp-mode/page/performance/][Performance - LSP Mode - LSP support for Emacs]]

#+begin_src shell
export LSP_USE_PLISTS=true
#+end_src

* =functions=: Sourceable helper function definitions
:PROPERTIES:
:header-args:shell: :tangle ~/.config/shell/functions :tangle-mode o644 :shebang #!/usr/bin/echo 'This is a source only file.'
:END:

This abstraction is useful for functions that should be available by
sourcing this file either in startup process or after. Because
functions are not inherited by subshells like environment variable
are.

Function copied from =/etc/profile= to append argument to variable PATH:
#+begin_src shell
append_path () {
    case ":$PATH:" in
        ,*:"$1":*)
        ;;
        ,*)
            PATH="${PATH:+$PATH:}$1"
            PATH="${PATH#:}"
            PATH="${PATH%:}"
    esac
}

prepend_path () {
    # Prioritize $1 over system PATH directories
    case ":$PATH:" in
        ,*:"$1":*)
        ;;
        ,*)
            PATH="$1:${PATH:+$PATH:}"
            PATH="${PATH#:}"
            PATH="${PATH%:}"
    esac
}
#+end_src

* Zsh
:PROPERTIES:
:tangle-dir: (concat (xdg-config-home) "/shell")
:END:

- [[https://ospfranco.com/post/2023/08/15/zsh-configuration-files-load-order/][ZSH configuration files load order | Oscar Franco]]
- [[https://apple.stackexchange.com/questions/388622/zsh-zprofile-zshrc-zlogin-what-goes-where][ZSH: .zprofile, .zshrc, .zlogin - What goes where?]]
# [2022-04-14 Thu 23:25:18]

# - Install zsh base extensions and font:
#   + zsh-autosuggestions
#   + zsh-history-substring-search
#   + zsh-syntax-highlighting
#   + zsh-theme-powerlevel10k
#   + ttf-liberation-mono-nerd
#   + noto-fonts-cjk
#   + noto-fonts-emoji
#   + noto-fonts

** =.zprofile=: Login profile setup and $ZDOTDIR
:PROPERTIES:
:header-args:bash: :tangle (tdir "/.zprofile") :mkdirp yes
:END:

*** Autostart
#+begin_src bash
if [ "$(tty)" = "/dev/tty1" ] # check if it is the first tty login
then
    WM_LOCKFILE=${XDG_RUNTIME_DIR:-/tmp}/wmstart.lock

    [[ -f $WM_LOCKFILE ]] &&
        printf '"%s" lockfile present, skipping WM "%s" restart...\n' "$WM_LOCKFILE" "$WM" >&2 &&
        return

    pgrep '^'"$WM"'$' &&
        printf '"%s" is already running. Skipping its startup...\n' "$WM" &&
        return

    touch "${WM_LOCKFILE}"

    exec "$WM"
fi
#+end_src

** =.zshrc=
:PROPERTIES:
:header-args:bash: :tangle (tdir "/.zshrc") :mkdirp yes
:END:

*** TRAMP/dumb terminal check
For some reason, specially on bigger configs split between [[*TRAMP/dumb terminal check][.zshrc]] and
[[*=.zshenv=][.zshenv]], this needs to be checked on BOTH.
#+NAME: tramp-dumb-terminal-check
#+begin_src bash
if [[ $TERM == "dumb" ]] || [[ -n $INSIDE_EMACS ]]; then
    # NOTE: set this on BOTH `.zshrc' AND `.zshenv'
    unsetopt zle
    PS1='$ '
    export HISTFILE=$HOME/.tramp_history
    return
fi
#+end_src

*** Debug / backtrace
#+begin_src bash
[[ -n $DEBUG ]] && set -x
#+end_src

*** Check if shell is interactive
If not interactive don't load configuration file.
#+begin_src bash
[[ $- != *i* ]] && return
#+end_src

*** powerlevel10k
- See
  + [[https://github.com/romkatv/powerlevel10k#instant-prompt][romkatv/powerlevel10k#instant-prompt]]
  + [[https://github.com/romkatv/powerlevel10k#how-do-i-configure-instant-prompt][romkatv/powerlevel10k#How-Do-I-Configure-Instant-Prompt]]

#+NAME: powerlevel10k-header
#+begin_src bash
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# generated by powerlevel10k theme:
# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f "${ZDOTDIR}"/.p10k.zsh ]] || source "${ZDOTDIR}"/.p10k.zsh
#+end_src

*** Colours
:PROPERTIES:
:CUSTOM_ID: orgid-wzokjz
:END:
https://github.com/garabik/grc
Install =grc=.
- NOTE: Add this to =.zprofile= for correct order of sourcing.
  + See [[https://github.com/garabik/grc/issues/220][zsh not sourcing the grc.zsh despite everything been set correctly · Issue #220 · garabik/grc]]
#+begin_src bash :tangle no :noweb-ref grc-zsh-source
[[ -z $DEBUG ]] && [[ -s "/etc/grc.zsh" ]] && source /etc/grc.zsh
#+end_src

#+begin_src bash
autoload -U colors && colors
#+end_src

**** TODO Customize how commands are highlighted using =zsh-syntax-highlighting=
wizard [[https://github.com/zsh-users/zsh-syntax-highlighting/issues/464][How to change the highlight color??? · Issue #464 · zsh-users/zsh-syntax-highlighting]]

Customizing =ZSH_HIGHLIGHT_STYLES= options
#+begin_src bash :tangle no
# if, for
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=magenta

# quotes
# ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg='#cbc3ff'
# ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg='#cbc3ff'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=magenta
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=magenta
#+end_src

*** zsh-newuser-install
#+begin_src bash
unsetopt beep
bindkey -e # set emacs mode
setopt autocd extendedglob nomatch notify
#+end_src

*** Enable case insensitivity
wizard [[https://stackoverflow.com/questions/24226685/have-zsh-return-case-insensitive-auto-complete-matches-but-prefer-exact-matches/24237590#24237590][oh my zsh - Have zsh return case-insensitive auto-complete matches, but prefer exact matches - Stack Overflow]]
# [2022-11-09 Wed 22:06:25 -03]
#+begin_src bash
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
#+end_src

*** Sourcing

**** Installed packages
#+begin_src bash
[[ -z $DEBUG ]] && source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
[[ -z $DEBUG ]] && source "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
[[ -z $DEBUG ]] && source "/usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"
#+end_src

**** Aliases
#+begin_src bash
source "$XDG_CONFIG_HOME/shell/aliases"
#+end_src

**** Theme
#+begin_src bash
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
#+end_src

*** Autosuggestions
#+begin_src bash
AUTOSUGGESTION_ACCEPT_RIGHT_ARROW=1
#+end_src

*** Bindkeys
:PROPERTIES:
:CUSTOM_ID: zsh-bindkeys
:END:
Emacs
# 😊
#+begin_src bash
#bindkey '^I'   complete-word       # tab          | complete
bindkey '^[[Z'  forward-word  # shift + tab  | autosuggest
# ctrl-left and ctrl-right
bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
# ctrl-bs and ctrl-del
bindkey "\e[3;5~" kill-word
bindkey "\C-_"    backward-kill-word
# del, home and end
bindkey "\e[3~" delete-char
bindkey "\e[H"  beginning-of-line
bindkey "\e[F"  end-of-line
# alt-bs
bindkey "\e\d"  undo
# ctrl+e
bindkey "^E"    end-of-line
bindkey "^F"    autosuggest-fetch

bindkey -e '' undo
bindkey -e 'd' kill-word

# search
# bindkey '' up-line-or-search
# bindkey '' down-line-or-search
#+end_src

**** Search
#+begin_src bash
bindkey "^S" history-incremental-search-backward
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# https://stackoverflow.com/questions/26409337/inserting-a-newline-in-a-multiline-zsh-command-pulled-from-history/26461450#26461450
# bindkey '^M'   accept-line # vterm fix
bindkey '^[^M' self-insert-unmeta # Insert newline without accepting the command

# `'^J' as self-insert-unmeta' conflicts with Emacs vterm, so only set
# it outside.
if [[ ! $INSIDE_EMACS == vterm ]] || [[ -z $EMACS_VTERM_PATH ]]; then
    bindkey '^J' self-insert-unmeta
fi

bindkey '^H'   backward-kill-word
bindkey '^F'   forward-char
#+end_src

**** Clipboard support
- See
  [[https://unix.stackexchange.com/questions/51933/zsh-copy-and-paste-like-emacs/51938#51938][clipboard - zsh copy and paste like emacs - Unix & Linux Stack Exchange]]
  # #wzrd

Different clipboard program based on (=loginctl=) session type
#+begin_src bash
current_clip() {
    selfSessionType=$( loginctl show-session self -p Type | awk -F'=' '{print $2}' )
    if [ "${selfSessionType}" = wayland ]; then
        ## Wayland
        export clipCopy=wl-copy
        export clipPaste=wl-paste
    else
        ## Xorg
        export clipCopy=(xclip -r -i -t UTF8_STRING -selection clip)
        export clipPaste=(xclip -o -selection clip \</dev/null)
    fi
}
#+end_src
Check for =tty= only is made later:
# #TODO-better-logic ?

#+begin_src bash
xw-clip-kill-region () {
    zle copy-region-as-kill
    printf '%s' "$CUTBUFFER" | ${clipCopy}
}
zle -N xw-clip-kill-region

xw-clip-kill-region () {
    zle kill-region
    printf '%s' "$CUTBUFFER" | ${clipCopy}
}
zle -N xw-clip-kill-region

xw-clip-kill-line () {
    zle kill-line
    printf '%s' "$CUTBUFFER" | ${clipCopy}
}
zle -N xw-clip-kill-line

xw-clip-yank () {
    CUTBUFFER=$( ${clipPaste} )
    zle yank
}
zle -N xw-clip-yank

x-wayland-bindkeys() {
    bindkey -e '^[w' xw-clip-kill-region
    bindkey -e '^W' xw-clip-kill-region
    bindkey -e '^Y' xw-clip-yank
    bindkey -e '^K' xw-clip-kill-line
}

tty-clipboard-binkeys-emacs() {
    bindkey -e '^[w' copy-region-as-kill
    bindkey -e '^W' kill-region
    bindkey -e '^Y' yank
    bindkey -e '^K' kill-line
}
current_clip

if [[ -n $WAYLAND_DISPLAY ]]; then
    x-wayland-bindkeys
elif [[ -n $DISPLAY ]] && [[ -z $WAYLAND_DISPLAY ]]; then
    x-wayland-bindkeys
else
    tty-clipboard-binkeys-emacs
fi
#+end_src

**** Disable shortcuts/bindkeys
[[https://askubuntu.com/questions/477474/prevent-command-from-stopping-when-pressing-ctrlc/477859#477859][shortcut keys - Prevent command from stopping when pressing CTRL+C - Ask Ubuntu]]
# [2022-05-07 Sat 22:58:42]
#+begin_src bash
bindkey -r '^[x' # execute-named-cmd

# remap default ctrl + c (interrupt)
stty intr '^G' <$TTY >$TTY
#+end_src

- Disable =C-d= exit action
  [[https://unix.stackexchange.com/questions/512862/use-bash-exit-trap-to-confirm-or-cancel-ctrld/512864#512864][shell script - Use bash EXIT trap to confirm or cancel ctrl+d - Unix & Linux Stack Exchange]]
  # [2022-05-20 Fri 00:48:39]
#+begin_src bash
set -o ignoreeof
#+end_src

# Disable =Ctrl + S= and =Ctrl + Q= on terminal/shell
- Disable =C-s= and =C-q= "control flow" keys, see:
  [[https://unix.stackexchange.com/questions/332791/how-to-permanently-disable-ctrl-s-in-terminal/332793#332793][command line - How to permanently disable Ctrl-s in terminal? - Unix & Linux Stack Exchange]]
  # [2022-12-12 Mon 01:07:16 -03]
  [[https://github.com/sorin-ionescu/prezto/pull/1771#issuecomment-575598782][apply `stty -ixon` only to tty by romkatv · Pull Request #1771 · sorin-ionescu/prezto]]

#+begin_src bash
[[ -r ${TTY:-} && -w ${TTY:-} && $+commands[stty] == 1 ]] &&
    stty -ixon <$TTY >$TTY
#+end_src

*** Footer
#+begin_src bash
# Disable lack-of-newline percentile symbol https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol/167600#167600
unsetopt PROMPT_SP
# https://www.cassey.dev/til/2020-11-09-zsh-percent-signs/
# https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol
# export PROMPT_EOL_MARK=''
#+end_src

*** DONE Dynamic terminal title based on current path
:PROPERTIES:
:header-args:bash: :tangle no
:END:

[[https://makandracards.com/makandra/494001-linux-how-to-make-a-terminal-window-title-reflect-the-current-path#section-zsh][How to make a terminal window title reflect the current path - makandra dev]]
# [2022-05-05 Thu 03:04:22]
#+begin_src bash
function precmd () {
    echo -ne "\033]0;Terminal (${SHELL##*/}): $(pwd | sed -e "s;^$HOME;~;")\a"
}
#+end_src

*** DONE Show time that command took to finish
:PROPERTIES:
:header-args:bash: :tangle no
:END:

Source code: [[https://github.com/popstas/zsh-command-time][popstas/zsh-command-time: Show execution time for long commands in zsh]]
# [2023-05-14 Sun 16:48:22 -03]

Useful when /not/ using a theme that provides this functionality.
#+begin_src bash
_command_time_preexec() {
  # check excluded
  if [ -n "$ZSH_COMMAND_TIME_EXCLUDE" ]; then
    cmd="$1"
    for exc ($ZSH_COMMAND_TIME_EXCLUDE) do;
      if [ "$(echo $cmd | grep -c "$exc")" -gt 0 ]; then
        # echo "command excluded: $exc"
        return
      fi
    done
  fi

  timer=${timer:-$SECONDS}
  ZSH_COMMAND_TIME_MSG=${ZSH_COMMAND_TIME_MSG-"Time: %s"}
  ZSH_COMMAND_TIME_COLOR=${ZSH_COMMAND_TIME_COLOR-"white"}
  export ZSH_COMMAND_TIME=""
}

_command_time_precmd() {
  if [ $timer ]; then
    timer_show=$(($SECONDS - $timer))
    if [ -n "$TTY" ] && [ $timer_show -ge ${ZSH_COMMAND_TIME_MIN_SECONDS:-3} ]; then
      export ZSH_COMMAND_TIME="$timer_show"
      if [ ! -z ${ZSH_COMMAND_TIME_MSG} ]; then
        zsh_command_time
      fi
    fi
    unset timer
  fi
}

# Default
# zsh_command_time() {
#   if [ -n "$ZSH_COMMAND_TIME" ]; then
#     timer_show=$(printf '%dh:%02dm:%02ds\n' $(($ZSH_COMMAND_TIME/3600)) $(($ZSH_COMMAND_TIME%3600/60)) $(($ZSH_COMMAND_TIME%60)))
#     print -P "%F{$ZSH_COMMAND_TIME_COLOR}$(printf "${ZSH_COMMAND_TIME_MSG}\n" "$timer_show")%f"
#   fi
# }

zsh_command_time() {
    if [ -n "$ZSH_COMMAND_TIME" ]; then
        hours=$(($ZSH_COMMAND_TIME/3600))
        min=$(($ZSH_COMMAND_TIME/60))
        sec=$(($ZSH_COMMAND_TIME%60))
        if [ "$ZSH_COMMAND_TIME" -le 60 ]; then
            timer_show="$fg[green]$ZSH_COMMAND_TIME s."
        elif [ "$ZSH_COMMAND_TIME" -gt 60 ] && [ "$ZSH_COMMAND_TIME" -le 180 ]; then
            timer_show="$fg[yellow]$min min. $sec s."
        else
            if [ "$hours" -gt 0 ]; then
                min=$(($min%60))
                timer_show="$fg[red]$hours h. $min min. $sec s."
            else
                timer_show="$fg[red]$min min. $sec s."
            fi
        fi
        printf "${ZSH_COMMAND_TIME_MSG}\n" "$timer_show"
    fi
}

precmd_functions+=(_command_time_precmd)
preexec_functions+=(_command_time_preexec)
#+end_src

*** Utility functions
#+begin_src bash
function is_command() {
    command -v "$1" &> /dev/null && return 0
    return 1
}
#+end_src

from https://gitlab.com/dwt1/dotfiles/-/blob/master/.bashrc#L138
#+begin_src bash :tangle no :noweb-ref dummy
up () {
  local d=""
  local limit="$1"

  # Default to limit of 1
  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
    limit=1
  fi

  for ((i=1;i<=limit;i++)); do
    d="../$d"
  done

  # perform cd. Show error if cd fails
  if ! cd "$d"; then
    echo "Couldn't go up $limit dirs.";
  fi
}
#+end_src

*** $FPATH: directories for autoload shell function definitions
Extensions to be placed on =FPATH=
- [[https://stackoverflow.com/questions/20451029/what-is-the-difference-between-path-and-fpath/20451088#20451088][macos - What is the difference between $PATH and $fpath? - Stack Overflow]]
- Add directories to =$fpath=. They should be defined before any other
  function/command that uses them.
- Note: =$fpath= is an array and =$FPATH= is a scalar path definition, aka
  =/dir1/:/dir2/=. So when customizing =FPATH= always use the lowercase
  array one (=$fpath=) and append or prepend a directory to it with
  =fpath+=/path/to/dir= or =fpath=("/path/to/dir" $fpath)= respectively.

#+begin_src bash
localFPATH="${XDG_DATA_HOME}"/zsh/functions
mkdir -p "$localFPATH"
fpath+="$localFPATH"

function is_user_fpath_file() {
    if [[ -f ${localFPATH%/}/$1 ]]; then
        return 0
    else
        return 1
    fi
}

function download_to_user_fpath() {
    if is_user_fpath_file "$1"; then
        return 0
    else
        printf 'Downloading "%s" to "%s"\nSource: %s\n\n' "$1" "$localFPATH"/"$1" "$2"
        curl -sL -o "$localFPATH"/"$1" "$2"
    fi
}
#+end_src

***** =delsel-mode=: delete-selection-mode for zsh
[[https://github.com/knu/zsh-delsel-mode][knu/zsh-delsel-mode: delsel-mode (delete-selection-mode) for zsh]]
# wizard
#+begin_src bash
download_to_user_fpath delsel-mode 'https://raw.githubusercontent.com/knu/zsh-delsel-mode/master/delsel-mode'
# then autoload it
autoload -Uz delsel-mode
delsel-mode
#+end_src

*** Autocompletion
:PROPERTIES:
:CUSTOM_ID: orgid-yuoowp
:END:
- *NOTE*: Place the start of =compinit= at the end:
  =compinit= only working when started manually/placed at the end
  of the file This is a problem related to the loading of the =$fpath=
  variable. If a directory in =$fpath= which includes completions is
  loaded after =compinit= is started it may not recognize that
  directory, so only when placing the call for =compinit= or calling it
  manually after makes it reload the =$fpath= directories and find the
  completion functions.

  + See
    [[https://github.com/conda-incubator/conda-zsh-completion/issues/26][Issue #26 · conda-incubator/conda-zsh-completion]]
    [[https://github.com/conda-incubator/conda-zsh-completion/blob/master/_conda#L19][conda-incubator/conda-zsh-completion/_conda#L19]]
    # [2023-05-23 Tue 06:40:53 -03]

  For the best performance all =$fpath= directories must be added before
  the call for =compinit=.

  Alternatively, the easiest fix, at the cost of startup performance, is
  to call =compinit= again after adding a new directory to =$fpath=:
  #+begin_src bash :tangle no :noweb-ref dummy
  userCompletionsDir=${ZDOTDIR}/completions
  fpath+=${userCompletionsDir}
  compinit
  #+end_src

**** Enable support for Bash completions
#+begin_src bash
autoload -U +X bashcompinit && bashcompinit
#+end_src

**** Program-specific completions
***** Git
# This section is using zero width spaces (ZERO WIDTH SPACE [00200B]) in some places.
# this comment may be placed anywhere else that is using it.

# [2022-03-30 Wed 18:27:02]
Install =bash-completion=

Download [[https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh][git-completion.zsh]] to a file named =_git= and place it in a
directory present in the =$fpath= array.
#+begin_src bash
is_command git &&
    download_to_user_fpath _git 'https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh'
#+end_src


***** Stack bash/zsh auto-completion                               :noexport:
# *NOTE*: This is valid for the arch repo install
# #TODO check ghcup's version
# [2022-11-09 Wed 22:01:58 -03]

[[https://docs.haskellstack.org/en/stable/shell_autocompletion/][Shell auto-completion - The Haskell Tool Stack]]
# [2022-05-11 Wed 16:30:14]
Install =stack=
#+begin_src bash
is_command stack && {
    is_user_fpath_file "$1" ||
        stack --bash-completion-script `which stack` > "$localFPATH"/_stack
}

#+end_src
make sure this is sourced before a call of =compinit=. Alternatively
source it directly with:
: source <(stack --bash-completion-script `which stack`)
# Alternatively, place the contents of =<(..)= in a file of any =$fpath=
# directory called =_stack=.

**** compinstall
#+begin_src bash
# The following lines were added (generated) by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' matcher-list '+' 'l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:]}={[:upper:]} r:|[._-]=** r:|=**'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle :compinstall filename "$ZDOTDIR/.zshrc"

# autoload -Uz compinit && compinit
_comp_options+=(globdots) # Include hidden files.
# End of lines added by compinstall
#+end_src

**** Custom completion files
#+begin_src bash
shellCompletionDir=${XDG_DATA_HOME}/shell-completion
[[ -d ${shellCompletionDir}/zsh ]] && fpath+=${shellCompletionDir}/zsh
#+end_src

**** compinit
After all =$fpath= setup, call =compinit=
#+begin_src bash
autoload -Uz compinit && compinit
#+end_src

**** Source bash completion files
Sourcing bash completion files have to be done after =compinit= because
they may only be interpreted when =zsh= loaded the =compdef= function,
provided by =compinit=.
# [2023-06-12 Mon 08:54:59 -03]
#+begin_src bash
[[ -d ${shellCompletionDir}/bash ]] &&
    for file in $(find "${shellCompletionDir}"/bash/* -type f); do
        [[ -f ${file} ]] && source "${file}"
    done
#+end_src

*** History
Default zsh history setup
#+begin_src bash
[[ -d ${XDG_STATE_HOME}/zsh ]] || mkdir -p "${XDG_STATE_HOME}"/zsh
export HISTFILE=$XDG_STATE_HOME/zsh/history
export HISTSIZE=10000000
export SAVEHIST=10000000
#+end_src

Clean duplicates in zsh's history memory, not file.
[[https://unix.stackexchange.com/questions/599641/why-do-i-have-duplicates-in-my-zsh-history/599656#599656][Why do I have duplicates in my zsh history? - Unix & Linux Stack Exchange]]
# [2022-11-08 Tue 18:33:01 -03]
#+begin_src bash
setopt histignorealldups
#+end_src

also more duplicates options can be set with:
#+begin_example shell
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
#+end_example

*** atuin: History alternative
:PROPERTIES:
:CUSTOM_ID: orgid-qromov
:END:
[[https://github.com/atuinsh/atuin][GitHub - atuinsh/atuin: ✨ Magical shell history]]

- Install =atuin= from standard repos
  + run =atuin import auto= for importing the current shell history into
    atuin's database.
  + add =eval "$(atuin init zsh)"= to =.zshrc= (alternatively print it to
    a file and source the file), also make sure to set it /after/ custom
    keybind definitions because it sets keybinds of its own.
# [2024-03-11 Mon 00:22:43 -03] @ak

Shell history third party tool
#+begin_src bash
eval "$(atuin init zsh --disable-up-arrow)"
#+end_src
# set additional keybinds
# actually use C-r for search and keep C-p default
# bindkey '^P' atuin-up-search
# [[https://github.com/atuinsh/atuin/issues/193][Custom key bindings · Issue #193 · atuinsh/atuin]]

*** zoxide: cd alternative
[[https://github.com/ajeetdsouza/zoxide][GitHub - ajeetdsouza/zoxide: A smarter cd command. Supports all major shells.]]

#+begin_src bash
eval "$(zoxide init zsh --cmd cd)"
#+end_src

*** Source setup modules
Modularized setup files sourcing
#+begin_src bash
source "$XDG_CONFIG_HOME"/shell/setup-modules-source.sh
#+end_src

*** Notes

**** stty: 'standard input': Inappropriate ioctl for device
When using =stty=, the =<$TTY >$TTY= redirections may be be
necessary in all call of it. See [[https://github.com/romkatv/powerlevel10k/issues/388#issuecomment-567679874][Issue #388 · romkatv/powerlevel10k]].



**** Add zsh completions
Add completion files that begin with undescore, like =_git=, to =$fpath=,
a custom directory can be placed in =fpath= as such:
#+begin_example
mkdir $HOME/.completions
fpath+=$HOME/.completions
#+end_example
- Also, see [[#orgid-yuoowp][compinit only working when initialized at the end of the file]].

** =.zshenv=
:PROPERTIES:
:header-args:bash: :tangle ~/.zshenv
:END:

*** TRAMP/dumb terminal check
For some reason, specially on bigger configs split between [[*TRAMP/dumb terminal check][.zshrc]] and
[[*=.zshenv=][.zshenv]], this needs to be checked on BOTH.
#+begin_src bash :noweb yes
«tramp-dumb-terminal-check»
#+end_src

*** Check if shell is "interative"
#+begin_src bash
[[ $- != *i* ]] && return
#+end_src

*** Load [[*=profile=: Shell environment variables & user-login configuration][profile: Shell environment variables & user-login configuration]]
#+begin_src bash
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
[[ -r "$XDG_CONFIG_HOME"/shell/profile ]] &&
    source "$XDG_CONFIG_HOME"/shell/profile
#+end_src

*** ZDOTDIR
=$ZDOTDIR= is the environment variable that tells ZSH where to search for its
configuration files.

The =ZDOTDIR= environment variable can be defined at boot before any
user logged-in.

Simply create the file =/etc/zsh/zshenv= and add, e.g.:
: export ZDOTDIR="$HOME/.config/zsh"

Note that Zsh reads this file first before sourcing =/etc/profile= so
setting =$ZDOTDIR= in a =/etc/profile.d= script is insufficient.
#+begin_src bash
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/shell"
#+end_src

* Setup Modules
:PROPERTIES:
:header-args: :mkdirp yes :tangle-mode o644 :shebang #!/usr/bin/echo 'This is a source only file.'
:END:
Files meant for sourcing, modulating the shell config and centralizing
program-specific setting into their own files.

Source this script to source the files in the modules directory, e.g.:
: . "$XDG_CONFIG_HOME"/shell/setup-modules-source.sh
#+begin_src shell :tangle setup-modules-source.sh
__setupModulesDir=$XDG_CONFIG_HOME/shell/setup-modules
if test -d "${__setupModulesDir}"; then
    for module in "${__setupModulesDir}"/*.sh \
                  "${__setupModulesDir}"/*.bash; do
        test -r "$module" && . "$module"
    done
    unset module
fi
unset __setupModulesDir
#+end_src

** Source functions
:PROPERTIES:
:header-args:shell: :tangle setup-modules/functions.sh
:END:

#+begin_src shell
source "$XDG_CONFIG_HOME/shell/functions"
#+end_src

** Shell colors
:PROPERTIES:
:header-args:shell: :tangle setup-modules/colors.sh
:END:

Source =LS_COLORS=. Some programs support it but default to something
else when =LS_COLORS= is unset, e.g. =fd=. See [[https://github.com/sharkdp/fd/issues/368][Issue #368 · sharkdp/fd]].
#+begin_src bash
LS_COLORS_ENV_FILE=${XDG_DATA_HOME}/LS_COLORS_ENV
if [ ! -s "${LS_COLORS_ENV_FILE}" ]; then
    dircolors > "${LS_COLORS_ENV_FILE}"
    source "${LS_COLORS_ENV_FILE}"
else
    source "${LS_COLORS_ENV_FILE}"
fi
#+end_src

aliases
#+begin_src shell
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
#+end_src

environment variables
#+begin_src shell
export MANPAGER="bat" # or "less -R --use-color -Dd+r -Du+b"
#+end_src

#+begin_src shell
export LESSOPEN="| /usr/bin/source-highlight-esc.sh %s"
export LESS='-R --use-color -Dd+g$Du+m'
#+end_src
See the meaning of the =-D/--color= flags:
: man less | less +/'-Dxcolor or --color=xcolor'
# : man less | sed -n '/-Dxcolor or --color=xcolor/,/-e or --quit-at-eof/p' | $PAGER

#+begin_src shell
export SYSTEMD_COLORS=256
export TERM='xterm-256color' # TrueColor output
export COLORTERM='truecolor'
#+end_src

** nnn file manager

*** Interactive shell setup
:PROPERTIES:
:header-args:shell: :tangle setup-modules/nnn.bash
:END:
# n³
- Using =.bash= as extension for sourceable files and adding a echo shebang.
  See https://unix.stackexchange.com/a/299621.

The nnn file manager is configured by environment variables.
#+begin_src shell
append_nnn_plug_commands() {
    # local mode="$1"  # 'append' or 'replace'
    local items="$1"

    # if [[ "$mode" == "append" ]]; then
    NNN_PLUG_COMMANDS="${NNN_PLUG_COMMANDS:+$NNN_PLUG_COMMANDS;}$items"
    # elif [[ "$mode" == "replace" ]]; then
    #     # #todo replace using string matching?
    #     NNN_PLUG_COMMANDS="$items"
    # else
    #     echo "Invalid mode. Please specify 'append' or 'replace'."
    #     return 1
    # fi
}


append_nnn_plug_official() {
    local items="$1"

    NNN_PLUG_OFFICIAL="${NNN_PLUG_OFFICIAL:+$NNN_PLUG_OFFICIAL;}$items"
}

alias anpca='append_nnn_plug_commands'
alias anpoa='append_nnn_plug_official'

anpca '0:!sacdx "$nnn"'
anpca 'm:!mediainfo-color "$nnn"'
# anpca 'q:!clear && audio-quality "$nnn"'
# anpca 'E:!echo-files "$nnn"'
anpca 'o:launch4nnn'
anpca 'x:xtosubdir4nnn'
anpca 's:dusum4nnn'
# anpca 'a:!archive "$nnn"'
# anpca 'c:!archive -11 "$nnn"'
# anpca 'r:rclone-gcrypt-to-local4nnn'

anpoa 'd:dragdrop'
anpoa 'F:fzopen'
anpoa 'i:imgview'
anpoa 'p:preview-tui'
anpoa 'z:autojump' # using with zoxide

## nnn = https://github.com/jarun/nnn/wiki/Usage#configuration
NNN_PLUG="$NNN_PLUG_COMMANDS;$NNN_PLUG_OFFICIAL"
export NNN_PLUG
export NNN_TRASH=1

# BLK="04" CHR="04" DIR="04" EXE="00" REG="00" HARDLINK="00" SYMLINK="06" MISSING="00" ORPHAN="01" FIFO="0F" SOCK="0F" OTHER="02"
# export NNN_FCOLORS="0404040404040404"

# export NNN_COLORS="2136" # colors of the 4 "workspaces"
# export NNN_TMPFILE=${XDG_STATE_HOME:-$HOME/.local/state}/nnn/lastd
# [[ ! -d ${NNN_TMPFILE%lastd} ]] && mkdir -p "${NNN_TMPFILE%.lastd}"
# export NNN_SEL=${XDG_STATE_HOME:-$HOME/.local/state}/nnn/selection
export NNN_TMPFILE=/tmp/nnn.tmp
export NNN_FIFO=/tmp/nnn.fifo
export NNN_SEL=/tmp/nnn.sel
#export NO_COLOR=1
#NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_OPENER="$OPENER"
export NNN_FALLBACK_OPENER="$OPENER"
# Hidden files on top
export LC_COLLATE="C"

# used by plugins
export NNN_PREVIEWIMGPROG=chafa
export NNN_PAGER=$PAGER
export NNN_TERMINAL=$TERMINAL


# include hidden files on 'r'ename
# [[https://github.com/jarun/nnn/commit/49be2cfcd19e800f69f2aa4e371db2bb13fc6a7c][Fix #1153: sync hidden on batch rename · jarun/nnn@49be2cf]]
export INCLUDE_HIDDEN=1
n() {
    VISUAL=$EDITOR # nnn reads in order: $VISUAL -> $EDITOR -> vi

    # Block nesting of nnn in subshells
    [ "${NNNLVL:-0}" = 0 ] || {
        echo "nnn is already running"
        return
    }

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # export NNN_TMPFILE="${XDG_STATE_HOME:-$HOME/.local/state}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    # set color scheme
    # nnn_dark_light_set # defined in sourced `nnn-setup.bash'
    # ^ disabled because using 'proper' ansi color theme.

    if command -v cpg >/dev/null && command -v mvg >/dev/null; then
        nnn -EHr "$@"
    else
        nnn -EH "$@"
    fi

    if [ -f "$NNN_TMPFILE" ]; then
        . "$NNN_TMPFILE"
        rm -f "$NNN_TMPFILE" > /dev/null
    fi
}

nnn_cd()
{
    if ! [ -z "$NNN_PIPE" ]; then
        printf "%s\0" "0c${PWD}" > "${NNN_PIPE}" !&
    fi
}

trap nnn_cd EXIT
#+end_src

**** nnn Colors
#+begin_src shell
block=08
char=03
dir=04
exe=02
regular=00
hardlink=05
symlink=06
miss=07 # also affects details
orph=09
fifo=0d
socket=05
unkn=01

export NNN_FCOLORS="$block$char$dir$exe$regular$hardlink$symlink$miss$orph$fifo$socket$unkn"

unset block char dir exe regular hardlink symlink miss orph fifo socket unkn
#+end_src

*** nnn Plugins
:PROPERTIES:
:header-args:shell: :shebang #!/usr/bin/env sh :tangle-mode o755
:tangle-dir: (expand-file-name "nnn/plugins" (xdg-config-home))
:END:

Install plugins from [[https://github.com/jarun/nnn/tree/master/plugins][jarun/nnn/plugins]].

**** launch4nnn
:PROPERTIES:
:header-args:shell+: :tangle (tdir "launch4nnn")
:END:

#+begin_src shell
#
# Description: Launches applications using $(launch)
#
# Dependencies: launch (custom launch script)
#
# Note: Works _only_ with selection (nnn can toggle the mode for the hovered file)
#
# Shell: POSIX compliant
# Author: 11xx (using Arun Prakash Jana's 'togglex' plugin as template)

command -v launch >/dev/null || {
    notify-send -a 'NNN plugin' \
                "Unable to exectute plugin \"${0}\"" \
                '"launch" command not found.'
    exit 1
}

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    xargs -0 launch < "$selection"

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
else
    launch "$1"
fi
#+end_src

**** xtosubdir4nnn
:PROPERTIES:
:header-args:shell+: :tangle (tdir "xtosubdir4nnn")
:END:

#+begin_src shell
command -v xtosubdir >/dev/null || {
    notify-send -a 'NNN plugin' \
                "Unable to exectute plugin \"${0}\"" \
                '"xtosubdir" command not found.'
    exit 1
}

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    xargs -0 xtosubdir < "$selection"

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
else
    xtosubdir "$1"
fi
#+end_src

**** dusum4nnn
:PROPERTIES:
:header-args:shell+: :tangle (tdir "dusum4nnn")
:END:

#+begin_src shell
command -v dusum >/dev/null || {
    notify-send -a 'NNN plugin' \
                "Unable to exectute plugin \"${0}\"" \
                '"dusum" command not found.'
    exit 1
}

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    xargs -0 dusum < "$selection" | less

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
else
    dusum "$1" | less
fi
#+end_src

** Haskell
:PROPERTIES:
:header-args:shell: :tangle setup-modules/haskell.sh
:END:

*** GHCup
Fail short if =ghcup= is not found
#+begin_src shell
! is_command ghcup && {
    printf '%s: ghcup not found. Skipping...\n' "$0" >&2
    return 1
}
#+end_src

Custom install directory for GHCup downloads.
#+begin_src shell
GHCUP_BIN_DIR=${XDG_BIN_HOME%/*}/ghcup-bin
#+end_src

This path is overriden by [[(ghcup-alias-bin-anchor)][an alias]], GHCup installs binaries and links
to =XDG_BIN_HOME= so with alias it is possible to override where it
installs and manages its files.
#+begin_src shell
is_command prepend_path &&
    prepend_path "${GHCUP_BIN_DIR}"
#+end_src
- Arch Linux Note: When building a PKGBUILD, its build process uses
  the running shell's PATH, so it may try to use GHCup's binaries and
  probably fail. To fix this remove GHCup's binaries from PATH before
  building the PKGBUILD e.g.:
  : PATH=$(echo $PATH | sed 's,/home/user/.local/ghcup-bin:,,') paru
  or if the directory to be removed is the first in PATH:
  : PATH=${PATH#*:} paru
  So to fix this simply alias the commands:
  #+begin_src shell
  __newPath=$(
      printf '%s\n' "$PATH" |
          awk -v ghcupdir=${GHCUP_BIN_DIR} \
              '{ sub(ghcupdir":", "", $0); print $0":"ghcupdir }'
           )
  is_command paru && # make sure variables expand.
      alias paru="PATH=\"${__newPath}\" paru"

  is_command makepkg &&
      alias makepkg="PATH=\"${__newPath}\" makepkg"

  unset __newPath
  #+end_src
  + Note: the aliases let the local variable ~__newPath~ expand because
    it is cleaned after the alias definition. Normally aliases can
    contain unexpanded variables since when run those variables expand
    at runtime.

#+begin_src shell
export GHCUP_USE_XDG_DIRS=t # https://www.haskell.org/ghcup/guide/#xdg-support
#+end_src

To prevent GHCup "littering" =XDG_BIN_HOME= it can be overriden by:
#+begin_src shell -r
alias ghcup='XDG_BIN_HOME="$GHCUP_BIN_DIR" ghcup'  (ref:ghcup-alias-bin-anchor)
#+end_src

Also give precedence to =$GHCUP_BIN_DIR= in =$PATH= for Haskell build tools
#+begin_src shell
alias cabal='PATH="$GHCUP_BIN_DIR":"$PATH" cabal'
#+end_src


Define some functions for working with Arch Linux's PKGBUILDs using
system PATH
#+begin_src shell
ghcup_remove_bin_dir_from_path() {
    export PATH=$(printf '%s\n' "$PATH" | sed "s,${GHCUP_BIN_DIR}:,,")
    unalias cabal
}
#+end_src
# - Install Arch Linux packages for using arch-hs:
#   + ghc
#   + ghc-libs
#   + cabal-install
#   + arch-hs-git

**** Stack integration with GHCup
:PROPERTIES:
:header-args:shell: :tangle (expand-file-name "stack/hooks/ghc-install.sh" (xdg-data-home)) :tangle-mode o755 :shebang #!/bin/sh :mkdirp yes
:END:
- Stack integration with GHCup
  https://www.haskell.org/ghcup/guide/#strategy-1-stack-hooks-new-recommended

- Using a Stack hook. Example script from:
  : https://raw.githubusercontent.com/haskell/ghcup-hs/master/scripts/hooks/stack/ghc-install.sh
  hooks are only run when =system-ghc: false=
  : stack config set system-ghc false --global

#+begin_src shell
# !! KEEP THIS SCRIPT POSIX COMPLIANT !!

# see https://docs.haskellstack.org/en/stable/configure/customisation_scripts/#ghc-installation-customisation
# for documentation about hooks

# Stack integration with GHCup
# https://www.haskell.org/ghcup/guide/#strategy-1-stack-hooks-new-recommended

set -eu

XDG_BIN_HOME=${XDG_BIN_HOME:-$HOME/.local/bin}
export GHCUP_BIN_DIR=${XDG_BIN_HOME%/*}/ghcup-bin
__newPath=$(
    printf '%s\n' "$PATH" |
        awk -v ghcupdir=${GHCUP_BIN_DIR} \
            '{ sub(ghcupdir":", "", $0); print $0":"ghcupdir }'
         )
unset __newPath

alias ghcup="XDG_BIN_HOME=$GHCUP_BIN_DIR ghcup"

case $HOOK_GHC_TYPE in
    bindist)
        ghc_path=$(ghcup whereis ghc "$HOOK_GHC_VERSION" || { ghcup install ghc "$HOOK_GHC_VERSION" >/dev/null && ghcup whereis ghc "$HOOK_GHC_VERSION" ; }) || { >&2 echo "Installing $HOOK_GHC_VERSION via ghcup failed" exit 3 ;}
        printf "%s" "${ghc_path}"
        ;;
    git)
        # TODO: should be somewhat possible
        >&2 echo "Hook doesn't support installing from source"
        exit 1
        ;;
    *)
        >&2 echo "Unsupported GHC installation type: $HOOK_GHC_TYPE"
        exit 2
        ;;
esac
#+end_src

*** Aliases for Haskell tools
- [[https://vrom911.github.io/blog/haskell-aliases][Haskell Aliases]]
#+begin_src shell
cabal_install_copy() {
    cabal install \
          --overwrite-policy=always \
          --install-method=copy \
          "$@"
}

cabal_install_copy_dir() {
    cabal_install_copy \
        --installdir="${cabalInstallDir:-dist}" \
        --enable-profiling \
        --enable-executable-profiling \
        "$@"
}

alias cinstall=cabal_install_copy
alias cidist=cabal_install_copy_dir
alias ci.='cabalInstallDir=. cabal_install_copy_dir'
#+end_src

*** Cabal
=cabal install= bin directory.
#+begin_src shell
export CABAL_DIR="$XDG_DATA_HOME"/cabal
export CABAL_CONFIG="$XDG_CONFIG_HOME"/cabal/config
append_path "$CABAL_DIR"/bin
#+end_src

*** Stack
#+begin_src shell
export STACK_ROOT="$XDG_DATA_HOME"/stack
export STACK_XDG=1
#+end_src

** Vault
:PROPERTIES:
:header-args:shell: :tangle setup-modules/vault.sh
:END:
Private repo to accompany the public one. This should be hosted
privately (in a local pc for example) and holds all other files meant
for proper desktop usage.
#+begin_src shell
alias vot='git --git-dir="$HOME/.local/vault.git" --work-tree="$HOME"'
#+end_src

** MPD
:PROPERTIES:
:header-args:shell: :tangle setup-modules/mpd.sh
:CUSTOM_ID: orgid-upnrlu
:END:
#+begin_src shell
alias m='ncmpcpp --config="$XDG_CONFIG_HOME/mpd/ncmpcpp-config" --bindings="$XDG_CONFIG_HOME/mpd/ncmpcpp-bindings"'
alias mm='rmpc'
#+end_src

** Wine

*** Default prefix
:PROPERTIES:
:header-args:shell: :tangle setup-modules/wine.sh
:END:
#+begin_src shell
wineDefaultPrefixDir=${XDG_DATA_HOME}/wine/prefixes/default
/usr/bin/mkdir -p "${wineDefaultPrefixDir}"
alias winedef="WINEPREFIX=${wineDefaultPrefixDir} wine"
unset wineDefaultPrefixDir
#+end_src

** GTK & Qt: Uniform look & live theme change
:PROPERTIES:
:header-args:shell: :tangle setup-modules/gtk-qt.sh
:CUSTOM_ID: orgid-twrkwj
:END:

- See the notes about this setup:
  + [[file:~/.config/darkman/README.org::#orgid-tjunht][darkman: GTK & QT: Uniform look and live theme change]]

Make Qt apps listen to =plasma-apply-colorscheme=
#+begin_src shell
export QT_QPA_PLATFORMTHEME=kde
#+end_src

Make GTK apps use a different file picker and read settings form the
portal depending on the XDG Desktop Portal (e.g. KDE's).
- *NOTE*:
  + To use this install =xdg-desktop-portal-gtk=.
    # [2024-09-07 Sat 12:54:06 -03] @ak
  + This may break more GTK apps than help and since
    =xdg-desktop-portal= doesn't really (yet) respect the config file
    order and it may cause slowdowns at Window Manager's startup.
    * See note in:
      - [[file:~/.config/xdg-desktop-portal/README.org::#orgid-uxoxxl][GTK apps lost font rendering, cursor theme or other settings]]
  + An alternative to this is to enable it on specific programs that
    should use it instead of enabling globally.
#+begin_src shell
# export GTK_USE_PORTAL=1
#+end_src

Make wrapper scripts that use ~QT_QPA_PLATFORMTHEME=gnome~ take
precedente, for pairing with =qgnomeplatform=.
#+begin_src shell
is_command prepend_path &&
    prepend_path "${XDG_DATA_HOME}/qt-platform-theme-wrappers"
#+end_src

# # ** Desktop Toolkit Theme
# # export QT_STYLE_OVERRIDE=adwaita-dark # deprecated by qgnomeplatform:
# # PS qgnomeplatform also is deprecated since 2023 [2024-09-02 Mon 06:29:21 -03] @ak
# #+begin_src shell
# # export QT_QPA_PLATFORMTHEME=gnome

# # export QT_WAYLAND_DECORATION=adwaita
# # provided by qadwaitadecorations-qt{5,6}-git, doesn't change Qt theme though
# #+end_src
# # AUR package 'qgnomeplatform-{common,qt5,qt6}-git'
# # env = QT_QPA_PLATFORMTHEME,gnome

** C Programming Language
:PROPERTIES:
:header-args:shell: :tangle setup-modules/c-prog.sh
:END:

Helper functions for running C files as scripts
#+begin_src shell
gcc-run-a.out () {
    gcc -std=c23 -Wall -Werror -fsanitize=address "$1" && ./a.out
}

gcc-no-sanitize-run-a.out () {
    gcc -std=c23 -Wall -Werror "$1" && ./a.out
}
#+end_src

** GPG
:PROPERTIES:
:header-args:shell: :tangle setup-modules/gpg.sh
:END:
#+begin_src shell
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
mkdir -p -m 700 "$GNUPGHOME"
#+end_src

The following is recommended in =man gpg-agent=:
#+begin_src shell
GPG_TTY=$(tty)
export GPG_TTY
#+end_src

** NPM
:PROPERTIES:
:header-args:shell: :tangle setup-modules/npm.sh
:END:

#+begin_src shell
append_path "$XDG_DATA_HOME/npm/bin"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export npm_config_devdir="$XDG_CACHE_HOME"/gyp # https://github.com/nodejs/node-gyp
export NVM_DIR="$XDG_DATA_HOME"/nvm
#+end_src


** Rust
:PROPERTIES:
:header-args:shell: :tangle setup-modules/rust.sh
:END:

*** Cargo
=cargo install= bin directory
#+begin_src shell
export CARGO_HOME="$XDG_DATA_HOME"/cargo
append_path "$CARGO_HOME"/bin
#+end_src



** Go
:PROPERTIES:
:header-args:shell: :tangle setup-modules/go.sh
:END:

=go install= bin directory
#+begin_src shell
export GOPATH="$XDG_DATA_HOME"/go
append_path "$GOPATH"/bin
#+end_src


** Sqlite
:PROPERTIES:
:header-args:shell: :tangle setup-modules/sqlite.sh
:END:

#+begin_src shell
sqlite_all_tables() {
    sqlite3 "$1" "SELECT name FROM sqlite_master WHERE type='table'" |
        xargs -I{} sqlite3 -table "$1" "SELECT * FROM {}"
}
#+end_src


* Local file variables                                             :noexport:
# Local Variables:
# org-confirm-babel-evaluate: nil
# eval: (org-babel-do-load-languages 'org-babel-load-languages '((shell . t)))
# End:

# meta comments
# #+title: ZSH Shell configuration.
# <2021-12-22 Wed 15:19>
# moved here (arch-linux.org) [2022-03-30 Wed 17:47:48]
# moved here arch-linux.org [2022-04-01 Fri 01:57:29]
# moved back # [2022-11-30 Wed 08:01:05 -03]
# moved back # [2022-12-12 Mon 19:17:12 -03]
# moved to ~/.config/shell/ # [2023-06-03 Sat 12:14:11 -03]
# back at # [2024-01-22 Mon 16:28:06 -03] @arch
