context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Browser Sink"
            audio.position = [ FL FR ]
            capture.props = {
                node.name        = "browser-sink"
                media.class      = "Audio/Sink"
                node.description = "Browser Sink"
                # Make it appear as a real device in pulsemixer
                device.description = "Browser Sink"
                device.class       = "sound"
                device.icon-name   = "audio-card"
                node.virtual       = false
            }
            playback.props = {
                node.name      = "browser-sink-output"
                node.passive   = true
                target.object  = "easyeffects_sink"
            }
        }
    }
]
