RIGHT        seek 1 exact
LEFT         seek -1 exact
Ctrl+RIGHT   seek 5
Ctrl+LEFT    seek -5
LEFT         seek -1 exact
LEFT         seek -1 exact
s            ignore
Shift+UP     seek  600
Shift+DOWN   seek -600
#            =            cycle video-unscaled
#            -            cycle-values window-scale 2 3 1 .5
UP           add volume 5
DOWN         add volume -5
#WHEEL_UP    add volume 5
WHEEL_UP     seek 2
#WHEEL_DOWN  add volume -5
WHEEL_DOWN   seek -2
WHEEL_LEFT   ignore
WHEEL_RIGHT  ignore
Alt+RIGHT    add video-rotate 90
Alt+LEFT     add video-rotate -90
-        add video-zoom -0.25
=        add video-zoom 0.25
+        add video-zoom 0.25
Ctrl+f       add video-pan-x 0.05
Ctrl+b       add video-pan-x -0.05
Ctrl+p       add video-pan-y -0.05
Ctrl+n       add video-pan-y 0.05
Ctrl+BS      set video-zoom 0; set video-pan-x 0; set video-pan-y 0; set video-scale-x 1; set video-scale-y 1
Ctrl+0       set video-zoom 0; set video-pan-x 0; set video-pan-y 0; set video-scale-x 1; set video-scale-y 1
# numpad, keypad
END          quit
KP0          playlist-next
KP_ENTER     playlist-next
KP_DEC       playlist-prev
/            ignore
w add speed -0.1
e add speed 0.1
r            set speed 1
# top row numbers
0            seek 0 absolute-percent
1            ignore
2            ignore
3            ignore
4            ignore
5            ignore
6            ignore
7            ignore
8            ignore
9            ignore

# Keybinding to cycle through video aspect ratios
A            cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "1:1" "9:16" "5:4" "3:2" "14:9" "21:9" "32:9" "64:27" "-1"

R            set video-aspect-override -1

# S            cycle shuffle
shift+s      cycle shuffle

# Audio sync
KP4          add audio-delay 0.100
KP5          add audio-delay -0.100
KP6          set audio-delay 0 # Reset audio delay
# sub timings
KP1          add sub-delay 0.1
KP2          add sub-delay -0.1
KP3          set sub-delay 0 # Reset subtitle delay
# Video scale

KP7   add video-scale-x  0.025
KP8   add video-scale-y  0.025
KP9   set video-scale-x 1; set video-scale-y 1
# Ctrl+Alt+n   add video-scale-y -0.05  # shrink vertically
# Ctrl+Alt+g   set video-scale-x 1; set video-scale-y 1 # reset scale

Ctrl+Alt+f   add video-scale-x  0.025  # expand horizontally
Ctrl+Alt+b   add video-scale-x -0.025  # shrink horizontally
Ctrl+Alt+p   add video-scale-y  0.025  # expand vertically
Ctrl+Alt+n   add video-scale-y -0.025  # shrink vertically
Ctrl+Alt+g   set video-scale-x 1; set video-scale-y 1 # reset scale

Ctrl+Alt+h   add video-scale-x  0.025  # expand horizontally
Ctrl+Alt+l   add video-scale-x -0.025  # shrink horizontally
Ctrl+Alt+j   add video-scale-y  0.025  # expand vertically
Ctrl+Alt+k   add video-scale-y -0.025  # shrink vertically

a script-message toggle-fullpath

h vf toggle hflip # toggle horizontal mirror
# v vf toggle vflip # toggle vertical flip​

Ctrl+h cycle-values hwdec nvdec-copy none
Ctrl+Alt+v cycle drm-vrr-enabled
