#osc=no
#osd-bar=no

# hwdec=nvdec
hwdec=nvdec-copy

cache=auto
demuxer-max-back-bytes=5GiB
demuxer-max-bytes=7GiB
watch-later-directory=~/.local/share/mpv/watch_later

# audio-device='alsa/front:CARD=Pro,DEV=0'
# audio-exclusive=yes
# demuxer-rawaudio-format=u32be

# https://superuser.com/questions/1051206/how-can-i-make-mpv-show-the-duration-counter-constantly
# osd-level=2
# osd-font-size=20
# osd-blur=12
# osd-scale=
# osd-scale-by-window=no

# https://hund.tty1.se/2021/10/12/how-to-use-yt-dlp-instead-of-yt-dl-with-mpv.html
# script-opts-append=ytdl_hook-ytdl_path=yt-dlp
# https://www.reddit.com/r/mpv/comments/opoorx/mpv_with_ytdlp/
# script-opts=ytdl_hook-ytdl_path=yt-dlp
# script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp



# keep open after last video ends
# [[https://unix.stackexchange.com/questions/390574/make-mpv-hold-on-the-last-picture-instead-of-closing/390579#390579][Make mpv hold on the last picture instead of closing - Unix & Linux Stack Exchange]]
# [2022-11-12 Sat 21:15:02 -03]
# keep-open=yes
force-window=yes # for audio

# sub-color='#bfbfbf' #subtitle color in rgb
# sub-shadow-color='#000000' #shadow color
# # sub-font='Noto Sans' #set font
# # sub-bold=yes
# sub-font-size=35
# # sub-pos=95 #subtitle position 5 percent above the bottom of the screen
# sub-blur=4

sub-font='Arial Regular'
sub-border-size=1
sub-color='#CDCDCD'
# sub-shadow=3


# Customize .ass fonts
# - Defined subtitle font using sub-font & sub-ass-force-style=FontName is no longer working · Issue #7333 · mpv-player/mpv
#   https://github.com/mpv-player/mpv/issues/7333
# - Mpv ignores ass-force-style when subtitle is str · Issue #1994 · mpv-player/mpv
#   https://github.com/mpv-player/mpv/issues/1994
# - How to change font when using ASS subtitle style override : r/mpv
#   https://www.reddit.com/r/mpv/comments/uadg7v/how_to_change_font_when_using_ass_subtitle_style/
# ass-style-override='FontName=Arial,Default.Regular=1,Default.FontSize=24,Shadow=1.5,BackColour=Black'
sub-ass-style-overrides='PrimaryColour=&H00BFBFBF'

profile=high-quality

alang=jp,jpn,eng,en
slang=en,eng

osd-bar-align-y=-1
osd-align-y=top
osd-font='LiterationSans Nerd Font'
osd-playing-msg='file: ${filename}'

osd-scale-by-window=no

screenshot-format=jxl

[lowvram]
profile-desc=Playback while another process holds the GPU memory
vo=dmabuf-wayland
