continue=true
log=/home/lobo/.local/state/aria2/aria2c.log
console-log-level=warn
summary-interval=0
file-allocation=none
max-concurrent-downloads=4
split=16
max-connection-per-server=16
min-split-size=32M
check-integrity=true
# dir=${HOME}/Downloads/aria2
