#!/usr/bin/env sh
command -v dusum >/dev/null || {
    notify-send -a 'NNN plugin' \
                "Unable to exectute plugin \"${0}\"" \
                '"dusum" command not found.'
    exit 1
}

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    xargs -0 dusum < "$selection" | less

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
else
    dusum "$1" | less
fi
