#!/usr/bin/env sh
command -v xtodir >/dev/null || {
    notify-send -a 'NNN plugin' \
                "Unable to exectute plugin \"${0}\"" \
                '"xtodir" command not found.'
    exit 1
}

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    xargs -0 xtodir < "$selection"

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
else
    xtodir "$1"
fi
