---
aiagent_name: aiagent
aiagent_shell: /bin/bash
aiagent_shared_group: aiwork
aiagent_workspace_root: /home/work
aiagent_container_root: "/home/{{ aiagent_name }}/aiagent_container"
aiagent_container_dirs:
  - agents
  - opencode_config
  - opencode_share
  - opencode_state
  - codex
  - t3
  - pi
aiagent_subuid_count: 65536
aiagent_host_user: "{{ local_user_name }}"
