---
- name: Install Android utilities for PC
  community.general.pacman:
    name:
      - android-tools # provides adb
      - gvfs-mtp # for android mounting by file manager
      - scrcpy
    state: present

- name: Install Android utilities for PC from the AUR
  aur:
    name:
      - simple-mtpfs # for mounting android file system
      - android-studio
    use: paru
    state: present
  become: true
  become_user: aurbuilder
