PATH=${PATH}:${XDG_BIN_HOME}/mpd
PATH=${PATH}:${XDG_BIN_HOME}/hyprland
PATH=${PATH}:${XDG_BIN_HOME}/yt
PATH=${PATH}:${XDG_BIN_HOME}/fd-helpers
PATH=${PATH}:${XDG_BIN_HOME}/fzf-scripts
PATH=${PATH}:${XDG_BIN_HOME}/stash
PATH=${PATH}:${XDG_BIN_HOME}/emacs
PATH=${PATH}:${XDG_BIN_HOME}/git
