XAUTHORITY="$XDG_DATA_HOME"/xorg/Xauthority
XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"
TERMINFO="$XDG_DATA_HOME"/terminfo
TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
LESSHISTFILE="$XDG_STATE_HOME"/less/history
GRIPHOME="$XDG_CONFIG_HOME/grip"
# https://github.com/vercel/pkg/issues/537
PKG_CACHE_PATH="$XDG_CACHE_HOME/pkg"
# alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine
# Mailutils
MAIL="$XDG_DATA_HOME"/mail
# dotNet
NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
UNISON="$XDG_DATA_HOME"/unison
PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
IPYTHONDIR="${XDG_CONFIG_HOME}"/ipython
ANDROID_HOME=${XDG_DATA_HOME}/android
CUDA_CACHE_PATH=${XDG_CACHE_HOME}/nv
GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
ANSIBLE_HOME=${XDG_DATA_HOME}/ansible
RUSTUP_HOME=${XDG_DATA_HOME}/rustup
CALCHISTFILE=${XDG_CACHE_HOME}/calc_history
RANDFILE=${XDG_CACHE_HOME}/rnd
SQLITE_HISTORY=${XDG_CACHE_HOME}/sqlite_history
WGETRC=${XDG_CONFIG_HOME}/wgetrc

GEM_PATH=${XDG_DATA_HOME}/ruby/gems
GEM_SPEC_CACHE=${XDG_DATA_HOME}/ruby/specs
