GHCUP_BIN_DIR=${HOME}/.local/ghcup-bin

PATH=${GHCUP_BIN_DIR}:${PATH}

GHCUP_USE_XDG_DIRS=t

CABAL_DIR=${XDG_DATA_HOME}/cabal
CABAL_CONFIG=${XDG_CONFIG_HOME}/cabal/config
PATH=${PATH}:${CABAL_DIR}/bin

STACK_ROOT=${XDG_DATA_HOME}/stack
STACK_XDG=1
