[Container]
# Syntax: <filename>.volume:<container-path>
Volume=cabal-cache.volume:/home/node/.cabal
Volume=ghcup-cache.volume:/home/node/.ghcup
Volume=%h/aiagent_container/bashrc.d/ghcup-env.sh:/home/node/.bashrc.d/ghcup-env.sh:ro,Z
