source = neron-color-vars.conf

$bg-color = $neron-bg
$fg-color = $neron-fg
$hyprbars-close-color = $neron-pink
$hyprbars-maximize-color = $neron-green
$hyprbars-float-color = $neron-cyan

source = neon-dark-borders.conf
