source = light-color-vars.conf

$bg-color = $lt-bg
$fg-color = $lt-fg
$hyprbars-close-color = $lt-pink
$hyprbars-maximize-color = $lt-green
$hyprbars-float-color = $lt-cyan

source = light-borders.conf
