# basic
$colorBlack = rgb(000000)
$colorWhite = rgb(ffffff)
$colorGrayBg = rgb(cccccc)

# light theme
$colorMonowhiteBg = $colorWhite
$colorMonowhiteFg = rgb(545e62)
$colorMonowhiteRed = rgb(ba0d0d)
$colorMonowhiteCyan = rgb(006861)
$colorMonowhitePink = rgb(b30071)
$colorMonowhiteGreen = rgb(1c6b00)

# dark theme (neron)
$colorNeronBg = rgb(222222)
$colorNeronGreen = rgb(61bd09)
$colorNeronPink = rgb(ff77cf)
$colorNeronCyan = rgb(16b0cf)
$colorNeronFg = rgb(a6a8a9)
$colorNeronCurrent = rgb(2f2f2f)
$colorNeronOrange = rgb(fd892c)

# misc
$colorCurrentIcon = rgb(666666)
$colorYtOrange = rgb(ef6c00)
$colorTransparent = rgba(ff000000)
