$black = rgb(000000)
$gray-bg = rgb(cccccc)
$white = rgb(ffffff)
$lt-bg = $white
$lt-fg = rgb(545e62)
$lt-red = rgb(ba0d0d)
$lt-cyan = rgb(006861)
$lt-pink = rgb(b30071)
$lt-green = rgb(1c6b00)

$bg-secondary = rgb(f6f6f6)
