---
- name: 'gak_media: Create the stack directory tree'
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
  - '{{ gak_media_dir }}'
  - '{{ gak_media_dir }}/.config'
  tags:
  - gak-media-config
