animations {
  enabled = false
  # animation=NAME,ONOFF,SPEED,CURVE[,STYLE]
  animation = windows     , 1, 2, default, popin
  animation = windowsOut  , 1, 2, default
  animation = border      , 1, 2, default
  animation = borderangle , 1, 2, default
  animation = fade        , 1, 2, default
  animation = workspaces  , 1, 2, default, fade
}
