# don't forget to set $mainMod aka SUPER
bind =                         , catchall, submap, reset
bind = $mainMod                , catchall, submap, reset
bind = $mainMod ALT            , catchall, submap, reset
bind = $mainMod CTRL           , catchall, submap, reset
bind = $mainMod SHIFT          , catchall, submap, reset
bind = $mainMod ALT CTRL       , catchall, submap, reset
bind = $mainMod ALT SHIFT      , catchall, submap, reset
bind = $mainMod CTRL SHIFT     , catchall, submap, reset
bind = $mainMod ALT CTRL SHIFT , catchall, submap, reset
