-- monitors.conf used to be generated by nwg-displays. Keep a sane fallback in
-- Lua; explicit monitor rules can be added here or generated as Lua later.
hl.monitor({
  output = "desc:Dell Inc. DELL P2418D 29J0P96K06MT",
  mode = "2560x1440@59.95",
  position = "0x0",
  scale = 1.25,
})

hl.monitor({
  output = "desc:Dell Inc. DELL S2721DGF FZ6B4H3",
  mode = "2560x1440@165.08",
  position = "2048x0",
  scale = 1.0,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL S2721DGF FZ6B4H3", default = true })
hl.workspace_rule({ workspace = "2", persistent = true })
hl.workspace_rule({ workspace = "3", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:Dell Inc. DELL P2418D 29J0P96K06MT", default = true })
hl.workspace_rule({ workspace = "5", persistent = true })
hl.workspace_rule({ workspace = "6", persistent = true })
hl.workspace_rule({ workspace = "7", persistent = true })
hl.workspace_rule({ workspace = "8", persistent = true })
hl.workspace_rule({ workspace = "9", persistent = true, gaps_in = 0, gaps_out = 0, no_rounding = true })
hl.workspace_rule({ workspace = "10", persistent = true })

for _, selector in ipairs({ "w[t1]", "w[tg1]", "f[1]" }) do
    hl.workspace_rule({ workspace = selector, gaps_in = 0, gaps_out = 0, border_size = 1 })
end
