general {
    allow_tearing = true
}

env = WLR_DRM_NO_ATOMIC,1

windowrule = immediate,class:^eldenring.exe$
windowrule = immediate,class:^gamescope$
windowrule = immediate,class:^steam_app_[0-9]+$
windowrule = immediate,class:^mpv$
windowrule = immediate,class:love,title:Freesync test
