general {
    allow_tearing = true
}

env = WLR_DRM_NO_ATOMIC,1

windowrulev2 = immediate,class:^eldenring.exe$
windowrulev2 = immediate,class:^gamescope$
windowrulev2 = immediate,class:^steam_app_[0-9]+$
windowrulev2 = immediate,class:^mpv$
windowrulev2 = immediate,class:love,title:Freesync test
