# =hypridle.conf=: Idle management daemon
# :PROPERTIES:
# :header-args:conf: :tangle hypridle.conf :comments org
# :END:
# - [[https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/][hypridle – Hyprland Wiki]]

# - Monitor DPMS and brightness for hypridle ::

listener {
    timeout = 1200 # 20m
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
