require("lib")
require("displays-workspaces")
require("startup")
require("environment")
require("keywords")
require("window-rules")
require("layer-surface-rules")
require("hyprmacs-keymap")
require("keybinds")
dofile((os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/systemd/agent-resources.lua")
require("theme")
require("nvidia")
require("vrr")
require("plugins.hyprbars")
require("enable-tearing")
require("misc-snippets")
require("idleinhibit")

local dev_ok, dev_err = pcall(require, "dev")
if not dev_ok and not dev_err:find("module 'dev' not found", 1, true) then
  error(dev_err)
end
