require("lib")
require("displays-workspaces")
require("startup")
require("environment")
require("keywords")
require("window-rules")
require("layer-surface-rules")
require("keybinds")
require("theme")
require("nvidia")
require("vrr")
-- require("plugins.hyprbars")
require("enable-tearing")
require("misc-snippets")
require("idleinhibit")
