require("lib")
require("displays-workspaces")
require("startup")
require("environment")
require("keywords")
require("window-rules")
require("layer-surface-rules")
require("hyprmacs-keymap")
require("keybinds")
dofile((os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/systemd/agent-resources.lua")
require("theme")
require("nvidia")
require("vrr")
require("plugins.hyprbars")
require("enable-tearing")
require("misc-snippets")
require("idleinhibit")

require("dev")
