layerrule = blur, notifications
layerrule = blur, wob
layerrule = blur, launcher

layerrule = ignorezero, notifications
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
