layerrule = blur on, match:namespace notifications
layerrule = blur on, match:namespace wob
layerrule = blur on, match:namespace launcher

layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
