# because Linux is easy 😿

# Cursor theme names are their directory names
$XCursorTheme = simp1e-amber
$hyprcursorTheme = simp1e-amber
$XCursorSize = 24
$hyprcursorSize = 24

# hyprcursor
exec-once = hyprctl setcursor '$hyprcursorTheme' $hyprcursorSize
env = HYPRCURSOR_THEME, $hyprcursorTheme
env = HYPRCURSOR_SIZE, $hyprcursorSize

# xcursor
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$XCursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $XCursorSize
env = XCURSOR_THEME, $XCursorTheme
env = XCURSOR_SIZE, $XCursorSize

cursor {
    inactive_timeout = 5
}
