# because Linux is easy 😿

# Cursor theme names are their directory names
$XCursorTheme = Oxygen_Yellow
$hyprcursorTheme = Oxygen_Yellow
# $XCursorTheme = BreezeX-RosePine
# $hyprcursorTheme = rose-pine-hyprcursor
$XCursorSize = 20
$hyprcursorSize = 22 # 2px difference from what I could tell

# hyprcursor
exec-once = hyprctl setcursor '$hyprcursorTheme' $hyprcursorSize
env = HYPRCURSOR_THEME, $hyprcursorTheme
env = HYPRCURSOR_SIZE, $hyprcursorSize

# xcursor
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$XCursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $XCursorSize
env = XCURSOR_SIZE, $XCursorSize
