#+TITLE: Hyprland
# moved (finally) # [2024-02-14 Wed 12:43:13 -03] @ak

* =hyprland.conf=: Hyprland's configuration file
:PROPERTIES:
:header-args:conf: :tangle hyprland.conf
:END:

The default example config file can be found in:
: /usr/share/hyprland/hyprland.conf

- Example Hyprland config
  + [[https://github.com/prasanthrangan/hyprdots/tree/main/Configs/.config/hypr][hyprdots/Configs/.config/hypr at main · prasanthrangan/hyprdots]]
  # Add the nix one too

# ** Additional configuration modules
# Split config files with specific functionality

** Displays & Workspaces
- See
  + [[https://wiki.hyprland.org/Configuring/Monitors/][Monitors – Hyprland Wiki]]
  + [[https://wiki.hyprland.org/Configuring/Workspace-Rules/][Workspace Rules – Hyprland Wiki]]
#+begin_src conf
source=./monitors.conf # generated by nwg-displays

workspace = 1, monitor:desc:Dell Inc. DELL S2721DGF FZ6B4H3, default:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, monitor:desc:Dell Inc. DELL P2418D 29J0P96K06MT, default:true
workspace = 5, persistent:true
workspace = 6, persistent:true
workspace = 7, persistent:true
workspace = 8, persistent:true
workspace = 9, persistent:true, gapsin:0, gapsout:0, border:true, rounding:false
workspace = 10, persistent:true
#+end_src

*** No gaps with only a single window in the workspace
- [[https://wiki.hyprland.org/Configuring/Workspace-Rules/#smart-gaps][Workspace Rules – Hyprland Wiki]]

Replacement for =no_gaps_when_only=, see
[[https://github.com/hyprwm/Hyprland/pull/8072][hyprwm/Hyprland/Pull Request #8072/layouts: Nuke no_gaps_when_only by vaxerski]].
#+begin_src conf
workspace = w[t1], gapsin:0, gapsout:0, border:1
workspace = w[tg1], gapsin:0, gapsout:0, border:1
workspace = f[1], gapsin:0, gapsout:0, border:1
#+end_src

** Startup
- http://wiki.hyprland.org/Useful-Utilities/Must-have/#authentication-agent
#+begin_src conf
exec-once = /usr/lib/polkit-kde-authentication-agent-1
#+end_src

#+begin_src conf
exec-once = lightordark-wallpaper # script
exec-once = kdeconnectd # KDE connect daemon
exec-once = sh -c 'eww open mainbar && eww open mainbar2'
exec-once = xsettingsd # GTK2-3 theme live changes
exec-once = sh -c 'emacs --daemon && sleep 1 && emacs-launcher'

# exec-once = gammastep -P
exec-once = hypridle
#+end_src

Fix file association in dolphin.
- [[https://bbs.archlinux.org/viewtopic.php?pid=2167673#p2167673][[SOLVED] Weird XDG MIME Behavior with KDE Dolphin on Hyprland / Applications & Desktop Environments / Arch Linux Forums]]
- [[https://wiki.archlinux.org/title/Xdg-menu][xdg-menu - ArchWiki]]
#+begin_src conf
exec-once = XDG_MENU_PREFIX=arch- kbuildsycoca6
#+end_src

#+begin_src conf
exec-once = hypr-eww-restart-on-monitor-change
#+end_src

** Environment variables
- [[https://wiki.hyprland.org/Configuring/Environment-variables/][Environment Variables | Hyprland Wiki]]
# #TODO-review utility of these
#+begin_src conf
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
#+end_src

*** Browsers
#+begin_src conf
# Firefox
env = EGL_PLATFORM,wayland # unset this when on X11
env = MOZ_ENABLE_WAYLAND,1 # necessary otherwise Firefox will only try X11
#+end_src

*** Toolkit backends
- [[https://wiki.hyprland.org/Configuring/Environment-variables/#toolkit-backend-variables][Environment variables – Hyprland Wiki]]
#+begin_src conf
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = SDL_VIDEODRIVER,wayland,x11
env = CLUTTER_BACKEND,wayland
#+end_src


** Keywords
- https://wiki.hyprland.org/Configuring/Keywords/
- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

*** Input
- [[https://wiki.hyprland.org/Configuring/Variables/#input][Variables#Input | Hyprland Wiki]]
#+begin_src conf
input {
    kb_layout = us,br
    numlock_by_default = true
    follow_mouse = 1
    # Follow Mouse
    # 0 - disabled
    # 1 - full
    # 2 - loose. Will focus mouse on other windows on focus but not the keyboard.
    # 3 - full loose, will not refocus on click, but allow mouse focus to be
      # detached from the keyboard like in 2.

    float_switch_override_focus = 0
    # See https://wiki.hyprland.org/Configuring/Variables/#:~:text=float_switch_override_focus

    sensitivity = -0.6 # -1.0 - 1.0, 0 means no modification.

    accel_profile = flat
    # force_no_accel = true # not recommended in the wiki

    # keyboard key repeat
    repeat_rate = 80 # char/sec i think
    repeat_delay = 200
}
#+end_src

*** General
#+begin_src conf
general {
    layout = dwindle

    resize_on_border = true
    extend_border_grab_area = 20
    # no_cursor_warps = true # don't move the cursor with keybinds
    resize_corner = 3 # bottom right
}
#+end_src

*** XWayland
#+begin_src conf
xwayland {
    use_nearest_neighbor = false # necessary when not forcing scaling to make it look ok/blurry
    force_zero_scaling = false # makes xwayland sharp when not using
                              # GDK_SCALE, if using scaling is
                              # overriden, but still sharp.
                              # [2023-06-14 Wed 08:24:55 -03]
}
#+end_src

*** Dwindle layout
#+begin_src conf
dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true
    preserve_split = true
    force_split = 2 # 0 -> split follows mouse, 1 -> always split to the left (new = left or top) 2 -> always split to the right (new = right or bottom)
    # use_active_for_splits = true
}
#+end_src

*** Misc
- [[https://wiki.hyprland.org/Configuring/Variables/#misc][Variables#Misc – Hyprland Wiki]]
#+begin_src conf
misc {
     disable_hyprland_logo = true
     # testing, it is recommended to set to true
     # vfr=false # why energy save on this for desktop :)

     animate_manual_resizes = true
     mouse_move_focuses_monitor = true
     animate_mouse_windowdragging = false
     enable_swallow = false
     swallow_regex = ^(Alacritty)$
     # swallow_exception_regex = ^(.*Microsoft Edge.*|Mozilla Firefox|.*Chromium|.*Brave.*|wev)$

     mouse_move_enables_dpms = true #prevents accidental wake up
     key_press_enables_dpms = true
}
#+end_src

*** Binds
- [[https://wiki.hyprland.org/Configuring/Variables/#binds][Variables#Binds – Hyprland Wiki]]
#+begin_src conf
binds {
      allow_workspace_cycles = true
      workspace_center_on = 1
      movefocus_cycles_fullscreen = false
}
#+end_src

** =window-rules.conf=: Window rules collection
:PROPERTIES:
:header-args:conf: :tangle window-rules.conf
:END:

See https://wiki.hyprland.org/Configuring/Window-Rules/
#+begin_src conf
# Polkit dialogs
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$, float on

# Picture-in-Picture (dynamic title, requires full regex match)
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, pin on

# Emacs floating frames
windowrule = match:title ^(Edit with Emacs FRAME)$, float on

# Wine/Proton windows
windowrule = match:class ^.*(floatWMRULE|FLOAT_WMRULE)$, float on
windowrule = match:title ^.*(floatWMRULE|FLOAT_WMRULE)$, float on

# File open dialogs (anchor pattern at start, not middle)
windowrule = match:title ^Open File, float on
windowrule = match:title ^Vivaldi Settings:, float on

# MPV suppress maximize (prevents maximization requests)
windowrule = match:class ^mpv$, suppress_event maximize

# Floating .exe windows (Windows app shortcuts)
windowrule = match:class .*\.exe$, float on

# Emacs
windowrule = match:class emacs match:title Ediff, float on
windowrule = match:class emacs match:title Ediff, size 720 330
windowrule = match:class emacs match:title Ediff, move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5))

# Blender
windowrule = match:title ^Blender (Render|Preferences)$, float on

# Steam & Games
windowrule = match:title ^Create or select new Steam library folder$, float on
windowrule = match:class steam match:title Friends List, float on
windowrule = match:class steam match:title Steam Settings, float on
# windowrule = match:class steam, float on  # Uncomment to float all Steam windows
# Steam apps: send to workspace 6, render in background for FPS stability
windowrule = match:class ^(steam_app_[0-9]+)$, monitor 0 silent
windowrule = match:class ^(steam_app_[0-9]+)$, workspace 6 silent

# Elden Ring: prevent FPS drops when unfocused
windowrule = match:class steam_app_2622380 match:title ELDEN RING NIGHTREIGN, render_unfocused on

# Render unfocused at lower FPS (add to config misc section)
# misc {
#   render_unfocused_fps = 30
# }

# File Managers
windowrule = match:class org.kde.ark match:title ^(File Already Exists).*Ark$, float on
windowrule = match:class org.kde.dolphin match:title ^(Choose Application).*Dolphin$, float on
windowrule = match:class org.freedesktop.impl.portal.desktop.kde, float on

# Firefox
# Empty title notifications (popups with no text)
windowrule = match:class firefox match:title ^$, float on
windowrule = match:class firefox match:title Library, float on

# Global rule: disable blur for windows with empty class/title (xwayland context menus)
windowrule = match:class ^()$ match:title ^()$, no_blur on

# Inkscape
windowrule = match:class org.inkscape.Inkscape match:title ^(SVG Input)$, float on
#+end_src

#+begin_src conf :tangle hyprland.conf
source = window-rules.conf

windowrule = suppress_event maximize, match:class .*
#+end_src


** =layer-surface-rules.conf=: Layer surface rules
:PROPERTIES:
:header-args:conf: :tangle layer-surface-rules.conf
:END:

- [[https://wiki.hyprland.org/Configuring/Window-Rules/#layer-rules][Hyprland Wiki: Window Rules#Layer Rules]]

- Blur layer
  + [[https://wiki.hyprland.org/Configuring/Keywords/#blurring-layersurfaces][Keywords | Hyprland Wiki]]
  + [[https://www.reddit.com/r/hyprland/comments/10q5t3e/comment/j6ok1qm/?context=3][No blur on hyprland? : hyprland]]
  Blur notifications and bars
#+begin_src conf
layerrule = blur on, match:namespace notifications
layerrule = blur on, match:namespace wob
layerrule = blur on, match:namespace launcher
#+end_src

- Layer Rules
  + =ignorezero=: Layer rule for Hyprland to ignore fully transparent
    pixels and e.g. not blur them.
#+begin_src conf
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
#+end_src

Source in the main config file
#+begin_src conf :tangle hyprland.conf
source = layer-surface-rules.conf
#+end_src

** Keybinds
*** =keybinds.conf=
:PROPERTIES:
:header-args:conf: :tangle keybinds.conf
:END:

- Note: Here, the stuff:
  #+begin_example
  bind = [MOD], [KEY], submap, [MAPNAME]
  submap = [MAPNAME]
  [...]
  source = ./catchall-reset-submap.conf
  submap = reset
  #+end_example
  Is to, basically, enable Emacs-like key chords. The key is the
  =source= of the file =./catchall-reset-submap.conf= that hardcodes any
  key press to reset it back to the normal/default submap since
  sourcing places the respective content of the file in the scope
  where it was sourced at. Then at the end
  =./catchall-reset-submap.conf= it still falls-back to using the
  built-in =catchall= special keyword.
  # [2024-07-03 Wed 04:56:22 -03] @ak
  # update again [2024-09-08 Sun 18:16:12 -03] @ak

Source in the main config file
#+begin_src conf :tangle hyprland.conf
source = keybinds.conf
#+end_src

+Pretty messy:+
#+begin_src conf
# #### Binds ####
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
$browser = firefox

bind = $mainMod, T, togglefloating,
bind = $mainMod, R, togglesplit, # dwindle

# [[https://github.com/hyprwm/Hyprland/issues/102][Submap of key bindings · Issue #102 · hyprwm/Hyprland]]
# [[https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#disabling-keybinds-with-one-master-keybind][Uncommon Tips & Tricks | Hyprland Wiki]]
# custom
# $reset = && hyprctl dispatch submap reset
# usage: $reset at the end of `exec' keybinds
# alternative for non-exec: declare the same keybind again with the `submap, reset' after the first two fields for the keybind.
# remember to set a safety reset keybind e.g.: bind = $mainMod, G, submap, reset

# [[https://www.reddit.com/r/hyprland/comments/12q4xib/comment/jgqd0gw/][Activating lock/dpms from script with swayidle : r/hyprland]]
bindl = $mainMod ALT, pause, exec, hyprctl dispatch dpms off

bind = $mainMod, X, submap, exemap
submap = exemap
# bind = , space, exec, dmenu-def run $reset # dmenu script with custom command line options
# escape # with ##
# bind = , space, exec, bemenu-run --fn 'Liberation Mono' --nf '##f0f0f0' --sb '##76ee00' --sf '##111111' -i
bind = , space, exec, $(tofi-run)
bind = , space, submap, reset
bind = , C, killactive, # for kill with M-x c
bind = , C, submap, reset
bind = $mainMod, C, killactive, # for kill with M-x M-c
bind = $mainMod, C, submap, reset
bind = , E, exec, zsh -i -c 'exec emacs'
bind = , F, exec, firefox
bind = , Z, exec, zen-browser
bind = , V, exec, vivaldi
# bind = , N, exec, [workspace special:emacs-quick-note;noanim] emacs-launcher -- -c -e '(bookmark-jump "chronological-random-notes")'
# bind = , N, exec, emacs-launcher -- -c -e '(bookmark-jump "chronological-random-notes")'

source = ./catchall-reset-submap.conf
submap = reset

bind = $mainMod ALT, C, killactive, # for kill with s-M-c

bind = $mainMod, return, exec, alacritty
bind = $mainMod, backspace, exec, foot

bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r
bind = $mainMod, P, cyclenext, prev
bind = $mainMod, N, cyclenext, next

bind = $mainMod, S, swapsplit,

# vim
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r
# emacs
# USING scratchpads see
# bind = $mainMod SHIFT, B, movewindow, l
# bind = $mainMod SHIFT, N, movewindow, d
# bind = $mainMod SHIFT, P, movewindow, u
# bind = $mainMod SHIFT, F, movewindow, r

binde = $mainMod ALT, B, resizeactive, -10 0
binde = $mainMod ALT, N, resizeactive, 0 10
binde = $mainMod ALT, P, resizeactive, 0 -10
binde = $mainMod ALT, F, resizeactive, 10 0

# Switch workspaces with mainMod + [0-9]
$workspaceChangeDispatcher = focusworkspaceoncurrentmonitor
# "exec, hypr-workspace" deprecated by https://wiki.hyprland.org/Configuring/Dispatchers/#:~:text=focusworkspaceoncurrentmonitor
bind = $mainMod, 1, $workspaceChangeDispatcher, 1
bind = $mainMod, 2, $workspaceChangeDispatcher, 2
bind = $mainMod, 3, $workspaceChangeDispatcher, 3
bind = $mainMod, 4, $workspaceChangeDispatcher, 4
bind = $mainMod, 5, $workspaceChangeDispatcher, 5
bind = $mainMod, 6, $workspaceChangeDispatcher, 6
bind = $mainMod, 7, $workspaceChangeDispatcher, 7
bind = $mainMod, 8, $workspaceChangeDispatcher, 8
bind = $mainMod, 9, $workspaceChangeDispatcher, 9
bind = $mainMod, 0, $workspaceChangeDispatcher, 10

bind = $mainMod ALT, 1, workspace, 1
bind = $mainMod ALT, 2, workspace, 2
bind = $mainMod ALT, 3, workspace, 3
bind = $mainMod ALT, 4, workspace, 4
bind = $mainMod ALT, 5, workspace, 5
bind = $mainMod ALT, 6, workspace, 6
bind = $mainMod ALT, 7, workspace, 7
bind = $mainMod ALT, 8, workspace, 8
bind = $mainMod ALT, 9, workspace, 9
bind = $mainMod ALT, 0, workspace, 10

bind = $mainMod SHIFT, S, swapactiveworkspaces, 0 1

# Move active window to a workspace with mainMod + SHIFT + [0-9]
$moveToWorkspace = movetoworkspacesilent # default is movetoworkspace
bind = $mainMod SHIFT, 1, $moveToWorkspace, 1
bind = $mainMod SHIFT, 2, $moveToWorkspace, 2
bind = $mainMod SHIFT, 3, $moveToWorkspace, 3
bind = $mainMod SHIFT, 4, $moveToWorkspace, 4
bind = $mainMod SHIFT, 5, $moveToWorkspace, 5
bind = $mainMod SHIFT, 6, $moveToWorkspace, 6
bind = $mainMod SHIFT, 7, $moveToWorkspace, 7
bind = $mainMod SHIFT, 8, $moveToWorkspace, 8
bind = $mainMod SHIFT, 9, $moveToWorkspace, 9
bind = $mainMod SHIFT, 0, $moveToWorkspace, 10

# **** Scratchpads
# aka special workspaces
# bind = $mainMod SHIFT, N, movetoworkspace, special:emacs-quick-note
# bind = $mainMod, N, workspace, special:emacs-quick-note
bind = $mainMod SHIFT, equal, movetoworkspacesilent,  special:scratch
bind = $mainMod,       equal, togglespecialworkspace, special:scratch
bind = $mainMod SHIFT, minus, movetoworkspacesilent,  special:minimized
bind = $mainMod,       minus, togglespecialworkspace, special:minimized


# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# ytdotool debounce script for faulty middle click
# bind = , mouse:274, exec, ydotool click -D 200 0xC2 --repeat=1
# middle-click-debouce

bind = $mainMod CTRL, P, pin,

# ## Layout binds
# bind = $mainMod, F, fullscreen, 1

# https://github.com/hyprwm/Hyprland/issues/7770
bind = $mainMod, F11, fullscreenstate, 2, -1

bind = $mainMod, F, submap, wm-actions
submap = wm-actions
bind = $mainMod, F, fullscreen, 1
source = ./catchall-reset-submap.conf
submap = reset

bind = $mainMod, W, submap, wm-actions-group
submap = wm-actions-group
bind = , T, togglegroup
bind = , H, moveintogroup, l
bind = , J, moveintogroup, d
bind = , K, moveintogroup, u
bind = , L, moveintogroup, r
source = ./catchall-reset-submap.conf
submap = reset
bind = $mainMod CTRL ALT, N, changegroupactive


# # MPD 2nd instance (deprecated)
# bind = $mainMod ALT, XF86AudioNext, exec, playerctl --player=mpd-local next
# bind = $mainMod ALT, XF86AudioPrev, exec, playerctl --player=mpd-local previous
# bind = $mainMod ALT, XF86AudioPlay, exec, playerctl --player=mpd-local play-pause
# bind = $mainMod ALT, XF86AudioStop, exec, playerctl --player=mpd-local stop

# [[https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon-keysyms.h][libxkbcommon/xkbcommon-keysyms.h at master · xkbcommon/libxkbcommon]]
bind = , print, exec, mkdir -p "$(xdg-user-dir PICTURES)/screenshots/" && grim -l 0 -t png "$(xdg-user-dir PICTURES)/screenshots/$(date +'%Y%m%d-%H%M%S-screenshot.png')" && notify-send -a Screenshot 'Fullscreen Screenshot taken'
# color picker: grim -g "$(slurp -p)" -t ppm - | magick - -format '%[pixel:p{0,0}]' txt:-

# Hang when using default exit:
# FIX wizard https://github.com/hyprwm/Hyprland/issues/3558#issuecomment-1848768654
bind = $mainMod CTRL ALT, pause, exec, hyprctl dispatch exit 0; sleep 2; pgrep -x Hyprland >/dev/null && killall -9 Hyprland

bind = $mainMod, O, focusmonitor, +1
bind = $mainMod SHIFT, O, movewindow, mon:+1
# exec, hyprctl dispatch movewindow mon:"$(hyprctl monitors -j | jq -r '.[] | select(.focused == false).id')"

# Notification contols
bind = $mainMod CTRL ALT, N, exec, dunstctl history-pop

# Reload second monitor to set the primary monitor:
bind = $mainMod CTRL ALT, D, exec, wlr-randr --output DP-2 --off && sleep 1 && wlr-randr --output DP-2 --on --pos 2048,122

# Switch keyboard layouts, find names with `hyprctl devices'
# bind = , control_r, exec, hyprctl switchxkblayout "$(pgrep kmonad && printf 'kmonad-uinput-sink' || printf 'sino-wealth-usb-keyboard')" next
# If using KMonad it will create a virtual keyboard device with the
# same name as defined in (uinput-sink ...) but with all lowercase an
# spaces replaces with hyphens, e.g.:
# `output (uinput-sink "KMonad uinput Sink"...)' will become kmonad-uinput-sink
# PS same works for kmonad:
bind = $mainMod ALT, control_r, exec, hyprctl switchxkblayout "$(pgrep -x xremap >/dev/null && printf 'xremap' || printf 'sino-wealth-usb-keyboard')" next

# pgrep kmonad > /dev/null && printf '%s\n' 'kmonad-uinput-sink' || printf 'sino-wealth-usb-keyboard\n'
# if pgrep kmonad > /dev/null; then printf '%s\n' 'kmonad-uinput-sink'; else printf 'sino-wealth-usb-keyboard\n'; fi

bind = $mainMod CTRL ALT, period, exec, tofimoji

bind = $mainMod CTRL ALT, M, exec, [float; stayfocused] terminal -w 120 -h 20 --float pulsemixer
#+end_src

# ## Issues
# Mouse getting to second monitor during games # [2023-04-03 Mon 22:05:43 -03]
# have a any-other-key exit for submaps
# - Focus other monitor key
# - When resize is enabled, while on fullscreen it makes the cursor freeze on the resize one. |||| FIXED
# - no_gaps_when_only = true per monitor?
# - # check monitor to compensate socket not updating active workspace if it is visible on the other monitor |||| almost almost
# libdisplay-info-git
# xorg-xwayland
**** video recording
Using =gpu-screen-recorder=
#+begin_src conf
# Save last 60 seconds
bind = $mainMod ALT, SPACE, exec, gpu-screen-recorder-replay-save

# Pause/resume replay buffer
bind = $mainMod, pause, exec, gpu-screen-recorder-replay-toggle

# Stop replay buffer entirely
bind = $mainMod, end, exec, gpu-screen-recorder-replay-stop

bind = , F1, exec, gpu-screen-recorder-replay-save-10
bind = , F2, exec, gpu-screen-recorder-replay-save-30
bind = , Capslock, exec, gpu-screen-recorder-replay-save-30
bind = , F3, exec, gpu-screen-recorder-replay-save-60
#+end_src
**** media/volume
#+begin_src conf
# Media keys
# the recommended in http://wiki.hyprland.org/Configuring/Binds/#uncommon-syms--binding-with-a-keycode
# is to use lower case for keysyms, it it stops working capitalized y'know
bind = $mainMod, XF86AudioNext, exec, playerctl next
bind = $mainMod, XF86AudioPrev, exec, playerctl previous
bind = $mainMod, XF86AudioPlay, exec, playerctl play-pause
bind = $mainMod, XF86AudioStop, exec, wptoggle
# MPD
bind = , XF86AudioNext, exec, playerctl --player=mpd next
bind = , XF86AudioPrev, exec, playerctl --player=mpd previous
bind = , XF86AudioPlay, exec, playerctl --player=mpd play-pause
bind = , XF86AudioStop, exec, playerctl --player=mpd stop

exec-once = pw-volume-wob-monitor
exec-once = wob-instance /tmp/wob-firefox-sink.pipe ~/.config/wob/wob-firefox-sink.ini
exec-once = wob-instance /tmp/wob-game-sink.pipe ~/.config/wob/wob-game-sink.ini

binde = , XF86AudioLowerVolume, exec, pw-volume @DEFAULT_AUDIO_SINK@ 1-
binde = , XF86AudioRaiseVolume, exec, pw-volume @DEFAULT_AUDIO_SINK@ 1+

binde = $mainMod ALT, XF86AudioLowerVolume, exec, env WOB_PIPE=/tmp/wob-game-sink.pipe pw-volume gamesink 5-
binde = $mainMod ALT, XF86AudioRaiseVolume, exec, env WOB_PIPE=/tmp/wob-game-sink.pipe pw-volume gamesink 5+
binde = $mainMod, XF86AudioLowerVolume, exec, env WOB_PIPE=/tmp/wob-firefox-sink.pipe pw-volume firefox-sink 5-
binde = $mainMod, XF86AudioRaiseVolume, exec, env WOB_PIPE=/tmp/wob-firefox-sink.pipe pw-volume firefox-sink 5+
#+end_src

** Theming
#+begin_src conf
# file containing nested sourcing for color definitions, useful for
# editing/automating changes from scripts like darkman.
source = themes/theme.conf # (ref:hyprland-conf-theming-sourcing)
source = shadows.conf
source = animations.conf
source = blur.conf
source = mouse.conf
#+end_src
Settings that use IPC like =gsettings= or =hyprctl= could and probably
should also be set from darkman.

*** =mouse.conf=: Settings for hyprcursor and the xcursor fallback
:PROPERTIES:
:header-args:conf: :tangle mouse.conf
:END:

- See
  + [[https://wiki.hyprland.org/FAQ/#how-do-i-change-me-mouse-cursor][FAQ#How do I change me mouse cursor? – Hyprland Wiki]]
  + [[https://github.com/hyprwm/Hyprland/issues/6320][Inconsistent cursor size · Issue #6320 · hyprwm/Hyprland · GitHub]]

Hyprcursors are installed the same way as normal ones. The cursor
theme directory should be installed preferably user-local in
=$XDG_DATA_HOME/icons= or alternatively system-wide in =/usr/share/icons/=.

- Cursor themes
  + [[https://codeberg.org/useless-utils/simp1e-amber-hyprcursor][Codeberg/useless-utils/simp1e-amber-hyprcursor: A gold-yellow hyprcursor]]
  + [[https://github.com/rose-pine/cursor][GitHub - rose-pine/cursor: Soho vibes for Cursors]]
  + [[https://github.com/ndom91/rose-pine-hyprcursor][ndom91/rose-pine-hyprcursor: BreezeX RosePine for Hyprcursor]]
#+begin_src conf
# because Linux is easy 😿

# Cursor theme names are their directory names
$XCursorTheme = simp1e-amber
$hyprcursorTheme = simp1e-amber
$XCursorSize = 24
$hyprcursorSize = 24

# hyprcursor
exec-once = hyprctl setcursor '$hyprcursorTheme' $hyprcursorSize
env = HYPRCURSOR_THEME, $hyprcursorTheme
env = HYPRCURSOR_SIZE, $hyprcursorSize

# xcursor
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$XCursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $XCursorSize
env = XCURSOR_THEME, $XCursorTheme
env = XCURSOR_SIZE, $XCursorSize

cursor {
    inactive_timeout = 5
}
#+end_src


*** =theme.conf=: General visual customization
:PROPERTIES:
:header-args:conf: :tangle themes/theme.conf :mkdirp yes
:END:

Split files, sourcing them at [[(hyprland-conf-theming-sourcing)][hyprland.conf Theming sourcing]]
#+begin_src conf
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
}

decoration {
    rounding = 4 # def 10
}
#+end_src

#+begin_src conf :tangle blur.conf
decoration {
    blur {
         enabled = true
         size = 5
         passes = 3
         new_optimizations = true
    }
}
#+end_src

- Animations are declared with the =animation=  keyword.
  : animation=NAME,ONOFF,SPEED,CURVE[,STYLE]
  + =ONOFF= can be either 0 or 1, 0 to disable, 1 to enable. /note:/  if it’s 0, you can omit further args.
  + =SPEED=  is the amount of ds (1ds = 100ms) the animation will take
  + =CURVE= is the bezier curve name, see [[https://wiki.hyprland.org/Configuring/Animations/#curves][curves]].
  + =STYLE=  (optional) is the animation style
  The animations are a tree. If an animation is unset, it will inherit
  its parent’s values. See [[https://wiki.hyprland.org/Configuring/Animations/#animation-tree][the animation tree]].
- See [[https://wiki.hyprland.org/Configuring/Animations/][Animations – Hyprland Wiki]].

#+NAME: hyprland-animations-conf
#+begin_src conf :tangle animations.conf
animations {
    enabled = false
    # animation=NAME,ONOFF,SPEED,CURVE[,STYLE]
    animation = windows     , 1, 2, default, popin
    animation = windowsOut  , 1, 2, default
    animation = border      , 1, 2, default
    animation = borderangle , 1, 2, default
    animation = fade        , 1, 2, default
    animation = workspaces  , 1, 2, default, fade
}
#+end_src


Since =theme.conf= is in a subdirectory, if it sources a file in the
same directory as itself the source path should also be relative to
itself and not to =hyprland.conf=. +(or just use fullpaths)+
#+begin_src conf :noweb yes
source = 00-<<lightordark()>>-theme.conf
#+end_src

#+begin_src conf :tangle themes/00-light-theme.conf :mkdirp yes
source = light-color-vars.conf
source = neron-color-vars.conf

$bg-color = $lt-bg
$fg-color = $lt-fg
$hyprbars-close-color = $lt-pink
$hyprbars-maximize-color = $lt-green
$hyprbars-float-color = $lt-cyan

source = light-borders.conf
#+end_src

#+begin_src conf :tangle themes/00-dark-theme.conf :mkdirp yes
source = neron-color-vars.conf

$bg-color = $neron-bg
$fg-color = $neron-fg
$hyprbars-close-color = $neron-pink
$hyprbars-maximize-color = $neron-green
$hyprbars-float-color = $neron-cyan

source = neon-dark-borders.conf
#+end_src

*** Border color themes
#+begin_src conf :tangle themes/neon-dark-borders.conf :mkdirp yes
general {
    col.active_border = $yt-orange
    col.inactive_border = rgba(25252500)
}
#+end_src

#+begin_src conf :tangle themes/light-borders.conf :mkdirp yes
general {
    # col.active_border = rgb(ff00aa)
    col.active_border = $neron-pink 45deg
    col.inactive_border = rgba(eeeeee00)

    gaps_in = 4
    gaps_out = 8
    border_size = 3
}
#+end_src

*** Theme color variables
#+begin_src conf :tangle themes/neron-color-vars.conf :mkdirp yes
$neron-bg = rgb(222222)
$neron-green = rgb(61bd09)
$neron-pink = rgb(ff77cf)
$neron-cyan = rgb(16b0cf)
$neron-fg = rgb(a6a8a9)
$neron-current = rgb(2f2f2f)
$current-icon = rgb(666666)
$neron-orange = rgb(fd892c)
$yt-orange = rgb(ef6c00)
#+end_src

#+begin_src conf :tangle themes/light-color-vars.conf :mkdirp yes
$black = rgb(000000)
$gray-bg = rgb(cccccc)
$white = rgb(ffffff)
$lt-bg = $white
$lt-fg = rgb(545e62)
$lt-red = rgb(ba0d0d)
$lt-cyan = rgb(006861)
$lt-pink = rgb(b30071)
$lt-green = rgb(1c6b00)
#+end_src

*** =shadows.conf=: Disable shadows
#+begin_src conf :tangle shadows.conf
decoration {
    shadow {
        enabled = false
        range = 20
        render_power = 3
        color = rgba(00000080)
        color_inactive = rgba(00000000)

        ignore_window = true
        scale = 1
    }
}
#+end_src

*** Auto dark/light theme change with =darkman=
#+INCLUDE: ~/.config/darkman/README.org::#orgid-xivkrg

** =nvidia.conf=: Nvidia-specific settings for Hyprland
# Nvidia support
#+begin_src conf :tangle nvidia.conf
# env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

env = GBM_BACKEND,nvidia-drm

cursor {
    no_hardware_cursors = true
}

# https://wiki.hyprland.org/Nvidia/#va-api-hardware-video-acceleration
env = NVD_BACKEND,direct
#+end_src

Source in the main config file
#+begin_src conf
source = nvidia.conf
#+end_src

** ~vrr.conf~: Variable Refresh Rate
- [[https://wiki.archlinux.org/title/Variable_refresh_rate][Variable refresh rate - ArchWiki]]
- VRR vs Immediate: [[https://github.com/hyprwm/Hyprland/issues/927#issuecomment-1771536802][Frame-perfect Games VRR (Adaptive sync) support · Issue #927 · hyprwm/Hyprland]]

Note that (at least for NVIDIA variable refresh rate can work but only
with one monitor on.
#+begin_src conf :tangle vrr.conf
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1

misc {
     vrr=2 # 0 - off, 1 - on, 2 - fullscreen only

     vfr=true
}

cursor {
    no_hardware_cursors = true
    # no_break_fs_vrr = true # not useful for me
}
#+end_src

#+begin_src conf
source = vrr.conf
#+end_src

** Plugins

*** Hyprbars
:PROPERTIES:
:header-args:conf: :tangle plugins/hyprbars.conf :mkdirp yes
:END:
- [[https://github.com/hyprwm/hyprland-plugins/tree/main/hyprbars][hyprland-plugins/hyprbars at main · hyprwm/hyprland-plugins]]
  # [2024-06-09 Sun 19:46:25 -03] @ak
#+begin_src conf
plugin {
    hyprbars {
        bar_height = 20
        bar_color = $bg-color
        col.text = $fg-color
        bar_text_size = 9
        # bar_text_font = Jetbrains Mono Nerd Font Mono Bold
        bar_text_font = LiterationMono Nerd Font Bold
        bar_button_padding = 10
        bar_padding = 5
        bar_precedence_over_border = true
        hyprbars-button = $hyprbars-close-color, 16, , hyprctl dispatch killactive
        hyprbars-button = $hyprbars-maximize-color, 16, , hyprctl dispatch fullscreen 2
        hyprbars-button = $hyprbars-float-color, 16, , hyprctl dispatch togglefloating
   }
}
#+end_src

Disable title bars for tiles (non-floating) windows
- See
  + [[https://github.com/hyprwm/hyprland-plugins/tree/main/hyprbars#window-rules][hyprland-plugins/hyprbars#Window rules at main · hyprwm/hyprland-plugins]]
  + [[https://www.reddit.com/r/hyprland/comments/1cyaz4u/comment/l5brgnw/][I like hyprbars. That's all. : r/hyprland]]
#+begin_src conf
windowrule = plugin:hyprbars:nobar, ^floating:0
#+end_src

Source in main config
#+begin_src conf :tangle hyprland.conf
# source = plugins/hyprbars.conf
#+end_src

** =enable-tearing.conf=
:PROPERTIES:
:header-args:conf: :tangle enable-tearing.conf
:END:
- See https://wiki.hyprland.org/Configuring/Tearing/
#+begin_src conf
general {
    allow_tearing = true
}

env = WLR_DRM_NO_ATOMIC,1

windowrule = immediate on, match:class ^eldenring.exe$
windowrule = immediate on, match:class ^gamescope$
windowrule = immediate on, match:class ^steam_app_[0-9]+$
windowrule = immediate on, match:class ^mpv$
windowrule = immediate on, match:class love, match:title Freesync test
#+end_src

#+begin_src conf :tangle hyprland.conf
source = enable-tearing.conf
#+end_src

* =hypridle.conf=: Idle management daemon
:PROPERTIES:
:header-args:conf: :tangle hypridle.conf :comments org
:END:
- [[https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/][hypridle – Hyprland Wiki]]

- Monitor DPMS and brightness for hypridle ::
#+begin_src conf :noweb tangle
listener {
    timeout = 300 # 5min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
#+end_src

** =idleinhibit.conf=: Window rules for idle on/off
:PROPERTIES:
:header-args:conf: :tangle idleinhibit.conf
:END:

#+begin_src conf
windowrule = idle_inhibit fullscreen, match:class ^(gamescope|steam_app_[0-9]+)$
windowrule = idle_inhibit fullscreen, match:class ^(eldenring.exe)$
#+end_src

#+begin_src conf :tangle hyprland.conf
source = idleinhibit.conf
#+end_src

* Notes

** Status Bars
[[https://wiki.hyprland.org/Useful-Utilities/Status-Bars/][Status Bars | Hyprland Wiki]]

*** waybar-hyprland
: paru waybar-hyprland-git
: mkdir ~/.config/waybar
: cp -r /etc/xdg/waybar/ ~/.config/waybar
: sed -i 's,sway/workspaces,wlr/workspaces,g' ~/.config/waybar
# [2023-04-03 Mon 03:13:59 -03]

Recommended installing =otf-font-awesome= for icons (though
=ttf-font-awesome= seems to work fine).

** Keychords / leader-key keybindings
- See
  [[https://github.com/hyprwm/Hyprland/issues/1647#issuecomment-1452246225][Add key chords support. · Issue #1647 · hyprwm/Hyprland]]
  # [2023-04-05 Wed 06:30:47 -03]

** Wayland/Hyprland NVIDIA screen capture

*** DONE Wayland/Hyprland NVIDIA screen capture troubleshooting
#OUTDATED # [2024-02-15 Thu 01:52:28 -03] @ak
nvidia patch has been deprecated
**** unsupported wl_shm format 0x34324742
[[https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580#unsupported-wl_shm-format-0x34324742-after-trying-to-share-the-screen-on-nvidia][Screen sharing on Hyprland (Arch Linux)]]
# master wizard
Install =hyprland-nvidia-git= or apply nvidia patch manually

* Hyprland Scripts
:PROPERTIES:
:tangle-dir: (concat (xdg-bin-home) "/hyprland")
:END:

** noweb setup helpers

#+NAME: hyprland-scripts-check-alias-jaq-or-jq
#+begin_src shell
unset __usingjaq

command -v jaq > /dev/null &&
    alias jq=jaq &&
    __usingjaq=t
# jaq is a faster jq clone

# if [`jq' is not alias] AND [`jq' not found] = fail
! alias jq > /dev/null && ! command -v jq > /dev/null &&
    notify-send -a hypr-workspace script \
                'jaq or jq not found' \
                'Install jaq or jq' &&
    exit 1
#+end_src

** DONE =hypr-workspace=: Workspace switching like xmonad/qtile
:PROPERTIES:
:header-args:shell: :tangle (tdir "/hypr-workspace") :shebang #!/usr/bin/env sh :mkdirp yes
:END:
- DEPRECATED by [[https://wiki.hyprland.org/Configuring/Dispatchers/#:~:text=focusworkspaceoncurrentmonitor][focusworkspaceoncurrentmonitor]].
  + Added by commit =3c964a9fdc220250a85b1c498e5b6fad9390272f= on Jan 15
    2024 but I only saw it now ;p
    # [2024-09-08 Sun 13:22:15 -03] @ak
  + [[https://github.com/hyprwm/Hyprland/pull/4439][Implement a dispatcher for xmonad/qtile-style workspace switching by virchau13 · Pull Request #4439 · hyprwm/Hyprland]]

- Sources:
  Original code +i think+: [[https://github.com/taylor85345/hyprland-dotfiles/blob/master/hypr/scripts/workspace][taylor85345/hyprland-dotfiles/workspace]]
  from https://github.com/hyprwm/Hyprland/issues/747
  also: [[https://github.com/Jareng/dotfiles/blob/main/.config/hypr/scripts/workspace][Jareng/dotfiles/workspace]]
  [[https://www.reddit.com/r/hyprland/comments/11z8w7u/comment/jdbrh24/?context=3][Make Hyperland Workspaces Work Like Qtile Work Spaces : hyprland]]

# from April 8th
# [2023-05-23 Tue 19:59:53 -03]
#+begin_src shell
while :
do case $1 in
       -v|--verbose)
           set -x
           ;;
       ,*) break
   esac; shift; done
#+end_src

#+begin_src shell :noweb yes
«hyprland-scripts-check-alias-jaq-or-jq»

p() {
    printf '%s\n' "$@"
}

monitors=$(hyprctl monitors -j)

if [ -z "$1" ]; then
    workspace=$(p "${monitors}" | jq '.[] | select(.focused == false).activeWorkspace.id')
else
    workspace=$1
fi

activemonitor=$(p "${monitors}" | jq -r '.[] | select(.focused == true).name')
passivemonitor=$(p "${monitors}" | jq -r '.[] | select(.focused == false).name')

passivews=$(p "${monitors}" | jq -r ".[] | select(.name == \"${passivemonitor}\").activeWorkspace.id")

if [ "${workspace}" = "${passivews}" ] && [ "${activemonitor}" != "${passivemonitor}" ]; then
    hyprctl dispatch swapactiveworkspaces "${activemonitor}" "${passivemonitor}"
    # echo "${activemonitor}" "${passivemonitor}"
else
    hyprctl --batch \
            "dispatch moveworkspacetomonitor ${workspace} ${activemonitor} ;\
             dispatch workspace ${workspace}"
fi

exit 0
#+end_src


# check: [ERR] Error in getMonitorFromString: invalid arg 1
# [ERR] Ignoring moveWorkspaceToMonitor: monitor doesnt exist
# after disconnecting monitors and their number changing, could it be a higher = problem? # [2023-04-17 Mon 05:36:43 -03] --- seems fixed on recent workspace overhaul stuff # [2023-04-28 Fri 22:23:13 -03]
# [[https://github.com/hyprwm/Hyprland/issues/2154][Switching workspace on focused monitor sometimes also changes workspace on non-focused monitor · Issue #2154 · hyprwm/Hyprland]]

** =hypr-dynamic-float-bitwarden-unlock-firefox=: Hack for dealing with Bitwarden's extension window on Firefox
:PROPERTIES:
:header-args:shell: :tangle (tdir "/hypr-dynamic-float-bitwarden-unlock-firefox") :shebang #!/usr/bin/env sh :mkdirp yes
:END:

Big name because this is so specific it will never be used outside of
=exec-once=.

- See
  + [[https://github.com/hyprwm/Hyprland/issues/3835][Make `float` rule dynamic (related issue with Bitwarden opening maximized window on vault unlock) · Issue #3835 · hyprwm/Hyprland]]
  + [[https://www.reddit.com/r/hyprland/comments/1bg25vf/how_to_exit_fullscreen_when_opening_a_new_window/][How to exit fullscreen when opening a new window? : r/hyprland]]
    Along with running this script, setting
    ~misc:new_window_takes_over_fullscreen = 2~ may also be desired.

#+begin_src shell
socat -U - UNIX-CONNECT:"${XDG_RUNTIME_DIR}"/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock |
    stdbuf -o0 grep '^activewindow>>.*Extension: (Bitwarden Password Manager) - Bitwarden — Mozilla Firefox$' |
    while read -r _; do
        hyprctl --batch \
                dispatch setfloating title:'^(Extension:)(.*)(- Bitwarden — Mozilla Firefox)$' \; \
                dispatch centerwindow
    done
#+end_src

** =hypr-gamemode-monitors=
:PROPERTIES:
:header-args:shell: :tangle (tdir "hypr-gamemode-monitors") :shebang #!/usr/bin/env sh :mkdirp yes
:END:
Having different fractional scaling messes somethings up with some games.

So I have a source keyword for a file that overrides the default.
#+begin_src shell
sed -Ei 's/^[[:blank:]]*source = \.\/monitors-gamemode\.conf$/#&/
t
s/^#([[:blank:]]*source = \.\/monitors-gamemode\.conf)$/\1/' \
    ~/.config/hypr/monitors.conf
#+end_src


* Hyprland Notes
** Turn screen off (screen energy saver)
[[https://www.reddit.com/r/hyprland/comments/14u9p3v/turning_off_screens_after_locking_them/][Turning off screens after locking them : r/hyprland]]
# [2023-09-11 Mon 17:02:46 -03]

Use the command
: hyprctl dispatch dpms off
Though the setting =misc:key_press_enables_dpms= may needed to be set to
=false= if the screen turns on immediately after.

* Eww - Widgets
:PROPERTIES:
:tangle-dir: (concat (xdg-config-home) "/eww")
:END:

- Arch Linux Note:
  When installing =eww-git= from the AUR it fails with:
  : error: failed to run: gpg --recv-keys 94E8F34BCE4F4BA8ED9B29BD50E76B4711E4C3E4 5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23:

  The pinned comment in the AUR page gives the gpg keys:
  : curl -sS https://github.com/elkowar.gpg | gpg --import -i -
  : curl -sS https://github.com/web-flow.gpg | gpg --import -i -

** =eww.yuck=: main bar configuration file
:PROPERTIES:
:header-args:yuck: :tangle (tdir "/eww.yuck") :mkdirp yes
:END:

- See (Learning material)
  + [[https://elkowar.github.io/eww/configuration.html][Configuration - eww documentation]]
  + [[https://dharmx.is-a.dev/eww-powermenu/][EWW Powermenu - dead airspace]]

#+begin_src yuck :noweb yes
(defwindow mainbar
           :monitor "DELL S2721DGF"
           :geometry (geometry :x "0px"
                               :y "0px"
                               :width "100%"
                               :height "26px"
                               :anchor "top center")
           :stacking "fg" ; foreground is still below fullscreen
           :reserve (struts :distance "30px" :side "top")
           ;; :windowtype "dock" ; x11
           ;; :wm-ignore false ; x11
           :exclusive true ; wayland
           :namespace "bar" ; wayland
           :class "mainbar"
           (bar-all-modules))

(defwindow mainbar2
           :monitor "DELL P2418D"
           :geometry (geometry :x "0px"
                               :y "0px"
                               :width "100%"
                               :height "26px"
                               :anchor "top center")
           :stacking "fg" ; foreground is still below fullscreen
           :reserve (struts :distance "30px" :side "top")
           :exclusive true ; wayland
           :namespace "bar" ; wayland

           ;; for some reason when two defwindows use the same class it either
           ;; appends a number to it or requires manual disambiguation.
           :class "mainbar2"
           (box :space-evenly true
                (box :orientation "h"
                     :space-evenly false
                     (label :text "${time}" :class "time-label"))
                (box :orientation "h"
                     :space-evenly false
                     :halign "end"
                     (window-title-second-monitor)
                     (sep)
                     (workspaces)
                     (sep))))

(defwidget bar-all-modules []
           (box :space-evenly true
                :class "bar-all-modules"
                :orientation "h"
                (left-modules)
                ;; (center-modules)
                (right-modules)))

(defwidget sep []
           (label :class "separator" :text "|"))

(defwidget left-modules []
           (box :orientation "h"
                :space-evenly false
                :halign "start"
                :class "left-modules"
                (workspaces)
                (sep)
                (window-title)))

(defwidget center-modules []
           (box :orientation "h"
                :space-evenly false
                ;; :halign "center"
                :halign "center"
                :class "center-modules"))

(defwidget right-modules []
           (box :orientation "h"
                :space-evenly false
                :halign "end"
                :class "right-modules"
                (mpd-current :nth 0)
                (sep)
                (systray :orientation "h" :spacing 10 :icon-size 24)
                (sep)
                (label :text "${time}" :class "time-label")))

(defvar time-visible false)   ; for :run-while property of below variable
                              ; when this turns true, the polling starts and
                              ; var gets updated with given interval

(defpoll time :interval "5s"
              :initial "Loading date..."  ; optional, defaults to poll at startup
              :run-while time-visible   ; optional, defaults to 'true'
              "date +'%Y/%m/%d (%H:%M)'")

(deflisten workspaces-listen :initial "[]" "hypr-get-workspaces")
(deflisten current-workspace :initial '{"focused_monitor":{"active_workspace":"1"},"unfocused":{"active_workspace":"2"}}' "hypr-get-current-monitor-workspace")
(defwidget workspaces []
  (eventbox
   :class "workspaces-widget-eventbox"

   (box
    :space-evenly true
    (label :text "${workspaces-listen}${current-workspace}"
           :visible false)
    (for workspace in workspaces-listen
         (eventbox
          (box :class "workspace-entry ${workspace.id == current-workspace.focused_monitor.active_workspace ? "current" : ""} \
                       ${workspace.windows > 0 ? "occupied" : "empty"} \
                       ${workspace.id == current-workspace.unfocused_monitor.active_workspace ? "active-unfocused" : ""}"
               (label :text "${workspace.id}")))))))

(deflisten window-listen :initial "..." "hypr-get-window-title")
(deflisten window-listen-second-monitor :initial "..." "hypr-get-window-title-second-monitor DP-2")
(defwidget window-title []
  (box
   (label :text "${window-listen}"
          :limit-width 50
          :class "window-title-label"
          ;; :truncate-left true
          )))

(defwidget window-title-second-monitor []
  (box
   (label :text "${window-listen-second-monitor}"
          :limit-width 70
          :class "window-title-label"
          ;; :truncate-left true
          )))

(include "mpd.yuck")

#+end_src

#+begin_src yuck :tangle (tdir "mpd.yuck")
(defvar mpd-current-poll-state-1st true)

(defpoll mpd-current-json-1st-instance
         :interval "1s"
         :run-while mpd-current-poll-state-1st
         ;; dummy json until it loads the executable:
         :initial '{"status":{"duration":0.0,"elapsed":0.0,"elapsed_percent":0.0},"tags":{"title":"","album_artist":"","album":""}}'
         "mpd-current-json")

(defwidget seconds-to-length-format-hours [secs]
           (label :text { secs >= 3600 ? "${round(secs / 3600, 0)}:" : "" }))

(defwidget seconds-to-length-format-minutes [secs]
           (label :text { (secs / 60) < 10 ?
                          "0${round(secs / 60, 0)}" :
                          "${round(secs / 60, 0)}" }))

(defwidget seconds-to-length-format-seconds [secs]
           (label :text { (secs % 60) < 10 ?
                          "0${round(secs % 60, 0)}" :
                          "${round(secs % 60, 0)}" }))

(defwidget seconds-to-length [secs]
           (box
            :space-evenly false
            (seconds-to-length-format-hours :secs secs)
            (seconds-to-length-format-minutes :secs secs)
            ":"
            (seconds-to-length-format-seconds :secs secs)))

(defwidget mpd-current-nth-instance [curr-json ?icon]
           (box
            :space-evenly false

            (label :class "mpd-current-icon" :text icon)
            ;; Title
            (label :class "mpd-current-meta-field mpd-current-meta-field-title"
                   :limit-width 50
                   :text {"${curr-json.tags.title}" != "null" ? "${curr-json.tags.title}" : ""}
                   :tooltip {"${curr-json.tags.title}" != "null" ? "${curr-json.tags.title}" : ""})

            ;; Title Artist separator
            (label :class "mpd-current-artist-separator" :text "·")

            ;; Artist: if album_artist is empty, use Artist
            (label :class "mpd-current-meta-field mpd-current-meta-field-albumartist"
                   :limit-width 50
                   :text {curr-json.tags.album_artist != "null" ? curr-json.tags.album_artist :
                                    curr-json.tags.artist != "null" ? curr-json.tags.artist : ""}
                   :tooltip {curr-json.tags.album_artist != "null" ? curr-json.tags.album_artist :
                                       curr-json.tags.artist != "null" ? curr-json.tags.artist : ""})

            ;; Title Artist separator
            (label :class "mpd-current-artist-separator" :text "·")

            ;; Album
            (label :class "mpd-current-meta-field mpd-current-meta-field-album"
                   :limit-width 50
                   :text {curr-json.tags.album != "null" ? "${curr-json.tags.album}" : ""}
                   :tooltip {curr-json.tags.album != "null" ? "${curr-json.tags.album}" : ""})

            ;; Elapsed/Duration
            (box :spacing 2
                 :class "mpd-current-meta-field mpd-current-meta-field-elapsed"
                 :space-evenly false
                 (seconds-to-length :secs {curr-json.status.elapsed})
                 (label :text "/" :class "mpd-time-sep")
                 (seconds-to-length :secs {curr-json.status.duration})
                 (circular-progress :class "mpd-circular-progress"
                                    :width 20
                                    :height 20
                                    :value {curr-json.status.elapsed_percent}
                                    :thickness 4
                                    :start-at 70
                                    :valign "center"
                                    :tooltip "${curr-json.status.elapsed_percent}%"))))

(defwidget mpd-current-1st-wrap []
           (mpd-current-nth-instance :curr-json {mpd-current-json-1st-instance}))

(defvar mpd-expand-bool true)
(defwidget mpd-current []
           (box :class "mpd-current-box"
                :space-evenly false
                :orientation "h"
                :valign "center"
                (mpd-current-1st-wrap)))
#+end_src

** =eww.scss=: Customization for =eww.yuck= widgets
:PROPERTIES:
:header-args:scss: :tangle (tdir "/eww.scss") :mkdirp yes
:END:

Variables files, first dark:
#+begin_src scss :tangle (tdir "/dark-colors.scss") :mkdirp yes
$bar-bg: #222;
$neon-green: #76ee00;
$neron-green: #61bd09;
$middle-gray: #808080;
$neron-pink: #ff77cf;
$neron-fg: #a6a8a9;
$neron-current: #2f2f2f;
$current-icon: #666666;
#+end_src
then light:
#+begin_src scss :tangle (tdir "/light-colors.scss") :mkdirp yes
$bar-bg: #fff;
$neon-green: #76ee00;
$neron-green: #61bd09;
$middle-gray: #808080;
$neron-pink: #ff77cf;
$neron-fg: #333333;
$neron-current: #eee;
$current-icon: #666666;
#+end_src

Now import /one/ of them on the normal file =eww= expects to read:
#+begin_src scss :noweb yes
@import "<<lightordark()>>-colors.scss";
#+end_src

Based on the variables, customize the widgets:
#+begin_src scss :noweb yes
$current-bb-t: .15em;

// * { all: unset; }

.mainbar {
  // font-size: 14;
  color: $neron-fg;
  background-color: $bar-bg;
}

// for some reason when two defwindows use the same class it either
// appends a number to it or requires manual disambiguation.
.mainbar2 {
  // font-size: 14;
  color: $neron-fg;
  background-color: $bar-bg;
}

.workspace-entry {
  padding: 0 .2em;
  border-bottom: $current-bb-t solid $bar-bg; /* to make text not shift position when
                                               ,* .current uses border-bottom too */
  &:hover {
    background-color: $middle-gray;
  }
}

.workspace-entry.current {
  font-weight: bold;
  background-color: $neron-current;
  border-bottom: $current-bb-t solid $neron-green;
  // padding-bottom: 0;
}

.workspace-entry.occupied {
  color: $neron-fg;
}

.workspace-entry.empty {
  color: $neron-current;
}

.workspace-entry.active-unfocused {
  font-weight: bold;
  background-color: $neron-current;
  border-bottom: $current-bb-t solid $neron-pink;
  // padding-bottom: 0;

}

.separator {
  color: $neron-current;
  margin: 0 1em;
  font-weight: bold;
}

.window-title-label {
  color: $middle-gray;
}

.time-label {
  margin: 0 10 0 0;
}



.mpd-circular-progress {
  color: $middle-gray;
  background-color: $neron-current;
  // margin: 0 0;
  // width: 100;
}

.mpd-current-box {
  font-size: inherit;
  // font-weight: bold;
}

.mpd-current-meta-field {
  margin: 0;
}

.mpd-current-meta-field-album {
  margin: 0;
}

.mpd-current-meta-field-elapsed {
  margin: 0 0 0 15;
}

// .mpd-current-elapsed {
//   padding: 0 10 0 10;
// }

.mpd-current-icon {
  color: $current-icon;
  margin-right: 15;
}

.mpd-current-artist-separator {
  margin: 0 8;
}
#+end_src

** Eww Hyprland Scripts
:PROPERTIES:
:header-args:shell: :shebang #!/usr/bin/env sh :mkdirp yes :noweb yes
:tangle-dir: (expand-file-name "hyprland" (xdg-bin-home))
:END:

Scripts from [[https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#eww][Status bars – Hyprland Wiki#Eww]]

- DEPENDENCIES
  + socat
  + jaq or jq
  + coreutils: provides stdbuf

*** =hypr-get-active-workspace=
:PROPERTIES:
:header-args:shell+: :tangle (tdir "hypr-get-active-workspace")
:END:

#+begin_src shell
# tested on a dual-monitor setup, may not work with different ones

«hyprland-scripts-check-alias-jaq-or-jq»

active_focused_ws() {
    hyprctl monitors -j | jq -r ".[] | select(.focused == $1).activeWorkspace.id"
}

json_out_format() {
    printf '{"focused":"%s","unfocused":"%s"}\n' "$1" "$2"
}

json_out_format "$(active_focused_ws true)" "$(active_focused_ws false)"

socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR}"/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock - |
    stdbuf -o0 awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}' |
    while read -r line; do
        json_out_format "$(active_focused_ws true)" "$(active_focused_ws false)"
    done
#+end_src

*** =hypr-get-window-title=
:PROPERTIES:
:header-args:shell+: :tangle (tdir "hypr-get-window-title")
:END:

#+begin_src shell
«hyprland-scripts-check-alias-jaq-or-jq»

hyprctl activewindow -j | jq --raw-output .title

# shellcheck disable=SC2016
socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR}"/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock - |
    stdbuf -o0 grep '^activewindow>>' |
    stdbuf -o0 awk -F '>>|,' '{print $3}'
#+end_src

*** =hypr-get-workspaces=
:PROPERTIES:
:header-args:shell+: :tangle (tdir "hypr-get-workspaces")
:END:

#+begin_src shell :noweb yes
«hyprland-scripts-check-alias-jaq-or-jq»

spacesJq (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    seq 1 10 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spacesJaq() {
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jaq 'map({key: .id | tostring, value: .windows}) | from_entries')
    seq 1 10 | jaq --arg windows "${WORKSPACE_WINDOWS}" --slurp -M -c 'map(tostring) | map({id: ., windows: (($windows | fromjson)[.]//0)})'
}

if [ -n "${__usingjaq}" ]; then
    alias spaces=spacesJaq
else
    alias spaces=spacesJq
fi

spaces

socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR}"/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock - |
    while read -r _; do
        spaces
    done
#+end_src


*** =hypr-get-window-title-second-monitor=
:PROPERTIES:
:header-args:shell+: :tangle (tdir "hypr-get-window-title-second-monitor")
:END:
#+begin_src shell :dir (expand-file-name "hypr" (xdg-config-home)) :noweb yes
«hyprland-scripts-check-alias-jaq-or-jq»

MONITOR_PORT=${MONITOR_PORT:-$1}
MONITOR_PORT=${MONITOR_PORT:-"DP-2"}

get_window_title_workspace_mon() {
    idActiveWorkspaceOnMon=$(hyprctl monitors -j | jq -r --arg monitor_port "${MONITOR_PORT}" '.[] | select(.name == $monitor_port).activeWorkspace.id')
    hyprctl workspaces -j | jq --arg idActiveWorkspaceOnMon "$idActiveWorkspaceOnMon" -r '.[] | select(.id == ($idActiveWorkspaceOnMon | tonumber)).lastwindowtitle'
}

get_window_title_workspace_mon

socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR}"/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock - |
    stdbuf -o0 grep '^\(activewindow\|focusedmon\)>>' |
    while read -r _; do
        get_window_title_workspace_mon
    done
#+end_src

*** =hypr-eww-restart-on-monitor-change=: Restart eww on monitor on/off/reconnect
:PROPERTIES:
:header-args:shell+: :tangle (tdir "hypr-eww-restart-on-monitor-change")
:END:
#+begin_src shell :noweb yes
eww_restart() {
    # [ -f /tmp/eww-restarting ] && return
    # touch /tmp/eww-restarting

    # tested debounce but enough sleep should work regardless, maybe
    sleep 5

    eww kill
    eww daemon &&
        eww ping &&
        eww open mainbar &&
        eww open mainbar2

    # rm -f /tmp/eww-restarting
}

socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR}"/hypr/"${HYPRLAND_INSTANCE_SIGNATURE}"/.socket2.sock - |
    stdbuf -o0 grep '^monitoradded>>' |
    while read -r event; do
        eww_restart
    done
#+end_src


* Hyprland-specific file mime associations
- *NOTE*: The file name for the "DE"-specific "=*-mimeapps.list=" file
  should contain the value of the =XDG_CURRENT_DESKTOP= env var, in this
  case, since it's =Hyprland= the filename is also named that, including
  the capital letter.
#+begin_src conf :tangle (expand-file-name "Hyprland-mimeapps.list" (xdg-config-home))
# [Default Applications]


# [Added Associations]
# text/x-c=firefox.desktop;
#+end_src

* Local file variables & Noweb variables                    :noexport:ignore:
:PROPERTIES:
:header-args:conf: :tangle no
:END:
# Local Variables:
# org-confirm-babel-evaluate: nil
# End:

#+NAME: lightordark
#+begin_src shell
lightordark
#+end_src

