decoration {
    shadow {
        enabled = false
        range = 20
        render_power = 3
        color = rgba(00000080)
        color_inactive = rgba(00000000)

        ignore_window = true
        scale = 1
    }
}
