env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1

misc {
     vrr=2 # 0 - off, 1 - on, 2 - fullscreen only

     vfr=true
}

cursor {
    no_hardware_cursors = true
    # no_break_fs_vrr = true # not useful for me
}
