# See https://wiki.hyprland.org/Configuring/Window-Rules/
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = float,title:^(Edit with Emacs FRAME)$
windowrulev2 = float,class:^.*(floatWMRULE|FLOAT_WMRULE)$
windowrulev2 = float,title:^.*(floatWMRULE|FLOAT_WMRULE)$
# windowrulev2 = opacity 0.94 0.94,class:^(Dunst)$
windowrulev2 = float,title:^Open File(|s)
windowrulev2 = float,title:^Vivaldi Settings:
windowrulev2 = suppressevent maximize, class:^mpv$
windowrulev2 = float,class:.*\.exe$

# Emacs
windowrulev2 = float,class:(emacs),title:(Ediff)
windowrulev2 = size 720 330,class:(emacs),title:(Ediff)
windowrulev2 = move cursor -50% -50%,class:(emacs),title:(Ediff)

# Blender
windowrulev2 = float,title:^Blender (Render|Preferences)$

# Steam & Games
windowrulev2 = float,title:^Create or select new Steam library folder$
windowrulev2 = float,class:steam,title:Friends List
windowrulev2 = float,class:steam,title:Steam Settings
# windowrulev2 = float,class:steam # just float everything steam
windowrule = monitor 0 silent,class:^(steam_app_[0-9]+)$
windowrule = workspace 6 silent,class:^(steam_app_[0-9]+)$
## unstable fps on background "minimize" fix
windowrulev2 = renderunfocused,class:steam_app_2622380,title:ELDEN RING NIGHTREIGN
misc {
  render_unfocused_fps = 30
}

# File managers
windowrulev2 = float,class:org.kde.ark,title:^(File Already Exists).*Ark$
windowrulev2 = float,class:org.kde.dolphin,title:^(Choose Application).*Dolphin$
windowrulev2 = float,class:org.freedesktop.impl.portal.desktop.kde # xdg-desktop-portal dolphin

# Browser
windowrulev2 = float,class:firefox,title:^$ # firefox notification pop-ups are empty
windowrulev2 = float,class:firefox,title:Library
# mainly for xwayland chromium browsers' context menu where ignorezero
# can't be used because of the lack of class or title.
windowrulev2 = noblur,class:^()$,title:^()$

# Inkscape
windowrulev2 = float, class:^(org.inkscape.Inkscape)$, title:^(SVG Input)$
