# See https://wiki.hyprland.org/Configuring/Window-Rules/
windowrule = float,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float,title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = float,title:^(Edit with Emacs FRAME)$
windowrule = float,class:^.*(floatWMRULE|FLOAT_WMRULE)$
windowrule = float,title:^.*(floatWMRULE|FLOAT_WMRULE)$
# windowrule = opacity 0.94 0.94,class:^(Dunst)$
windowrule = float,title:^Open File(|s)
windowrule = float,title:^Vivaldi Settings:
windowrule = suppressevent maximize, class:^mpv$
windowrule = float,class:.*\.exe$

# Emacs
windowrule = float,class:(emacs),title:(Ediff)
windowrule = size 720 330,class:(emacs),title:(Ediff)
windowrule = move cursor -50% -50%,class:(emacs),title:(Ediff)

# Blender
windowrule = float,title:^Blender (Render|Preferences)$

# Steam & Games
windowrule = float,title:^Create or select new Steam library folder$
windowrule = float,class:steam,title:Friends List
windowrule = float,class:steam,title:Steam Settings
# windowrule = float,class:steam # just float everything steam
windowrule = monitor 0 silent,class:^(steam_app_[0-9]+)$
windowrule = workspace 6 silent,class:^(steam_app_[0-9]+)$
## unstable fps on background "minimize" fix
windowrule = renderunfocused,class:steam_app_2622380,title:ELDEN RING NIGHTREIGN
misc {
  render_unfocused_fps = 30
}

# File managers
windowrule = float,class:org.kde.ark,title:^(File Already Exists).*Ark$
windowrule = float,class:org.kde.dolphin,title:^(Choose Application).*Dolphin$
windowrule = float,class:org.freedesktop.impl.portal.desktop.kde # xdg-desktop-portal dolphin

# Browser
windowrule = float,class:firefox,title:^$ # firefox notification pop-ups are empty
windowrule = float,class:firefox,title:Library
# mainly for xwayland chromium browsers' context menu where ignorezero
# can't be used because of the lack of class or title.
windowrule = noblur,class:^()$,title:^()$

# Inkscape
windowrule = float, class:^(org.inkscape.Inkscape)$, title:^(SVG Input)$
