width = 400
height = 60
border_offset = 0
border_size = 2
anchor = center center
margin = 100

background_color = 00000000
bar_color = 61bd09ee
# neronfg a6a8a9
border_color = ff77cf80
# col.active_border = rgba(61bd09ee) rgba(ff77cfee) 45deg
