:PROPERTIES:
:header-args:emacs-lisp: :export both :mkdirp yes :results drawer :cache yes :noweb no-export
:END:
#+title: Emacs "init" config file
#+author: 11xx
# #+STARTUP: hidestars

# Export as HTML
#+SETUPFILE: ~/org/setupfiles/theme-readtheorg.setup

# #+OPTIONS: toc:2

Send errors to *Backtrace*, only set to true while debugging
: (setq debug-on-error t)

* Dependencies
- Arch
  + ttf-liberation-mono-nerd
  + otf-fira-code-symbol [AUR]
  + aspell + aspell-* # ispell
  + xdg-desktop-portal: See [[*Day/Night theme switch][Day/Night theme switch]].

* References
Here are some complete configuration examples:

- [[https://github.com/progfolio/.emacs.d/blob/master/init.org][progfolio's .emacs.d/init.org]]
- [[https://github.com/garyo/emacs-config][garyo/emacs-config: Emacs configuration]]
- [[https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org][angrybacon's dotemacs]]
- [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org][David Wilson's Emacs Configuration]]
- [[https://tecosaur.github.io/emacs-config/config.html][tecosaur's Doom Emacs Configuration]]
- [[https://github.com/zw963/.emacs.d/tree/master][GitHub - zw963/.emacs.d: My own .emacs.d]]


* early-init.el
:PROPERTIES:
:header-args:emacs-lisp: :tangle early-init.el
:END:

Enable lexical binding default.
# Had bad luck with this actually being set globally in the past but let's see
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-

(setq-default lexical-binding t)
#+end_src

** Local Lisp modules
Emacs activates a user Lisp directory during startup: every file below it is
byte-compiled, scraped for autoload cookies and added to =load-path=, all
before =init.el= runs. The [[#load-config][pseudo-packages]] live in =lisp/= rather than the
default =user-lisp/=, which is where the Org blocks in this file tangle them.

Startup reads this variable between loading =early-init.el= and activating the
directory, so it only takes effect here.
#+begin_src emacs-lisp
(setq user-lisp-directory (locate-user-emacs-file "lisp/"))
#+end_src

** Activate packages before the Lisp modules compile
:PROPERTIES:
:CUSTOM_ID: activate-packages-early
:END:
Startup activates the installed packages, then byte-compiles the user Lisp
directory, and only then loads =init.el=. Byte-compiling a ~use-package~ form
needs the package on =load-path= to expand its macros, reads the ~use-package~
defaults at expansion time, and installs a missing package right then rather
than at run time. Everything that shapes that compilation therefore has to be
in place here: package activation stays enabled, the archives are registered,
and the ~use-package~ defaults are set before any module compiles.
#+begin_src emacs-lisp
(setq package-enable-at-startup t)

(require 'package)
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("nongnu" . "https://elpa.nongnu.org/nongnu/") t)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(setopt use-package-always-ensure t)
#+end_src

The modules compile one by one, and a module that requires a sibling whose
source changed would load the sibling's stale byte-code into this very
session. Preferring the newer of source and byte-code prevents that.
#+begin_src emacs-lisp
(setq load-prefer-newer t)
#+end_src

Compiling the modules also queues their native compilation before =init.el=
gets a chance to quieten it, so the reporting level is set here.
#+begin_src emacs-lisp
(setopt native-comp-async-report-warnings-errors 'silent)
#+end_src

That native compilation writes into the first directory of the eln load path,
so the cache is redirected here as well. The location is the =var/= directory
that [[#no-littering][no-littering]] manages once =init.el= loads it; naming it here keeps every
compiler writing to the one cache the running session reads from.
#+begin_src emacs-lisp
(when (and (fboundp 'startup-redirect-eln-cache) (native-comp-available-p))
  (startup-redirect-eln-cache
   (convert-standard-filename
    (expand-file-name "var/eln-cache/" user-emacs-directory))))
#+end_src

** Startup time report
#+begin_src emacs-lisp
(add-hook 'emacs-startup-hook
  (lambda ()
    (message "*** Emacs loaded in %s seconds with %d garbage collections."
             (emacs-init-time "%.2f")
             gcs-done)))
#+end_src
#+begin_seealso
- https://blog.d46.us/advanced-emacs-startup/
- Defun [[https://youtu.be/9i_9hse_Y08?t=234]]
#+end_seealso

** Prevent white flashbang on startup
:PROPERTIES:
:CUSTOM_ID: prevent-white-flashbang-on-startup
:END:

#+begin_seealso
Credits: [[https://github.com/doomemacs/doomemacs/issues/2828#issuecomment-627095431][White flash on initial open · Issue #2828 · doomemacs/doomemacs]]
#+end_seealso

When starting a fresh Emacs instance the frame may display a white background
for a few moments. To fix this simply change the default =background-color=
from the =early-init.el= file, just so it loads before the frame is created:
# "#17191a"
#+begin_example
(add-to-list 'default-frame-alist '(background-color . "#222222"))
#+end_example
# [2022-12-02 Fri 21:23:24 -03]

***** Set initial background color based on system's color scheme
# pcase example from [[https://www.reddit.com/r/emacs/comments/108kwyl/comment/j3w5j88/?context=3][New package: Darkman integration with Emacs. : emacs]]
Before loading the theme
#+begin_src emacs-lisp
(require 'dbus nil t)
(defun is-dark-color-scheme-dbus ()
  ;; copy of 'auto-dark--is-dark-mode-dbus' from 'auto-dark.el'.
  ;; 0 = light, being a fallback default
  ;; 1 = dark
  ;; 2 = light
   "Read color-scheme from org.freedesktop.portal.Settings appearance interface.
Returns t if dark, nil otherwise."
  (eq 1 (caar (dbus-ignore-errors
                (dbus-call-method
                 :session
                 "org.freedesktop.portal.Desktop"
                 "/org/freedesktop/portal/desktop"
                 "org.freedesktop.portal.Settings" "Read"
                 "org.freedesktop.appearance" "color-scheme")))))

(when (and initial-window-system (is-dark-color-scheme-dbus))
  (setq frame-background-mode 'dark)

  (let ((bg-color "#222222")
        (fg-color "#eeeeee"))
    (add-to-list 'initial-frame-alist `(background-color . ,bg-color))
    (add-to-list 'initial-frame-alist `(foreground-color . ,fg-color))
    (add-to-list 'default-frame-alist `(background-color . ,bg-color))
    (add-to-list 'default-frame-alist `(foreground-color . ,fg-color))))
#+end_src


* init.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle init.el
:CUSTOM_ID: init-el
:END:

** Customise Options/Variables
#+begin_src emacs-lisp
(setopt read-process-output-max (* 3 (* 1024 1024)))
#+end_src
"Increase the amount of data which Emacs reads from the process.
Again the emacs default is too low 4k considering that the some of
the language server responses are in 800k - 3M range."
[[https://emacs-lsp.github.io/lsp-mode/page/performance/][emacs-lsp - Performance Guide]]

- Indentation options
  + See
    * [[https://www.emacswiki.org/emacs/NoTabs#h5o-1][So How Do I Insert a Tab If I Really Have To?]]
    * [[https://kb.iu.edu/d/abde][Set tab size]]
    * [[https://www.emacswiki.org/emacs/NoTabs][No Tabs]]

Disable tabs for spaces.
#+begin_src emacs-lisp
(setopt indent-tabs-mode nil ; disable tabs
        tab-width 2
        tab-stop-list (number-sequence 2 4 2) ; if `tab-width' in not read, use this
        tab-always-indent t)
#+end_src

Where paragraph breaks
#+begin_src emacs-lisp
(setopt fill-column 79)
#+end_src

start up behavior
See [[https://tychoish.com/post/towards-faster-emacs-start-times/][Towards Faster Emacs Start Times#Helpful Settings]]
#+begin_src emacs-lisp
(setopt inhibit-startup-message t
        initial-scratch-message nil)
#+end_src

undo/redo
[[https://emacs.stackexchange.com/questions/51956/no-further-undo-information/51970#51970][No further undo information - Emacs Stack Exchange]]
#+begin_src emacs-lisp
(setopt undo-limit (* 1024 1024 1024)
        undo-strong-limit (* 1024 1024 1024)
        undo-outer-limit (* 1024 1024 1024))
#+end_src

Turn off sounds
- [[https://emacs.stackexchange.com/questions/28906/how-to-switch-off-the-sounds][bell - How to switch off the sounds? - Emacs Stack Exchange]]
#+begin_src emacs-lisp
(setopt ring-bell-function 'ignore)
#+end_src
# [2024-02-03 Sat 23:36:30 -03:00] @winr58

- Laggy/Sluggish cursor movement
  #+begin_seealso
  - [[https://emacs.stackexchange.com/questions/28736/emacs-pointcursor-movement-lag/28746#28746][motion - Emacs point(cursor) movement lag - Emacs Stack Exchange]]
  # [2023-06-20 Tue 12:58:11 -03]
  - [[https://www.reddit.com/r/emacs/comments/819v0h/how_to_speed_up_cursor_movement_by_10x/][How to speed up cursor movement by 10x : emacs]]
    As pointed in the command, this is probably a package issue, since running
    ~emacs -Q~ doesn't present this issue.
  - ~auto-window-vscroll~ made the most difference, go figure 🤷‍
  #+end_seealso
#+begin_src emacs-lisp
(setopt auto-window-vscroll nil)
#+end_src

Little safety-net for internal deletion functions
#+begin_src emacs-lisp
(setopt delete-by-moving-to-trash t)
#+end_src

Native compilation settings
#+begin_src emacs-lisp
(setopt native-comp-jit-compilation t
        package-native-compile t)
#+end_src

- Garbage colletion \\
  Increase Garbage Collection threshold:
  + [[https://github.com/mnewt/dotemacs/blob/master/early-init.el#L19-L22][mnewt/dotemacs/early-init.el#L19-L22]].
  + [[https://emacs-lsp.github.io/lsp-mode/page/performance/#adjust-gc-cons-threshold][Performance - LSP Mode - LSP support for Emacs]]

  The 500 MiB threshold only spans startup, where allocation is heavy and
  short-lived. Once init is done it drops to the 100 MiB the LSP performance
  page recommends, so a collection stays short while still being rare.
#+begin_src emacs-lisp
(setq gc-cons-threshold (* 500 1024 1024))
(add-hook 'after-init-hook
          (lambda ()
            (setq gc-cons-threshold (* 100 1024 1024)
                  gc-cons-percentage 0.6)))
#+end_src

** Clean Emacs directory

*** no-littering
:PROPERTIES:
:CUSTOM_ID: no-littering
:END:
Package activation and the native-compilation cache are already arranged in
[[#activate-packages-early][early-init]], so the package only needs loading.
#+begin_src emacs-lisp
(use-package no-littering)
#+end_src

*** Move back-up and auto-save files
Backup & auto-save
#+begin_seealso
- See
  + [[https://lucidmanager.org/productivity/manage-files-with-emacs/][manage-files-with-emacs]]
  + [[https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files/18330742#18330742][backup files config example]]
  + [[https://emacs.stackexchange.com/questions/60970/how-to-replace-focus-out-hook-with-after-focus-change-function-in-emacs-27/60971#60971][replacing focus-out-hook]]
  + [[https://superuser.com/questions/411982/emacs-changing-the-location-of-auto-save-files/437563#437563][Emacs: Changing the location of auto-save files#437563]]
  + [[https://superuser.com/questions/411982/emacs-changing-the-location-of-auto-save-files/412007#412007][Emacs: Changing the location of auto-save files#412007]]
#+end_seealso

#+begin_src emacs-lisp
(require '11xx-functions)

(defvar 11xx--backup-directory
  (expand-file-name "backups"
                    (expand-file-name "var" user-emacs-directory))
  "Custom backup-files directory.")

;; Auto-save directory variable
(defvar 11xx--auto-save-directory
  (expand-file-name "auto-save"
                    (expand-file-name "var" user-emacs-directory))
  "Custom auto-save files directory.")

(ensure-directory 11xx--backup-directory)
(ensure-directory 11xx--auto-save-directory)

(setopt backup-directory-alist `((".*" . ,11xx--backup-directory))
        auto-save-file-name-transforms `(("\\(?:[^/]*/\\)*\\(.*\\)" ,(concat 11xx--auto-save-directory "\\\\1") t))
        auto-save-list-file-prefix 11xx--auto-save-directory
        auto-save-list-file-name (concat 11xx--auto-save-directory "/auto-save-list")
        make-backup-files t    ; backup of a file the first time it is saved.
        backup-by-copying t    ; don't clobber symlinks
        version-control t      ; version numbers for backup files
        delete-old-versions t  ; delete excess backup files silently
        kept-old-versions 6    ; oldest versions to keep when a new numbered backup is made (default: 2)
        kept-new-versions 9    ; newest versions to keep when a new numbered backup is made (default: 2)
        auto-save-default t    ; auto-save every buffer that visits a file
        auto-save-timeout 10   ; number of seconds idle time before auto-save (default: 30)
        auto-save-interval 150) ; number of keystrokes between auto-saves (default: 300)

;; silence "Auto-saving..." messages on minibuffer
(advice-add 'do-auto-save :around
  (lambda (orig-fn &rest args)
    (let ((inhibit-message t))
      (apply orig-fn args))))
#+end_src
- *NOTE* about =.#filename@=: They're lock files and are meant to be
  alongside the file being edited until a save occurs.

  Instead, disable lock files (=.#file@=).
  + See https://emacs.stackexchange.com/a/78802.
  #+begin_src emacs-lisp
  (setopt create-lockfiles nil)
  #+end_src
  +Is this legacy stuff from the ancient times of shared terminals?+
  # [2024-02-14 Wed 11:00:23 -03] @ak

** Load config
:PROPERTIES:
:CUSTOM_ID: load-config
:END:
Personal config modularized into "pseudo-packages". The [[*Local Lisp modules][user Lisp directory]]
already put =lisp/= on =load-path= and loaded its autoloads, so these resolve
without further setup.
#+begin_src emacs-lisp
(require '11xx-functions)
(require 'utf-8-default)
(require '11xx-defaults)
(require '11xx-completion)
(require '11xx-ui)
(require '11xx-navigation)
(require '11xx-half-scroll)
(require '11xx-pixel-scroll)

(require '11xx-dired)

(require '11xx-magit)
(with-eval-after-load 'org
  (require '11xx-org))

(require '11xx-modes)
(require 'llm-ai-assistants)
(require '11xx-pdf-viewer)
#+end_src

* 11xx-defaults.el: New defaults
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-defaults.el
:END:
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

** Emacs setup
- Notes:
  + *Modes not starting:* Probably due to them being local-buffer specific.
    See [[https://stackoverflow.com/questions/22968922/function-defined-in-emacs-does-not-start-automatically][Function defined in .emacs does not start automatically]].
  + *Describe Hooks:* Hooks are variables.
  + *Hook orders matters:* e.g. ~:with-mode~ options should have
    ~:hook-into~ macro /before/ ~:with-hook~.
  + *Use of lamba():* Usually the use of ~(lambda()...)~ around this
    config was tested and caused problems when not using it.

#+begin_src emacs-lisp
(keymap-global-set "C-c C-/" #'comment-region)
(keymap-global-set "C-c C-M-/" #'uncomment-region)
(keymap-global-set "<remap> <mark-word>" #'mark-whole-word)
(keymap-global-set "C-c a f v" #'add-file-local-variable)
(keymap-global-set "C-c d f v" #'delete-file-local-variable)
(keymap-global-set "C-c a f p" #'add-file-local-variable-prop-line)
(keymap-global-set "C-c d f p" #'delete-file-local-variable-prop-line)
(keymap-global-set "C-c C-M-t" #'visual-line-mode)
(keymap-global-set "C-c M-t" #'toggle-truncate-lines)
(keymap-global-set "C-x C-z" #'org-set-property)
(keymap-global-set "C-z" #'org-set-property)
(keymap-global-set "C-S-<left>" #'shrink-window-horizontally)
(keymap-global-set "C-S-<right>" #'enlarge-window-horizontally)
(keymap-global-set "C-S-<down>" #'shrink-window)
(keymap-global-set "C-S-<up>" #'enlarge-window)
(keymap-global-set "C-M-d" #'delete-pair)
(keymap-global-set "M-D" #'delete-pair)
(keymap-global-set "M-." #'forward-list)
(keymap-global-set "M-," #'backward-list)
(keymap-global-set "C-M-." #'down-list)
(keymap-global-set "C-M-," #'backward-up-list)

(put 'narrow-to-region 'disabled nil)
(put 'narrow-to-page 'disabled nil)
(put 'narrow-to-defun 'disabled nil)
(put 'widen 'disabled nil)
(put 'downcase-region 'disabled nil)

(add-function :after after-focus-change-function
              (lambda () (save-some-buffers t)))

(save-place-mode 1)
(delete-selection-mode 1)
(electric-pair-mode 1)
(electric-indent-mode 1)
#+end_src

- Show whitespace but disable in some modes
  + Also see [[org-dispatcher-disable-show-whitespace][Disable show-trailing-whitespace on Org Export Dispatcher]]
#+begin_src emacs-lisp
(use-package whitespace
  :hook ((prog-mode . whitespace-mode)
         (text-mode . whitespace-mode))
  :init
  (setq whitespace-style '(face tabs missing-newline-at-eof)
        show-trailing-whitespace t)
  :config
  (dolist (hook '(special-mode-hook
                  term-mode-hook
                  vterm-mode-hook
                  comint-mode-hook
                  compilation-mode-hook
                  minibuffer-setup-hook
                  minibuffer-mode-hook
                  calendar-mode-hook
                  eshell-mode-hook
                  completion-list-mode-hook
                  messages-buffer-mode-hook
                  diff-mode-hook))
    (add-hook hook (lambda () (setq-local show-trailing-whitespace nil)))))
#+end_src

- sexp movement
  #+begin_seealso
  - [[https://stackoverflow.com/questions/1771102/changing-emacs-forward-word-behaviour/2565961#2565961][emacs23 - Changing Emacs Forward-Word Behaviour - Stack Overflow]]
  - [[https://stackoverflow.com/questions/58300666/backward-same-syntax-in-emacs/58306071#58306071]["backward-same-syntax" in Emacs - Stack Overflow]]
  #+end_seealso
#+begin_src emacs-lisp
(add-hook 'after-init-hook #'global-superword-mode)
#+end_src


#+begin_src emacs-lisp
(use-package ace-window
  :bind (("M-o" . ace-window))
  :init
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)
        aw-scope 'frame))

;; new remap format is "<remap> <what-to-remap>" #'my-function
(use-package helpful
  :bind (("<remap> <describe-function>" . helpful-callable)
         ("<remap> <describe-command>" . helpful-command)
         ("<remap> <describe-variable>" . helpful-variable)
         ("<remap> <describe-key>" . helpful-key)
         ("<remap> <describe-symbol>" . helpful-symbol)))

(use-package which-key
  :init
  (setq which-key-idle-delay 2.0))


(use-package jump-char
  :after kmacro
  :bind (("C-c j f" . jump-char-forward)
         ("C-c j b" . jump-char-backward)
         ("C-c j m f" . jump-char-forward-set-mark)
         ("C-c j m b" . jump-char-backward-set-mark)))

#+end_src

- Customize how mode indicators appear in the modeline
  + See [[https://www.gnu.org/software/emacs/manual/html_node/use-package/Delight.html][Delight (use-package User Manual)]].
#+begin_src emacs-lisp
(use-package delight)
#+end_src

- Spell check
  + =ispell-program-name= should be automatically set when a supported program is
    installed
  #+begin_seealso
  [[https://endlessparentheses.com/ispell-and-org-mode.html][Making Ispell work with org-mode in Emacs · Endless Parentheses]]
  #+end_seealso

#+begin_src emacs-lisp
(setopt ispell-dictionary "en_GB")

(defun endless/org-ispell ()
  "Configure `ispell-skip-region-alist' for `org-mode'."
  (make-local-variable 'ispell-skip-region-alist)
  (add-to-list 'ispell-skip-region-alist '(org-property-drawer-re))
  (add-to-list 'ispell-skip-region-alist '("~" "~"))
  (add-to-list 'ispell-skip-region-alist '("=" "="))
  (add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_SRC" . "^#\\+END_SRC")))
(add-hook 'org-mode-hook #'endless/org-ispell)
#+end_src

** =custom.el= file
file to store ~customize~ options. This can be disabled but
~init.el~ will receive all generated code. It's also useful
for preventing Org Babel Tangle to override =Customize= changes. [[https://stackoverflow.com/questions/5052088/what-is-custom-set-variables-and-faces-in-my-emacs/5058752#5058752][src]]

Defined in Emacs setup
#+begin_src emacs-lisp
(setq custom-file (expand-file-name "custom.el" no-littering-var-directory))

(defun check-file-touch (file)
  "Check if FILE exists and create it if it doesn't.
It uses `make-empty-file' PARENTS argument 't'."
  (if (not (file-exists-p file))
      (make-empty-file file)))

(check-file-touch custom-file)

(load custom-file 'noerror 'nomessage)
#+end_src
** Async
[[https://github.com/jwiegley/emacs-async][jwiegley/emacs-async: Simple library for asynchronous processing in Emacs]]
#+begin_src emacs-lisp
(use-package async)
#+end_src

*** =detached.el=
[[https://git.sr.ht/~niklaseklund/detached.el][~niklaseklund/detached.el - sourcehut git]]

Install the AUR =dtach= package, or the newer fork =dtach-ng=.
Note that by default =dired= don't provide the full path to the =dtach= command.
The full path is required.
#+begin_src emacs-lisp
(use-package detached
  :bind (("<remap> <async-shell-command>" . detached-shell-command)
         ("<remap> <compile>" . detached-compile)
         ("<remap> <recompile>" . detached-compile-recompile)
         ("<remap> <detached-open-session>" . detached-consult-session))
  :init
  (setq detached-show-output-on-attach t)
  :config
  (detached-init))
#+end_src

** TRAMP
Fix connecting to a GUIX system, e.g. when given the errors:
: Tramp: Opening connection nil for user@192.168.xx.xx using ssh...done
: File error: Couldn't find a proper `ls' command
: tramp-error: Couldn't find a proper `ls' command
#+begin_src emacs-lisp
(use-package tramp
  :ensure nil
  :config
  (add-to-list 'tramp-remote-path 'tramp-own-remote-path))
#+end_src
#+begin_quote
Basically, since Guix doesn't store =ls= in the normal FHS-like location
(it's not =/bin/ls=), TRAMP can't find it by default. There's a symbol
called =tramp-own-remote-path= that (I think) is supposed to use the
login shell's environment to grab a path and find the commands TRAMP
needs.

--- [[https://www.reddit.com/r/GUIX/comments/uco6fg/comment/i6c407x/][emacs multihop sudo fails with guix : r/GUIX]]
#+end_quote
# (Retrieved at [2024-11-12 Tue 01:14])

** desktop-save
Save state for session restoring
#+begin_src emacs-lisp
(use-package desktop
  :ensure nil
  :init
  (defvar 11xx--daemon-name
    (let ((d (daemonp)))
      (cond
       ((stringp d) d)
       ((eq d t)   "default")
       (t           nil)))
    "Server name this Emacs instance is running as, or nil if not a daemon.
Mirrors `daemonp': a string for named daemons (--daemon=NAME), \"default\"
for unnamed (--daemon), nil for interactive sessions.")

  :config
  (when 11xx--daemon-name
    (setq desktop-base-file-name (format ".emacs-%s.desktop" 11xx--daemon-name)
          desktop-base-lock-name (format ".emacs-%s.desktop.lock" 11xx--daemon-name)))

  (setq desktop-dirname (expand-file-name "desktop/" no-littering-var-directory)
        desktop-auto-save-timeout 1
        desktop-save 'ask-if-new)
  (desktop-save-mode))
#+end_src

** eros: Overlay eval result (better C-x C-e)
#+begin_src emacs-lisp
(use-package eros
  :hook (org-mode . eros-mode)
  :init
  (setq eros-eval-result-duration 'command
        eros-overlays-use-font-lock t))
#+end_src

** provide footer
#+begin_src emacs-lisp
(provide '11xx-defaults)
;;; 11xx-defaults.el ends here
#+end_src


* utf-8-default.el: Use UTF-8 for all character encoding
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/utf-8-default.el :noweb-ref utf-8-default
:END:
Encoding, pretty much anything other than strictly english ascii
writing requires a different encoding. So use UTF-8 as the
default encoding.
- See
  + [[http://xahlee.info/emacs/emacs/emacs_file_encoding.html][Emacs: Set Default File Encoding]]
  + [[https://stackoverflow.com/questions/20212703/problems-saving-file-with-unicode-characters/20564324#20564324][emacs - Problems saving file with Unicode characters - Stack Overflow]]
  + [[https://www.emacswiki.org/emacs/ChangingEncodings][EmacsWiki: Changing Encodings]]
  + [[https://emacs.stackexchange.com/questions/68647/automatically-change-encoding-of-process-buffers/68649#68649][shell - Automatically change encoding of process buffers - Emacs Stack Exchange]]
  + [[https://emacs.stackexchange.com/questions/19641/emacs-is-asking-me-for-a-coding-system-on-each-save][org mode - Emacs is asking me for a coding system on each save - Emacs Stack Exchange]]
  + [[https://stackoverflow.com/questions/20723229/how-to-reset-emacs-to-save-files-in-utf-8-unix-character-encoding/26401113#26401113][linux - How to reset emacs to save files in utf-8-unix character encoding? - Stack Overflow]]
  + [[https://skybert.net/craftsmanship/utf-8-for-the-impatient/][UTF-8 for the Impatient | skybert.net]]
# do this especially on Windows, else python output problem
#+begin_src emacs-lisp
(prefer-coding-system 'utf-8-unix)
(setopt x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING)
        default-process-coding-system '(utf-8-unix . utf-8-unix))

;; other than setting this one setting the others may be redundant.
(set-default-coding-systems 'utf-8-unix)

(set-buffer-file-coding-system 'utf-8-unix)
(set-clipboard-coding-system 'utf-8-unix)
(set-file-name-coding-system 'utf-8-unix)
(set-keyboard-coding-system 'utf-8-unix)
(set-selection-coding-system 'utf-8-unix)
(set-terminal-coding-system 'utf-8-unix)

(set-locale-environment "en.UTF-8")

(set-charset-priority 'unicode)

(provide 'utf-8-default)
#+end_src
# ;; (set-language-environment "UTF-8") ; maybe this is not for coding system :p
#
# ;; v-- maybe this is too much? keep cjk encoding by having this disabled.
# ;; (setq utf-translate-cjk-mode nil) ; disable CJK coding/encoding

To force LF UTF-8 on specific files, add a buffer or file local
variable with:
: M-: (setq-local buffer-file-coding-system 'utf-8-unix) RET
or
: M-x add-file-local-variable-prop-line RET coding RET utf-8 RET
or
: M-x add-file-local-variable RET coding RET utf-8 RET
# [2022-11-08 Tue 17:10:44 -03]

* 11xx-modes.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-modes.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src


** Add =modes= directory to Emacs path
Local mode-providing files
# [2022-04-27 Wed 07:19:42]
# [2026-04-07 Tue 05:50:12 -03] @ak
#+begin_src emacs-lisp
(add-to-list 'load-path (expand-file-name "modes" user-emacs-directory))
#+end_src

** Make shebang (#!) file executable when saved
[[https://youtu.be/764zoG1TxVk?t=1845][emacs early-init.el and general tips and tricks - YouTube]]

#+begin_src emacs-lisp
;; Make shebang (#!) file executable when saved
(add-hook 'after-save-hook 'executable-make-buffer-file-executable-if-script-p)
#+end_src

** Minor modes, Customisation, Hacks

*** Tree-Sitter Syntax Highlighting
[[https://emacs-tree-sitter.github.io/syntax-highlighting/][Tree-sitter Syntax Highlighting]]

- Emacs 29+, using =treesit=
  + [[https://git.savannah.gnu.org/cgit/emacs.git/tree/admin/notes/tree-sitter/starter-guide?h=feature/tree-sitter][starter-guide\tree-sitter\notes\admin - emacs.git - Emacs source repository]]
  + [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][How to Get Started with Tree-Sitter - Mastering Emacs]]
  + [[https://emacs.stackexchange.com/questions/78605/language-specific-tree-sitter-major-mode-wont-show-up][language specific tree-sitter major mode wont show up - Emacs Stack Exchange]]
  + use =treesit= instead of the third-party =tree-sitter= and:
    #+begin_quote
    Note that, just because you have installed a grammar, does /not/
    mean Emacs supports it. Someone still has to write the –
    admittedly, /way/ easier – syntax and indentation logic and all that
    good stuff.

    ----- [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][How to Get Started with Tree-Sitter - Mastering Emacs]]
    #+end_quote
    # (Retrieved at # [2024-03-16 Sat 07:03:10 -03] @ak

- Tree-Sitter supports Org-Mode code blocks since:
  + [[https://github.com/nvim-orgmode/orgmode/pull/139][Pull Request #139]].
  + [[https://github.com/nvim-orgmode/orgmode/issues/31][would it be possible to use treesitter in this · Issue #31 · nvim-orgmode/orgmode]]
  + [[https://www.masteringemacs.org/article/lets-write-a-treesitter-major-mode][Let's Write a Tree-Sitter Major Mode - Mastering Emacs]]

*NOTE*: =htmlize= uses different CSS selectors for =tree-sitter-hl-mode=
code highlighting, prefixed by something like
=org-tree-sitter-hl-faceX=, so CSS templetes that rely on normal
selectors may not work, causing exported code snippets to not be
colored by the stylesheet on the HTML file.
# [2022-04-25 Mon 05:44:00]

Additional Tree-Sitter content
- [[https://siraben.de11xx--2022/03/01/tree-sitter.html][How to write a tree-sitter grammar in an afternoon | siraben’s musings]]
  # [2022-04-28 Thu 16:46:45]

# #TODO moving to built-in `treesit' package
#+begin_src emacs-lisp
(add-to-list 'treesit-extra-load-path
             (expand-file-name "tree-sitter" user-emacs-directory))
#+end_src

*** Colour codes highlighting
#+begin_src emacs-lisp
(use-package rainbow-mode
  :hook (css-mode . rainbow-mode))
#+end_src

** Require split files
#+begin_src emacs-lisp
(require '11xx-modes-edit)
(require '11xx-modes-terminal)
(require '11xx-modes-langs)
(require '11xx-modes-special)
(require '11xx-modes-web)
#+end_src

** Edit Modes
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-edit.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** Systemd
Use [[https://github.com/pdbrown/systemd-mode][pdbrown's systemd-mode updated repo]], better for use with native-comp.
#+begin_src emacs-lisp
(use-package systemd
  :vc (:url "https://github.com/pdbrown/systemd-mode"))
#+end_src
# :files ("*.txt" "systemd.el" (:exclude ".git"))

*** YAML
#+begin_src emacs-lisp
(use-package yaml-mode
  :defer t)

;; considering `yaml-ts-mode' is already provided by Emacs
;; use `yaml-indent-line' with it.
(with-eval-after-load 'yaml-ts-mode
  (require 'yaml-mode)
  (add-hook 'yaml-ts-mode-hook
            (lambda ()
              (setq-local indent-line-function #'yaml-indent-line)
              (setq-local yaml-indent-offset 2)))

  (define-advice org-src-font-lock-fontify-block
    (:around (orig lang start end) my/yaml-strip-org-coderefs)
  "Prevent org code refs from breaking tree-sitter YAML fontification."
  (if (not (string-match-p (rx word-start "yaml") lang))
      (funcall orig lang start end)
    (let* ((coderef-re (rx (1+ blank)
                           "(ref:" (1+ (not (any " \t\n)"))) ")"
                           (* blank) eol))
           replacements)
      ;; Phase 1: swap (ref:...) for same-length spaces so TS sees valid YAML
      (with-silent-modifications
        (save-excursion
          (goto-char start)
          (while (re-search-forward coderef-re end t)
            (push (list (match-beginning 0)
                        (match-end 0)
                        (match-string 0))
                  replacements)
            (replace-match
             (make-string (- (match-end 0) (match-beginning 0)) ?\s)
             t t))))
      ;; Phase 2: fontify (TS sees clean YAML), then unconditionally restore
      (unwind-protect
          (funcall orig lang start end)
        (with-silent-modifications
          (save-excursion
            (pcase-dolist (`(,beg ,_end ,str) replacements)
              (goto-char beg)
              (delete-region beg (+ beg (length str)))
              (insert str)
              ;; faces on these positions are now from our spaces; override with comment
              (put-text-property beg (+ beg (length str))
                                 'face 'font-lock-comment-face)))))))))
#+end_src

*** PKGBUILD
#+begin_src emacs-lisp
(use-package pkgbuild-mode
  :hook (pkgbuild-mode . (lambda () (flymake-mode -1))))
#+end_src

*** PowerShell
# [2024-01-14 Sun 13:58:20 -03:00] @winr58
#+begin_src emacs-lisp
(use-package powershell
  :defer t)
#+end_src

*** Ansible
#+begin_src emacs-lisp
(use-package ansible
  :defer t)
(use-package ansible-vault
  :defer t)
(use-package ansible-doc
  :defer t)
#+end_src

*** =yuck-mode=: Specifically for EWW's (bar) config file
#+begin_src emacs-lisp
(use-package yuck-mode
  :defer t)
#+end_src

*** hyprlang/hyprland config language
#+begin_src emacs-lisp
(use-package hyprlang-ts-mode
  :mode "*hyprland.conf")
#+end_src

*** Picard
#+begin_src emacs-lisp
(use-package picard-mode
  :vc (:url "https://codeberg.org/useless-utils/picard-mode" :rev :newest)
  :config
  (use-package picard-ts-mode
    :ensure nil
    :after picard-mode
    :if (treesit-available-p)))
#+end_src

*** etc
randoms
#+begin_src emacs-lisp
(use-package etc-sudoers-mode :defer t)
(use-package dockerfile-mode :defer t)
#+end_src


*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-edit)
;;; 11xx-modes-edit.el ends here
#+end_src

** Special
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-special.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** =sensitive-mode=: Disable backup files on sensitive files
wizard [[https://anirudhsasikumar.net/blog/2005.01.21.html][Disabling Backup and Auto-save in Emacs]],
src [[https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files/18330742#18330742][How do I control how Emacs makes backup files? - Stack Overflow]]
# [2022-11-11 Fri 03:15:47 -03]

to enable it in files use e.g.
: # -*- eval: (sensitive-mode 1); -*-
: // -*-mode:asciidoc; mode:sensitive-minor; fill-column:132-*-

#+begin_src emacs-lisp
(define-minor-mode sensitive-mode
  "For sensitive files like password lists.
It disables backup creation and auto saving.

With no argument, this command toggles the mode.
Non-null prefix argument turns on the mode.
Null prefix argument turns off the mode."
  ;; The initial value.
  :init-value nil
  ;; The indicator for the mode line.
  :lighter " Sensitive"
  ;; The minor mode bindings.
  :keymap nil
  ;; added keywords instead of deprecated positional arguments:
  ;; fix for "Warning: Use keywords rather than deprecated positional
  ;; arguments to `define-minor-mode'" # [2022-11-11 Fri 16:09:40 -03]
  ;; See the commits from [[https://github.com/purcell/emacs.d/issues/780][Use keywords rather than positional arguments to define-minor-mode · Issue #780 · purcell/emacs.d]]

  (if (symbol-value sensitive-mode)
      (progn
        ;; disable backups
        (set (make-local-variable 'backup-inhibited) t)
        ;; disable auto-save
        (if auto-save-default
            (auto-save-mode -1)))
                                        ;resort to default value of backup-inhibited
    (kill-local-variable 'backup-inhibited)
                                        ;resort to default auto save setting
    (if auto-save-default
        (auto-save-mode 1))))
#+end_src

or use a list:
#+begin_example emacs-lisp
(setq auto-mode-alist
 (append
  (list
   '("\\.\\(vcf\\|gpg\\)$" . sensitive-minor-mode)
   )
   auto-mode-alist))
#+end_example

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-special)
;;; 11xx-modes-special.el ends here
#+end_src

** Terminal modes
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-terminal.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

[[https://www.youtube.com/watch?v=wa_wZIuT9Vw&t=2126s][Emacs From Scratch #9 - Learn to Love the Terminal Modes - YouTube]]
# [2022-04-30 Sat 13:45:02]
*** =eshell=: Emacs Lisp shell
[[https://www.emacswiki.org/emacs/EshellAlias][EmacsWiki: Eshell Alias]]
# [2022-05-03 Tue 17:49:09]
#+begin_src emacs-lisp
;; 'eshell-output-filter-functions void variable means that eshell has to be
;; started once first.
(use-package eshell
  :ensure nil
  :defer t
  :init
  (setq eshell-hist-ignoredups t
        eshell-scroll-to-bottom-on-input t
        eshell-history-size 10000
        eshell-buffer-maximum-lines 2048)
  :config
  (use-package eshell-syntax-highlighting)
  (use-package eshell-git-prompt)
  (add-hook 'eshell-first-time-mode-hook
            (lambda ()
              (add-hook 'eshell-pre-command-hook #'eshell-save-some-history)
              (add-to-list 'eshell-output-filter-functions #'eshell-truncate-buffer))))
#+end_src

*** eterm-256color
256color for =term-mode=
#+begin_src emacs-lisp
(use-package eterm-256color
  :hook (term-mode . eterm-256color-mode)
  :init
  (setq explicit-shell-file-name "bash"))
#+end_src

*** vterm
#+begin_src emacs-lisp
(use-package multi-vterm
  :defer t)
#+end_src

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-terminal)
;;; 11xx-modes-terminal.el ends here
#+end_src

** Languages
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-langs.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** Haskell
#+begin_src emacs-lisp
(use-package haskell-mode
  :defer t)
#+end_src

*** C
#+begin_src emacs-lisp
(use-package cc-mode
  :ensure nil
  :defer t
  :init
  (setq c-default-style '((java-mode . "java")
                          (awk-mode  . "awk")
                          (other     . "k&r"))
        c-basic-offset 2))
#+end_src

#+begin_src emacs-lisp
(defun org-babel-execute:c-ts (body params)
  "Execute a block of `c-ts-mode' as `c-mode' with Org Babel."
  (org-babel-execute:C body params))
#+end_src

**** TODO COMMENT Compile helper functions
# #TODO update # [2024-03-18 Mon 22:34:43 -03] @ak
# lol [2026-04-07 Tue 05:39:52 -03] @ak
***** Compile current C file
The =(compile)= function already defines the workin directory as the same
as the buffer's file location.
#+begin_src emacs-lisp
(defun compile-current-c-or-cpp-file ()
  "Compile current C or C++ buffer and return executable path.

Uses `gcc' for `.c' files and `g++' for `.cpp' files."
  (interactive)
  (let* ((file (buffer-file-name))
         (ext (downcase (or (file-name-extension file) "")))
         (compiler (pcase ext
                     ("c" "gcc")
                     ((or "cc" "cpp" "cxx" "c++") "g++")
                     (_ (user-error "Unsupported source extension: %s" ext))))
         (output (concat (file-name-sans-extension file) ".out"))
         (command (format "%s -o %s %s"
                          compiler
                          (shell-quote-argument output)
                          (shell-quote-argument file))))
    (compile command)
    output))
#+end_src

****** Hide compilation info buffer
wizard [[https://emacs.stackexchange.com/questions/62/hide-compilation-window/110#110][Hide *compilation* window - Emacs Stack Exchange]]
# [2022-04-25 Mon 05:32:31]
It continues open as =*compilation*=
#+begin_src emacs-lisp
(add-hook 'compilation-finish-functions
          (lambda (buf strg)
            (let ((win  (get-buffer-window buf 'visible)))
              (when win (delete-window win)))))
#+end_src

***** Floating terminal
#+begin_src emacs-lisp
(defun run-command-in-floating-terminal (command)
  "Open Alacritty with class=float and run shell COMMAND."
  (interactive)
  (message "Opening command in floating terminal: %s" command)
  (shell-command
   (concat
    "alacritty --class=float"
    " "
    "--option window.dimensions.columns=\"${w:-80}\""
    " "
    "window.dimensions.lines=\"${h:-20}\""
    " "
    "--command sh -c " (shell-quote-argument command))))
;; removed --hold bc bat paging holds the terminal until othewise [2022-04-24 Sun 14:41:04]
#+end_src

#+RESULTS:
: run-command-in-floating-terminal
***** C compile current file and run in the terminal
#+begin_src emacs-lisp
(defun compile-and-run-current-c-or-cpp-file ()
  "Compile current C/C++ file and run it in the terminal."
  (interactive)
  (let* ((file (buffer-file-name))
         (ext (downcase (or (file-name-extension file) "")))
         (compiler (pcase ext
                     ("c" "gcc")
                     ((or "cc" "cpp" "cxx" "c++") "g++")
                     (_ (user-error "Unsupported source extension: %s" ext))))
         (output (concat (file-name-sans-extension file) ".out"))
         (command (format "%s -o %s %s && %s | bat --paging=always"
                          compiler
                          (shell-quote-argument output)
                          (shell-quote-argument file)
                          (shell-quote-argument output))))
    (run-command-in-floating-terminal command)))
#+end_src

***** keybindings for compile functions
[[https://tr.wikibooks.org/wiki/Emacs/Windows_%C4%B0%C3%A7in_Emacs_Dosyas%C4%B1][Emacs/Windows İçin Emacs Dosyası - Vikikitap: Özgür kütüphane]]
# ;; keybindings for all supported languages.  We can put these in
# ;; c-mode-base-map because c-mode-map, c++-mode-map, objc-mode-map,
# ;; java-mode-map, and idl-mode-map inherit from it.

[[https://stackoverflow.com/questions/34067495/binding-a-key-in-c-c-mode-only][emacs - Binding a key in C/C++ mode only? - Stack Overflow]]
# [2022-04-23 Sat 19:08:13]

Using =define-key= inside a hook instead of =setup='s =:bind= because =c-mode= seems
to conflict with it.
#+begin_src emacs-lisp
(with-eval-after-load 'cc-mode
  (define-key c-mode-base-map (kbd "C-c '") #'compile-and-run-current-c-or-cpp-file)
  (define-key c-mode-base-map (kbd "C-c C-c") #'compile-and-run-current-c-or-cpp-file))
#+end_src

*** Rust
#+begin_seealso
- [[https://github.crookster.org/my-emacs-rust-language-config/][My Emacs Rust Language Config | David Crook]]
- [[https://robert.kra.hn/posts/rust-emacs-setup/][Configuring Emacs for Rust development | Robert Krahn]]
#+end_seealso
# [2022-05-03 Tue 17:50:00]

#+begin_src emacs-lisp :tangle no
(use-package rust-mode)
#+end_src
# theres one called rustic

Install Org Babel rust library:

*NOTE*: this requires the program =rust-script= (available in standard Arch repos).
#+begin_src emacs-lisp
(use-package ob-rust
  :after org)
#+end_src

**** Rust Object Notation (ron)
- Used by
  + [[https://github.com/mierak/rmpc][mierak/rmpc]] \\
    /"A configurable, terminal based Media Player Client with album art
    support via various terminal image protocols."/
#+begin_src emacs-lisp
(use-package ron-mode
  :mode "*.ron")
#+end_src


*** Lua
#+begin_src emacs-lisp
(use-package lua-mode
  :defer t)
#+end_src

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-langs)
;;; 11xx-modes-langs.el ends here
#+end_src

** Web
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-web.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** HTML
[[https://docs.emmet.io/cheat-sheet/][Emmet Cheat Sheet]] [2022-04-02 Sat 15:54:53]
**** Emmet
#+begin_src emacs-lisp
(use-package emmet-mode
  :hook (html-mode . emmet-mode))
#+end_src

*** CSS/SCSS
#+begin_src emacs-lisp
(use-package css-mode
  :ensure nil
  :defer t
  :init
  (setq css-indent-offset 2))
#+end_src

*** Web-mode
[[https://timunkert.net/2021/12/emacs-setup.html][Emacs Setup for my Front-End Development Course with Calculus]] [2022-04-20 Wed 01:02:24]
[[https://github.com/glynnforrest/emacs.d/blob/master/site-lisp/setup-web-mode.el][emacs.d/setup-web-mode.el at master · glynnforrest/emacs.d]] [2022-04-20 Wed 01:02:45]


#+begin_src emacs-lisp
(use-package web-mode
  :defer t
  :init
  (setq web-mode-markup-indent-offset 2
        web-mode-css-indent-offset 2
        web-mode-code-indent-offset 2
        web-mode-style-padding 2
        web-mode-script-padding 2
        web-mode-enable-auto-closing t
        web-mode-enable-auto-opening t
        web-mode-enable-auto-pairing t
        web-mode-enable-auto-indentation t))
#+end_src

*** Javascript
Javascript related packages
#+begin_src emacs-lisp
(use-package typescript-mode
  :hook (js-mode . typescript-mode)
  :init
  (setq typescript-indent-level 2))
#+end_src

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-web)
;;; 11xx-modes-web.el ends here
#+end_src

** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes)
;;; 11xx-modes.el ends here
#+end_src


* 11xx-functions.el: Utility functions
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-functions.el
:END:

#+begin_src emacs-lisp
;;; 11xx-functions.el --- Utility functions  -*- lexical-binding: t; -*-
#+end_src

** Electric modes
[[https://www.emacswiki.org/emacs/ElectricPair][EmacsWiki: Electric Pair]]
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/Auto_002dIndentation.html][24.7 Automatic indentation of code]]

Electric pairs are like when a open parenthesis is inserted and the
closing one is inserted automatically.

** Mark whole work
#wizard src [[https://emacs.stackexchange.com/questions/35069/best-way-to-select-a-word/35072#35072][mark - Best way to select a word - Emacs Stack Exchange]]

=mark-whole-word=, to replace the built-in =mark-word= function.
| M-@ | use =mark-whole-word= function |

#+begin_src emacs-lisp
(defun mark-whole-word (&optional arg allow-extend)
  "Like `mark-word', but select whole words and skips over whitespace.
If you use a negative prefix ARG then select words backward.
Otherwise select them forward.

If cursor starts in the middle of word then select that whole word.

If there is whitespace between the initial cursor position and the
first word (in the selection direction), it is skipped (not selected).

If the command is repeated or the mark is active, select the next NUM
words, where NUM is the numeric prefix argument ARG.  (Negative NUM
selects backward.)

If second argument ALLOW-EXTEND is nil don't expand selection across words.
See `mark-word' for more."
  (interactive "P\np")
  (let ((num  (prefix-numeric-value arg)))
    (unless (eq last-command this-command)
      (if (natnump num)
          (skip-syntax-forward "\\s-")
        (skip-syntax-backward "\\s-")))
    (unless (or (eq last-command this-command)
                (if (natnump num)
                    (looking-at "\\b")
                  (looking-back "\\b")))
      (if (natnump num)
          (left-word)
        (right-word)))
    (mark-word arg allow-extend)))
#+end_src

** Use tabs for indentation if needed
See [[https://www.emacswiki.org/emacs/NoTabs#h5o-1][EmacsWiki: No Tabs]]
#+begin_src emacs-lisp
(defun infer-indentation-style ()
  "Compare number of spaces and tabs and define `indent-tabs-mode' to t or nil.

If the current buffer or file has more tabs than spaces,
set `indent-tabs-mode' to t; if it has more spaces than tabs, set it to nil;
and if inconclusive, use current `indent-tabs-mode'."
  (interactive)
  (let ((space-count (how-many "^  " (point-min) (point-max)))
        (tab-count (how-many "^\t" (point-min) (point-max))))
    (setq-local indent-tabs-mode (> tab-count space-count))))
(add-hook 'prog-mode-hook #'infer-indentation-style)
#+end_src

** Kill matching lines
[[https://www.emacswiki.org/emacs/KillMatchingLines][EmacsWiki: Kill Matching Lines]]
# [2022-04-21 Thu 01:08:16]
Delete lines with matching string and send them to killring
#+begin_src emacs-lisp :results code
(defun kill-matching-lines (regexp &optional rstart rend interactive)
  "Kill lines containing matches for REGEXP.

Second and third arg RSTART and REND specify the region to operate on.
When calling this function from Lisp, you can pretend that it was
called interactively by passing a non-nil INTERACTIVE argument.
See `flush-lines' or `keep-lines' for behavior of this command.

If the buffer is read-only, Emacs will beep and refrain from deleting
the line, but put the line in the kill ring anyway.  This means that
you can use this command to copy text from a read-only buffer.
\(If the variable `kill-read-only-ok' is non-nil, then this won't
even beep.)"
  (interactive
   (keep-lines-read-args "Kill lines containing match for regexp"))
  (let ((buffer-file-name nil)) ;; HACK for `clone-buffer'
    (with-current-buffer (clone-buffer nil nil)
      (let ((inhibit-read-only t))
        (keep-lines regexp rstart rend interactive)
        (kill-region (or rstart (line-beginning-position))
                     (or rend (point-max))))
      (kill-buffer)))
  (unless (and buffer-read-only kill-read-only-ok)
    ;; Delete lines or make the "Buffer is read-only" error.
    (flush-lines regexp rstart rend interactive)))
#+end_src

** Check if directory exists and create it if not
#+begin_src emacs-lisp :results code
(defun ensure-directory (dir)
  "Ensure DIR exists."
  (unless (file-directory-p dir)
    (make-directory dir t)))
#+end_src

** Return XDG home directories
- =$XDG_BIN_HOME=
  #+begin_src emacs-lisp
(defun xdg-bin-home ()
  "Return the base directory for user specific executable files."
  (xdg--dir-home "XDG_BIN_HOME" "~/.local/bin"))
  #+end_src

- =$XDG_STATE_HOME=
  #+begin_src emacs-lisp
(defun xdg-state-home ()
  "Return the base directory for user specific log files."
  (xdg--dir-home "XDG_STATE_HOME" "~/.local/state"))
  #+end_src

** Return file contents as string
#+begin_src emacs-lisp
(defun read-file-contents (file-path)
  "Read the contents of the file at FILE-PATH and return it as a string."
  (with-temp-buffer
    (insert-file-contents file-path)
    (buffer-string)))
#+end_src

** Unfill paragraph
[[https://www.emacswiki.org/emacs/UnfillParagraph][EmacsWiki: Unfill Paragraph]]
# [2023-06-23 Fri 13:28:42 -03]
#+begin_src emacs-lisp
    ;;; Stefan Monnier <foo at acm.org>. It is the opposite of fill-paragraph
(defun unfill-paragraph (&optional region)
  "Takes a multi-line paragraph and makes it into a single line of text."
  (interactive (progn (barf-if-buffer-read-only) '(t)))
  (let ((fill-column (point-max))
        ;; This would override `fill-column' if it's an integer.
        (emacs-lisp-docstring-fill-column t))
    (fill-paragraph nil region)))

;; Handy key definition
(define-key global-map "\M-Q" 'unfill-paragraph)
#+end_src

** Filter any matching list item from a list
# ;; from chatgpt: function for filtering items from a list using a list
#+begin_src emacs-lisp
(defun filter-list-any (source-list filter-list)
  "Filter out items from SOURCE-LIST that are found in FILTER-LIST."
  (let ((hash-table (make-hash-table :test 'equal))
        result)
    ;; Populate the hash table with elements from the filter list
    (dolist (item filter-list)
      (puthash item t hash-table))
    ;; Build the result list by filtering out items in the hash table
    (dolist (item source-list)
      (unless (gethash item hash-table)
        (push item result)))
    ;; The result list is built in reverse order, so reverse it
    (nreverse result)))
#+end_src

** Filter list items that match any prefix from a list
#+begin_src emacs-lisp
(defun filter-list-any-string-prefix (source-list filter-list)
  "Filter out items from SOURCE-LIST that match any prefix in FILTER-LIST.

Example:

   (filter-list-any-string-prefix
     '(\"--fruit=banana\" \"orange\" \"cherry\" \"--veggie=potato\")
     '(\"--fruit\" \"--veggie\"))
   => '(\"orange\" \"cherry\")"
  (let (result)
    (dolist (item source-list)
      (unless (seq-some
               (lambda (prefix)
                 (string-prefix-p prefix item))
               filter-list)
        (push item result)))
    (nreverse result)))
#+end_src
# (filter-list-any-prefix '("--fruit=banana" "orange" "cherry" "--veggie=potato") '("--fruit" "--veggie"))

** Platform check
Define macro for checking if =system-type= is =type=, if so, evaluate
body.
- [[https://stackoverflow.com/questions/1817257/how-to-determine-operating-system-in-elisp/26137517#26137517][emacs - How to determine operating system in elisp? - Stack Overflow]].
#+begin_src emacs-lisp
(defmacro with-system (type &rest body)
  "Evaluate BODY if `system-type' equals TYPE."
  (declare (indent defun))
  `(when (eq system-type ',type)
     ,@body))
#+end_src
# around # [2023-12-10  01:20:49 -03] @winr58
Usage
#+begin_example
(with-system gnu/linux
  (message "Free as in Freedom!"))
#+end_example

** Replace alist item
like =add-to-list= but replaces item
#+begin_src emacs-lisp
(cl-defun add-or-replace-to-alist (list-var element &key append prepend)
  "Add or replace ELEMENT or a list of ELEMENTS in the alist stored in LIST-VAR.

LIST-VAR should be a symbol whose value is a proper alist.
ELEMENT may be a single alist entry (a list or cons whose CAR is the lookup key)
or a list of such entries.  If multiple entries are given, each is merged
individually rather than nesting.

By default, new entries are prepended.  Use :append to add at the end,
or :prepend to force prepending (it overrides :append).

Returns the updated alist value (like 'add-to-list').  Also echoes a
message indicating how many entries were added or replaced.

Arguments:
  LIST-VAR   Symbol naming the target alist variable.
  ELEMENT    A single entry (list or cons) or a list of entries.
  ':append'   If non-nil, append new entries.
  `:prepend'  If non-nil, prepend new entries.

Examples:
    ;; Single entry - replaces if key exists, adds if not
    (setq servers '((\"prod\" . \"192.168.1.10\") (\"dev\" . \"192.168.1.20\")))
    (add-or-replace-to-alist 'servers '(\"prod\" . \"10.0.0.100\"))
    ;; => ((\"prod\" . \"10.0.0.100\") (\"dev\" . \"192.168.1.20\"))

    ;; Multiple entries with :append
    (add-or-replace-to-alist
    'auto-mode-alist
    '((\"\\.tsx\\'\" . typescript-mode)
    (\"\\.vue\\'\" . vue-mode))
    :append t)"
  (let ((count 0)
        updated)
    ;; Handle a list of entries recursively
    (cl-labels ((process-entry (entry)
                  (let* ((key   (car entry))
                         (alist (symbol-value list-var))
                         (found (assoc key alist)))
                    ;; remove any old entry
                    (setq alist (cl-remove-if (lambda (old)
                                                (equal (car old) key))
                                              alist))
                    ;; insert
                    (setq alist
                          (cond
                           (prepend  (cons entry alist))
                           (append   (append alist (list entry)))
                           (t        (cons entry alist))))
                    ;; update var, bump counter
                    (set list-var alist)
                    (cl-incf count)
                    alist)))
      (if (and (listp element)
               element
               (cl-every (lambda (e) (and (listp e)
                                          (not (keywordp (car e)))))
                         element))
          (dolist (e element)
            (setq updated (process-entry e)))
        (setq updated (process-entry element))))
    (message "add-or-replace-to-alist: %d entr%s %s"
             count
             (if (> count 1) "ies were" "y was")
             (if append "appended/replaced." "prepended/replaced."))
    updated))
#+end_src

** provide footer
#+begin_src emacs-lisp
(use-package insert-timestamp
  :ensure nil
  :bind
  (("C-c i t t" . current-timestamp-insert-iso-basic)
   ("C-c i t c" . current-timestamp-insert-comment)
   ("C-c i t o" . current-timestamp-insert-org)
   ("C-c i t i" . current-timestamp-insert-iso)))

(provide '11xx-functions)
#+end_src


** insert-timestamp.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/insert-timestamp.el
:END:

#+begin_src emacs-lisp
;;; insert-timestamp.el --- Small timestamp insertion helpers -*- lexical-binding: t; -*-

(defun current-timestamp--hostname-suffix ()
  "Return hostname suffix used by timestamp insertion commands."
  (concat " @" (system-name)))

(defun current-timestamp-org ()
  "Return current timestamp in Org-friendly human-readable format."
  (format-time-string "%Y-%m-%d %a %H:%M:%S %Z"))

(defun current-timestamp-iso-basic ()
  "Return current UTC timestamp in ISO 8601 basic format.

This is compact and alphanumeric-only, for example:

  20260522T183045Z"
  (format-time-string "%Y%m%dT%H%M%SZ" nil t))

(defun current-timestamp-iso ()
  "Return current timestamp in ISO 8601 / RFC 3339-style extended format.

This contains no spaces, for example:

  2026-05-22T15:30:45-03:00"
  (let ((ts (format-time-string "%Y-%m-%dT%H:%M:%S%z")))
    (replace-regexp-in-string
     "\\([+-][0-9][0-9]\\)\\([0-9][0-9]\\)\\'"
     "\\1:\\2"
     ts)))

(defun current-timestamp-comment-format ()
  "Return current timestamp and hostname in comment-marker format.

This is intended for code timestamp marks with readable metadata, for example:

  [2026-05-22 Fri 15:30:45 -03] @hostname"
  (concat "["
          (format-time-string "%Y-%m-%d %a %H:%M:%S %Z")
          "]"
          (current-timestamp--hostname-suffix)))

;; Backward-compatible alias for the old frequently-used name.
(defalias 'current-timestamp-format #'current-timestamp-comment-format)

(defun current-timestamp--insert-as-comment (str)
  "Insert STR and comment it using the current major mode's syntax."
  (let ((start-point (point)))
    (insert str)
    (comment-region start-point (point))))

;;;###autoload
(defun current-timestamp-insert-comment ()
  "Insert the current comment-marker timestamp and hostname as a comment."
  (interactive)
  (current-timestamp--insert-as-comment
   (current-timestamp-comment-format)))

;; Backward-compatible alias for the old frequently-used command.
(defalias 'current-timestamp-insert #'current-timestamp-insert-comment)

;;;###autoload
(defun current-timestamp-insert-org ()
  "Insert current Org-friendly timestamp followed by hostname."
  (interactive)
  (insert (current-timestamp-org)
          (current-timestamp--hostname-suffix)))

;;;###autoload
(defun current-timestamp-insert-iso-basic ()
  "Insert current ISO 8601 basic UTC timestamp followed by hostname.

The timestamp itself is alphanumeric-only."
  (interactive)
  (insert (current-timestamp-iso-basic)
          (current-timestamp--hostname-suffix)))

;;;###autoload
(defun current-timestamp-insert-iso ()
  "Insert current ISO 8601 / RFC 3339-style timestamp followed by hostname.

The timestamp contains no spaces."
  (interactive)
  (insert (current-timestamp-iso)
          (current-timestamp--hostname-suffix)))

(provide 'insert-timestamp)
;;; insert-timestamp.el ends here
#+end_src
# ;; [2026-05-22 Fri 15:23:46 -03] @ak | refactored
# ;; [2024-08-28 Wed 03:14:39 -03] @ak
# ;; # [2023-12-10 Sun 01:33:12 -03:00] @winr58



* 11xx-org.el: Org Mode
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-org.el
:END:

#+begin_src emacs-lisp
<<11xx-org-setup>>

(provide '11xx-org)
#+end_src


** Org setup
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-org-setup :tangle no
:END:

- See:
  + [[https://www.youtube.com/watch?v=VcgjTEa0kU4][Emacs From Scratch #5 - Org Mode Basics]]
  + [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org#auto-show-markup-symbols][Auto-show Markup Symbols]]
  + [[https://stackoverflow.com/questions/10969617/hiding-markup-elements-in-org-mode/10970665#10970665][Hiding markup elements in org-mode]]
  + [[https://emacs.stackexchange.com/questions/50216/org-mode-code-block-parentheses-mismatch/68321#68321][org babel - org-mode code block parentheses mismatch - Emacs Stack Exchange]]
    # [2022-05-14 Sat 20:54:33]

Org loads the link libraries in ~org-modules~ the first time a buffer enters
~org-mode~. The default set pulls in Gnus, BBDB, IRC, MH-E, Rmail, w3m and
EWW support that nothing here uses, and Gnus alone is a noticeable share of
the first Org buffer's load time, with EWW's link support pulling it in through
the MIME helpers, so the list is trimmed to the link types in use.
This module is loaded right after =org.el= and before any buffer enters
~org-mode~, so the value is in place when the modules load.
#+begin_src emacs-lisp
(setq org-modules '(ol-doi ol-bibtex ol-docview ol-info))

(require '11xx-org-functions)

(use-package org-contrib
  :after org
  :config
  (require 'org-eldoc))

(use-package org
  :ensure nil
  :bind (:map org-mode-map
              ("C-c C-;" . org-babel-repeat-previous-src-block)
              ("C-M-p" . org-previous-visible-heading)
              ("C-M-n" . org-next-visible-heading)
              ("C-c o t l" . org-toggle-link-display)
              ("M-F" . org-metaright)
              ("M-B" . org-metaleft)
              ("M-P" . org-metaup)
              ("M-N" . org-metadown)
              ("C-c o p" . org-kill-full-outline-path))
  :init
  (keymap-global-set "C-c o l" #'org-store-link)
  (keymap-global-set "C-c o a" #'org-agenda)
  (keymap-global-set "C-c o c" #'org-capture)
  (setq org-src-content-indentation 0
        org-adapt-indentation nil
        org-ellipsis " ▾"
        org-babel-default-header-args:emacs-lisp '((:lexical . yes))
        org-image-actual-width nil
        org-src-window-setup 'current-window)
  :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((haskell t)
     (shell t)
     (C t)))
  (add-hook 'org-mode-hook
            (lambda ()
              (modify-syntax-entry ?< "." org-mode-syntax-table)
              (modify-syntax-entry ?> "." org-mode-syntax-table)))
  (dolist (begin
           '(;; code
             ("sh" . "src shell")
             ("el" . "src emacs-lisp")
             ("py" . "src python")
             ("js" . "src javascript")
             ("css" . "src css")
             ("cc" . "src conf")
             ("hs" . "src haskell")
             ("sd" . "src systemd")
             ("y" . "src yaml")
             ;; org special
             ("sa" . "seealso")))
    (add-to-list 'org-structure-template-alist begin)))

(use-package org-bulletproof
  :after org
  :hook (org-mode . org-bulletproof-mode))
#+end_src

[[https://github.com/daviwil/emacs-from-scratch/blob/master/Emacs.org#center-org-buffers][Emacs From Scratch/Emacs.org#Center Org Buffers]].
#+begin_src emacs-lisp
(use-package visual-fill-column
  :after org
  :bind (("C-c d c" . visual-fill-column-mode))
  :init
  (setq visual-fill-column-width 130
        visual-fill-column-center-text t))
#+end_src

*** Disable show-trailing-whitespace on Org Export Dispatcher
Hack for customizing the "Org Export Dispatch" buffer, the one triggered
with =C-c C-e=.
- See
  [[https://emacs.stackexchange.com/questions/48490/how-to-change-font-size-only-for-the-buffer-org-export-dispatcher][How to change font size only for the buffer *Org Export Dispatcher*? - Emacs Stack Exchange]]
  # #masterwizard

#+NAME: org-dispatcher-disable-show-whitespace
#+begin_src emacs-lisp
(defun org-export-dispatch-disable-whitespace (&rest args)
  "Disable trailing whitespace in Org Export Dispatch buffer."
  (let ((buf (get-buffer "*Org Export Dispatcher*")))
    (when buf
      (with-current-buffer buf
        (setq-local show-trailing-whitespace nil)))))

(advice-add 'org-export--dispatch-action
            :before #'org-export-dispatch-disable-whitespace)
#+end_src

*** org-appear
Make syntax markers like ~=word=~ or =~word~= be hidden normally and only
appear when hovered.
#+begin_src emacs-lisp
(use-package org-appear
  :disabled
  :after org
  :hook (org-mode . org-appear-mode)
  :init
  (setq org-appear-autolinks 'just-brackets
        org-hide-emphasis-markers t))
#+end_src

*** Prettify Org Mode
#+begin_src emacs-lisp
(use-package org-modern
  :init
  (setopt org-modern-block-fringe nil)
  :config
  (global-org-modern-mode))
#+end_src

*** org-transclusion
aka literate (?hopefully)
- [[https://github.com/nobiot/org-transclusion/][nobiot/org-transclusion: Emacs package to enable transclusion with Org Mode]]
- [[https://www.youtube.com/watch?v=6U9wG-pf-aQ][Assembling Org Mode Files with Transclusion - System Crafters Live! - YouTube]]

#+begin_src emacs-lisp
(use-package org-transclusion
  :bind (:map org-mode-map
              ("C-c o t a" . org-transclusion-add)
              ("C-c o t A" . org-transclusion-add-all)
              ("C-c o t r" . org-transclusion-remove)))
#+end_src

*** Export & Publish

**** Export
- [[https://stackoverflow.com/questions/8395036/make-org-ignore-underscores-when-exporting-to-html][emacs - make Org ignore underscores when exporting to HTML - Stack Overflow]]
#+begin_src emacs-lisp
(setopt org-export-with-sub-superscripts nil ; interpret "_" and "^" for export.
        org-html-html5-fancy t
        org-export-in-background nil ; export async default: Use 'M-x org-export-stack' to display current processes:
        org-html-validation-link "" ; remove validade xml
        )
#+end_src

**** htmlize
- See
  + [[https://github.com/hniksic/emacs-htmlize][GitHub - hniksic/emacs-htmlize: Convert buffer text and decorations to HTML.]]
  + [[https://emacs.stackexchange.com/questions/3374/set-the-background-of-org-exported-code-blocks-according-to-theme/3512#3512][org mode - Set the background of org-exported <code> blocks according to theme - Emacs Stack Exchange]]
  + [[https://melpa.org/#/htmlize][htmlize - MELPA]]
#+begin_src emacs-lisp
(use-package htmlize
  :init
  (setq org-html-head-include-default-style nil
        org-html-htmlize-output-type 'css
        htmlize-html-charset "UTF-8"
        htmlize-face-overrides '(whitespace-missing-newline-at-eof
                                 (:foreground nil :background nil))))
#+end_src
- For supported html charsets see
  + [[https://help.hcltechsw.com/dom_designer/9.0.1/appde11xx--LSAZ_APPENDIX_E_MIME_CHARSET_NAMES.html][MIME Charset Names]]
  + [[https://www.w3schools.com/charsets/][HTML Character Sets]]
  + [[https://en.wikipedia.org/wiki/Character_encodings_in_HTML][Character encodings in HTML - Wikipedia]]
- Notes:
  + The package =htmlize= is also capable of exporting normal buffers as
    HTML, but here it's mostly used for Org Mode exports.
  + Also the face of =whitespace-missing-newline-at-eof= may show up at
    the end of code blocks as a yellow square. To fix it unset the
    face e.g.:
    : (setq htmlize-face-overrides '(whitespace-missing-newline-at-eof (:foreground nil :background nil)))

**** GitHub Markdown
- [[https://codeberg.org/useless-utils/org-stable-ids][useless-utils/org-stable-ids: Human-readable ASCII slug IDs for Org headings and export - Codeberg.org]]
#+begin_src emacs-lisp
(use-package ox-gfm)

(use-package ox-md-title
  :vc (:url "https://github.com/jeffkreeftmeijer/ox-md-title.el")
  :config
  (require 'ox-md-title))

(defun readme-to-markdown (filename &optional confirm-overwrite)
  "Export the current Org buffer to a Markdown file named FILENAME.
Alternative version using display-buffer-overriding-action for cleaner approach."
  (interactive
   (list (read-file-name "Export markdown to file: "
                         nil nil nil
                         (concat (file-name-sans-extension
                                  (or (buffer-file-name)
                                      (buffer-name)))
                                 ".md"))
         current-prefix-arg))

  (unless (derived-mode-p 'org-mode)
    (user-error "This function only works in Org mode buffers"))

  ;; Check for file existence and confirm if requested
  (when (and confirm-overwrite (file-exists-p filename))
    (unless (yes-or-no-p (format "File %s exists. Overwrite? " filename))
      (user-error "Export cancelled")))

  ;; Save current state
  (let ((original-buffer (current-buffer))
        (make-backup-files nil)
        (original-display-action display-buffer-overriding-action)
        export-buffer)

    ;; Temporarily set display-buffer to not show any buffers
    (setq display-buffer-overriding-action
          '((lambda (buffer alist)
              ;; Return the buffer without displaying it
              buffer)
            . nil))

    (unwind-protect
        (save-window-excursion
          ;; Add the markdown title
          (org-md-title-add)

          ;; Export to buffer (silently)
          (let ((org-md-title t))
            (setq export-buffer (org-gfm-export-as-markdown)))

          ;; Write to file
          (with-current-buffer export-buffer
            (write-region (point-min) (point-max) filename nil 'no-message))

          (message "Exported to %s" filename))

      ;; Restore original display action and cleanup
      (setq display-buffer-overriding-action original-display-action)
      (when (and export-buffer (buffer-live-p export-buffer))
        (kill-buffer export-buffer)))))

(defun readme-org-to-readme-md ()
  (interactive)
  (readme-to-markdown "README.md"))


(use-package org-stable-ids
  :vc (:url "https://codeberg.org/useless-utils/org-stable-ids")
  :init
  (keymap-global-set "C-c o i" #'org-stable-ids-get-create)
  :config
  (org-stable-ids-enable))
#+end_src

**** Publishing
#+begin_src emacs-lisp
;; Publish
(let ((dir (expand-file-name "org-timestamps/" no-littering-var-directory)))
  (unless (file-exists-p dir) (make-directory dir t))
  (setopt org-publish-timestamp-directory dir))
#+end_src

*** Org Babel

**** tangle-dir
#+begin_src emacs-lisp
(use-package org-tangle-dir
  :vc (:url "https://codeberg.org/useless-utils/org-tangle-dir")
  :config
  (defun tdir-set-heading-property ()
      "Set :tangle-dir: for the current heading to (tdir-base \"SLUG\").
SLUG is derived from the heading title and confirmed in the minibuffer."
      (interactive)
      (let* ((title (substring-no-properties (org-entry-get nil "ITEM")))
             (slug  (org-stable-ids--slugify title))
             (slug  (read-string "Slug for tdir-base: " slug))
             (value (format "(tdir-base \"%s\")" slug)))
        (org-set-property "tangle-dir" value)
        (message "Set :tangle-dir: %s" value)))

  (with-eval-after-load 'org
    (keymap-set org-mode-map "C-c C-x T" #'tdir-set-heading-property)))
#+end_src


*** Library of Babel
https://orgmode.org/manual/Library-of-Babel.html
#+begin_src emacs-lisp
(use-package ob-lob
  :ensure nil
  :after org
  :config
  (org-babel-lob-ingest (expand-file-name "lob/xdg-vars.org" user-emacs-directory))

  (use-package org-bitwarden
    :vc (:url "https://codeberg.org/useless-utils/org-bitwarden")
    :config
    (require 'org-bitwarden)))
#+end_src

** Troubleshooting

*** I can't find the format file `pdflatex.fmt!'
Install all relevant =texlive-*= packages. On Arch, install the =texlive=
group package.
# [2025-02-11 Tue 17:18:49 -03] @ak

* 11xx-org-functions.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-org-functions.el
:END:
#+begin_src emacs-lisp
<<org-functions>>

(provide '11xx-org-functions)
#+end_src

** Org functions
:PROPERTIES:
:header-args:emacs-lisp: :noweb-ref org-functions
:END:

*** Copy previous source-block with header arguments
- [[https://emacs.stackexchange.com/questions/55890/is-it-possible-to-repeat-the-last-org-mode-source-blocks-headers/55894#55894][yasnippet - Is it possible to repeat the last org-mode source block's headers - Emacs Stack Exchange]]
  # #wizard
- tip: [[https://stackoverflow.com/questions/5500035/set-custom-keybinding-for-specific-emacs-mode/14230685#14230685][How to add keybindig to specific mode]].
#+begin_src emacs-lisp
(defun org-babel-repeat-previous-src-block ()
  "Copy previous src block excluding the content."
  (interactive)
  (let (result)
    (save-excursion
      (org-babel-previous-src-block)
      (let ((element (org-element-at-point)))
        (when (eq (car element) 'src-block)
          (let* ((pl (cadr element))
                 (lang (plist-get pl :language))
                 (switches (plist-get pl :switches))
                 (parms (plist-get pl :parameters)))
            (setq result
                  (format
                   (concat "\n#+begin_src %s\n"
                           "\n"
                           "#+end_src\n")
                   (mapconcat #'identity
                              (delq nil (list lang switches parms))
                              " ")))))))
    (and result (insert result))
    (forward-line -2))
  (recenter-top-bottom))
#+end_src

*** Fix noweb substring syntax highlighting display in code blocks
Use either ~<< ... >>~ (the default) or =«= & =»= (=0000AB= & =0000BB=) overriden here,
when syntax highlighting breaks such as shell code blocks that interpret
=<<nowebname>>= as heredocs.
# The latter preserves syntax highlighting in sh-mode.
- [[https://emacs.stackexchange.com/questions/63643/noweb-references-in-sh-blocks-breaks-the-syntax-highlighting/73720#73720][org mode - Noweb references in sh blocks breaks the syntax highlighting - Emacs Stack Exchange]]
  # #wizard
  + original =org-babel-noweb-wrap= function:
    * [[https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/ob-core.el#n195][ob-core.el\lisp - emacs/org-mode.git - Emacs Org mode]]

# [2023-09-13 Wed 14:18:13 -03]
#+begin_src emacs-lisp
;; override the default
(with-eval-after-load 'org
  (defun org-babel-noweb-wrap (&optional regexp)
    "Return regexp matching a Noweb reference.

Match any reference, or only those matching REGEXP, if non-nil.

When matching, reference is stored in match group 1."
    (rx-to-string
     `(and (or "<<" "«")
           (group
            (not (or " " "\t" "\n"))
            (? (*? any) (not (or " " "\t" "\n"))))
           (or ">>" "»"))))

  (defun org-babel-noweb-wrap-insert-chars ()
    "Insert « and »." 
    (interactive)
    (insert "«»")
    (backward-char)))
#+end_src

*** Get full path of headings
# NVM there's (org-format-outline-path (org-get-outline-path t t) nil nil "/")
#+begin_src emacs-lisp
(defun org-get-full-outline-path ()
  "Retrieve the full heading path of the current heading."
  (interactive)
  (let ((path (org-get-outline-path t t)))
    (if path
        (mapconcat 'identity path "/")
      ;; (message (concat "Killed current Org outline path: " (mapconcat 'identity path "/")))
      (message "Not in an Org mode heading"))))

(defun org-kill-full-outline-path ()
  "Adds the full heading path of the current heading to kill-ring.

Wrapper for `org-get-full-outline-path'."
  (interactive)
  (kill-new (org-get-full-outline-path)))
#+end_src


*** Random characters string
:PROPERTIES:
:CUSTOM_ID: orgid-vuivrg
:END:

- source https://stackoverflow.com/a/60790863
#+begin_src emacs-lisp
(defun random-string-g-to-z (n)
  "Generate N random characters from G to Z.

The reason for using G to Z is to differentiate from MD5/HEX
strings that use A-F and 0-9. Also this is meant for simple
\"ID-fication\" of certain components like creating anchor links.

Inefficient implementation; don't use for large N. Testing showed
a limit of 530, more than that and lisp nesting will overflow."

  (let* ((alpha "ghijklmnopqrstuvwxyz")
         (i (% (abs (random)) (length alpha))))
    (if (= 0 n) ""
      (concat (substring alpha i (1+ i))
              (random-string-g-to-z (1- n))))))
#+end_src

- Number of possibilities
  #+begin_example
  (let ((number-of-characters 21)
        (length-of-string 6))
    (expt number-of-characters length-of-string))
  #+end_example

*** Get list of tangle files that match extension
#+begin_src emacs-lisp
(defun org-babel-get-tangle-files-by-ext (&optional ext)
  "Returns a list of unique filenames to be tangled that end with the specified EXT.

If EXT is not provided, default to \".el\".

This function parses all code blocks in the current Org buffer, identifies
those that contain the `:tangle' header argument (inherited or directly) and
collects the tangle filenames of those that end with the specified EXT.

Note that for this `string-suffix-p' is used to search for an EXT in the
format `.EXT' (with a period) so if a period isn't provided it is added and
if it was it is kept.

Example:

(org-babel-get-tangle-files-by-ext \"el\")"
  (let ((tangle-files '())
        (tangle-files-ext (concat "." (if ext (string-trim-left ext "\\.")
                                        ".el"))))
    (org-element-map (org-element-parse-buffer) 'src-block
      (lambda (src-block)
        (let* ((info (org-babel-get-src-block-info t src-block))
               (header-args (nth 2 info))
               (tangle (cdr (assoc :tangle header-args))))
          (when (and tangle
                     (stringp tangle)
                     (string-suffix-p tangle-files-ext tangle t))
            (push tangle tangle-files)))))
    (delete-dups tangle-files)))
#+end_src

*** Add lexical-binding property to tangle files
The following functions together with
=org-babel-get-tangle-files-by-ext= can be used for adding
=lexical-binding: t= to tangled files automatically without having to
add them as a header in the code blocks. Example usage with local file
variables:

: # eval: (add-hook 'org-babel-tangle-finished-hook #'org-babel-tangle-add-lexical-prop-to-el-tangled-files nil nil)
Note that using ='org-babel-tangle-finished-hook= is important because
=org-babel-get-tangle-files-by-ext=, the function that gets the target
tangle files, needs to read the right buffer/Org document and that
hook is triggered after tangling is finished and Emacs' focus is back
in the source Org buffer so it can get the list.

#+begin_src emacs-lisp
(defun add-lexical-binding-prop (file)
  "Add `lexical-binding: t' prop to FILE without disrupting open buffers."
  (let ((buffer (get-buffer (find-file-noselect file))))
    (with-current-buffer buffer
      (add-file-local-variable-prop-line 'lexical-binding t nil)
      (save-buffer))
    (unless (get-buffer-window buffer 'visible)
      (kill-buffer buffer))))

(defun org-babel-tangle-add-lexical-prop-to-el-tangled-files()
  (dolist (file (let ((source-list (org-babel-get-tangle-files-by-ext "el"))
                      (filter-list '(".dir-locals.el")))
                  (filter-list-any source-list filter-list)))
    (add-lexical-binding-prop file)))
#+end_src

* 11xx-org-functions-tangle-export-helpers.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-org-functions-tangle-export-helpers.el
:END:

#+begin_src emacs-lisp
;;; 11xx-org-functions-tangle-export-helpers.el --- Org babel tangle/export helpers  -*- lexical-binding: t -*-

;;; Code:
;;;###autoload
(defun org-babel-get-src-block-header-arg (header-arg)
  "Get the value of the header argument HEADER-ARG from the provided SRC-BLOCK-INFO.

First argument `org-babel-get-src-block-info' is set to `t'
because it will try to evaluate function in e.g. `:tangle' and if
for some reason that function refers to
`org-babel-get-src-block-info' it infinite loops."
  ;; This could be set as an optional arg? but then what's the point meh haha
  (let* ((src-block-info (org-babel-get-src-block-info t)) ; t for NO-EVAL, otherwise it will infinite loop
         (params (nth 2 src-block-info)))
    (assoc-default header-arg params)))
#+end_src

for [[file:~/.config/darkman/README.org]]
#+begin_src emacs-lisp
;;;###autoload
(defun darkmandir (shfile)
  "Evaluate to a filename in a directory from `XDG_DATA_HOME' that's either `light-mode.d' or `dark-mode.d'.

The string argument SHFILE is the target filename of the darkman script to be tangled.

Usage:
  Either set
  A header-arg \":theme light\" or \":theme dark\";
  A `org-set-property' called 'theme' with value \"dark\" or \"light\".

  Then using the function returns:
  (darkmandir \"script.sh\")
    => \"/home/user/.local/share/light-mode.d/script.sh\"
    or
    => \"/home/user/.local/share/dark-mode.d/script.sh\""
  (let* ((file (if shfile (string-trim shfile "/")))
         (dir-light (expand-file-name "light-mode.d/" (xdg-data-home)))
         (dir-dark (expand-file-name "dark-mode.d/" (xdg-data-home)))
         (out-path-light (expand-file-name file dir-light))
         (out-path-dark (expand-file-name file dir-dark)))
    (cond
     ((or (string= (org-babel-get-src-block-header-arg :theme) "light")
          (string= (org-entry-get nil "theme" t) "light"))
      out-path-light)
     ((or (string= (org-babel-get-src-block-header-arg :theme) "dark")
          (string= (org-entry-get nil "theme" t) "dark"))
      out-path-dark))))
#+end_src

Values that cannot be published, such as a non-default port or a password
manager item id, live one per file under =conf/= in a private vault directory
outside this repository. A block reads them while tangling and tangles the
result only into ignored targets, so neither the value nor its output is ever
tracked. The vault root is =$VAULT_HOME=, or =~/.local/vault= when unset.
#+begin_src emacs-lisp
;;;###autoload
(defun vault-value (name)
  "Return the trimmed contents of the vault value NAME."
  (let ((root (or (getenv "VAULT_HOME") "~/.local/vault")))
    (with-temp-buffer
      (insert-file-contents (expand-file-name (concat "conf/" name) root))
      (string-trim (buffer-string)))))
#+end_src

#+begin_src emacs-lisp
(provide '11xx-org-functions-tangle-export-helpers)
;;; 11xx-org-functions-tangle-export-helpers.el ends here
#+end_src


* 11xx-dired.el
:PROPERTIES:
:CUSTOM_ID: orgid-wlgppl
:header-args:emacs-lisp+: :tangle lisp/11xx-dired.el
:END:

#+begin_src emacs-lisp
<<11xx-dired>>

(provide '11xx-dired)
#+end_src

** Dired
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-dired :tangle no
:END:

*** Dired functions

**** Single buffer dired
[[https://github.com/crocket/dired-single#recommended-keybindings][dired-single#recommended-keybindings]] | [[https://youtu.be/PMWwM8QJAtU?t=2182][Emacs From Scratch #10 - Effortless File Management with Dired@36:22]]

Or the later =(setq dired-kill-when-opening-new-dired-buffer t)= in Emacs 28.1+.

**** Dired up directory without opening new buffer
#+begin_src emacs-lisp
(defun dired-find-alternate-file-up ()
  "Sames as `dired-find-alternate-file' but go up one directory instead."
  (interactive)
  (find-alternate-file ".."))
#+end_src


**** dired open with external app
[[https://emacs.stackexchange.com/questions/21796/dired-alternative-to-openwith-how-to-open-file-per-extension/21808#21808][wizard]]
~launch~ is a script xdg alternative located in ~~.local/bin~.
#+begin_src emacs-lisp
(defun mu-open-in-external-app ()
  "Open the file where point is or the marked files in Dired in external app.

The app is chosen from your OS's preference."
  (interactive)
  (let* ((file-list
          (dired-get-marked-files)))
    (mapc
     (lambda (file-path)
       (let ((process-connection-type nil))
         (start-process "" nil "launch" file-path)))
     file-list)))
#+end_src

**** Open Terminal here
[[https://truongtx.me/2013/09/13/emacs-dired-new-terminal-window-at-current-directory-on-macos][wizard src]]
this gets the terminal name from the environment variable ~$TERMINAL~,
if not set edit the code accordinly. Don't forget to edit the call flags!
#+begin_src emacs-lisp
;; default terminal application path
(defvar 11xx--terminal (getenv "TERMINAL")
  "The default terminal as in the TERMINAL environment variable.")
;;; function to open new terminal window at current directory
(defun tmtxt/open-current-dir-in-terminal ()
  "Open current directory in 'dired-mode' in terminal application."
  (interactive)
  (shell-command (concat
                  (shell-quote-argument 11xx--terminal)
                  " "
                  "--working-directory"
                  " "
                  (shell-quote-argument (file-truename default-directory)))))

;; (define-key dired-mode-map (kbd "<f4>") 'tmtxt/open-current-dir-in-terminal) ;; was kmacro-end-or-call-macro
#+end_src

*** Dired setup

- [[https://writequit.org/denver-emacs/presentations/2016-05-24-elpy-and-dired.html][Using Dired as a file manager]]
- [[https://www.youtube.com/watch?v=PMWwM8QJAtU][Emacs From Scratch #10 - Effortless File Management with Dired]]
- [[https://github.com/Fuco1/dired-hacks#dired-rainbow][Dired-Rainbow]]
- [[help:dired-compress-files-alist][Add compression]]

NOTE: =dired-async= is provided by the =async= package.
#+begin_src emacs-lisp
(use-package ls-lisp
  :ensure nil
  :init
  (setq dired-hacks-datetime-regexp "[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\} [0-9]\\{2\\}:[0-9]\\{2\\}")
  (setq ls-lisp-use-insert-directory-program nil
        ls-lisp-dirs-first t
        ls-lisp-ignore-case t
        ls-lisp-use-string-collate nil
        dired-use-ls-dired nil
        dired-listing-switches "-lA"
        ls-lisp-format-time-list '("%Y-%m-%d %H:%M" "%Y-%m-%d %H:%M")
        ls-lisp-use-localized-time-format t))

(use-package dired
  :ensure nil
  :hook (dired-mode . auto-revert-mode)
  :init
  (put 'dired-find-alternate-file 'disabled nil)
  (setq dired-recursive-copies #'always
        dired-recursive-deletes #'always
        dired-compress-directory-default-suffix ".tar.zst"
        dired-compress-file-alist '(("\\.zst\\'" . "zstd -qf -11 --rm -o %o %i"))
        dired-compress-files-alist '(("\\.tar\\.zst\\'" . "tar -cf - %i | zstd -11 -o %o"))
        dired-deletion-confirmer #'y-or-n-p
        dired-kill-when-opening-new-dired-buffer t
        dired-dwim-target t
        dired-hide-details-hide-symlink-targets nil)
  :bind (:map dired-mode-map
              ("RET" . mu-open-in-external-app)
              ("/" . dired-narrow-fuzzy)
              ("<tab>" . dired-subtree-toggle)
              ("<remap> <dired-maybe-insert-subdir>" . dired-subtree-toggle)
              ("<backtab>" . dired-subtree-cycle)
              ("t" . tmtxt/open-current-dir-in-terminal)
              ("f" . dired-find-file)
              ("b" . dired-up-directory)
              ("h" . dired-up-directory)
              ("j" . dired-next-line)
              ("k" . dired-previous-line)
              ("l" . dired-find-file)
              ("SPC" . dired-mark)
              ("~" . dired-open-home-directory)))
#+end_src

#+begin_src emacs-lisp
(use-package dired-rainbow
  :after dired
  :config
  (dired-rainbow-define-chmod directory nil "d.*")
  (dired-rainbow-define-chmod executable-unix nil "-.*x.*")
  (dired-rainbow-define html nil ("css" "less" "sass" "scss" "htm" "html" "jhtm" "mht" "eml" "mustache" "xhtml"))
  (dired-rainbow-define xml nil ("xml" "xsd" "xsl" "xslt" "wsdl" "bib" "json" "msg" "pgn" "rss" "yaml" "yml" "rdata"))
  (dired-rainbow-define document nil ("docm" "doc" "docx" "odb" "odt" "pdb" "pdf" "ps" "rtf" "djvu" "epub" "odp" "ppt" "pptx"))
  (dired-rainbow-define markdown nil ("org" "etx" "info" "markdown" "md" "mkd" "nfo" "pod" "rst" "tex" "textfile" "txt"))
  (dired-rainbow-define database nil ("xlsx" "xls" "csv" "accdb" "db" "mdb" "sqlite" "nc"))
  (dired-rainbow-define media nil ("mp3" "mp4" "MP3" "MP4" "avi" "mpeg" "mpg" "flv" "ogg" "mov" "mid" "midi" "wav" "aiff" "flac"))
  (dired-rainbow-define image nil ("tiff" "tif" "cdr" "gif" "ico" "jpeg" "jpg" "png" "psd" "eps" "svg" "webp"))
  (dired-rainbow-define log nil ("log"))
  (dired-rainbow-define shell nil ("awk" "bash" "bat" "sed" "sh" "zsh" "vim"))
  (dired-rainbow-define interpreted nil ("py" "ipynb" "rb" "pl" "t" "msql" "mysql" "pgsql" "sql" "r" "clj" "cljs" "scala" "js"))
  (dired-rainbow-define compiled nil ("asm" "cl" "lisp" "el" "elc" "eln" "c" "h" "c++" "h++" "hpp" "hxx" "m" "cc" "cs" "cp" "cpp" "go" "f" "for" "ftn" "f90" "f95" "f03" "f08" "s" "rs" "hi" "hs" "pyc" ".java"))
  (dired-rainbow-define executable nil ("exe" "msi"))
  (dired-rainbow-define compressed nil ("7z" "zip" "bz2" "tgz" "txz" "gz" "xz" "z" "Z" "jar" "war" "ear" "rar" "sar" "xpi" "apk" "xz" "tar" "rsn" "vsix"))
  (dired-rainbow-define packaged nil ("deb" "rpm" "apk" "jad" "jar" "cab" "pak" "pk3" "vdf" "vpk" "bsp"))
  (dired-rainbow-define encrypted nil ("gpg" "pgp" "asc" "bfe" "enc" "signature" "sig" "p12" "pem"))
  (dired-rainbow-define fonts nil ("afm" "fon" "fnt" "pfb" "pfm" "ttf" "otf"))
  (dired-rainbow-define partition nil ("dmg" "iso" "bin" "nrg" "qcow" "toast" "vcd" "vmdk" "bak"))
  (dired-rainbow-define vc nil ("git" "gitignore" "gitattributes" "gitmodules")))

(defun dired-open-home-directory ()
  (interactive)
  (dired (getenv "HOME")))

(use-package dired-hide-dotfiles
  :after dired
  :config
  (keymap-set dired-mode-map "." #'dired-hide-dotfiles-mode)
  (setq dired-hide-dotfiles-verbose nil))

(use-package dired-narrow)
(use-package dired-subtree)

(use-package dired-efap
  :after dired
  :bind (:map dired-mode-map ("r" . dired-efap))
  :config
  (setq dired-efap-initial-filename-selection nil))

(use-package all-the-icons-dired
  :after dired
  :hook (dired-mode . all-the-icons-dired-mode))

(use-package diredfl
  :after dired
  :config
  (diredfl-global-mode))

(use-package dired-hl-line-mode
  :ensure nil
  :hook (dired-mode . dired-hl-line-mode))
#+end_src

**** TODO dirvish
#+begin_src emacs-lisp :tangle no :noweb-ref dummy
(use-package dirvish
  :config
  (dirvish-override-dired-mode)

  ;; Fixes for dired-efap and wdired
  (defun dirvish-hide-cursor--on ()
    "Browsing state: Enable buffer-local `dirvish-hide-cursor'."
    (setq-local dirvish-hide-cursor t
                cursor-type nil))
  (defun dirvish-hide-cursor--off ()
    "Editing state: show cursor, disable buffer-local `dirvish-hide-cursor'."
    (setq-local dirvish-hide-cursor nil
                cursor-type t))
  (add-hook   'dired-mode-hook                         #'dirvish-hide-cursor--on)
  (add-hook   'wdired-mode-hook                        #'dirvish-hide-cursor--off)
  (advice-add 'wdired-change-to-dired-mode      :after #'dirvish-hide-cursor--on)
  (advice-add 'dired-efap                       :after #'dirvish-hide-cursor--off)
  (advice-add 'dired-efap--change-to-dired-mode :after #'dirvish-hide-cursor--on)
  )
;; (setopt dirvish-attributes '(nerd-icons file-time file-size collapse subtree-state vc-state git-msg))
#+end_src

**** DONE Show current directory in Dired header line
#+begin_src emacs-lisp :tangle no :noweb-ref dummy
(defun dired-directory-header-line ()
  "Uses `header-line-format' to display the current directory."
  (interactive)
  (setq-local header-line-format
              '((:eval (abbreviate-file-name default-directory)))))
(add-hook 'dired-mode-hook 'dired-directory-header-line)
#+end_src

* Magit

** 11xx-magit.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-magit.el
:END:

- See
  + [[https://emacs.stackexchange.com/questions/15270/whats-the-magit-equivalent-of-git-add/15272#15272][What's the Magit equivalent of 'git add'? - Emacs Stack Exchange]]
  + [[https://emacs.stackexchange.com/questions/30602/use-nonstandard-git-directory-with-magit][use nonstandard `.git` directory with magit - Emacs Stack Exchange]]
  + [[https://gitlab.com/dwt1/dotfiles/-/blob/master/.emacs.d.gnu/config.org#magit][.emacs.d.gnu/config.org · master · Derek Taylor / Dotfiles · GitLab]]
  + [[https://gitlab.com/dwt1/dotfiles/-/commit/125f9d2630994911ad15425ff1cad69474bead7e][Merge branch 'emacs' into 'master' (125f9d26) · Commits · Derek Taylor / Dotfiles · GitLab]]
    # #wizard

Magit itself loads on first use. The bindings, the bare-repository helpers and
the Dired staging command do not need it, so they are installed up front.
#+begin_src emacs-lisp
(require 'magit-status-bare)

(use-package magit
  :defer t
  :init
  (keymap-global-unset "C-x g")
  (keymap-global-set "C-x g g" #'magit-status-default)
  (magit-status-bare :git-dir "~/.local/dotfiles.git/"
                     :work-tree (getenv "HOME")
                     :key-bind "C-x g d")
  (dired-git-add-bare :git-dir "~/.local/dotfiles.git/"
                      :work-tree (getenv "HOME")
                      :key-bind "C-c g d a"))

(with-eval-after-load 'dired
  (defun dired-git-add (&optional arg)
    "Execute 'git add' command for current or marked files in Dired mode.
With prefix ARG, prompt for additional arguments to pass to the command."
    (interactive "P")
    (let* ((files (dired-get-marked-files nil arg))
           (git-cmd "git")
           (output (mapconcat (lambda (file)
                                (shell-command-to-string
                                 (concat git-cmd " add --verbose " (shell-quote-argument file))))
                              files
                              "\n")))
      (message "Git add command completed:\n%s" output)))
  (keymap-set dired-mode-map "C-c g g a" #'dired-git-add))

(require '11xx-vot nil t)

(provide '11xx-magit)
#+end_src

** magit-status-bare.el
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/magit-status-bare.el
:END:

#+begin_src emacs-lisp
;; NOTE: This requires lexical-binding = t
(require 'dired)
(require '11xx-functions) ; filter-list-any-string-prefix
(declare-function magit-status "magit")
(defvar magit-git-global-arguments)

;;;###autoload
(defun magit-status-default ()
  "Wrapper for `magit-status' without \"--git-dir\" or \"--work-tree\" CLI args.

Magit relies on `magit-git-global-arguments' for passing to git
command-line arguments, normally it's not necessary to customize
it but when invoking `magit-status' for a bare git repository is
desired `magit-git-global-arguments' needs to include the
`--git-dir=<dir>' and `--work-tree=<dir>' options. Though there's
a problem with this approach: Customizing
`magit-git-global-arguments' needs to change it globally because
even though `magit-status' may work when called inside a `let',
other commands inside the magit buffer will also read from the
same variable, but if the new values have not been set globally
commands like `magit-stage' will not work because they will be
missing `--git-dir' and `--work-tree'. A hacky way of doing it is
having a version for the bare git function calls that include the
custom flags, and this version that removes the custom
flags. Then replace the keybind for `magit-status'."
  (interactive)
  (setq magit-git-global-arguments (filter-list-any-string-prefix
                                    magit-git-global-arguments
                                    '("--git-dir" "--work-tree")))
  (call-interactively #'magit-status))

;;;###autoload
(defun magit-status-bare (&rest args)
  "Configure Magit to operate on a bare repository using ARGS.

ARGS is a property list that supports the following keys:
- `:git-dir'     (required) Path to a bare Git directory.
- `:work-tree'   (required) Path to the repository's worktree.
- `:key-bind'    (optional) Set a global key binding. If
  provided, the key binding is set, but the function is not
  executed."
  (interactive)
  (let* ((git-dir (plist-get args :git-dir))
         (work-tree (plist-get args :work-tree))
         (key-binding (plist-get args :key-bind))
         (git-dir-arg (concat "--git-dir=" (expand-file-name git-dir)))
         (work-tree-arg (concat "--work-tree=" (expand-file-name work-tree)))
         )
    (setq magit-git-global-arguments (append (eval (car (get 'magit-git-global-arguments 'standard-value)))
                                             (list git-dir-arg work-tree-arg)))

    (if (key-valid-p key-binding)
        (keymap-global-set key-binding
                           (let ((expanded-git-dir git-dir)
                                 (expanded-work-tree work-tree))
                             (lambda ()
                               (interactive)
                               (magit-status-bare :git-dir expanded-git-dir :work-tree expanded-work-tree))))
      (call-interactively 'magit-status))))

;;;###autoload
(defun dired-git-add-bare (&rest args)
  "Add files to a bare repository from Dired using ARGS.

ARGS is a property list that supports the following keys:
- `:git-dir'       (required) The absolute path to the bare Git directory.
- `:work-tree'     (required) The absolute path to the repository's worktree.
- `:key-bind'      (optional) Set a key binding to invoke this
  function in `dired-mode-map'. If provided, the key binding is
  set, but the function is not executed."
  (interactive)
  (let* ((git-dir (plist-get args :git-dir))
         (work-tree (plist-get args :work-tree))
         (key-binding (plist-get args :key-bind))
         (git-dir-arg (concat "--git-dir=" (expand-file-name git-dir)))
         (work-tree-arg (concat "--work-tree=" (expand-file-name work-tree))))

    (if (key-valid-p key-binding)
        ;; Set the key binding without executing the function
        (keymap-set dired-mode-map key-binding
                    (lambda (&optional arg)
                      (interactive "P")
                      (dired-git-add-bare :git-dir git-dir :work-tree work-tree)))
      ;; Execute the function
      (let* ((files (dired-get-marked-files nil nil))
             (git-cmd (mapconcat 'identity (list "git" git-dir-arg work-tree-arg) " "))
             (output (mapconcat (lambda (file)
                                  (shell-command-to-string
                                   (concat git-cmd " add --verbose " (shell-quote-argument file))))
                                files "\n")))
        (message "Git add command completed:\n%s" output)))))


(provide 'magit-status-bare)
#+end_src

* 11xx-completion.el: Completion frakework, Minibuffer
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-completion.el
:END:

#+begin_src emacs-lisp
<<11xx-completion>>

(provide '11xx-completion)
#+end_src


** def
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-completion :tangle no
:END:

- [[https://www.reddit.com/r/emacs/comments/qfrxgb/comment/hi6mfh7/?utm_source=share&utm_medium=web2x&context=3][what are Vertico, Consult, Marginalia, Embark]]

*** VERTico

- See
  + [[https://github.com/minad/vertico][VERTical Interactive COmpletion - GitHub]]
  + [[https://github.com/axelf4/hotfuzz][hotfuzz]]
  + [[https://www.youtube.com/watch?v=J0OaRy85MOo][Streamline Your Emacs Completions with Vertico]]
  + [[https://www.reddit.com/r/emacs/comments/qfrxgb/comment/hi6nxs11xx--?context=3][What these packages do migrating from ivy]]
  + [[https://stackoverflow.com/questions/6133799/delete-a-word-without-adding-it-to-the-kill-ring-in-emacs/6133921#6133921][Delete a word without adding it to the kill-ring in Emacs - Stack Overflow]]
  + https://systemcrafters.cc/live-streams/may-21-2021/
  # [2022-02-24 Thu 00:01:03]

#+begin_src emacs-lisp
(use-package vertico
  :bind (:map vertico-map
              ("?" . minibuffer-completion-help)
              ("M-RET" . minibuffer-force-complete-and-exit)
              ("M-TAB" . minibuffer-complete)
              ("M-<backspace>" . minibuffer-backward-delete-word)
              ("M-D" . minibuffer-backward-delete-word)
              ("C-M-d" . backward-delete-char)
              ("M-d" . minibuffer-delete-word)
              ("C-k" . minibuffer-delete-line)
              ("C-M-k" . kill-line))
  :init
  (defun minibuffer-backward-delete-word (arg)
    "Delete characters backward until encountering the beginning of a word.
With argument ARG, do this that many times."
    (interactive "p")
    (delete-region (point) (progn (backward-word arg) (point))))

  (defun minibuffer-delete-word (arg)
    "Delete characters forward until the end of a word.
Like `kill-word' but doesn't add deleted words to kill ring."
    (interactive "p")
    (delete-region (point) (progn (forward-word arg) (point))))

  (defun minibuffer-delete-line (arg)
    "Delete characters forward until the end of the line.
Like `kill-line' but doesn't add deleted characters to kill ring."
    (interactive "p")
    (delete-region (point) (progn (end-of-line arg) (point))))

  (setq vertico-scroll-margin 4
        vertico-cycle t
        read-extended-command-predicate #'command-completion-default-include-p
        enable-recursive-minibuffers t
        completion-cycle-threshold 3
        minibuffer-prompt-properties '(read-only t cursor-intangible t face minibuffer-prompt))
  :hook ((minibuffer-setup . cursor-intangible-mode)
         (after-init . vertico-mode)))
#+end_src

*** Savehist
See https://www.reddit.com/r/emacs/comments/ie7g17/emacs_clipboard_between_sessions/
[[https://help-gnu-emacs.gnu.narkive.com/LOddwNvQ/don-t-clear-kill-ring-when-restart-emacs][Don't clear kill-ring when restart emacs]]
# [2022-11-09 Wed 17:02:36 -03]

Have =M-x= commands history across sessions

#+begin_src emacs-lisp
;; Persist history over Emacs restarts. Vertico sorts by history position.
(use-package savehist
  :ensure nil
  :init
  (setq savehist-additional-variables '(kill-ring compile-command search-ring regexp-search-ring)
        history-length 1000
        history-delete-duplicates t)
  :config
  (put 'savehist-minibuffer-history-variables 'history-length 1000)
  (put 'org-read-date-history 'history-length 1000)
  (put 'read-expression-history 'history-length 1000)
  (put 'org-table-formula-history 'history-length 1000)
  (put 'extended-command-history 'history-length 1000)
  (put 'ido-file-history 'history-length 1000)
  (put 'helm-M-x-input-history 'history-length 1000)
  (put 'minibuffer-history 'history-length 1000)
  (put 'ido-buffer-history 'history-length 1000)
  (put 'buffer-name-history 'history-length 1000)
  (put 'file-name-history 'history-length 1000)
  :hook (after-init . savehist-mode))
#+end_src

*** Orderless
[[https://github.com/oantolin/orderless#style-dispatchers][Style dispatchers]]
#+begin_src emacs-lisp
(use-package orderless
  :init
  (setq completion-category-defaults nil
        completion-styles '(orderless initials substring basic)
        completion-category-overrides '((file (styles basic partial-completion)))
        orderless-component-separator "[ &]"
        orderless-smart-case t)
  :config
  (defun just-one-face (fn &rest args)
    (let ((orderless-match-faces [completions-common-part]))
      (apply fn args)))
  (advice-add 'company-capf--candidates :around #'just-one-face))
#+end_src

*** Marginalia
- [[https://github.com/minad/marginalia/][marginalia github]]
#+begin_src emacs-lisp
;; Enable richer annotations using the Marginalia package
(use-package marginalia
  :hook (after-init . marginalia-mode)
  :bind (:map minibuffer-local-map ("M-A" . marginalia-cycle))
  :init
  (setq marginalia-align 'left
        marginalia-field-width 120))
#+end_src

*** Consult
[[https://github.com/minad/consult#use-package-example][Example configuration for Consult]]
#+begin_src emacs-lisp
(use-package consult
  :bind (("C-s" . consult-line)
         ("C-x b" . consult-buffer)
         ("C-r" . consult-history)
         ("C-c o s" . consult-org-heading)))
;; note: consult-outline & consult-org-heading
#+end_src

https://github.com/minad/consult/issues/563#issuecomment-1186612641
#+begin_example emacs-lisp
(defun org-show-entry-consult-a (fn &rest args)
  (when-let ((pos (apply fn args)))
    (org-fold-show-entry)))

(advice-add 'consult-line :around #'org-show-entry-consult-a)
(advice-add 'consult-org-heading :around #'org-show-entry-consult-a)
(advice-add 'consult-org-heading :around #'consult--grep)
#+end_example

*** Embark
[[https://github.com/oantolin/embark#quick-start][Embark#Quick start]]
#+begin_src emacs-lisp
(use-package embark
  :after consult
  :bind (("C-." . embark-act)
         ("C-h B" . embark-bindings))
  :init
  (setq prefix-help-command #'embark-prefix-help-command)
  :config
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))

(use-package embark-consult
  :after embark)
#+end_src

*** Corfu
yoinked [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org#completions-in-regions-with-corfu][daviwil/dotfiles/Emacs.org#completions-in-regions-with-corfu]]
#+begin_src emacs-lisp
(use-package corfu
  :bind (("<tab>" . completion-at-point))
  :bind (:map corfu-map
              ("M-SPC" . corfu-insert-separator)
              ([remap next-line] . nil)
              ([remap previous-line] . nil))
  :init
  (setq corfu-cycle t
        corfu-auto-delay 0.1
        corfu-auto-prefix 4
        corfu-preview-current nil)
  :hook (after-init . global-corfu-mode)
  :config
  (global-corfu-mode 1)
  (defun corfu-enable-in-minibuffer ()
    "Enable Corfu in the minibuffer if `completion-at-point' is bound."
    (when (where-is-internal #'completion-at-point (list (current-local-map)))
      (setq-local corfu-echo-delay nil
                  corfu-popupinfo-delay nil)
      (corfu-mode 1)))
  (add-hook 'minibuffer-setup-hook #'corfu-enable-in-minibuffer))
#+end_src

Corfu draws its popup with child frames, which work on TTY frames as well as
graphical ones, so the same configuration covers both.

#+begin_src emacs-lisp
(use-package prescient
  :after corfu
  :config
  (prescient-persist-mode 1))

(use-package corfu-prescient
  :after corfu
  :hook (corfu-mode . corfu-prescient-mode))
#+end_src

*** Cape: Completion extensions!
- [[https://github.com/minad/cape][minad/cape: 🦸cape.el - Completion At Point Extensions]]
- [[https://kisaragi-hiu.com/switching-to-corfu.html][Switching to Corfu - Kisaragi Hiu]].
# [2022-12-01 Thu 01:46:10 -03]
#+begin_src emacs-lisp
;; Add extensions
(use-package cape
  :bind ("M-<tab>" . cape-prefix-map)
  :config
  ;; Bind dedicated completion commands
  ;; Alternative prefix keys: C-c p, M-p, M-+, ...
  ;; (:global-set
  ;;  "C-c p p" completion-at-point ;; capf
  ;;  "C-c p t" complete-tag        ;; etags
  ;;  "C-c p d" cape-dabbrev        ;; or dabbrev-completion
  ;;  "C-c p h" cape-history
  ;;  "C-c p f" cape-file
  ;;  "C-c p k" cape-keyword
  ;;  "C-c p s" cape-elisp-symbol
  ;;  "C-c p e" cape-elisp-block
  ;;  "C-c p a" cape-abbrev
  ;;  "C-c p l" cape-line
  ;;  "C-c p w" cape-dict
  ;;  "C-c p :" cape-emoji
  ;;  "C-c p \\" cape-tex
  ;;  "C-c p _" cape-tex
  ;;  "C-c p ^" cape-tex
  ;;  "C-c p &" cape-sgml
  ;;  "C-c p r" cape-rfc1345)
  ;; Add to the global default value of `completion-at-point-functions' which is
  ;; used by `completion-at-point'.  The order of the functions matters, the
  ;; first function returning a result wins.  Note that the list of buffer-local
  ;; completion functions takes precedence over the global list.
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-file)
  (add-to-list 'completion-at-point-functions #'cape-elisp-block)
  ;;(add-to-list 'completion-at-point-functions #'cape-history)
  ;;(add-to-list 'completion-at-point-functions #'cape-keyword)
  ;;(add-to-list 'completion-at-point-functions #'cape-tex)
  ;;(add-to-list 'completion-at-point-functions #'cape-sgml)
  ;;(add-to-list 'completion-at-point-functions #'cape-rfc1345)
  ;;(add-to-list 'completion-at-point-functions #'cape-abbrev)
  ;;(add-to-list 'completion-at-point-functions #'cape-dict)
  ;;(add-to-list 'completion-at-point-functions #'cape-elisp-symbol)
  ;;(add-to-list 'completion-at-point-functions #'cape-line)
  )
#+end_src

*** TempEl
[[https://github.com/minad/tempel][minad/tempel: TempEl - Simple templates for Emacs]].
See the example template file: [[https://github.com/minad/tempel#template-file-format][minad/tempel: TempEl - Simple templates for Emacs]].
#+begin_src emacs-lisp
(use-package tempel
  :bind (("M-+" . tempel-complete)
         ("M-*" . tempel-insert))
  :init
  ;; Setup completion at point
  (defun tempel-setup-capf ()
    ;; Add the Tempel Capf to `completion-at-point-functions'.
    ;; `tempel-expand' only triggers on exact matches. Alternatively use
    ;; `tempel-complete' if you want to see all matches, but then you
    ;; should also configure `tempel-trigger-prefix', such that Tempel
    ;; does not trigger too often when you don't expect it. NOTE: We add
    ;; `tempel-expand' *before* the main programming mode Capf, such
    ;; that it will be tried first.
    (setq-local completion-at-point-functions
                (cons #'tempel-expand
                      completion-at-point-functions)))


  ;; Optionally make the Tempel templates available to Abbrev,
  ;; either locally or globally. `expand-abbrev' is bound to C-x '.
  ;; (add-hook 'prog-mode-hook #'tempel-abbrev-mode)
  ;; (global-tempel-abbrev-mode)
  :hook ((prog-mode . tempel-setup-capf)
         (text-mode . tempel-setup-capf)))
#+end_src

*** Language Server Protocols (LSP)
*Arch packages:*
- [[https://github.com/bash-lsp/bash-language-server][bash-language-server]]
- [[https://github.com/typescript-language-server/typescript-language-server][typescript-language-server]]
- [[https://github.com/haskell/haskell-language-server#readme][haskell-language-server]]

**** lsp-mode
# :PROPERTIES:
# :header-args:emacs-lisp: :noweb-ref dummy :tangle no
# :END:

- [[https://emacs-lsp.github.io/lsp-mode/page/performance/#use-plists-for-deserialization][Performance - LSP Mode - LSP support for Emacs#Use =plists= for deserialization]]
  + Set environment variable
    : export LSP_USE_PLISTS=true
    or call Emacs as =LSP_USE_PLISTS=true emacs=.
  + In the case of using =straight.el= delete all cloned files:
    : cd "${XDG_CONFIG_HOME}"/emacs && fd -td lsp -x echo rm -rf
    /(remove echo to make real changes)/
  + Set =(setq lsp-use-plists t)= /before/ installing =lsp-mode= packages
  + [[https://github.com/emacs-lsp/lsp-mode/issues/837][Moving cursor is very slow · Issue #837 · emacs-lsp/lsp-mode]]

Both clients load on demand: ~lsp~ is the entry point, and ~lsp-mode~ turns on
~lsp-ui-mode~ itself whenever ~lsp-ui~ is installed, so ~lsp-ui~ only has to
follow it. Flycheck loads when a mode asks for it.
#+begin_src emacs-lisp
(setq lsp-use-plists t)

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :init
  (setq lsp-idle-delay 0.1
        lsp-keymap-prefix "C-c l"
        lsp-log-io nil))
(use-package lsp-ui
  :after lsp-mode)
(use-package flycheck
  :defer t)
#+end_src

**** Eglot
[[https://github.com/joaotavora/eglot][joaotavora/eglot: A client for Language Server Protocol servers]].
#+begin_src emacs-lisp
(use-package eldoc-box
  :init
  (setq eldoc-box-doc-separator (concat "\n\n" (make-string 3 ?-) "\n\n")
        eldoc-box-clear-with-C-g t
        eldoc-box-max-pixel-height 1400)
  :config
  (add-hook 'eldoc-box-buffer-hook
            (lambda () (setq-local show-trailing-whitespace nil))))

(use-package eglot
  :ensure nil
  :init
  (setq eglot-send-changes-idle-time 0.01
        eldoc-idle-delay 0.01
        eldoc-echo-area-prefer-doc-buffer t))
#+end_src

***** Performance
See [[https://emacs-lsp.github.io/lsp-mode/page/performance/][Performance - LSP Mode - LSP support for Emacs]]
# [2022-05-27 Fri 11:00:30 -03]

**** TODO lsp-bridge
- To sandbox the pip dependencies do:
  + On Linux
    : ❯ python -m venv ./.python-venv
    : ❯ ./.python-venv/bin/pip install epc orjson sexpdata six setuptools paramiko rapidfuzz
    then source the venv before launching Emacs:
    : ❯ source ./.python-venv/bin/activate
    : ❯ emacs
  # + On Windows (#TODO does it work on windows-nt?)
  #   : python -m venv .\.python-venv
  #   : .\.python-venv\Scripts\pip.exe install epc orjson sexpdata six setuptools paramiko rapidfuzz
  # + Install Now set the python venv root inside Emacs:
- Or on Arch Linux install:
  : pacman -S python-orjson python-six python-setuptools python-paramiko python-rapidfuzz --needed
  : paru -S python-epc python-sexpdata --needed

#+begin_src emacs-lisp :noweb-ref dummy :tangle no
(use-package yasnippet)
(use-package lsp-bridge
  :vc (:url "https://github.com/manateelazycat/lsp-bridge")
  :config
  (global-lsp-bridge-mode))
#+end_src

[[https://github.com/manateelazycat/lsp-bridge#installation][manateelazycat/lsp-bridge: A blazingly fast LSP client for Emacs]]

Before testing disable Corfu or any other completion.
Run with =lsp-bridge-mode=.

*** Prescient
[[https://github.com/raxod502/prescient.el][raxod502/prescient.el: ☄️ Simple but effective sorting and filtering for Emacs.]]
# [2022-04-27 Wed 22:45:04]
Remembers used completion items and put them up.

**** Prescient with Corfu
See [[*Corfu][Corfu]].

* 11xx-ui.el: User Interface settings
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-ui.el
:END:

#+begin_src emacs-lisp
<<11xx-ui>>

(provide '11xx-ui)
#+end_src


** User Interface
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-ui :tangle no
:END:

*** Change UI modes
#+begin_src emacs-lisp
;;; UI
(menu-bar-mode -1)    ; Disable menu bar
(tool-bar-mode -1)    ; Disable toolbar
;; scroll-bar-mode is void on emacs-nox
(scroll-bar-mode -1)  ; Disable scrolllbar

(blink-cursor-mode 1)
(setopt blink-cursor-blinks 1)

(column-number-mode 1) ; column number in mode-line
(line-number-mode 1) ; line number in mode-line
;; (global-hl-line-mode 1) ;; highlight current line
;; (visual-line-mode 1)
;; (toggle-truncate-lines -1)
#+end_src

*** Font
#+begin_src emacs-lisp
;; Font configuration
;; Check if on Windows and change font (Windows-NT)
(defvar 11xx--default-font
  (if (eq system-type 'windows-nt)
      ;; "Consolas"
      ;; "Literation Mono Nerd Font" on Linux or "LiterationMono Nerd Font" on (Windows-NT)
      "LiterationMono Nerd Font"
    "Literation Mono Nerd Font")
  "Sets the default font based on the system type.
To be used with `set-font'.")

(defvar 11xx--default-font-size
  (if (eq system-type 'windows-nt)
      11
    11)
  "Sets the default font size based on the system type.
To be used with `set-font'.")

(defun set-font (&rest args)
  "Set font face using `set-face-attribute' and keywords.
Available keywords are:

`:name' = a string with the font name like \"Liberation Mono\" or
\"DejaVu Sans Mono\". It defaults to the value from the helper
    function `11xx--default-font' that returns a string.

`:size' = a number that is multiplied by 10 internally to pass as
\":height\" to `set-face-attribute'. It defaults to the value
  from the helper function `11xx--default-font-size' that returns a
number."
  (let* ((font (or (plist-get args :name) 11xx--default-font))
         (size (or (plist-get args :size) 11xx--default-font-size)))
    (set-face-attribute 'default nil
                        :font font
                        :height (* size 10))))

(if (daemonp) ;; Load font after daemon frame is created/init hook
    (add-hook 'after-make-frame-functions
              (lambda (frame)
                (with-selected-frame frame
                  (set-font))))
  (add-hook 'after-init-hook
            (lambda () (set-font))))
;; end set font
#+end_src

*** Options
#+begin_src emacs-lisp
(setopt cursor-type 'box
        ;; display-line-numbers-type 'relative
        linum-relative-current-symbol ""
        inhibit-startup-screen t
        auto-hscroll-mode 'current-line ; nano-like line horizontal scrolling ; https://emacs.stackexchange.com/questions/40864/scroll-only-current-line-when-truncating-lines
        use-dialog-box nil)
#+end_src

*** Display line numbers
#+begin_src emacs-lisp
(setq display-line-numbers-grow-only t)
(add-hook 'prog-mode-hook #'display-line-numbers-mode)
(add-hook 'text-mode-hook #'display-line-numbers-mode)

(dolist (hook '(term-mode-hook
                shell-mode-hook
                eshell-mode-hook
                org-mode-hook))
  (add-hook hook (lambda () (display-line-numbers-mode -1))))
#+end_src

*** Parens appearance
#+begin_src emacs-lisp
(setopt show-paren-mode t
        show-paren-delay 0.01
        show-paren-style 'parenthesis)

(use-package rainbow-delimiters
  :hook (emacs-lisp-mode . rainbow-delimiters-mode))
#+end_src

*** Theme
#+begin_seealso
- [[#prevent-white-flashbang-on-startup][Prevent white flashbang on startup]]
- [[https://emacs.stackexchange.com/questions/2797/emacs-wont-load-theme-on-startup/19271#19271][init file - Emacs won't load theme on startup - Emacs Stack Exchange]]
- [[https://stackoverflow.com/questions/22977387/setting-the-emacs-theme-on-startup-without-the-interactive-mode][elisp - setting the emacs theme on startup without the interactive mode - Stack Overflow]]
- [[https://stackoverflow.com/questions/18904529/after-emacs-deamon-i-can-not-see-new-theme-in-emacsclient-frame-it-works-fr/23668935#23668935][After 'emacs --deamon' I can not see new theme in emacsclient frame. It works from 'emacs M-x server-start' - Stack Overflow]]
#+end_seealso

**** Load theme path
*NOTE:* Make sure to save a custom theme with the =-theme= suffix,
otherwise Emacs will ignore the file.
# My dumbass ignored this for two days of "troubleshooting" :s [2022-04-13 Wed 22:08:31]
#+begin_src emacs-lisp
(let ((themedir (expand-file-name "themes/" user-emacs-directory)))
  (add-to-list 'custom-theme-load-path themedir)
  (add-to-list 'load-path themedir))
#+end_src

**** Remove background color when opening from terminal
wizard [[https://stackoverflow.com/questions/19054228/emacs-disable-theme-background-color-in-terminal/20233611#20233611][Emacs: disable theme background color in terminal - Stack Overflow]]
Remove background face when on terminal
#+begin_src emacs-lisp
(defun on-after-init ()
  (unless (display-graphic-p (selected-frame))
    (set-face-background 'default "unspecified-bg" (selected-frame))))
(add-hook 'window-setup-hook #'on-after-init)
;; idk if the string "unspecified-bg" specifically has to be used but it works


;; [[https://stackoverflow.com/questions/19054228/emacs-disable-theme-background-color-in-terminal/33298750#33298750][Emacs: disable theme background color in terminal - Stack Overflow]]
(defun on-frame-open (&optional frame)
  "If the FRAME created in terminal don't load background color."
  (unless (display-graphic-p frame)
    (set-face-background 'default "unspecified-bg" frame)))
(add-hook 'after-make-frame-functions #'on-frame-open)
#+end_src
# [2022-12-03 Sat 00:26:02 -03]

**** Day/Night theme switch
Load theme based on Dark or Light system theme:
- Dependencies:
  + =xdg-desktop-portal=, there are multiple providers targeted for
    different Desktop Environments and Window Managers, install one
    and it should provide the dbus that =auto-dark= depends on.

- =auto-dark= Supports Linux/Mac/Windows
  + See [[https://github.com/LionyxML/auto-dark-emacs][GitHub - LionyxML/auto-dark-emacs: Auto-Dark-Emacs is an auto changer between 2 themes, dark/light, following MacOS, Linux or Windows Dark Mode settings]]
  + NOTE: for this package to work with =darkman= the file
    =~/.config/xdg-desktop-portal/portals.conf= has to override
    =org.freedesktop.impl.portal.Settings= to use darkman's
    implementation, e.g.:
    See [[file:~/.config/darkman/README.org::#orgid-ohmzyr][Making Darkman portal implementation work on minimal setups]].
    #+begin_example
    [preferred]
    org.freedesktop.impl.portal.Settings=darkman
    #+end_example

#+begin_src emacs-lisp
(use-package neron-themes
  :load-path "~/code/emacs/neron-themes")

(use-package auto-dark
  :init
  (setq auto-dark-themes '((neron-dark)
                           (neron-light)))
  :config
  (if (daemonp)
      (add-hook 'after-make-frame-functions #'auto-dark-mode)
    (auto-dark-mode))
  (setq minor-mode-alist
        (delq (assq 'auto-dark-mode minor-mode-alist) minor-mode-alist)))
#+end_src

*** ibuffer mode
[[https://www.reddit.com/r/emacs/comments/19xwk3/comment/c8sg4rq/?utm_source=share&utm_medium=web2x&context=3][wizard src]] | [[http://martinowen.net/blog/2010/02/03/tips-for-emacs-ibuffer.html][Tips for using Emacs Ibuffer]]
#+begin_src emacs-lisp
(use-package ibuffer
  :ensure nil
  :bind (("C-x C-b" . ibuffer))
  :hook (ibuffer-mode . (lambda () (ibuffer-switch-to-saved-filter-groups "default")))
  :init
  (setq ibuffer-show-empty-filter-groups nil
        ibuffer-saved-filter-groups
        '(("default"
           ("shell" (mode . shell-mode))
           ("dired" (mode . dired-mode))
           ("org" (mode . org-mode))
           ("emacs-lisp" (mode . emacs-lisp))))
        ibuffer-expert t))
#+end_src

*** Ruler
#+begin_src emacs-lisp
(setq display-fill-column-indicator-column 79)
(add-hook 'prog-mode-hook #'display-fill-column-indicator-mode)
(add-hook 'text-mode-hook #'display-fill-column-indicator-mode)
(add-hook 'prog-mode-hook
          (lambda () (setq-local display-fill-column-indicator-column 120)))
#+end_src

*** Modeline

**** Doom Modeline
[[https://github.com/daviwil/emacs-from-scratch/blob/master/Emacs.org#better-modeline][daviwil/emacs-from-scratch/Emacs.org#Better Modeline]]
# [2022-05-07 Sat 02:54:50]
[[https://github.com/seagle0128/doom-modeline#customize=][seagle0128/doom-modeline]]
# [2022-05-07 Sat 03:02:57]

and more examples [[https://www.reddit.com/r/emacs/comments/izksoi/2020_modelines_besides_doom/][2020 Modelines besides Doom? : emacs]]
# [2022-05-07 Sat 03:45:54]
#+begin_src emacs-lisp
(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
  :init
  (setq doom-modeline-height 15
        doom-modeline-buffer-encoding nil
        doom-modeline-percent-position nil
        doom-modeline-icon nil
        doom-modeline-enable-word-count nil
        doom-modeline-buffer-file-name-style 'truncate-nil))
#+end_src

**** Window margin/padding
#+begin_src emacs-lisp
(set-window-margins nil 5 5)
#+end_src
- See
  [[https://emacs.stackexchange.com/questions/19022/adding-padding-to-the-left-of-text-in-buffer/19041#19041][linum mode - Adding padding to the left of text in buffer - Emacs Stack Exchange]]
  [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Margins.html][Display Margins (GNU Emacs Lisp Reference Manual)]]
  # [2023-06-06 07:35:53]

*** Fira Code ligatures minor mode
[[https://melpa.org/#/fira-code-mode][fira-code-mode - MELPA]]

Display code ligatures using supported font symbols.

Install =otf-fira-code-symbol= from the AUR

The funciton =(fira-code-mode-set-font)= seems to be required having installed
Fira Code Symbol externally.
[[https://github.com/jming422/fira-code-mode#troubleshooting-common-issues][jming422/fira-code-mode:Troubleshooting Common Issues]]

[[https://github.com/microsoft/cascadia-code][microsoft/cascadia-code]]
[[https://github.com/tonsky/FiraCode/wiki/Emacs-instructions#using-prettify-symbols=][Emacs instructions · tonsky/FiraCode Wiki]]

# [2022-05-30 Mon 13:53:19 -03]
# b [2023-06-19 Mon 15:52:18 -03]

#+begin_src emacs-lisp
(use-package fira-code-mode
  :config
  ;; most of this boiler plate is to handle loading order when in daemon mode
  ;; cool thing I learnt here, defun returns the function name so it can be
  ;; used as symbol too, then that symbol can be called from inside itself
  ;; because of lexical order.
  (if (daemonp)
      (add-hook 'after-make-frame-functions
                (defun fira-code-daemon-init (frame)
                  (when (display-graphic-p frame)
                    (with-selected-frame frame
                      (fira-code-mode-set-font))
                    ;; fontset is global, only needs to run once
                    (remove-hook 'after-make-frame-functions
                                 #'fira-code-daemon-init))))
    (fira-code-mode-set-font))

  :hook ((prog-mode text-mode) . (lambda ()
                                   (when (display-graphic-p)
                                     (fira-code-mode 1)))))
#+end_src
- Note: It doesn't work properly on terminal

* 11xx-half-scroll.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-half-scroll.el :noweb-ref 11xx-half-scroll
:END:

Scroll half-page hack: [[https://www.emacswiki.org/emacs/HalfScrolling][emacswiki.org/Half Scrolling]]
#+begin_src emacs-lisp
;; source https://www.emacswiki.org/emacs/HalfScrolling
(defun window-half-height ()
  (max 1 (/ (1- (window-height (selected-window))) 2)))

(cl-defun window-div-height (&optional (n 2))
  (max 1 (/ (1- (window-height (selected-window))) n)))

(defun scroll-up-half ()
  (interactive)
  (scroll-up (window-half-height)))

(defun scroll-down-half ()
  (interactive)
  (scroll-down (window-half-height)))

;;;###autoload
(defun scroll-up-div ()
  (interactive)
  (scroll-up (window-div-height 10)))

;;;###autoload
(defun scroll-down-div ()
  (interactive)
  (scroll-down (window-div-height 10)))

(keymap-global-set "<remap> <scroll-up-command>" #'scroll-up-div)
(keymap-global-set "<remap> <scroll-down-command>" #'scroll-down-div)

(provide '11xx-half-scroll)
#+end_src
# ;; [next] good-scroll-up-full-screen
# ;; [prior] good-scroll-down-full-screen
# ;; Scroll
# ;; "<remap> <scroll-up-command>" scroll-up-half
# ;; "<remap> <scroll-down-command>" scroll-down-half
# ;; "<remap> <scroll-up-command>" pixel-scroll-up
# ;; "<remap> <scroll-down-command>" pixel-scroll-down
* 11xx-pixel-scroll.el: Smooth scrolling
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-pixel-scroll.el :noweb-ref 11xx-pixel-scroll
:END:
- See
  + [[https://www.emacswiki.org/emacs/SmoothScrolling#h5o-1][EmacsWiki: Smooth Scrolling]]
  + [[https://stackoverflow.com/questions/1128927/how-to-scroll-line-by-line-in-gnu-emacs/1128948#1128948][How to scroll line by line in GNU Emacs? - Stack Overflow]]

#+begin_src emacs-lisp
(use-package pixel-scroll
  :ensure nil
  :hook (after-init . pixel-scroll-precision-mode)
  :init
  (setq pixel-scroll-precision-use-momentum t
        pixel-scroll-precision-large-scroll-height 5.0
        mouse-wheel-scroll-amount '(1 ((shift) . 1))
        mouse-wheel-progressive-speed nil
        mouse-wheel-follow-mouse t))

(provide '11xx-pixel-scroll)
#+end_src

* 11xx-navigation.el: Controlling Emacs
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-navigation.el
:END:

#+begin_src emacs-lisp
<<11xx-navigation>>

(provide '11xx-navigation)
#+end_src

** def
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-navigation :tangle no
:END:

*** Navigation

**** Window movement with ace-window
[[https://www.admiralbumblebee.com/programming/2020/01/04/Six-months-VS-Code.html#window-management][Window Management with ace-window src]]

Packages for enhanced Emacs minibuffers and better completions/matches
https://youtu.be/43Dg5zYPHTU

**** Rotate frames
wizard [[https://emacs.stackexchange.com/questions/5371/how-to-change-emacs-windows-from-vertical-split-to-horizontal-split/5372#5372][How to change Emacs windows from vertical split to horizontal split? - Emacs Stack Exchange]]
# [2022-12-02 Fri 23:34:18 -03]

Use the package =transpose-frame= (see [[https://www.emacswiki.org/emacs/TransposeFrame][EmacsWiki: Transpose Frame]]):
#+begin_src emacs-lisp
(use-package transpose-frame
  :bind (("M-r" . rotate-frame-clockwise-or-default)
         ("M-S-r" . rotate-frame-anticlockwise-or-default))
  :config
  (defun rotate-frame-clockwise-or-default ()
    "Rotate frame clockwise if more than one frame exists; otherwise, execute default command."
    (interactive)
    (if (cdr (frame-list))
        (rotate-frame-clockwise)
      ;; Default command:
      (call-interactively #'move-to-window-line-top-bottom)))

  (defun rotate-frame-anticlockwise-or-default ()
    "Rotate frame anticlockwise if more than one frame exists; otherwise, execute default command."
    (interactive)
    (if (cdr (frame-list))
        (rotate-frame-anticlockwise)
      ;; Default command:
      (call-interactively #'move-to-window-line-top-bottom)))

  )
#+end_src

*** Multiple Cursors
~multiple-cursors~
#+begin_src emacs-lisp
(use-package multiple-cursors
  :bind (("C-S-c C-S-c" . mc/edit-lines)
         ("C-<" . mc/mark-previous-like-this)
         ("C->" . mc/mark-next-like-this)
         ("C-c C-<" . mc/mark-all-like-this)))
#+end_src


* llm-ai-assistants.el: Large Language Models (LLM) AI Assistants
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/llm-ai-assistants.el
:END:

#+begin_src emacs-lisp
;;; llm-ai-assistants.el --- AI assistant features config -*- lexical-binding: t -*-

;;; Code
#+end_src

** gptel
- See
  + [[https://www.reddit.com/r/emacs/comments/14glmqc/use_emacs_as_a_chatgpt_app/][Use emacs as a ChatGPT app : emacs]]
    that links [[https://www.armindarvish.com/en/post/use_emacs_as_a_chatgpt_client/][Use Emacs as a ChatGPT App from Anywhere on Your System | /\r|\/|i|\|]]
  + [[https://github.com/karthink/gptel][karthink/gptel: A no-frills ChatGPT client for Emacs]]
  + ChatGPT API keys can be generated from
    https://platform.openai.com/account/api-keys
# [2023-06-23 Fri 13:14:22 -03]
#+begin_src emacs-lisp
(use-package gptel
  :init
  (setq gptel-default-mode 'org-mode)
  :config
  (gptel-make-gemini "Gemini"
    :stream t
    :key (gptel-api-key-from-auth-source "generativelanguage.googleapis.com"))
  (gptel-make-anthropic "Claude"
    :stream t
    :key (gptel-api-key-from-auth-source "api.anthropic.com"))

  (gptel-make-openai "MiniMax"
    :host "api.minimax.io"
    :endpoint "/v1/chat/completions"
    :stream t
    :key (gptel-api-key-from-auth-source "api.minimax.io")
    :models '(MiniMax-M2.5
              MiniMax-M2.5-highspeed
              MiniMax-M2.1
              MiniMax-M2.1-highspeed
              MiniMax-M2
              MiniMax-M2.7
              MiniMax-M2.7-highspeed
              MiniMax-M3
              MiniMax-M3-highspeed))
  (setq gptel-model 'MiniMax-M3-highspeed)

  (gptel-make-ollama "Ollama"
    :host "localhost:11434"
    :stream t
    :models '(qwen3.5:9b
              ))

  (use-package gptel-openrouter
    :vc (:url "https://github.com/darcamo/gptel-openrouter")
    :after gptel
    :config
    (require 'seq)

    (defun gptel-openrouter-model-free-p (model)
      "Return non-nil if MODEL appears to be a free OpenRouter model.

MODEL is one model alist from the cached OpenRouter `/models` response."
      (let ((id (alist-get 'id model)))
        (and id
             (string-match-p "\\(:free\\|^openrouter/free$\\)" id))))

    (defun gptel-openrouter-get-all-models (&optional predicate)
      "Return all cached OpenRouter model IDs as symbols.

If PREDICATE is non-nil, it is called with each model alist from the
cached OpenRouter model data. Only models for which PREDICATE returns
non-nil are kept."
      ;; Downloads only if the cache is missing or older than one day,
      ;; according to gptel-openrouter's own logic.
      (gptel-openrouter-download-model-data)

      ;; Invalidate the in-memory parsed JSON cache so a freshly downloaded
      ;; models.json is visible during the same Emacs session.
      (setq gptel-openrouter--json-cache-content nil)

      (let* ((content (gptel-openrouter--get-json-content))
             (models (alist-get 'data content)))
        (unless models
          (user-error
           "No OpenRouter model data found; run M-x gptel-openrouter-download-model-data"))
        (mapcar
         (lambda (model)
           (intern (alist-get 'id model)))
         (seq-filter
          (lambda (model)
            (and (alist-get 'id model)
                 (or (null predicate)
                     (funcall predicate model))))
          models))))

    (defun gptel-openrouter-get-all-annotated-models (&optional predicate)
      "Return all cached OpenRouter models annotated for gptel.

If PREDICATE is non-nil, only annotate models for which PREDICATE
returns non-nil."
      (gptel-openrouter-get-annotated-models
       (gptel-openrouter-get-all-models predicate)))

    (gptel-make-openai "OpenRouter"
      :host "openrouter.ai"
      :endpoint "/api/v1/chat/completions"
      :stream t
      :key (gptel-api-key-from-auth-source "openrouter.ai")

      ;; All current cached OpenRouter models, excluding free models.
      :models
      (gptel-openrouter-get-all-annotated-models
       (lambda (model)
         (not (gptel-openrouter-model-free-p model))))

      :request-params
      '(:service_tier "flex"
        :provider (:sort "throughput"
                         :allow_fallbacks :json-false
                         :data_collection "deny"
                         :zdr t))))

  (gptel-make-openai "Groq"
    :host "api.groq.com"
    :endpoint "/openai/v1/chat/completions"
    :stream t
    :key (gptel-api-key-from-auth-source "api.groq.com")
    :models '(openai/gpt-oss-120b
              llama-3.3-70b-versatile
              qwen/qwen3-32b
              llama-3.1-8b-instant
              openai/gpt-oss-safeguard-20b
              whisper-large-v3-turbo
              canopylabs/orpheus-v1-english
              canopylabs/orpheus-arabic-saudi))

  (gptel-make-deepseek "DeepSeek"
    :stream t
    :key (gptel-api-key-from-auth-source "api.deepseek.com"))

  (with-eval-after-load 'org
    (add-to-list 'org-use-property-inheritance "GPTEL_MODEL")
    (add-to-list 'org-use-property-inheritance "GPTEL_BACKEND")
    (add-to-list 'org-use-property-inheritance "GPTEL_SYSTEM")
    (add-to-list 'org-use-property-inheritance "GPTEL_TEMPERATURE")))

(with-eval-after-load 'gptel
  (defun gptel--append-response-footer (beg end)
    "Append a footer after a completed gptel response."
    (when (> end beg)
      (save-excursion
        (goto-char end)
        (insert
         (pcase major-mode
           ('markdown-mode
            (concat "\n\n[comment]: <> (Responded: "
                    (format-time-string "%Y-%m-%d %a %H:%M:%S %:::z")
                    ")"))
           ('org-mode
            (concat "\n\n# Responded: "
                    (format-time-string "%Y-%m-%d %a %H:%M:%S %:::z")))
           (_ ""))))))

  (add-hook 'gptel-post-response-functions #'gptel--append-response-footer))

(use-package gptel-titler
  :after gptel
  :load-path "~/code/emacs/gptel-titler/"
  :init
  (setopt gptel-titler-model 'openai/gpt-oss-safeguard-20b)
  :config
  ;; example add new model name to existing backend
  ;; (let ((backend (gptel-get-backend "OpenRouter")))
  ;;   (when backend
  ;;     (cl-pushnew 'openai/gpt-oss-safeguard-20b
  ;;                 (gptel-backend-models backend)
  ;;                 :key (lambda (x) (if (listp x) (car x) x)))))
  )
#+end_src

mcp
#+begin_src emacs-lisp
(use-package mcp
  :init
  (setq mcp-hub-servers
        `(("searxng-isokoliuk" . (:command "podman"
                                           :args ("run" "--rm" "-i"
                                                  "--network" "host"
                                                  "--env-file" ,(expand-file-name "~/ai/searxng/.env")
                                                  "isokoliuk/mcp-searxng:latest"))) ; ts
          ("searxng-icewreck" . (:command "podman"
                                          :args ("run" "--rm" "-i"
                                                 "--network" "host"
                                                 "--env-file" ,(expand-file-name "~/ai/searxng/.env")
                                                 "docker.io/icewreck/searxng-mcp-server:latest"))))) ; python
  )

(use-package gptel-integrations
  :ensure nil
  :after mcp)
#+end_src

** chat file helper
#+begin_src emacs-lisp
(defun new-ai-chat-file (&optional new-file)
  (interactive)
  (let* ((defoutfile (expand-file-name (concat (time-stamp-string "%Y%m%dT%H%M%S") ".org") "~/ai/chats/"))
         (outfile (file-truename (or new-file defoutfile))))
    (find-file outfile)))
#+end_src


** provide pseudo-package
#+begin_src emacs-lisp
(provide 'llm-ai-assistants)
;;; llm-ai-assistants.el ends here
#+end_src


* 11xx-pdf-viewer.el
- [[https://www.reddit.com/r/emacs/comments/opkzxm/view_pdf_in_dark_mode_with_pdftools/][View PDF in dark mode with pdf-tools : r/emacs]]
- [[https://github.com/vedang/pdf-tools][vedang/pdf-tools: Emacs support library for PDF files.]]

Nothing here loads until a PDF is opened. ~pdf-loader-install~ registers the
file associations and installs pdf-tools on first use, which also keeps the
=epdfinfo= server from starting with the daemon. The =pdf:= Org link type is
registered from the autoloaded ~org-pdftools~ commands, so following, storing
or exporting such a link loads the package while merely opening an Org buffer
does not.
#+begin_src emacs-lisp :noweb-ref dummy :tangle lisp/11xx-pdf-viewer.el
(use-package pdf-tools
  :init (pdf-loader-install)
  :bind (:map pdf-view-mode-map
              ("j" . pdf-view-next-line-or-next-page)
              ("k" . pdf-view-previous-line-or-previous-page))
  :hook (pdf-view-mode . pdf-view-themed-minor-mode))

(use-package org-pdftools
  :defer t
  :init
  (with-eval-after-load 'org
    (org-link-set-parameters "pdf"
                             :follow #'org-pdftools-open
                             :complete #'org-pdftools-complete-link
                             :store #'org-pdftools-store-link
                             :export #'org-pdftools-export)))

(provide '11xx-pdf-viewer)
#+end_src

** Troubleshooting
Getting =[...]: pdf-info-epdfinfo-program is not executable= means
epdfinfo was not built. Having installed from MELPA or NonGNU ELPA it
should be available but running =pdf-tools-install= may be necessary:
: M-x pdf-tools-install
or eval =(pdf-tools-install)=, it returns nil if it successfully detects
a working executable.
- See [[https://github.com/politza/pdf-tools/issues/288][pdf-info-check-epdfinfo: pdf-info-epdfinfo-program is not executable · Issue #288 · politza/pdf-tools]]

* 11xx-latex.el: LaTeX config
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-latex.el
:END:

- See [[https://abode.karthinks.com/org-latex-preview/][org-latex-preview: Set up and troubleshooting]]
  # [2024-09-18 Wed 19:39:19 -03] @ak

For math and chemestry equations and notations.
# [2022-12-07 Wed 09:15:05 -03]

=tex-mode.el= provides =latex-mode=:
#+begin_src emacs-lisp
(use-package tex-mode
  :ensure nil)
#+end_src

Install auctex for a better, faster backend:
[[https://karthinks.com/software/fast-latex-previews-in-org-mode/][Fast Latex previews in Org-mode | Karthinks]]
#+begin_src emacs-lisp
(use-package auctex)
#+end_src

*** Customize LaTeX preview image size
#wizard [[https://emacs.stackexchange.com/questions/19880/font-size-control-of-latex-previews-in-org-files/33992#33992][org mode - Font size control of LateX previews in Org files - Emacs Stack Exchange]]
#+begin_src emacs-lisp :tangle no
(setq org-format-latex-options (plist-put org-format-latex-options :scale 1.5))
#+end_src

Export sizes of LaTeX in HTML, from Org Mode
[[https://emacs.stackexchange.com/questions/59174/properly-exporting-latex-to-html-from-org-mode-using-dvisvgm-dvipng/59184#59184][Properly exporting latex to HTML from org-mode using dvisvgm / dvipng - Emacs Stack Exchange]]
#+begin_src emacs-lisp
(with-eval-after-load 'ox-html
  (setq org-html-head
        (replace-regexp-in-string
         ".org-svg { width: 90%; }"
         ".org-svg { width: auto; }"
         org-html-style-default)))
#+end_src
LaTeX preview in org-mode:
- [[https://github.com/io12/org-fragtog][io12/org-fragtog: Automatically toggle Org mode LaTeX fragment previews as the cursor enters and exits them]]
- See "=LaTeX previews=" heading: [[https://lucidmanager.org/productivity/ricing-org-mode/][Ricing Org Mode: A Beautiful Writing Environment]]
#+begin_src emacs-lisp
(use-package org-fragtog)
#+end_src

* dired-hl-line-mode.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/dired-hl-line-mode.el
:END:

#+begin_src emacs-lisp
;;; dired-hl-line-mode.el --- Hide block cursor and highlights current line with hl-line -*- lexical-binding: t -*-

;;; Commentary
;; Minor mode for Dired that hides the block cursor and enables `hl-line'.
;; Automatically transitions in/out when entering wdired or dired-efap for editing.

;;; Code

(require 'hl-line)

(defun dired-hl-line-mode--on ()
  "Enable hl-line and hide cursor."
  (hl-line-mode 1)
  (setq-local cursor-type nil))

(defun dired-hl-line-mode--off ()
  "Disable hl-line and restore cursor."
  (hl-line-mode -1)
  (setq-local cursor-type t))

(defun dired-hl-line-mode--maybe-on (&rest _)
  "Re-enable if mode is active in this buffer."
  (when dired-hl-line-mode
    (dired-hl-line-mode--on)))

(defun dired-hl-line-mode--maybe-off (&rest _)
  "Disable if mode is active in this buffer."
  (when dired-hl-line-mode
    (dired-hl-line-mode--off)))

(define-minor-mode dired-hl-line-mode
  "Toggle hl-line + hidden cursor for read-only Dired browsing."
  :lighter " HlC"
  :group 'dired
  (if dired-hl-line-mode
      (progn
        (add-hook 'wdired-mode-hook #'dired-hl-line-mode--maybe-off nil t)
        (advice-add 'wdired-change-to-dired-mode      :after #'dired-hl-line-mode--maybe-on)
        (advice-add 'dired-efap                       :after #'dired-hl-line-mode--maybe-off)
        (advice-add 'dired-efap--change-to-dired-mode :after #'dired-hl-line-mode--maybe-on)
        (dired-hl-line-mode--on))
    (remove-hook 'wdired-mode-hook                   #'dired-hl-line-mode--maybe-off t)
    (advice-remove 'wdired-change-to-dired-mode      #'dired-hl-line-mode--maybe-on)
    (advice-remove 'dired-efap                       #'dired-hl-line-mode--maybe-off)
    (advice-remove 'dired-efap--change-to-dired-mode #'dired-hl-line-mode--maybe-on)
    (dired-hl-line-mode--off)))

(provide 'dired-hl-line-mode)
;;; dired-hl-line-mode.el ends here
#+end_src


* File Local Variables                                             :noexport:
- [[https://www.reddit.com/r/orgmode/comments/jy8fuc/orgbabeltangle_on_save/][org-babel-tangle on save? : r/orgmode]]
- [[https://gitlab.com/joseph8th/literatemacs/-/blob/master/README.org?ref_type=heads&plain=1#L1915][README.org · master · Joseph E. Edwards VIII / literatemacs · GitLab]]
- [[https://web.archive.org/web/20230117073433/https://github.com/joseph8th/literatemacs#conclusion][GitHub - joseph8th/literatemacs: My literate Emacs config]]

#+begin_comment
# Local Variables:
# eval: (add-hook 'org-babel-tangle-finished-hook #'org-babel-tangle-add-lexical-prop-to-el-tangled-files nil nil)
# End:
#+end_comment
