:PROPERTIES:
:header-args:emacs-lisp: :export both :mkdirp yes :results drawer :cache yes :noweb no-export
:END:
#+title: Emacs "init" config file
#+author: 11xx
# #+STARTUP: hidestars

# Export as HTML
# #+SETUPFILE: ~/org/.setup/theme-readtheorg.setup

# #+OPTIONS: toc:2

Send errors to *Backtrace*, only set to true while debugging
: (setq debug-on-error t)

* Dependencies
- Arch
  + ttf-liberation-mono-nerd
  + otf-fira-code-symbol [AUR]
  + aspell + aspell-* # ispell
  + xdg-desktop-portal: See [[*Day/Night theme switch][Day/Night theme switch]].

* References
Here are some complete configuration examples:

- [[https://github.com/progfolio/.emacs.d/blob/master/init.org][progfolio's .emacs.d/init.org]]
- [[https://github.com/garyo/emacs-config][garyo/emacs-config: Emacs configuration]]
- [[https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org][angrybacon's dotemacs]]
- [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org][David Wilson's Emacs Configuration]]
- [[https://tecosaur.github.io/emacs-config/config.html][tecosaur's Doom Emacs Configuration]]
- [[https://github.com/zw963/.emacs.d/tree/master][GitHub - zw963/.emacs.d: My own .emacs.d]]


* early-init.el
:PROPERTIES:
:header-args:emacs-lisp: :tangle early-init.el
:END:

Enable lexical binding default.
# Had bad luck with this actually being set globally in the past but let's see
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-

(setq-default lexical-binding t)
#+end_src

** Disable =package.el=
In favour of [[#elpaca-bootstrap.el][elpaca]]
# TODO thinking about changing to package.el+use-package at some point
#+begin_src emacs-lisp
(setq package-enable-at-startup nil)
#+end_src

** Startup time report
#+begin_src emacs-lisp
(add-hook 'emacs-startup-hook
  (lambda ()
    (message "*** Emacs loaded in %s seconds with %d garbage collections."
             (emacs-init-time "%.2f")
             gcs-done)))
#+end_src
#+begin_seealso
- https://blog.d46.us/advanced-emacs-startup/
- Defun [[https://youtu.be/9i_9hse_Y08?t=234]]
#+end_seealso

** Prevent white flashbang on startup
:PROPERTIES:
:CUSTOM_ID: prevent-white-flashbang-on-startup
:END:

#+begin_seealso
Credits: [[https://github.com/doomemacs/doomemacs/issues/2828#issuecomment-627095431][White flash on initial open · Issue #2828 · doomemacs/doomemacs]]
#+end_seealso

When starting a fresh Emacs instance the frame may display a white background
for a few moments. To fix this simply change the default =background-color=
from the =early-init.el= file, just so it loads before the frame is created:
# "#17191a"
#+begin_example
(add-to-list 'default-frame-alist '(background-color . "#222222"))
#+end_example
# [2022-12-02 Fri 21:23:24 -03]

***** Set initial background color based on system's color scheme
# pcase example from [[https://www.reddit.com/r/emacs/comments/108kwyl/comment/j3w5j88/?context=3][New package: Darkman integration with Emacs. : emacs]]
Before loading the theme
#+begin_src emacs-lisp
(require 'dbus nil t)
(defun is-dark-color-scheme-dbus ()
  ;; copy of 'auto-dark--is-dark-mode-dbus' from 'auto-dark.el'.
  ;; 0 = light, being a fallback default
  ;; 1 = dark
  ;; 2 = light
   "Read color-scheme from org.freedesktop.portal.Settings appearance interface.
Returns t if dark, nil otherwise."
  (eq 1 (caar (dbus-ignore-errors
                (dbus-call-method
                 :session
                 "org.freedesktop.portal.Desktop"
                 "/org/freedesktop/portal/desktop"
                 "org.freedesktop.portal.Settings" "Read"
                 "org.freedesktop.appearance" "color-scheme")))))

(when (and initial-window-system (is-dark-color-scheme-dbus))
  (setq frame-background-mode 'dark)

  (let ((bg-color "#222222")
        (fg-color "#eeeeee"))
    (add-to-list 'initial-frame-alist `(background-color . ,bg-color))
    (add-to-list 'initial-frame-alist `(foreground-color . ,fg-color))
    (add-to-list 'default-frame-alist `(background-color . ,bg-color))
    (add-to-list 'default-frame-alist `(foreground-color . ,fg-color))))
#+end_src


* init.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle init.el :padline no
:CUSTOM_ID: init-el
:END:

** Customise Options/Variables
#+begin_src emacs-lisp
(setopt read-process-output-max (* 3 (* 1024 1024)))
#+end_src
"Increase the amount of data which Emacs reads from the process.
Again the emacs default is too low 4k considering that the some of
the language server responses are in 800k - 3M range."
[[https://emacs-lsp.github.io/lsp-mode/page/performance/][emacs-lsp - Performance Guide]]

- Indentation options
  + See
    * [[https://www.emacswiki.org/emacs/NoTabs#h5o-1][So How Do I Insert a Tab If I Really Have To?]]
    * [[https://kb.iu.edu/d/abde][Set tab size]]
    * [[https://www.emacswiki.org/emacs/NoTabs][No Tabs]]

Disable tabs for spaces.
#+begin_src emacs-lisp
(setopt indent-tabs-mode nil ; disable tabs
        tab-width 2
        tab-stop-list (number-sequence 2 4 2) ; if `tab-width' in not read, use this
        tab-always-indent t)
#+end_src

Where paragraph breaks
#+begin_src emacs-lisp
(setopt fill-column 79)
#+end_src

start up behavior
See [[https://tychoish.com/post/towards-faster-emacs-start-times/][Towards Faster Emacs Start Times#Helpful Settings]]
#+begin_src emacs-lisp
(setopt inhibit-startup-message t
        initial-scratch-message nil)
#+end_src

undo/redo
[[https://emacs.stackexchange.com/questions/51956/no-further-undo-information/51970#51970][No further undo information - Emacs Stack Exchange]]
#+begin_src emacs-lisp
(setopt undo-limit (* 1024 1024 1024)
        undo-strong-limit (* 1024 1024 1024)
        undo-outer-limit (* 1024 1024 1024))
#+end_src

Turn off sounds
- [[https://emacs.stackexchange.com/questions/28906/how-to-switch-off-the-sounds][bell - How to switch off the sounds? - Emacs Stack Exchange]]
#+begin_src emacs-lisp
(setopt ring-bell-function 'ignore)
#+end_src
# [2024-02-03 Sat 23:36:30 -03:00] @winr58

- Laggy/Sluggish cursor movement
  #+begin_seealso
  - [[https://emacs.stackexchange.com/questions/28736/emacs-pointcursor-movement-lag/28746#28746][motion - Emacs point(cursor) movement lag - Emacs Stack Exchange]]
  # [2023-06-20 Tue 12:58:11 -03]
  - [[https://www.reddit.com/r/emacs/comments/819v0h/how_to_speed_up_cursor_movement_by_10x/][How to speed up cursor movement by 10x : emacs]]
    As pointed in the command, this is probably a package issue, since running
    ~emacs -Q~ doesn't present this issue.
  - ~auto-window-vscroll~ made the most difference, go figure 🤷‍
  #+end_seealso
#+begin_src emacs-lisp
(setopt auto-window-vscroll nil)
#+end_src

Little safety-net for internal deletion functions
#+begin_src emacs-lisp
(setopt delete-by-moving-to-trash t)
#+end_src

** Additional load-path directories
Add subdirectory to load path containing custom modules.
#+begin_src emacs-lisp :padline yes
(defvar config-lisp-directory
  (expand-file-name "lisp/" user-emacs-directory)
  "Directory containing local configuration Lisp source files.")

(add-to-list 'load-path config-lisp-directory)
#+end_src

** Elpaca package manager bootstrap & setup.el
Bootstrap elpaca
#+begin_src emacs-lisp
(require 'elpaca-bootstrap)
#+end_src

Install setup with Elpaca and define macros
#+begin_src emacs-lisp
(require '11xx-setup)
#+end_src

** Clean Emacs directory
#+begin_src emacs-lisp
(require 'init-no-littering)
(require 'init-backup-auto-save)
#+end_src

** Native compilation settings
#+begin_src emacs-lisp
(setopt native-comp-jit-compilation t
        package-native-compile t
        native-comp-async-report-warnings-errors 'silent)
#+end_src

** Garbage colletion

Increase Garbage Collection threshold:
- [[https://github.com/mnewt/dotemacs/blob/master/early-init.el#L19-L22][mnewt/dotemacs/early-init.el#L19-L22]].
- [[https://emacs-lsp.github.io/lsp-mode/page/performance/#adjust-gc-cons-threshold][Performance - LSP Mode - LSP support for Emacs]]
#+begin_src emacs-lisp
(setq gc-cons-threshold (* 500 1024 1024))
(add-hook 'elpaca-after-init-hook (lambda() (setq gc-cons-percentage 0.6)))
#+end_src

** Load autoloads
#+begin_src emacs-lisp
(defun loaddefs-setup (&optional lisp-dir)
  "Generate and load autoloads for Lisp files in LISP-DIR.

Scans LISP-DIR (defaults to `config-lisp-directory') for autoload
cookies and writes the result to config-loaddefs.el in
`no-littering-var-directory', adding LISP-DIR to `load-path'."
  (let* ((dir (file-truename (or lisp-dir config-lisp-directory)))
         (out (expand-file-name "config-loaddefs.el" no-littering-var-directory)))
    (loaddefs-generate dir out)
    (load out nil :nomessage)))

(loaddefs-setup config-lisp-directory)
#+end_src

** Load config
Personal config modularized into "pseudo-packages"
#+begin_src emacs-lisp
(require '11xx-functions)
(require 'utf-8-default)
(require '11xx-defaults)
(require '11xx-completion)
(require '11xx-ui)
(require '11xx-navigation)
(require '11xx-half-scroll)
(require '11xx-pixel-scroll)

(setup 11xx-dired
  (:load-after dired))
(require '11xx-magit)
(setup 11xx-org
  (:load-after org))

(require '11xx-modes)
(require 'llm-ai-assistants)
(require '11xx-pdf-viewer)
#+end_src



* elpaca-bootstrap.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/elpaca-bootstrap.el
:CUSTOM_ID: elpaca-bootstrap.el
:END:

#+begin_src emacs-lisp
(defvar elpaca-installer-version 0.11)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1 :inherit ignore
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (<= emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                  ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                  ,@(when-let* ((depth (plist-get order :depth)))
                                                      (list (format "--depth=%d" depth) "--no-single-branch"))
                                                  ,(plist-get order :repo) ,repo))))
                  ((zerop (call-process "git" nil buffer t "checkout"
                                        (or (plist-get order :ref) "--"))))
                  (emacs (concat invocation-directory invocation-name))
                  ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                        "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                  ((require 'elpaca))
                  ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))
#+end_src

/(Separated this provide line to make updating the previous bootstrap
block easier)/
#+begin_src emacs-lisp
(provide 'elpaca-bootstrap)
#+end_src


- *NOTE*: If the following error is given after =M-x elpaca-fetch -> pull -> merge= ::
  : ⛔ Warning (elpaca): Init installer version does not match [...]
  Update the install bootstrap: [[https://github.com/progfolio/elpaca/blob/master/doc/manual.md#installer][progfolio/elpaca/doc/manual.md at master]].
  + [[https://github.com/progfolio/elpaca/issues/70#issuecomment-1440633070][[Bug]: Warning (emacs): Elpaca installer version mismatch · Issue #70 · progfolio/elpaca]]

* 11xx-setup.el
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-setup.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

#+begin_seealso
- [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org#streamlined-configuration-with-setupel][daviwil/dotfiles/Emacs.org#streamlined-configuration-with-setupel]]
- [[https://git.sr.ht/~pkal/setup/tree/master/item/setup.el][~pkal/setup (master): setup.el - sourcehut git]]
#+end_seealso

Install pkal's =setup.el= and define its macros
#+begin_src emacs-lisp
(elpaca setup (require 'setup))
(elpaca-wait)
#+end_src

- [[https://www.emacswiki.org/emacs/SetupEl#:~:text=the%20above%20example-,transforming%20configuration%20errors%20into%20warnings,-This%20code%20transforms][Transforming Configuration Errors Into Warnings | EmacsWiki: Setup El]]
#+begin_src emacs-lisp :noweb-ref
(defun setup-config-error-into-warning (expansion)
  "Wrap `setup' output with `condition-case'."
  (let ((err (gensym "setup-err")))
    `(condition-case ,err
   ,expansion
       (error
  (display-warning 'setup (concat "Problem in config: "
          (error-message-string ,err)
          ": \n"
          (with-output-to-string
            (pp (quote ,expansion))))
                   :error)))))

(advice-add 'setup :filter-return #'setup-config-error-into-warning)
#+end_src

** =setup.el= additional macros

*** :elpaca
- [[https://www.emacswiki.org/emacs/SetupEl#:~:text=elpaca%20is%20an%20elisp%20package%20manager.][EmacsWiki/Setup El#Elpaca]]

Two ways of using elpaca with these macros:
: (setup-elpaca package-name)
or
: (setup (:elpaca package-name))
also note that elpaca isn't really compatible with setup's lists so
instead of multiple packages being assigned to the same macro,
multiple macro calls have to be used, e.g.:
: (setup (:elpaca package-name1))
: (setup (:elpaca package-name2))

This macro is a replacement for =(setup)= that uses elpaca to install packages.
#+begin_src emacs-lisp
(defmacro setup-elpaca (order &rest body)
  "Execute BODY in `setup' declaration after ORDER is finished.
The elpaca package manager installs ORDER."
  (declare (indent 1))
  (let ((o order))
    (when-let ((ensure (cl-position :ensure body)))
      (setq o (if (null (nth (1+ ensure) body)) nil order)
            body (append (cl-subseq body 0 ensure)
                         (cl-subseq body (+ ensure 2)))))
    `(elpaca ,o (setup
                    ,(if-let (((memq (car-safe order) '(quote \`)))
                              (feature (flatten-tree order)))
                         (cadr feature)
                       (elpaca--first order))
                  ,@body))))
#+end_src

This method uses =setup='s internal keyword and defines =:elpaca= for
installing packages or if using =(:elpaca nil)= Elpaca won't install but
still allow execution of BODY.
#+begin_src emacs-lisp
(defun setup-wrap-to-install-package (body _name)
  "Wrap BODY in an `elpaca' block if necessary.
The body is wrapped in an `elpaca' block if `setup-attributes'
contains an alist with the key `elpaca'."
  (if (assq 'elpaca setup-attributes)
      `(elpaca ,(cdr (assq 'elpaca setup-attributes)) ,@(macroexp-unprogn body))
    body))

;; Add the wrapper function
(add-to-list 'setup-modifier-list #'setup-wrap-to-install-package)

(setup-define :elpaca
  (lambda (order &rest recipe)
    (push (cond
           ((eq order t) `(elpaca . ,(setup-get 'feature)))
           ((eq order nil) '(elpaca . nil))
           (`(elpaca . (,order ,@recipe))))
          setup-attributes)
    ;; If the macro wouldn't return nil, it would try to insert the result of
    ;; `push' which is the new value of the modified list. As this value usually
    ;; cannot be evaluated, it is better to return nil which the byte compiler
    ;; would optimize away anyway.
    nil)
  :documentation "Install ORDER with `elpaca'.
The ORDER can be used to deduce the feature context."
  :shorthand #'cadr)
#+end_src

*** :local-or-package
from [[https://www.emacswiki.org/emacs/SetupEl#:~:text=setup-define%20%3Alocal-or-package][EmacsWiki/Setup El#Install a package if not available locally]]
#+begin_src emacs-lisp
(setup-define :local-or-package
  (lambda (feature-or-package)
    `(unless (locate-file ,(symbol-name feature-or-package)
                          load-path
                          (get-load-suffixes))
       (:elpaca ,feature-or-package)))
  :documentation "Install PACKAGE if it is not available locally.
This macro can be used as NAME, and it will replace itself with
the first PACKAGE."
  :repeatable t
  :shorthand #'cadr)
#+end_src

*** :disabled
https://github.com/daviwil/dotfiles/blob/master/Emacs.org#disabled
#+begin_src emacs-lisp
(setup-define :disabled
  (lambda ()
    (setup-quit))
  :documentation "Always stop evaluating the body.")
#+end_src

*** :advise
[[https://www.emacswiki.org/emacs/SetupEl#h5o-11][Add advice]]

Simplify the definition of [[https://www.emacswiki.org/emacs/Advice][Advice]]:
#+begin_src emacs-lisp
(setup-define :advise
    (lambda (symbol where function)
      `(advice-add ',symbol ,where ,function))
  :documentation "Add a piece of advice on a function.
See `advice-add' for more details."
  :after-loaded t
  :debug '(sexp sexp function-form)
  :ensure '(nil nil func)
  :repeatable t)
#+end_src

*** :load-after
#+begin_src emacs-lisp
(setup-define :load-after
  (lambda (&rest features)
    (let ((body `(require ',(setup-get 'feature))))
      (dolist (feature (nreverse features))
        (setq body `(with-eval-after-load ',feature ,body)))
      body))
  :documentation "Load the current feature after FEATURES.")
#+end_src

*** :hide-mode
#+begin_src emacs-lisp
(setup-define :hide-mode
  (lambda (&optional mode)
    (let* ((mode (or mode (setup-get 'mode)))
           (mode (if (string-match-p "-mode\\'" (symbol-name mode))
                     mode
                   (intern (format "%s-mode" mode)))))
      `(setq minor-mode-alist
             (delq (assq ',mode minor-mode-alist)
                   minor-mode-alist))))
  :documentation "Hide the mode-line lighter of the current mode.
Alternatively, MODE can be specified manually, and override the
current mode."
  :after-loaded t)
#+end_src

*** :put-enable
#+begin_src emacs-lisp
(setup-define :put-enable
  (lambda (commands)
    `(put ',commands 'disabled nil))
  :documentation "Enable disabled COMMANDS."
  :after-loaded t
  :repeatable t)
#+end_src

*** :face
#+begin_src emacs-lisp
(setup-define :face
  (lambda (face spec) `(custom-set-faces (quote (,face ,spec))))
  :documentation "Customize FACE to SPEC."
  :signature '(face spec ...)
  :debug '(setup)
  :repeatable t
  :after-loaded t)
#+end_src

*** :autoload
#+begin_src emacs-lisp
(setup-define :autoload
  (lambda (func)
    (let ((fn (if (memq (car-safe func) '(quote function))
                  (cadr func)
                func)))
      `(unless (fboundp (quote ,fn))
         (autoload (function ,fn) ,(symbol-name (setup-get 'feature)) nil t))))
  :documentation "Autoload COMMAND if not already bound."
  :repeatable t
  :signature '(FUNC ...))
#+end_src

*** =:option*= prefix-less alternative to =:option=
#+begin_src emacs-lisp
(setup-define :option*
  (lambda (name val)
    `(customize-set-variable
      ',(intern (format "%s-%s" (setup-get 'feature) name))
      ,val
      ,(format "Set for %s's setup block" (setup-get 'feature))))
  :documentation "Set the option NAME to VAL.
NAME is not the name of the option itself, but of the option with
the feature prefix."
  :debug '(sexp form)
  :repeatable t)
#+end_src

*** :global-set
Adress =:global= deprecation:
: The ‘:global’ macro for setup has been deprecated, please use ‘keymap-global-set’.
#+begin_src emacs-lisp
(setup-define :global-set
  (lambda (key command)
    `(keymap-global-set ,key #',command))
  :documentation "Globally bind KEY to COMMAND using keymap-global-set."
  :debug '(form sexp)
  :repeatable t)
#+end_src


*** :config
#+begin_src emacs-lisp
(setup-define :config
  (lambda (&rest body)
    `(with-eval-after-load ',(setup-get 'feature)
       ,@body))
  :documentation "Defer BODY until the current feature is actually loaded.
Analogous to use-package's :config — runs on first require, not on elpaca activation."
  :debug '(&rest form)
  :repeatable nil)
#+end_src

** provide footer
#+begin_src emacs-lisp
(provide '11xx-setup)
;;; 11xx-setup.el ends here
#+end_src



* init-no-littering.el: Keep user-emacs-directory clean
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/init-no-littering.el
:END:

#+begin_src emacs-lisp
(elpaca no-littering (require 'no-littering))
(elpaca-wait)

(when (fboundp 'startup-redirect-eln-cache)
  (startup-redirect-eln-cache
   (convert-standard-filename
    (expand-file-name  "eln-cache" no-littering-var-directory))))

(add-to-list 'native-comp-eln-load-path
             (convert-standard-filename
              (expand-file-name "eln-cache" no-littering-var-directory)))

(provide 'init-no-littering)
#+end_src

* init-backup-auto-save.el: Move back-up and auto-save files
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/init-backup-auto-save.el
:END:

Backup & auto-save
#+begin_seealso
- See
  + [[https://lucidmanager.org/productivity/manage-files-with-emacs/][manage-files-with-emacs]]
  + [[https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files/18330742#18330742][backup files config example]]
  + [[https://emacs.stackexchange.com/questions/60970/how-to-replace-focus-out-hook-with-after-focus-change-function-in-emacs-27/60971#60971][replacing focus-out-hook]]
  + [[https://superuser.com/questions/411982/emacs-changing-the-location-of-auto-save-files/437563#437563][Emacs: Changing the location of auto-save files#437563]]
  + [[https://superuser.com/questions/411982/emacs-changing-the-location-of-auto-save-files/412007#412007][Emacs: Changing the location of auto-save files#412007]]
#+end_seealso

#+begin_src emacs-lisp
(require '11xx-functions)

(defvar 11xx--backup-directory
  (expand-file-name "backups"
                    (expand-file-name "var" user-emacs-directory))
  "Custom backup-files directory.")

;; Auto-save directory variable
(defvar 11xx--auto-save-directory
  (expand-file-name "auto-save"
                    (expand-file-name "var" user-emacs-directory))
  "Custom auto-save files directory.")

(f/check-make-directory 11xx--backup-directory)
(f/check-make-directory 11xx--auto-save-directory)

;; ;; add random number to auto save file list
;; (defun f/auto-save-list-file-name-function ()
;;   (let ((basename (concat 11xx--auto-save-directory "/auto-save-list-"))
;;         (random-number (number-to-string (random))))
;;     (concat basename (substring random-number 0 8) "~")))
;; (setq auto-save-list-file-name-function #'f/auto-save-list-file-name-function)

(setopt backup-directory-alist `((".*" . ,11xx--backup-directory))
        auto-save-file-name-transforms `(("\\(?:[^/]*/\\)*\\(.*\\)" ,(concat 11xx--auto-save-directory "\\\\1") t))
        auto-save-list-file-prefix 11xx--auto-save-directory
        auto-save-list-file-name (concat 11xx--auto-save-directory "/auto-save-list")
        make-backup-files t    ; backup of a file the first time it is saved.
        backup-by-copying t    ; don't clobber symlinks
        version-control t      ; version numbers for backup files
        delete-old-versions t  ; delete excess backup files silently
        kept-old-versions 6    ; oldest versions to keep when a new numbered backup is made (default: 2)
        kept-new-versions 9    ; newest versions to keep when a new numbered backup is made (default: 2)
        auto-save-default t    ; auto-save every buffer that visits a file
        auto-save-timeout 10   ; number of seconds idle time before auto-save (default: 30)
        auto-save-interval 150) ; number of keystrokes between auto-saves (default: 300)

;; silence "Auto-saving..." messages on minibuffer
(advice-add 'do-auto-save :around
  (lambda (orig-fn &rest args)
    (let ((inhibit-message t))
      (apply orig-fn args))))

(provide 'init-backup-auto-save)
#+end_src
- *NOTE* about =.#filename@=: They're lock files and are meant to be
  alongside the file being edited until a save occurs.

  Instead, disable lock files (=.#file@=).
  + See https://emacs.stackexchange.com/a/78802.
  #+begin_src emacs-lisp
  (setopt create-lockfiles nil)
  #+end_src
  +Is this legacy stuff from the ancient times of shared terminals?+
  # [2024-02-14 Wed 11:00:23 -03] @ak


* 11xx-defaults.el: New defaults
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-defaults.el
:END:
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

** Emacs setup
- Notes:
  + *Modes not starting:* Probably due to them being local-buffer specific.
    See [[https://stackoverflow.com/questions/22968922/function-defined-in-emacs-does-not-start-automatically][Function defined in .emacs does not start automatically]].
  + *Describe Hooks:* Hooks are variables.
  + *Hook orders matters:* e.g. ~:with-mode~ options should have
    ~:hook-into~ macro /before/ ~:with-hook~.
  + *Use of lamba():* Usually the use of ~(lambda()...)~ around this
    config was tested and caused problems when not using it.

#+begin_src emacs-lisp
(setup emacs
  ;; Keybindings
  (:global-set
   "C-c C-/"          comment-region
   "C-c C-M-/"        uncomment-region
   "<remap> <mark-word>"  f/mark-whole-word
   ;; Local file variables
   "C-c a f v"        add-file-local-variable
   "C-c d f v"        delete-file-local-variable
   "C-c a f p"        add-file-local-variable-prop-line
   "C-c d f p"        delete-file-local-variable-prop-line
   ;; Custom functions
   ;; Text display
   "C-c C-M-t"  visual-line-mode
   "C-c M-t"    toggle-truncate-lines
   ;; Insert text
   "C-c i t" f/current-timestamp-insert

   "C-x C-z" org-set-property
   "C-z" org-set-property
   ;; [[https://www.emacswiki.org/emacs/WindowResize][EmacsWiki: Window Resize]] [2022-04-20 Wed 02:50:51]
   "C-S-<left>"   shrink-window-horizontally
   "C-S-<right>"  enlarge-window-horizontally
   "C-S-<down>"   shrink-window
   "C-S-<up>"     enlarge-window
   ;; Cursor
   ;; "C-M-d" backward-delete-char ; was down-list
   "C-M-d" delete-pair ; was down-list
   ;; "M-D"   backward-kill-word
   "M-D"   delete-pair
   ;; "M-h"          backward-delete-char ; was `mark-paragraph' global
   ;; "M-H"          backward-kill-word ; was `mark-paragraph' global, separate override may be necessary for local maps
   "M-." forward-list
   "M-," backward-list
   "C-M-." down-list ; up-list
   "C-M-," backward-up-list
   )

  ;; Enable disabled 'advanced' commands
  (:put-enable narrow-to-region
               narrow-to-page
               narrow-to-defun
               widen
               downcase-region)

  (add-function :after after-focus-change-function
                (lambda() (save-some-buffers t)))

  ;;; Minor modes
  ;; (:also-load mouse)
  ;; (xterm-mouse-mode 1) ;; xterm mouse support
  (save-place-mode 1)
  (delete-selection-mode 1) ; delete marked region with backspace

  ;; #manual-smartparens
  (electric-pair-mode 1)
  (electric-indent-mode 1))
#+end_src

- Show whitespace but disable in some modes
  + Also see [[org-dispatcher-disable-show-whitespace][Disable show-trailing-whitespace on Org Export Dispatcher]]
#+begin_src emacs-lisp
(setup whitespace
  (:hide-mode)
  (:hook-into prog-mode text-mode)
  (:option whitespace-style '(face tabs missing-newline-at-eof)
           show-trailing-whitespace t)
  ;; Disable `show-trailing-whitespace' in some modes:
  (:with-hook (special-mode-hook
               term-mode-hook
               vterm-mode-hook
               comint-mode-hook
               compilation-mode-hook
               minibuffer-setup-hook
               minibuffer-mode-hook
               calendar-mode-hook
               ;; embark-mode-hook
               eshell-mode-hook
               completion-list-mode-hook
               messages-buffer-mode-hook
               diff-mode-hook
               messages-buffer-mode-hook)
    (:hook (lambda() (setq-local show-trailing-whitespace nil)))))
#+end_src

- sexp movement
  #+begin_seealso
  - [[https://stackoverflow.com/questions/1771102/changing-emacs-forward-word-behaviour/2565961#2565961][emacs23 - Changing Emacs Forward-Word Behaviour - Stack Overflow]]
  - [[https://stackoverflow.com/questions/58300666/backward-same-syntax-in-emacs/58306071#58306071]["backward-same-syntax" in Emacs - Stack Overflow]]
  #+end_seealso
#+begin_src emacs-lisp
(add-hook 'elpaca-after-init-hook #'global-superword-mode)
#+end_src


#+begin_src emacs-lisp
(setup (:elpaca ace-window)
  ;; Prefixed with C-u swaps, see 'M-h f ace-window'
  (:global-set "M-o" ace-window)

  ;; https://github.com/abo-abo/ace-window?tab=readme-ov-file#aw-keys
  (setopt aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)
          aw-scope 'frame))

;; new remap format is "<remap> <what-to-remap>" #'my-function
(setup (:elpaca helpful)
  ;; Helpful.el
  (:global-set
   "<remap> <describe-function>" helpful-callable
   "<remap> <describe-command>" helpful-command
   "<remap> <describe-variable>" helpful-variable
   "<remap> <describe-key>" helpful-key
   "<remap> <describe-symbol>" helpful-symbol))

(setup (:elpaca which-key)
  ;; :defer 10
  (setopt which-key-idle-delay 2.0))


(setup (:elpaca jump-char)
  (:load-after kmacro) ; bc I only use this for macro-ing anyway

  (:global-set
   "C-c j f" jump-char-forward
   "C-c j b" jump-char-backward
   "C-c j m f" jump-char-forward-set-mark
   "C-c j m b" jump-char-backward-set-mark))

#+end_src

- Customize how mode indicators appear in the modeline
  + See [[https://www.gnu.org/software/emacs/manual/html_node/use-package/Delight.html][Delight (use-package User Manual)]].
#+begin_src emacs-lisp
(setup (:elpaca delight))
#+end_src

- Spell check
  + =ispell-program-name= should be automatically set when a supported program is
    installed
  #+begin_seealso
  [[https://endlessparentheses.com/ispell-and-org-mode.html][Making Ispell work with org-mode in Emacs · Endless Parentheses]]
  #+end_seealso

#+begin_src emacs-lisp
(setopt ispell-dictionary "en_GB")

(defun endless/org-ispell ()
  "Configure `ispell-skip-region-alist' for `org-mode'."
  (make-local-variable 'ispell-skip-region-alist)
  (add-to-list 'ispell-skip-region-alist '(org-property-drawer-re))
  (add-to-list 'ispell-skip-region-alist '("~" "~"))
  (add-to-list 'ispell-skip-region-alist '("=" "="))
  (add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_SRC" . "^#\\+END_SRC")))
(add-hook 'org-mode-hook #'endless/org-ispell)
#+end_src

** =custom.el= file
file to store ~customize~ options. This can be disabled but
~init.el~ will receive all generated code. It's also useful
for preventing Org Babel Tangle to override =Customize= changes. [[https://stackoverflow.com/questions/5052088/what-is-custom-set-variables-and-faces-in-my-emacs/5058752#5058752][src]]

Defined in Emacs setup
#+begin_src emacs-lisp
(setq custom-file (expand-file-name "custom.el" no-littering-var-directory))

(defun check-file-touch (file)
  "Check if FILE exists and create it if it doesn't.
It uses `make-empty-file' PARENTS argument 't'."
  (if (not (file-exists-p file))
      (make-empty-file file)))

(check-file-touch custom-file)

(load custom-file 'noerror 'nomessage)
#+end_src
** Async
[[https://github.com/jwiegley/emacs-async][jwiegley/emacs-async: Simple library for asynchronous processing in Emacs]]
#+begin_src emacs-lisp
(setup (:elpaca async))
#+end_src

*** =detached.el=
[[https://git.sr.ht/~niklaseklund/detached.el][~niklaseklund/detached.el - sourcehut git]]

Install the AUR =dtach= package, or the newer fork =dtach-ng=.
Note that by default =dired= don't provide the full path to the =dtach= command.
The full path is required.
#+begin_src emacs-lisp
(setup (:elpaca detached)
  (:global-set
   ;; Replace `async-shell-command' with `detached-shell-command'
   "<remap> <async-shell-command>" detached-shell-command
   ;; Replace `compile' with `detached-compile'
   "<remap> <compile>" detached-compile
   "<remap> <recompile>" detached-compile-recompile
   ;; Replace built in completion of sessions with `consult'
   "<remap> <detached-open-session>" detached-consult-session)
  (:option detached-show-output-on-attach t)
  (detached-init))
#+end_src

** TRAMP
Fix connecting to a GUIX system, e.g. when given the errors:
: Tramp: Opening connection nil for user@192.168.xx.xx using ssh...done
: File error: Couldn't find a proper `ls' command
: tramp-error: Couldn't find a proper `ls' command
#+begin_src emacs-lisp
(setup tramp
  (:require tramp)
  (add-to-list 'tramp-remote-path 'tramp-own-remote-path))
#+end_src
#+begin_quote
Basically, since Guix doesn't store =ls= in the normal FHS-like location
(it's not =/bin/ls=), TRAMP can't find it by default. There's a symbol
called =tramp-own-remote-path= that (I think) is supposed to use the
login shell's environment to grab a path and find the commands TRAMP
needs.

--- [[https://www.reddit.com/r/GUIX/comments/uco6fg/comment/i6c407x/][emacs multihop sudo fails with guix : r/GUIX]]
#+end_quote
# (Retrieved at [2024-11-12 Tue 01:14])

** desktop-save
Save state for session restoring
#+begin_src emacs-lisp
(setup desktop
  (:require)

  (defvar 11xx--daemon-name
    (let ((d (daemonp)))
      (cond
       ((stringp d) d)
       ((eq d t)   "default")
       (t           nil)))
    "Server name this Emacs instance is running as, or nil if not a daemon.
Mirrors `daemonp': a string for named daemons (--daemon=NAME), \"default\"
for unnamed (--daemon), nil for interactive sessions.")

  (when 11xx--daemon-name
    (setopt desktop-base-file-name (format ".emacs-%s.desktop" 11xx--daemon-name)
            desktop-base-lock-name (format ".emacs-%s.desktop.lock" 11xx--daemon-name)))

  (setopt desktop-dirname (expand-file-name "desktop/" no-littering-var-directory)
          desktop-auto-save-timeout 1
          desktop-save 'ask-if-new)
  (desktop-save-mode))
#+end_src

** eros: Overlay eval result (better C-x C-e)
#+begin_src emacs-lisp
(setup (:elpaca eros)
  (:load-after org-mode)
  (:hook-into org-mode)
  (setopt ;; eros-eval-result-prefix    "∷ "
           eros-eval-result-duration  'command
           eros-overlays-use-font-lock t))
#+end_src

** provide footer
#+begin_src emacs-lisp
(provide '11xx-defaults)
;;; 11xx-defaults.el ends here
#+end_src


* utf-8-default.el: Use UTF-8 for all character encoding
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/utf-8-default.el :noweb-ref utf-8-default
:END:
Encoding, pretty much anything other than strictly english ascii
writing requires a different encoding. So use UTF-8 as the
default encoding.
- See
  + [[http://xahlee.info/emacs/emacs/emacs_file_encoding.html][Emacs: Set Default File Encoding]]
  + [[https://stackoverflow.com/questions/20212703/problems-saving-file-with-unicode-characters/20564324#20564324][emacs - Problems saving file with Unicode characters - Stack Overflow]]
  + [[https://www.emacswiki.org/emacs/ChangingEncodings][EmacsWiki: Changing Encodings]]
  + [[https://emacs.stackexchange.com/questions/68647/automatically-change-encoding-of-process-buffers/68649#68649][shell - Automatically change encoding of process buffers - Emacs Stack Exchange]]
  + [[https://emacs.stackexchange.com/questions/19641/emacs-is-asking-me-for-a-coding-system-on-each-save][org mode - Emacs is asking me for a coding system on each save - Emacs Stack Exchange]]
  + [[https://stackoverflow.com/questions/20723229/how-to-reset-emacs-to-save-files-in-utf-8-unix-character-encoding/26401113#26401113][linux - How to reset emacs to save files in utf-8-unix character encoding? - Stack Overflow]]
  + [[https://skybert.net/craftsmanship/utf-8-for-the-impatient/][UTF-8 for the Impatient | skybert.net]]
# do this especially on Windows, else python output problem
#+begin_src emacs-lisp
(prefer-coding-system 'utf-8-unix)
(setopt x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING)
        default-process-coding-system '(utf-8-unix . utf-8-unix))

;; other than setting this one setting the others may be redundant.
(set-default-coding-systems 'utf-8-unix)

(set-buffer-file-coding-system 'utf-8-unix)
(set-clipboard-coding-system 'utf-8-unix)
(set-file-name-coding-system 'utf-8-unix)
(set-keyboard-coding-system 'utf-8-unix)
(set-selection-coding-system 'utf-8-unix)
(set-terminal-coding-system 'utf-8-unix)

(set-locale-environment "en.UTF-8")

(set-charset-priority 'unicode)

(provide 'utf-8-default)
#+end_src
# ;; (set-language-environment "UTF-8") ; maybe this is not for coding system :p
#
# ;; v-- maybe this is too much? keep cjk encoding by having this disabled.
# ;; (setq utf-translate-cjk-mode nil) ; disable CJK coding/encoding

To force LF UTF-8 on specific files, add a buffer or file local
variable with:
: M-: (setq-local buffer-file-coding-system 'utf-8-unix) RET
or
: M-x add-file-local-variable-prop-line RET coding RET utf-8 RET
or
: M-x add-file-local-variable RET coding RET utf-8 RET
# [2022-11-08 Tue 17:10:44 -03]

* 11xx-modes.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-modes.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src


** Add =modes= directory to Emacs path
Local mode-providing files
# [2022-04-27 Wed 07:19:42]
# [2026-04-07 Tue 05:50:12 -03] @ak
#+begin_src emacs-lisp
(add-to-list 'load-path (expand-file-name "modes" user-emacs-directory))
#+end_src

** Make shebang (#!) file executable when saved
[[https://youtu.be/764zoG1TxVk?t=1845][emacs early-init.el and general tips and tricks - YouTube]]

#+begin_src emacs-lisp
;; Make shebang (#!) file executable when saved
(add-hook 'after-save-hook 'executable-make-buffer-file-executable-if-script-p)
#+end_src

** Minor modes, Customisation, Hacks

*** Tree-Sitter Syntax Highlighting
[[https://emacs-tree-sitter.github.io/syntax-highlighting/][Tree-sitter Syntax Highlighting]]

- Emacs 29+, using =treesit=
  + [[https://git.savannah.gnu.org/cgit/emacs.git/tree/admin/notes/tree-sitter/starter-guide?h=feature/tree-sitter][starter-guide\tree-sitter\notes\admin - emacs.git - Emacs source repository]]
  + [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][How to Get Started with Tree-Sitter - Mastering Emacs]]
  + [[https://emacs.stackexchange.com/questions/78605/language-specific-tree-sitter-major-mode-wont-show-up][language specific tree-sitter major mode wont show up - Emacs Stack Exchange]]
  + use =treesit= instead of the third-party =tree-sitter= and:
    #+begin_quote
    Note that, just because you have installed a grammar, does /not/
    mean Emacs supports it. Someone still has to write the –
    admittedly, /way/ easier – syntax and indentation logic and all that
    good stuff.

    ----- [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][How to Get Started with Tree-Sitter - Mastering Emacs]]
    #+end_quote
    # (Retrieved at # [2024-03-16 Sat 07:03:10 -03] @ak

- Tree-Sitter supports Org-Mode code blocks since:
  + [[https://github.com/nvim-orgmode/orgmode/pull/139][Pull Request #139]].
  + [[https://github.com/nvim-orgmode/orgmode/issues/31][would it be possible to use treesitter in this · Issue #31 · nvim-orgmode/orgmode]]
  + [[https://www.masteringemacs.org/article/lets-write-a-treesitter-major-mode][Let's Write a Tree-Sitter Major Mode - Mastering Emacs]]

*NOTE*: =htmlize= uses different CSS selectors for =tree-sitter-hl-mode=
code highlighting, prefixed by something like
=org-tree-sitter-hl-faceX=, so CSS templetes that rely on normal
selectors may not work, causing exported code snippets to not be
colored by the stylesheet on the HTML file.
# [2022-04-25 Mon 05:44:00]

Additional Tree-Sitter content
- [[https://siraben.de11xx--2022/03/01/tree-sitter.html][How to write a tree-sitter grammar in an afternoon | siraben’s musings]]
  # [2022-04-28 Thu 16:46:45]

# #TODO moving to built-in `treesit' package
#+begin_src emacs-lisp
(add-to-list 'treesit-extra-load-path
             (expand-file-name "tree-sitter" user-emacs-directory))
#+end_src

*** Colour codes highlighting
#+begin_src emacs-lisp
(setup (:elpaca rainbow-mode)
  (:hook-into css-mode))
#+end_src

** Require split files
#+begin_src emacs-lisp
(require '11xx-modes-edit)
(require '11xx-modes-terminal)
(require '11xx-modes-langs)
(require '11xx-modes-special)
(require '11xx-modes-web)
#+end_src

** Edit Modes
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-edit.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** Systemd
Use [[https://github.com/pdbrown/systemd-mode][pdbrown's systemd-mode updated repo]], better for use with native-comp.
#+begin_src emacs-lisp
(setup (:elpaca systemd :host github :repo "pdbrown/systemd-mode"))
#+end_src
# :files ("*.txt" "systemd.el" (:exclude ".git"))

*** YAML
#+begin_src emacs-lisp
(elpaca yaml-mode)
(elpaca-wait)

;; considering `yaml-ts-mode' is already provided by Emacs
;; use `yaml-indent-line' with it.
(with-eval-after-load 'yaml-ts-mode
  (require 'yaml-mode)
  (add-hook 'yaml-ts-mode-hook
            (lambda ()
              (setq-local indent-line-function #'yaml-indent-line)
              (setq-local yaml-indent-offset 2)))

  (define-advice org-src-font-lock-fontify-block
    (:around (orig lang start end) my/yaml-strip-org-coderefs)
  "Prevent org code refs from breaking tree-sitter YAML fontification."
  (if (not (string-match-p (rx word-start "yaml") lang))
      (funcall orig lang start end)
    (let* ((coderef-re (rx (1+ blank)
                           "(ref:" (1+ (not (any " \t\n)"))) ")"
                           (* blank) eol))
           replacements)
      ;; Phase 1: swap (ref:...) for same-length spaces so TS sees valid YAML
      (with-silent-modifications
        (save-excursion
          (goto-char start)
          (while (re-search-forward coderef-re end t)
            (push (list (match-beginning 0)
                        (match-end 0)
                        (match-string 0))
                  replacements)
            (replace-match
             (make-string (- (match-end 0) (match-beginning 0)) ?\s)
             t t))))
      ;; Phase 2: fontify (TS sees clean YAML), then unconditionally restore
      (unwind-protect
          (funcall orig lang start end)
        (with-silent-modifications
          (save-excursion
            (pcase-dolist (`(,beg ,_end ,str) replacements)
              (goto-char beg)
              (delete-region beg (+ beg (length str)))
              (insert str)
              ;; faces on these positions are now from our spaces; override with comment
              (put-text-property beg (+ beg (length str))
                                 'face 'font-lock-comment-face)))))))))
#+end_src

*** PKGBUILD
#+begin_src emacs-lisp
(setup (:elpaca pkgbuild-mode)
  (add-hook 'pkgbuild-mode-hook (lambda() (flymake-mode -1))))
#+end_src

*** PowerShell
# [2024-01-14 Sun 13:58:20 -03:00] @winr58
#+begin_src emacs-lisp
(setup (:elpaca powershell))
#+end_src

*** Ansible
#+begin_src emacs-lisp
(setup (:elpaca ansible))
(setup (:elpaca ansible-vault))
(setup (:elpaca ansible-doc))
#+end_src

*** =yuck-mode=: Specifically for EWW's (bar) config file
#+begin_src emacs-lisp
(setup (:elpaca yuck-mode))
#+end_src

*** hyprlang/hyprland config language
#+begin_src emacs-lisp
(setup (:elpaca hyprlang-ts-mode)
  (:autoload hyprlang-ts-mode)
  (:match-file "*hyprland.conf"))
#+end_src

*** Picard
#+begin_src emacs-lisp
(elpaca (picard-mode :host codeberg
                     :repo "useless-utils/picard-mode")
  (use-package picard-mode
    :config
    (use-package picard-ts-mode
      :after picard-mode
      :if (treesit-available-p))))
#+end_src

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-edit)
;;; 11xx-modes-edit.el ends here
#+end_src

** Special
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-special.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** =sensitive-mode=: Disable backup files on sensitive files
wizard [[https://anirudhsasikumar.net/blog/2005.01.21.html][Disabling Backup and Auto-save in Emacs]],
src [[https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files/18330742#18330742][How do I control how Emacs makes backup files? - Stack Overflow]]
# [2022-11-11 Fri 03:15:47 -03]

to enable it in files use e.g.
: # -*- eval: (sensitive-mode 1); -*-
: // -*-mode:asciidoc; mode:sensitive-minor; fill-column:132-*-

#+begin_src emacs-lisp
(define-minor-mode sensitive-mode
  "For sensitive files like password lists.
It disables backup creation and auto saving.

With no argument, this command toggles the mode.
Non-null prefix argument turns on the mode.
Null prefix argument turns off the mode."
  ;; The initial value.
  :init-value nil
  ;; The indicator for the mode line.
  :lighter " Sensitive"
  ;; The minor mode bindings.
  :keymap nil
  ;; added keywords instead of deprecated positional arguments:
  ;; fix for "Warning: Use keywords rather than deprecated positional
  ;; arguments to `define-minor-mode'" # [2022-11-11 Fri 16:09:40 -03]
  ;; See the commits from [[https://github.com/purcell/emacs.d/issues/780][Use keywords rather than positional arguments to define-minor-mode · Issue #780 · purcell/emacs.d]]

  (if (symbol-value sensitive-mode)
      (progn
        ;; disable backups
        (set (make-local-variable 'backup-inhibited) t)
        ;; disable auto-save
        (if auto-save-default
            (auto-save-mode -1)))
                                        ;resort to default value of backup-inhibited
    (kill-local-variable 'backup-inhibited)
                                        ;resort to default auto save setting
    (if auto-save-default
        (auto-save-mode 1))))
#+end_src

or use a list:
#+begin_example emacs-lisp
(setq auto-mode-alist
 (append
  (list
   '("\\.\\(vcf\\|gpg\\)$" . sensitive-minor-mode)
   )
   auto-mode-alist))
#+end_example

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-special)
;;; 11xx-modes-special.el ends here
#+end_src

** Terminal modes
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-terminal.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

[[https://www.youtube.com/watch?v=wa_wZIuT9Vw&t=2126s][Emacs From Scratch #9 - Learn to Love the Terminal Modes - YouTube]]
# [2022-04-30 Sat 13:45:02]
*** =eshell=: Emacs Lisp shell
[[https://www.emacswiki.org/emacs/EshellAlias][EmacsWiki: Eshell Alias]]
# [2022-05-03 Tue 17:49:09]
#+begin_src emacs-lisp
;; 'eshell-output-filter-functions void variable means that eshell has to be
;; started once first.
(setup eshell (:elpaca eshell-syntax-highlighting)
       (:elpaca eshell-git-prompt)
       (setopt eshell-hist-ignoredups t
               eshell-scroll-to-bottom-on-input t
               eshell-history-size 10000
               eshell-buffer-maximum-lines 2048)
       (:with-hook eshell-first-time-mode-hook
         (:hook (lambda() (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)
                  (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)))))
#+end_src

*** eterm-256color
256color for =term-mode=
#+begin_src emacs-lisp
(setup term (:elpaca eterm-256color)
       (:option explicit-shell-file-name "bash")
       (:with-mode eterm-256color-mode
         (:hook-into term-mode)))
#+end_src

*** vterm
#+begin_src emacs-lisp
(setup (:elpaca multi-vterm))
#+end_src

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-terminal)
;;; 11xx-modes-terminal.el ends here
#+end_src

** Languages
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-langs.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** Haskell
#+begin_src emacs-lisp
(setup (:elpaca haskell-mode))
#+end_src
# (setup (:elpaca haskell-ts-mode)
#   (:disabled)
#   (:load-after haskell-mode)
#   ;; (:elpaca haskell-snippets) ; yasnippets
#   (:file-match "*.hs" "*.lhs")
#   (defun org-babel-execute:haskell-ts (body params)
#     "Execute a code block of `haskell-ts-mode' as `haskell-mode' with Org Babel."
#     (org-babel-execute:haskell body params))

#   ;; use haskell-ts-mode for "haskell" code-blocks
#   (add-to-list 'org-src-lang-modes '("haskell" . haskell-ts))

#   (defun haskell-setup-hs-initialize ()
#     "Insert default content into a new Setup.hs file."
#     (when (and (string= (buffer-name) "Setup.hs")
#                (= (buffer-size) 0)) ;; Only if the buffer is empty
#       (insert "import Distribution.Simple\nmain = defaultMain\n")
#       (save-buffer)))
#   (add-hook 'find-file-hooks #'haskell-setup-hs-initialize)

#   (:with-mode haskell-cabal-mode
#     (:file-match "stack.yaml" "package.yaml"))

#   ;; hoogle
#   (setopt haskell-hoogle-port-number "4141")

#   (setopt haskell-ts-use-indent nil)
#   (:hook haskell-indentation-mode)
#   )

*** C
#+begin_src emacs-lisp
(setup cc-mode
  (setopt c-default-style '((java-mode . "java")
                            (awk-mode  . "awk")
                            (other     . "k&r"))
          c-basic-offset 2))
#+end_src

#+begin_src emacs-lisp
(defun org-babel-execute:c-ts (body params)
  "Execute a block of `c-ts-mode' as `c-mode' with Org Babel."
  (org-babel-execute:C body params))
#+end_src

**** TODO COMMENT Compile helper functions
# #TODO update # [2024-03-18 Mon 22:34:43 -03] @ak
# lol [2026-04-07 Tue 05:39:52 -03] @ak
***** Compile current C file
The =(compile)= function already defines the workin directory as the same
as the buffer's file location.
#+begin_src emacs-lisp
(defun f/gcc-compile-current-file ()
  "Compile current file with gcc.

Get the current buffer's filename with the function `buffer-file-name' and
using the function `compile' build a command like:
   \"gcc -o filename.c.out /path/to/filename.c\""
  (interactive)
  (defvar-local fullpath-filename (file-truename (buffer-file-name))
    "Get filename of the current buffer")
  (let ((filename (file-name-nondirectory fullpath-filename)))
    (if (string= (file-name-extension filename) "c")
        (compile (concat "gcc -o " (shell-quote-argument
                                    (file-name-base filename)) ".out"
                                    " "
                                    (shell-quote-argument filename))))
    (if (string= (file-name-extension filename) "cpp")
        (compile (concat "g++ -o " (shell-quote-argument
                                    (file-name-base filename)) ".out"
                                    " "
                                    (shell-quote-argument filename)))))
  (message (concat "\"" fullpath-filename ".out\"")))
#+end_src

****** Hide compilation info buffer
wizard [[https://emacs.stackexchange.com/questions/62/hide-compilation-window/110#110][Hide *compilation* window - Emacs Stack Exchange]]
# [2022-04-25 Mon 05:32:31]
It continues open as =*compilation*=
#+begin_src emacs-lisp
(add-hook 'compilation-finish-functions
          (lambda (buf strg)
            (let ((win  (get-buffer-window buf 'visible)))
              (when win (delete-window win)))))
#+end_src

***** Floating terminal
#+begin_src emacs-lisp
(defun f/run-executable-in-floating-terminal (exe-file)
  "Open Alacritty with class=float and run executable EXE-FILE."
  (interactive)
  (message "Opening executable file: " exe-file ".")
  (shell-command
   (concat
    "alacritty --class=float"
    " "
    "--option window.dimensions.columns=\"${w:-80}\""
    " "
    "window.dimensions.lines=\"${h:-20}\""
    " "
    "--command sh -c " (shell-quote-argument
                        (concat exe-file " | bat --paging=always")))))
;; removed --hold bc bat paging holds the terminal until othewise [2022-04-24 Sun 14:41:04]
#+end_src

#+RESULTS:
: f/run-executable-in-floating-terminal
***** C compile current file and run in the terminal
#+begin_src emacs-lisp
(defun f/c-comp-and-run()
  "Compile current C/C++ file and run it in the terminal."
  (interactive)
  (f/run-executable-in-floating-terminal
   ;; (f/gcc-compile-current-file v-local/compiled-file-out)
   (f/gcc-compile-current-file)
   ))
#+end_src

***** keybindings for compile functions
[[https://tr.wikibooks.org/wiki/Emacs/Windows_%C4%B0%C3%A7in_Emacs_Dosyas%C4%B1][Emacs/Windows İçin Emacs Dosyası - Vikikitap: Özgür kütüphane]]
# ;; keybindings for all supported languages.  We can put these in
# ;; c-mode-base-map because c-mode-map, c++-mode-map, objc-mode-map,
# ;; java-mode-map, and idl-mode-map inherit from it.

[[https://stackoverflow.com/questions/34067495/binding-a-key-in-c-c-mode-only][emacs - Binding a key in C/C++ mode only? - Stack Overflow]]
# [2022-04-23 Sat 19:08:13]

Using =define-key= inside a hook instead of =setup='s =:bind= because =c-mode= seems
to conflict with it.
#+begin_src emacs-lisp
(with-eval-after-load 'cc-mode
  (define-key c-mode-base-map (kbd "C-c '") #'f/c-comp-and-run)
  (define-key c-mode-base-map (kbd "C-c C-c") #'f/c-comp-and-run))
#+end_src

*** Rust
#+begin_seealso
- [[https://github.crookster.org/my-emacs-rust-language-config/][My Emacs Rust Language Config | David Crook]]
- [[https://robert.kra.hn/posts/rust-emacs-setup/][Configuring Emacs for Rust development | Robert Krahn]]
#+end_seealso
# [2022-05-03 Tue 17:50:00]

#+begin_src emacs-lisp :tangle no
(setup (:elpaca rust-mode))
#+end_src
# theres one called rustic

Install Org Babel rust library:

*NOTE*: this requires the program =rust-script= (available in standard Arch repos).
#+begin_src emacs-lisp
(setup (:elpaca ob-rust)
  (:load-after org))
#+end_src

**** Rust Object Notation (ron)
- Used by
  + [[https://github.com/mierak/rmpc][mierak/rmpc]] \\
    /"A configurable, terminal based Media Player Client with album art
    support via various terminal image protocols."/
#+begin_src emacs-lisp
(setup ron-mode
  (:elpaca ron-mode)
  (:autoload ron-mode)
  (:match-file "*.ron"))
#+end_src


*** Lua
#+begin_src emacs-lisp
(setup (:elpaca lua-mode))
#+end_src

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-langs)
;;; 11xx-modes-langs.el ends here
#+end_src

** Web
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/11xx-modes-web.el
:END:

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** HTML
[[https://docs.emmet.io/cheat-sheet/][Emmet Cheat Sheet]] [2022-04-02 Sat 15:54:53]
**** Emmet
#+begin_src emacs-lisp
(setup (:elpaca emmet-mode)
  ;; (:with-map emmet-mode-keymap
  ;;     (:bind ))
  (:hook-into html-mode))
#+end_src

*** CSS/SCSS
#+begin_src emacs-lisp
(setup css
  (:option css-indent-offset 2))
#+end_src

*** Web-mode
[[https://timunkert.net/2021/12/emacs-setup.html][Emacs Setup for my Front-End Development Course with Calculus]] [2022-04-20 Wed 01:02:24]
[[https://github.com/glynnforrest/emacs.d/blob/master/site-lisp/setup-web-mode.el][emacs.d/setup-web-mode.el at master · glynnforrest/emacs.d]] [2022-04-20 Wed 01:02:45]


#+begin_src emacs-lisp
(setup (:elpaca web-mode)
  ;; (add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.php\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.scss\\'" . web-mode))
  ;; (add-to-list 'auto-mode-alist '("\\.css\\'" . web-mode))
  ;; (:hook-into html-mode css-mode)
  (:hook (:option web-mode-markup-indent-offset 2
                  web-mode-css-indent-offset 2
                  web-mode-code-indent-offset 2
                  web-mode-markup-indent-offset 2
                  web-mode-style-padding 2
                  web-mode-script-padding 2
                  web-mode-enable-auto-closing t
                  web-mode-enable-auto-opening t
                  web-mode-enable-auto-pairing t
                  web-mode-enable-auto-indentation t)))
#+end_src

*** Javascript
Javascript related packages
#+begin_src emacs-lisp
(setup (:elpaca typescript-mode)
  (:option typescript-indent-level 2)
  (:hook-into js-mode))
#+end_src

*** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes-web)
;;; 11xx-modes-web.el ends here
#+end_src

** provide footer
#+begin_src emacs-lisp
(provide '11xx-modes)
;;; 11xx-modes.el ends here
#+end_src


* 11xx-functions.el: Utility functions
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-functions.el
:END:

#+begin_src emacs-lisp
<<11xx-functions-el>>

(provide '11xx-functions)
#+end_src

** Function definitions
:PROPERTIES:
:header-args:emacs-lisp: :noweb-ref 11xx-functions-el
:END:
*** Electric modes
[[https://www.emacswiki.org/emacs/ElectricPair][EmacsWiki: Electric Pair]]
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/Auto_002dIndentation.html][24.7 Automatic indentation of code]]

Electric pairs are like when a open parenthesis is inserted and the
closing one is inserted automatically.

*** Mark whole work
#wizard src [[https://emacs.stackexchange.com/questions/35069/best-way-to-select-a-word/35072#35072][mark - Best way to select a word - Emacs Stack Exchange]]

=mark-whole-word=, to replace the built-in =mark-word= function.
| M-@ | use =mark-whole-word= function |

#+begin_src emacs-lisp
(defun f/mark-whole-word (&optional arg allow-extend)
  "Like `mark-word', but select whole words and skips over whitespace.
If you use a negative prefix ARG then select words backward.
Otherwise select them forward.

If cursor starts in the middle of word then select that whole word.

If there is whitespace between the initial cursor position and the
first word (in the selection direction), it is skipped (not selected).

If the command is repeated or the mark is active, select the next NUM
words, where NUM is the numeric prefix argument ARG.  (Negative NUM
selects backward.)

If second argument ALLOW-EXTEND is nil don't expand selection across words.
See `mark-word' for more."
  (interactive "P\np")
  (let ((num  (prefix-numeric-value arg)))
    (unless (eq last-command this-command)
      (if (natnump num)
          (skip-syntax-forward "\\s-")
        (skip-syntax-backward "\\s-")))
    (unless (or (eq last-command this-command)
                (if (natnump num)
                    (looking-at "\\b")
                  (looking-back "\\b")))
      (if (natnump num)
          (left-word)
        (right-word)))
    (mark-word arg allow-extend)))
#+end_src

*** Use tabs for indentation if needed
See [[https://www.emacswiki.org/emacs/NoTabs#h5o-1][EmacsWiki: No Tabs]]
#+begin_src emacs-lisp
(defun f/infer-indentation-style ()
  "Compare number of spaces and tabs and define `indent-tabs-mode' to t or nil.

If the current buffer or file has more tabs than spaces,
set `indent-tabs-mode' to t; if it has more spaces than tabs, set it to nil;
and if inconclusive, use current `indent-tabs-mode'."
  (interactive)
  (let ((space-count (how-many "^  " (point-min) (point-max)))
        (tab-count (how-many "^\t" (point-min) (point-max))))
    (if (> space-count tab-count) (setq indent-tabs-mode nil))
    (if (> tab-count space-count) (setq indent-tabs-mode t))))
(add-hook 'prog-mode-hook #'f/infer-indentation-style)
#+end_src

*** Insert current timestamp
#+begin_src emacs-lisp
(defun f/current-timestamp-format ()
  "Return current timestamp and hostname in a formatted string."
  (concat "[" (format-time-string "%Y-%m-%d %a %H:%M:%S %Z" (current-time)) "] @" (system-name)))

;;;###autoload
(defun f/current-timestamp-insert ()
  "Insert the current timestamp and hostname in a formatted string as a comment."
  (interactive)
  (let ((str (f/current-timestamp-format))
        (start-point (point)))
    (insert str)
    (set-mark start-point)
    (comment-region (region-beginning) (region-end))))
;; [2024-08-28 Wed 03:14:39 -03] @ak
;; # [2023-12-10 Sun 01:33:12 -03:00] @winr58
#+end_src

*** Kill matching lines
[[https://www.emacswiki.org/emacs/KillMatchingLines][EmacsWiki: Kill Matching Lines]]
# [2022-04-21 Thu 01:08:16]
Delete lines with matching string and send them to killring
#+begin_src emacs-lisp :results code
(defun f/kill-matching-lines (regexp &optional rstart rend interactive)
  "Kill lines containing matches for REGEXP.

Second and third arg RSTART and REND specify the region to operate on.
When calling this function from Lisp, you can pretend that it was
called interactively by passing a non-nil INTERACTIVE argument.
See `flush-lines' or `keep-lines' for behavior of this command.

If the buffer is read-only, Emacs will beep and refrain from deleting
the line, but put the line in the kill ring anyway.  This means that
you can use this command to copy text from a read-only buffer.
\(If the variable `kill-read-only-ok' is non-nil, then this won't
even beep.)"
  (interactive
   (keep-lines-read-args "Kill lines containing match for regexp"))
  (let ((buffer-file-name nil)) ;; HACK for `clone-buffer'
    (with-current-buffer (clone-buffer nil nil)
      (let ((inhibit-read-only t))
        (keep-lines regexp rstart rend interactive)
        (kill-region (or rstart (line-beginning-position))
                     (or rend (point-max))))
      (kill-buffer)))
  (unless (and buffer-read-only kill-read-only-ok)
    ;; Delete lines or make the "Buffer is read-only" error.
    (flush-lines regexp rstart rend interactive)))
#+end_src

*** Check if directory exists and create it if not
#+begin_src emacs-lisp :results code
(defun f/check-make-directory (dir)
  "Check if DIR exists and create it if it doesn't.

It uses `make-directory' PARENTS argument 't'."
  (if (not (file-exists-p dir))
      (make-directory dir t)))
#+end_src

*** Return XDG home directories
- =$XDG_BIN_HOME=
  #+begin_src emacs-lisp
(defun xdg-bin-home ()
  "Return the base directory for user specific executable files."
  (xdg--dir-home "XDG_BIN_HOME" "~/.local/bin"))
  #+end_src

- =$XDG_STATE_HOME=
  #+begin_src emacs-lisp
(defun xdg-state-home ()
  "Return the base directory for user specific log files."
  (xdg--dir-home "XDG_STATE_HOME" "~/.local/state"))
  #+end_src

*** Return file contents as string
#+begin_src emacs-lisp
(defun f/read-file-contents (file-path)
  "Read the contents of the file at FILE-PATH and return it as a string."
  (with-temp-buffer
    (insert-file-contents file-path)
    (buffer-string)))
#+end_src

*** Unfill paragraph
[[https://www.emacswiki.org/emacs/UnfillParagraph][EmacsWiki: Unfill Paragraph]]
# [2023-06-23 Fri 13:28:42 -03]
#+begin_src emacs-lisp
    ;;; Stefan Monnier <foo at acm.org>. It is the opposite of fill-paragraph
(defun unfill-paragraph (&optional region)
  "Takes a multi-line paragraph and makes it into a single line of text."
  (interactive (progn (barf-if-buffer-read-only) '(t)))
  (let ((fill-column (point-max))
        ;; This would override `fill-column' if it's an integer.
        (emacs-lisp-docstring-fill-column t))
    (fill-paragraph nil region)))

;; Handy key definition
(define-key global-map "\M-Q" 'unfill-paragraph)
#+end_src

*** Filter any matching list item from a list
# ;; from chatgpt: function for filtering items from a list using a list
#+begin_src emacs-lisp
(defun filter-list-any (source-list filter-list)
  "Filter out items from SOURCE-LIST that are found in FILTER-LIST."
  (let ((hash-table (make-hash-table :test 'equal))
        result)
    ;; Populate the hash table with elements from the filter list
    (dolist (item filter-list)
      (puthash item t hash-table))
    ;; Build the result list by filtering out items in the hash table
    (dolist (item source-list)
      (unless (gethash item hash-table)
        (push item result)))
    ;; The result list is built in reverse order, so reverse it
    (nreverse result)))
#+end_src

*** Filter list items that match any prefix from a list
#+begin_src emacs-lisp
(defun filter-list-any-string-prefix (source-list filter-list)
  "Filter out items from SOURCE-LIST that match any prefix in FILTER-LIST.

Example:

   (filter-list-any-string-prefix
     '(\"--fruit=banana\" \"orange\" \"cherry\" \"--veggie=potato\")
     '(\"--fruit\" \"--veggie\"))
   => '(\"orange\" \"cherry\")"
  (let (result)
    (dolist (item source-list)
      (unless (seq-some
               (lambda (prefix)
                 (string-prefix-p prefix item))
               filter-list)
        (push item result)))
    (nreverse result)))
#+end_src
# (filter-list-any-prefix '("--fruit=banana" "orange" "cherry" "--veggie=potato") '("--fruit" "--veggie"))

*** Platform check
Define macro for checking if =system-type= is =type=, if so, evaluate
body.
- [[https://stackoverflow.com/questions/1817257/how-to-determine-operating-system-in-elisp/26137517#26137517][emacs - How to determine operating system in elisp? - Stack Overflow]].
#+begin_src emacs-lisp
(defmacro with-system (type &rest body)
  "Evaluate BODY if `system-type' equals TYPE."
  (declare (indent defun))
  `(when (eq system-type ',type)
     ,@body))
#+end_src
# around # [2023-12-10  01:20:49 -03] @winr58
Usage
#+begin_example
(with-system gnu/linux
  (message "Free as in Freedom!"))
#+end_example

*** Replace alist item
like =add-to-list= but replaces item
#+begin_src emacs-lisp
(cl-defun add-or-replace-to-alist (list-var element &key append prepend)
  "Add or replace ELEMENT or a list of ELEMENTS in the alist stored in LIST-VAR.

LIST-VAR should be a symbol whose value is a proper alist.
ELEMENT may be a single alist entry (a list or cons whose CAR is the lookup key)
or a list of such entries.  If multiple entries are given, each is merged
individually rather than nesting.

By default, new entries are prepended.  Use :append to add at the end,
or :prepend to force prepending (it overrides :append).

Returns the updated alist value (like 'add-to-list').  Also echoes a
message indicating how many entries were added or replaced.

Arguments:
  LIST-VAR   Symbol naming the target alist variable.
  ELEMENT    A single entry (list or cons) or a list of entries.
  ':append'   If non-nil, append new entries.
  `:prepend'  If non-nil, prepend new entries.

Examples:
    ;; Single entry - replaces if key exists, adds if not
    (setq servers '((\"prod\" . \"192.168.1.10\") (\"dev\" . \"192.168.1.20\")))
    (add-or-replace-to-alist 'servers '(\"prod\" . \"10.0.0.100\"))
    ;; => ((\"prod\" . \"10.0.0.100\") (\"dev\" . \"192.168.1.20\"))

    ;; Multiple entries with :append
    (add-or-replace-to-alist
    'auto-mode-alist
    '((\"\\.tsx\\'\" . typescript-mode)
    (\"\\.vue\\'\" . vue-mode))
    :append t)"
  (let ((count 0)
        updated)
    ;; Handle a list of entries recursively
    (cl-labels ((process-entry (entry)
                  (let* ((key   (car entry))
                         (alist (symbol-value list-var))
                         (found (assoc key alist)))
                    ;; remove any old entry
                    (setq alist (cl-remove-if (lambda (old)
                                                (equal (car old) key))
                                              alist))
                    ;; insert
                    (setq alist
                          (cond
                           (prepend  (cons entry alist))
                           (append   (append alist (list entry)))
                           (t        (cons entry alist))))
                    ;; update var, bump counter
                    (set list-var alist)
                    (cl-incf count)
                    alist)))
      (if (and (listp element)
               element
               (cl-every (lambda (e) (and (listp e)
                                          (not (keywordp (car e)))))
                         element))
          (dolist (e element)
            (setq updated (process-entry e)))
        (setq updated (process-entry element))))
    (message "add-or-replace-to-alist: %d entr%s %s"
             count
             (if (> count 1) "ies were" "y was")
             (if append "appended/replaced." "prepended/replaced."))
    updated))
#+end_src


* 11xx-org.el: Org Mode
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-org.el
:END:

#+begin_src emacs-lisp
<<11xx-org-setup>>

(provide '11xx-org)
#+end_src


** Org setup
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-org-setup :tangle no
:END:

- See:
  + [[https://www.youtube.com/watch?v=VcgjTEa0kU4][Emacs From Scratch #5 - Org Mode Basics]]
  + [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org#auto-show-markup-symbols][Auto-show Markup Symbols]]
  + [[https://stackoverflow.com/questions/10969617/hiding-markup-elements-in-org-mode/10970665#10970665][Hiding markup elements in org-mode]]
  + [[https://emacs.stackexchange.com/questions/50216/org-mode-code-block-parentheses-mismatch/68321#68321][org babel - org-mode code block parentheses mismatch - Emacs Stack Exchange]]
    # [2022-05-14 Sat 20:54:33]

#+begin_src emacs-lisp
(setq org-modules '(ol-info ol-docview ol-doi))

(require '11xx-org-functions)
;; (setup org
;;   ;; Disable angle bracket syntax highlighting/matching
;;   (:hook (lambda()
;;            (modify-syntax-entry ?< "." org-mode-syntax-table)
;;            (modify-syntax-entry ?> "." org-mode-syntax-table))))

(setup (:elpaca org-contrib)
  (:load-after org)
  (require 'org-eldoc) ; shows inherited code block properties
  )

(setup org
  (:with-map org-mode-map
    (:bind
     "C-c C-;" org-babel-repeat-previous-src-block
     "C-M-p" org-previous-visible-heading ; was `backward-list'
     "C-M-n" org-next-visible-heading ; was `forward-list'
     "C-c o t l" org-toggle-link-display
     ;; Meta indentation
     "M-F" org-metaright
     "M-B" org-metaleft
     "M-P" org-metaup
     "M-N" org-metadown
     "C-c o p" org-kill-full-outline-path))

  ;; [[https://orgmode.org/manual/Activation.html][src]]
  ;; Enable Org-mode commands to be available anywhere.
  (:global-set
   "C-c o l" org-store-link
   "C-c o a" org-agenda
   "C-c o c" org-capture)

  ;; Move this to file local
  (org-babel-do-load-languages
   'org-babel-load-languages
   (append org-babel-load-languages
           '((haskell t)
             ;; (async   . t) ; from ob-async
             (shell   . t)
             (C       . t))))
  ;; Disable angle bracket syntax highlighting/matching
  (add-hook 'org-mode-hook
            (lambda()
              (modify-syntax-entry ?< "." org-mode-syntax-table)
              (modify-syntax-entry ?> "." org-mode-syntax-table)))
  ;; Additional templates for `org-insert-structure-template'
  (dolist (begin
           '(;; code
             ("sh" . "src shell")
             ("el" . "src emacs-lisp")
             ("py" . "src python")
             ("js" . "src javascript")
             ("css" . "src css")
             ("cc" . "src conf")
             ("hs" . "src haskell")
             ("sd" . "src systemd")
             ("y" . "src yaml")
             ;; org special
             ("sa" . "seealso")
             ))
    (add-to-list 'org-structure-template-alist begin))

  (setopt
   org-edit-src-content-indentation 0
   org-adapt-indentation nil
   org-ellipsis " ▾"
   org-babel-default-header-args:emacs-lisp '((:lexical . yes))
   org-image-actual-width nil
   org-src-window-setup 'current-window)

(setup (:elpaca org-bulletproof)
  (:load-after org)
  (:hook-into org-mode))
#+end_src

[[https://github.com/daviwil/emacs-from-scratch/blob/master/Emacs.org#center-org-buffers][Emacs From Scratch/Emacs.org#Center Org Buffers]].
#+begin_src emacs-lisp
(setup (:elpaca visual-fill-column)
  (:load-after org)
  (:global-set "C-c d c" visual-fill-column-mode)
  (setopt visual-fill-column-width 130 ; `display-fill-column-indicator-mode's width
          visual-fill-column-center-text t))
#+end_src

# auto generate/export markdown version of the current org file, GitHub-flavored
# ;; usage in local file variables: `eval: (add-hook 'before-save-hook #'org-gfm-export-to-markdown nil t)'
# (setup (:elpaca ox-gfm)
#   (:load-after org))
#
# ;; (:with-mode org-num-mode
# ;;   (:load-after org)
# ;;   (:hook-into org-mode))


*** Disable show-trailing-whitespace on Org Export Dispatcher
Hack for customizing the "Org Export Dispatch" buffer, the one triggered
with =C-c C-e=.
- See
  [[https://emacs.stackexchange.com/questions/48490/how-to-change-font-size-only-for-the-buffer-org-export-dispatcher][How to change font size only for the buffer *Org Export Dispatcher*? - Emacs Stack Exchange]]
  # #masterwizard

#+NAME: org-dispatcher-disable-show-whitespace
#+begin_src emacs-lisp
(defun f/org-export-dispatch-disable-whitespace-mode (&rest args)
  "Disable `whitespace-mode' for the Org Export Dispatch Buffer."
  (let ((buf (get-buffer "*Org Export Dispatcher*")))
    (when buf
      (with-current-buffer buf
        (setq-local show-trailing-whitespace nil)))))

(advice-add 'org-export--dispatch-action
            :before #'f/org-export-dispatch-disable-whitespace-mode)
#+end_src

*** org-appear
Make syntax markers like ~=word=~ or =~word~= be hidden normally and only
appear when hovered.
#+begin_src emacs-lisp
(setup (:elpaca org-appear)
  (:load-after org)
  ;; Toggle for links display set in (setup org)
  (setopt org-appear-autolinks 'just-brackets) ; nil is default
  (setopt org-hide-emphasis-markers t) ; needs to be t
  (:hook-into org-mode))
#+end_src

*** Prettify Org Mode
#+begin_src emacs-lisp
(setup (:elpaca org-modern)
  (setopt org-modern-block-fringe nil)
  (global-org-modern-mode))
#+end_src

*** org-transclusion
aka literate (?hopefully)
- [[https://github.com/nobiot/org-transclusion/][nobiot/org-transclusion: Emacs package to enable transclusion with Org Mode]]
- [[https://www.youtube.com/watch?v=6U9wG-pf-aQ][Assembling Org Mode Files with Transclusion - System Crafters Live! - YouTube]]

#+begin_src emacs-lisp
(setup (:elpaca org-transclusion)
  (:with-map org-mode-map
    (:bind "C-c o t a" org-transclusion-add
           "C-c o t A" org-transclusion-add-all
           "C-c o t r" org-transclusion-remove)))
#+end_src

*** Export & Publish

**** Export
- [[https://stackoverflow.com/questions/8395036/make-org-ignore-underscores-when-exporting-to-html][emacs - make Org ignore underscores when exporting to HTML - Stack Overflow]]
#+begin_src emacs-lisp
(setopt org-export-with-sub-superscripts nil ; interpret "_" and "^" for export.
        org-html-html5-fancy t
        org-export-in-background nil ; export async default: Use 'M-x org-export-stack' to display current processes:
        org-html-validation-link "" ; remove validade xml
        )
#+end_src

**** htmlize
- See
  + [[https://github.com/hniksic/emacs-htmlize][GitHub - hniksic/emacs-htmlize: Convert buffer text and decorations to HTML.]]
  + [[https://emacs.stackexchange.com/questions/3374/set-the-background-of-org-exported-code-blocks-according-to-theme/3512#3512][org mode - Set the background of org-exported <code> blocks according to theme - Emacs Stack Exchange]]
  + [[https://melpa.org/#/htmlize][htmlize - MELPA]]
#+begin_src emacs-lisp
(setup (:elpaca htmlize)
  (setopt org-html-head-include-default-style nil
          org-html-htmlize-output-type 'css ; classes
          htmlize-html-charset "UTF-8"
          htmlize-face-overrides '(whitespace-missing-newline-at-eof
                                   (:foreground nil :background nil))))
#+end_src
- For supported html charsets see
  + [[https://help.hcltechsw.com/dom_designer/9.0.1/appde11xx--LSAZ_APPENDIX_E_MIME_CHARSET_NAMES.html][MIME Charset Names]]
  + [[https://www.w3schools.com/charsets/][HTML Character Sets]]
  + [[https://en.wikipedia.org/wiki/Character_encodings_in_HTML][Character encodings in HTML - Wikipedia]]
- Notes:
  + The package =htmlize= is also capable of exporting normal buffers as
    HTML, but here it's mostly used for Org Mode exports.
  + Also the face of =whitespace-missing-newline-at-eof= may show up at
    the end of code blocks as a yellow square. To fix it unset the
    face e.g.:
    : (setq htmlize-face-overrides '(whitespace-missing-newline-at-eof (:foreground nil :background nil)))

**** GitHub Markdown
- [[https://codeberg.org/useless-utils/org-stable-ids][useless-utils/org-stable-ids: Human-readable ASCII slug IDs for Org headings and export - Codeberg.org]]
#+begin_src emacs-lisp
(setup (:elpaca ox-gfm))

(elpaca (ox-md-title :host github
                     :repo "jeffkreeftmeijer/ox-md-title.el")
  (require 'ox-md-title))

(defun readme-to-markdown (filename &optional confirm-overwrite)
  "Export the current Org buffer to a Markdown file named FILENAME.
Alternative version using display-buffer-overriding-action for cleaner approach."
  (interactive
   (list (read-file-name "Export markdown to file: "
                         nil nil nil
                         (concat (file-name-sans-extension
                                  (or (buffer-file-name)
                                      (buffer-name)))
                                 ".md"))
         current-prefix-arg))

  (unless (derived-mode-p 'org-mode)
    (user-error "This function only works in Org mode buffers"))

  ;; Check for file existence and confirm if requested
  (when (and confirm-overwrite (file-exists-p filename))
    (unless (yes-or-no-p (format "File %s exists. Overwrite? " filename))
      (user-error "Export cancelled")))

  ;; Save current state
  (let ((original-buffer (current-buffer))
        (make-backup-files nil)
        (original-display-action display-buffer-overriding-action)
        export-buffer)

    ;; Temporarily set display-buffer to not show any buffers
    (setq display-buffer-overriding-action
          '((lambda (buffer alist)
              ;; Return the buffer without displaying it
              buffer)
            . nil))

    (unwind-protect
        (save-window-excursion
          ;; Add the markdown title
          (org-md-title-add)

          ;; Export to buffer (silently)
          (let ((org-md-title t))
            (setq export-buffer (org-gfm-export-as-markdown)))

          ;; Write to file
          (with-current-buffer export-buffer
            (write-region (point-min) (point-max) filename nil 'no-message))

          (message "Exported to %s" filename))

      ;; Restore original display action and cleanup
      (setq display-buffer-overriding-action original-display-action)
      (when (and export-buffer (buffer-live-p export-buffer))
        (kill-buffer export-buffer)))))

(defun readme-org-to-readme-md ()
  (interactive)
  (readme-to-markdown "README.md"))


(elpaca (org-stable-ids :host codeberg :repo "useless-utils/org-stable-ids")
  (use-package org-stable-ids
    :init
    (keymap-global-set "C-c o i" #'org-stable-ids-get-create)
    :config
    (org-stable-ids-enable)))
#+end_src


***** =ox-html-template.el=: Custom output export HTML with template support
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/ox-html-template.el :noweb-ref dummy
:END:

# Custom TOC position
#+begin_src emacs-lisp
;;; ox-html-template.el --- Org -> HTML via external template  -*- lexical-binding: t; -*-

;; Emacs 30+ focused exporter backend using a user-editable template file.
;; Features:
;;  - Uses an external template with placeholders: {{HEAD}}, {{TITLE}},
;;    {{PREAMBLE}}, {{TOC}}, {{CONTENT}}, {{POSTAMBLE}}
;;  - Generates a single, predictable TOC with both `table-of-contents` and
;;    `text-table-of-contents` ids, avoids mutating the original INFO plist,
;;    and reuses the parse tree for performance.
;;  - Conditional preamble/postamble wrappers (omitted when empty).
;;  - Adds C-c C-e h 5 menu entry for interactive export.
;;  - Includes a publish wrapper that suppresses the usual fontification/htmlize messages.

;;; Commentary:
;; Drop this file into your `load-path` and (require 'ox-html-template).
;; Configure `org-html-template-file' to point to your HTML template file
;; (or leave nil to use the built-in default).
;;
;; Template placeholders (order matters; change `org-html-template-placeholders`
;; if you use a different layout):
;;   {{HEAD}} {{TITLE}} {{PREAMBLE}} {{TOC}} {{CONTENT}} {{POSTAMBLE}}
;;
;; Example template snippet:
;; <!doctype html>
;; <html lang="en">
;; <head>
;; {{HEAD}}
;; <title>{{TITLE}}</title>
;; </head>
;; <body>
;; {{PREAMBLE}}
;; {{TOC}}
;; <main class="content">{{CONTENT}}</main>
;; {{POSTAMBLE}}
;; </body>
;; </html>

;;; Code:

(require 'cl-lib)
(require 'subr-x)
(require 'ox-html)

(defgroup org-html-template nil
  "Export Org to HTML using an external HTML template with placeholders."
  :group 'org-export)

(defcustom org-html-template-file nil
  "Path to an HTML template file used by the `html-template' backend.
If nil, a small built-in default template will be used.
Template placeholders: {{HEAD}}, {{TITLE}}, {{PREAMBLE}}, {{TOC}},
{{CONTENT}}, {{POSTAMBLE}}."
  :type '(file)
  :group 'org-html-template)

(defcustom org-html-template-placeholders
  '("{{HEAD}}" "{{TITLE}}" "{{PREAMBLE}}" "{{TOC}}" "{{CONTENT}}" "{{POSTAMBLE}}")
  "List of placeholders (strings) the template uses, in this order.
Order is HEAD, TITLE, PREAMBLE, TOC, CONTENT, POSTAMBLE."
  :type '(repeat string)
  :group 'org-html-template)

(defcustom org-html-template-treat-custom-toc-as-first t
  "When non-nil, treat the custom-generated TOC as the first TOC.
This makes the TOC use `id=\"table-of-contents\"` / `id=\"text-table-of-contents\"`
(with no numeric suffix).  After generating the TOC we update the
`:org-html--toc-counter` so later TOC generation remains unique."
  :type 'boolean
  :group 'org-html-template)


;;; Backend definition REMOVED

;;; Template reading
(defun org-html-template--read-template (info)
  "Return template text. Prefer `org-html-template-file' if set."
  (let*  ((tpl-file (or (plist-get info :html-template-file)
                        (and org-html-template-file (file-exists-p org-html-template-file))))
          (tpl-read (if tpl-file
                        (with-temp-buffer
                          (insert-file-contents tpl-file)
                          (buffer-string)))))
    (if tpl-read
        tpl-read
      (org-html-template--default-template))))

(defun org-html-template--default-template ()
  "A tiny default HTML5 template used if no external file is configured."
  (string-join
   '("<!doctype html>"
     "<html lang=\"en\">"
     "<head>"
     "{{HEAD}}"
     "  <title>{{TITLE}}</title>"
     "</head>"
     "<body>"
     "{{PREAMBLE}}"
     "{{TOC}}"
     "  <main class=\"content\">"
     "    {{CONTENT}}"
     "  </main>"
     "{{POSTAMBLE}}"
     "</body>"
     "</html>")
   "\n"))

;;; Body-only rendering (reuses parse tree when available)
(defun org-html-template--body-only (info &optional parse-tree)
  "Return HTML for the document body only (no title, no TOC).
INFO is the export info plist. If PARSE-TREE is non-nil, use it instead of parsing."
  (let ((info (copy-sequence info))
        (pt (or parse-tree (org-element-parse-buffer))))
    (plist-put info :with-title nil)
    (plist-put info :with-toc nil)
    (org-export-data pt info)))

;;; TOC generation that guarantees text-table-of-contents id and matching suffix
(defun org-html-template--generate-toc (info &optional parse-tree)
  "Generate a `<nav id=\"table-of-contents...\" role=\"doc-toc\">...</nav>` string or nil.
If `org-html-template-treat-custom-toc-as-first' is non-nil, temporarily
clear `:org-html--toc-counter` so the generated TOC has no suffix, and then
update the counter so subsequent TOC calls are unique."
  (let ((depth (plist-get info :with-toc)))
    (when depth
      (let* ((scope (plist-get info :parse-tree))
             (pt (or parse-tree scope (org-element-parse-buffer)))
             ;; the field we will play with
             (old-counter (plist-get info :org-html--toc-counter)))
        (condition-case err
            (progn
              ;; If user requested to treat custom toc as first, temporarily set counter nil
              (when org-html-template-treat-custom-toc-as-first
                (plist-put info :org-html--toc-counter nil))
              ;; call canonical org-html-toc (depth INFO &optional SCOPE)
              (let ((toc (org-html-toc depth info scope)))
                ;; After generating, set the counter to reflect we've emitted one more TOC
                ;; so subsequent calls will produce unique suffixes.
                (plist-put info :org-html--toc-counter (1+ (or old-counter 0)))
                ;; Return the toc HTML string (may be nil)
                (when toc
                  (concat
                   "<nav id=\"table-of-contents\" role=\"doc-toc\">"
                   toc
                   "</nav>"))))
          (error
           ;; restore on error, then re-signal
           (plist-put info :org-html--toc-counter old-counter)
           (signal (car err) (cdr err))))))))

;;; Template transcode
(defun org-html-template--template (contents info)
  "Template transcode for the `html-template' backend.
CONTENTS is the already-transcoded contents (unused here). INFO is the export plist."
  ;; ensure ox-html helpers are available (defensive; cheap)
  (unless (fboundp 'org-html-preamble)
    (require 'ox-html))
  (let* ((tpl (org-html-template--read-template info))
         ;; compute parse-tree once and reuse
         (parse-tree (or (plist-get info :parse-tree) (org-element-parse-buffer)))
         ;; simple fields
         (head (or (plist-get info :html-head) ""))
         (title (or (format "%s" (plist-get info :title)) ""))
         ;; preamble/postamble via canonical helpers (Emacs 30+)
         (preamble (cond
                    ((fboundp 'org-html-preamble) (or (org-html-preamble info) ""))
                    ((stringp (plist-get info :html-preamble)) (plist-get info :html-preamble))
                    (t "")))
         (postamble (cond
                     ((fboundp 'org-html-postamble) (or (org-html-postamble info) ""))
                     ((stringp (plist-get info :html-postamble)) (plist-get info :html-postamble))
                     (t "")))
         ;; generate toc and content using same parse-tree
         (toc (or (org-html-template--generate-toc info parse-tree) ""))
         (content (org-html-template--body-only info parse-tree))
         ;; build wrappers only when content is non-empty
         (preamble-wrapper (if (and (stringp preamble) (not (string-empty-p preamble)))
                               (format "<header class=\"site-preamble\">%s</header>" preamble)
                             ""))
         (postamble-wrapper (if (and (stringp postamble) (not (string-empty-p postamble)))
                                (format "<footer class=\"site-postamble\">%s</footer>" postamble)
                              ""))
         (replacements (list head title preamble-wrapper toc content postamble-wrapper)))
    ;; Perform placeholder replacement. Use targeted substitution to avoid scanning huge text.
    (cl-loop for ph in org-html-template-placeholders
             for rep in replacements
             do (let ((rep-str (if (stringp rep) rep (format "%s" rep))))
                  (setq tpl (replace-regexp-in-string (regexp-quote ph) rep-str tpl t t))))
    tpl))

;;;###autoload
(defun org-html-template-export-to-html (&optional async subtreep visible-only)
  "Export current buffer to HTML using the `html-template' backend.
Optional ASYNC SUBTREEP VISIBLE-ONLY are forwarded to `org-export-to-file'."
  (interactive)
  (let* ((outfile (concat (file-name-sans-extension (or (buffer-file-name) "untitled")) ".html")))
    (org-export-to-file 'html-template outfile async subtreep visible-only nil nil)
    (message "Wrote %s" outfile)))

;;;###autoload
(defun org-html-template-publish-to-html (plist filename pub-dir)
  "Publish FILENAME to HTML, using settings from the project PLIST.

This function supports selective renaming of files to \"index.html\" and
can use different backends.

PLIST is the project property list, which can specify:
  `:backend'            The export backend to use, e.g., 'html or
                        'html-template. Defaults to 'html.
  `:index-files'        A list of file paths (relative to :base-directory)
                        that should be published as \"index.html\" in their
                        respective subdirectories.
  `:html-template-file' A path to an HTML template file, used by the
                        `html-template' backend.

Return the path to the generated output file."

  (let* ((base-dir   (plist-get plist :base-directory))
         (backend    (or (plist-get plist :backend) 'html))
         (index-list (plist-get plist :index-files))
         (tpl-file   (plist-get plist :html-template-file))
         (rel        (file-relative-name filename base-dir))
         (dir        (file-name-directory rel))
         (is-index   (member rel index-list))
         (out-dir    (expand-file-name (or dir "") pub-dir))
         (out-name   (if is-index "index.html"
                       (concat (file-name-sans-extension
                                (file-name-nondirectory filename))
                               ".html")))
         (out        (expand-file-name out-name out-dir))
         (org-inhibit-startup t)
         (visiting (find-buffer-visiting filename))
         (work-buf (or visiting (find-file-noselect filename))))
    (make-directory out-dir t)
    (unwind-protect
        (with-current-buffer work-buf
          (org-export-to-file backend out nil nil nil nil plist))
      (unless visiting (kill-buffer work-buf)))
    out))

;;; Ensure backend is registered: if the file was loaded but the backend wasn't,
;;; define it now. This guards against situations where top-level execution
;;; failed earlier and left feature provided but backend unregistered.
(unless (org-export-get-backend 'html-template)
  (org-export-define-derived-backend 'html-template 'html
    :translate-alist '((template . org-html-template--template))))


;;; Provide
(provide 'ox-html-template)
;;; ox-html-template.el ends here
#+end_src


**** Publishing
#+begin_src emacs-lisp
;; Publish
(let ((dir (expand-file-name "org-timestamps/" no-littering-var-directory)))
  (unless (file-exists-p dir) (make-directory dir t))
  (setopt org-publish-timestamp-directory dir))

(:with-mode eldoc
  (:hook-into org-mode))

) ;; (setup org ends here
#+end_src

***** Custom publishing projects

****** 11xx.org website
[[file:~/www/11xx.org/lisp/11xx-org-publish.el]]

#+begin_src emacs-lisp
(when (file-exists-p "~/www/11xx.org/lisp/11xx-org-publish.el")
  (add-to-list 'load-path "~/www/11xx.org/lisp/")
  (with-eval-after-load 'ox-publish
    (require '11xx-org-publish)))
#+end_src

*** Library of Babel
https://orgmode.org/manual/Library-of-Babel.html
#+begin_src emacs-lisp
(setup ob-lob
  (:load-after org)
  (org-babel-lob-ingest "~/org/.setup/xdg.org.setup")
  (require 'org-bitwarden))
#+end_src

** Troubleshooting

*** I can't find the format file `pdflatex.fmt!'
Install all relevant =texlive-*= packages. On Arch, install the =texlive=
group package.
# [2025-02-11 Tue 17:18:49 -03] @ak

* 11xx-org-functions.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-org-functions.el
:END:
#+begin_src emacs-lisp
<<org-functions>>

(provide '11xx-org-functions)
#+end_src

** Org functions
:PROPERTIES:
:header-args:emacs-lisp: :noweb-ref org-functions
:END:

*** Copy previous source-block with header arguments
- [[https://emacs.stackexchange.com/questions/55890/is-it-possible-to-repeat-the-last-org-mode-source-blocks-headers/55894#55894][yasnippet - Is it possible to repeat the last org-mode source block's headers - Emacs Stack Exchange]]
  # #wizard
- tip: [[https://stackoverflow.com/questions/5500035/set-custom-keybinding-for-specific-emacs-mode/14230685#14230685][How to add keybindig to specific mode]].
#+begin_src emacs-lisp
(defun org-babel-repeat-previous-src-block ()
  "Copy previous src block excluding the content."
  (interactive)
  (let (result)
    (save-excursion
      (org-babel-previous-src-block)
      (let ((element (org-element-at-point)))
        (when (eq (car element) 'src-block)
          (let* ((pl (cadr element))
                 (lang (plist-get pl :language))
                 (switches (plist-get pl :switches))
                 (parms (plist-get pl :parameters)))
            (setq result
                  (format
                   (concat "\n#+begin_src %s\n"
                           "\n"
                           "#+end_src\n")
                   (mapconcat #'identity
                              (delq nil (list lang switches parms))
                              " ")))))))
    (and result (insert result))
    (forward-line -2))
  (recenter-top-bottom))
#+end_src

*** tangle-dir with expand
- See
  + [[https://emacs.stackexchange.com/questions/19877/how-to-evaluate-elisp-code-contained-in-a-string/19878#19878][read - How to evaluate Elisp code contained in a string? - Emacs Stack Exchange]]
  + [[https://emacs.stackexchange.com/questions/46479/how-to-set-a-tangled-parent-directory-for-each-subtree-in-org-mode/55859#55859][How to set a tangled parent directory for each subtree in org mode?]]
# [2023-05-19 Fri 23:48:32 -03]
#+begin_src emacs-lisp
(defvar 11xx--tdir-allowed-functions
  '(tdir-base
    expand-file-name
    concat
    xdg-config-home
    xdg-data-home
    xdg-cache-home
    xdg-bin-home
    xdg-config-dirs
    xdg-data-dirs
    getenv
    xdg-runtime-dir
    )
  "Side-effect-free functions permitted inside :tangle-dir: sexp values.
All must return strings or path components.")

(defun f/tdir-safe-form-p (form)
  "Return t if FORM is safe to evaluate as a :tangle-dir: expression.
Safe means: a self-evaluating atom, or a list whose car is in
`11xx--tdir-allowed-functions' and whose every argument is also safe."
  (cond
   ((stringp form)          t)
   ((numberp form)          t)
   ((memq form '(t nil))    t)
   ((keywordp form)         t)
   ((and (consp form)
         (symbolp (car form))
         (memq (car form) 11xx--tdir-allowed-functions)
         (cl-every #'f/tdir-safe-form-p (cdr form)))
    t)
   (t nil)))

(defun f/eval-tdir-sexp (string)
  "Safely evaluate STRING as a :tangle-dir: property value.
Returns STRING as-is if it does not start with '('."
  (let ((s (string-trim string)))
    (if (not (string-prefix-p "(" s))
        s
      (let ((form (condition-case err
                      (read s)
                    (error (user-error
                            "tdir: malformed sexp in :tangle-dir: %s — %s" s err)))))
        (unless (f/tdir-safe-form-p form)
          (user-error
           "tdir: unsafe form in :tangle-dir: %s\n  Only %s with literal/whitelisted args are permitted"
           form 11xx--tdir-allowed-functions))
        (let ((result (eval form t)))
          (unless (stringp result)
            (user-error "tdir: :tangle-dir: sexp must return a string, got: %S" result))
          result)))))

(defvar tdir--resolving nil
  "Stack of heading positions currently being resolved.
Used to detect circular :tangle-dir: references.")

(defun tdir--effective-dir ()
  "Resolve :tangle-dir: for the current heading without Org's built-in
property inheritance, to retain full control over sexp evaluation.

- Plain string → returned directly.
- Sexp         → validated and evaluated; circular refs cause a user-error.
- Missing      → walks up the outline tree recursively."
  (let* ((raw (org-entry-get nil "tangle-dir" nil))
         (pos (save-excursion (org-back-to-heading t) (point))))
    (cond
     ((and raw (not (string-prefix-p "(" (string-trim raw))))
      (string-trim raw nil "/"))

     (raw
      (when (memq pos tdir--resolving)
        (user-error
         "tdir: circular :tangle-dir: at '%s' — use `tdir-base' in properties, not `tdir'"
         (org-entry-get nil "ITEM")))
      (let ((tdir--resolving (cons pos tdir--resolving)))
        (string-trim (f/eval-tdir-sexp (string-trim raw)) nil "/")))

     (t
      (save-excursion
        (unless (org-up-heading-safe)
          (user-error "tdir: no :tangle-dir: property found in heading hierarchy"))
        (tdir--effective-dir))))))

(defun tdir-base (&optional subdir)
  "Return the parent heading's effective tangle-dir, joined with SUBDIR.
Use in :tangle-dir: property values for hierarchy-relative paths:

  :tangle-dir: (tdir-base \"tasks\")

For externally-rooted paths, use expand-file-name directly:

  :tangle-dir: (expand-file-name \"nnn/plugins\" (xdg-config-home))"
  (save-excursion
    (unless (org-up-heading-safe)
      (user-error "tdir-base: no parent heading"))
    (let ((parent-dir (tdir--effective-dir)))
      (if subdir
          (expand-file-name (string-trim subdir "/" nil) parent-dir)
        parent-dir))))

(defun tdir (&optional path)
  "Return the effective tangle directory for the current Org entry,
optionally joined with PATH via `expand-file-name'.

Use in :tangle src block headers:
  :tangle (tdir \"filename.yml\")

For :tangle-dir: property values, use `tdir-base' or `expand-file-name'."
  (let ((dir (tdir--effective-dir)))
    (if path
        (expand-file-name (string-trim path "/" nil) dir)
      dir)))

(defun f/tdir-set-heading-property ()
  "Set :tangle-dir: for the current heading to (tdir-base \"SLUG\").
SLUG is derived from the heading title and confirmed in the minibuffer."
  (interactive)
  (let* ((title (substring-no-properties (org-entry-get nil "ITEM")))
         (slug  (thread-last title
                  (downcase)
                  (replace-regexp-in-string "[[:space:]]+" "-")
                  (replace-regexp-in-string "[^a-z0-9_-]" "")
                  (replace-regexp-in-string "-+" "-")
                  (string-trim "-")))
         (slug  (read-string "Slug for tdir-base: " slug))
         (value (format "(tdir-base \"%s\")" slug)))
    (org-set-property "tangle-dir" value)
    (message "Set :tangle-dir: %s" value)))

(with-eval-after-load 'org
  (keymap-set org-mode-map "C-c C-x T" #'f/tdir-set-heading-property))
#+end_src

#+RESULTS:
: f/tdir-set-heading-property

- Usage:
  + Functions can be used in the =:tangle= header argument of a src code
    block, e.g. =:tangle (tdir "filename")=.

*** Fix noweb substring syntax highlighting display in code blocks
Use either =<<= & =>>= (the default) or =«= & =»= (=0000AB= & =0000BB=), when
syntax highlighting breaks such as shell code blocks that interpret
=<<nowebname>>= as heredocs.
# The latter preserves syntax highlighting in sh-mode.
- [[https://emacs.stackexchange.com/questions/63643/noweb-references-in-sh-blocks-breaks-the-syntax-highlighting/73720#73720][org mode - Noweb references in sh blocks breaks the syntax highlighting - Emacs Stack Exchange]]
  # #wizard
  + original =org-babel-noweb-wrap= function:
    * [[https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/ob-core.el#n195][ob-core.el\lisp - emacs/org-mode.git - Emacs Org mode]]

# [2023-09-13 Wed 14:18:13 -03]
#+begin_src emacs-lisp
;; override the default
(with-eval-after-load 'org
  (defun org-babel-noweb-wrap (&optional regexp)
    "Return regexp matching a Noweb reference.

Match any reference, or only those matching REGEXP, if non-nil.

When matching, reference is stored in match group 1."
    (rx-to-string
     `(and (or "<<" "«")
           (group
            (not (or " " "\t" "\n"))
            (? (*? any) (not (or " " "\t" "\n"))))
           (or ">>" "»"))))

  (defun f/org-babel-noweb-wrap-insert-chars ()
    "Insert \"«\" and \"»\" "
    (interactive)
    (insert "«»")
    (backward-char)))
#+end_src

*** Get full path of headings
# NVM there's (org-format-outline-path (org-get-outline-path t t) nil nil "/")
#+begin_src emacs-lisp
(defun org-get-full-outline-path ()
  "Retrieve the full heading path of the current heading."
  (interactive)
  (let ((path (org-get-outline-path t t)))
    (if path
        (mapconcat 'identity path "/")
      ;; (message (concat "Killed current Org outline path: " (mapconcat 'identity path "/")))
      (message "Not in an Org mode heading"))))

(defun org-kill-full-outline-path ()
  "Adds the full heading path of the current heading to kill-ring.

Wrapper for `org-get-full-outline-path'."
  (interactive)
  (kill-new (org-get-full-outline-path)))
#+end_src


*** Random characters string
:PROPERTIES:
:CUSTOM_ID: orgid-vuivrg
:END:

- source https://stackoverflow.com/a/60790863
#+begin_src emacs-lisp
(defun random-string-g-to-z (n)
  "Generate N random characters from G to Z.

The reason for using G to Z is to differentiate from MD5/HEX
strings that use A-F and 0-9. Also this is meant for simple
\"ID-fication\" of certain components like creating anchor links.

Inefficient implementation; don't use for large N. Testing showed
a limit of 530, more than that and lisp nesting will overflow."

  (let* ((alpha "ghijklmnopqrstuvwxyz")
         (i (% (abs (random)) (length alpha))))
    (if (= 0 n) ""
      (concat (substring alpha i (1+ i))
              (random-string-g-to-z (1- n))))))
#+end_src

- Number of possibilities
  #+begin_example
  (let ((number-of-characters 21)
        (length-of-string 6))
    (expt number-of-characters length-of-string))
  #+end_example

*** Get list of tangle files that match extension
#+begin_src emacs-lisp
(defun org-babel-get-tangle-files-by-ext (&optional ext)
  "Returns a list of unique filenames to be tangled that end with the specified EXT.

If EXT is not provided, default to \".el\".

This function parses all code blocks in the current Org buffer, identifies
those that contain the `:tangle' header argument (inherited or directly) and
collects the tangle filenames of those that end with the specified EXT.

Note that for this `string-suffix-p' is used to search for an EXT in the
format `.EXT' (with a period) so if a period isn't provided it is added and
if it was it is kept.

Example:

(org-babel-get-tangle-files-by-ext \"el\")"
  (let ((tangle-files '())
        (tangle-files-ext (concat "." (if ext (string-trim-left ext "\\.")
                                        ".el"))))
    (org-element-map (org-element-parse-buffer) 'src-block
      (lambda (src-block)
        (let* ((info (org-babel-get-src-block-info t src-block))
               (header-args (nth 2 info))
               (tangle (cdr (assoc :tangle header-args))))
          (when (and tangle
                     (stringp tangle)
                     (string-suffix-p tangle-files-ext tangle t))
            (push tangle tangle-files)))))
    (delete-dups tangle-files)))
#+end_src

*** Add lexical-binding property to tangle files
The following functions together with
=org-babel-get-tangle-files-by-ext= can be used for adding
=lexical-binding: t= to tangled files automatically without having to
add them as a header in the code blocks. Example usage with local file
variables:

: # eval: (add-hook 'org-babel-tangle-finished-hook #'org-babel-tangle-add-lexical-prop-to-el-tangled-files nil nil)
Note that using ='org-babel-tangle-finished-hook= is important because
=org-babel-get-tangle-files-by-ext=, the function that gets the target
tangle files, needs to read the right buffer/Org document and that
hook is triggered after tangling is finished and Emacs' focus is back
in the source Org buffer so it can get the list.

#+begin_src emacs-lisp
(defun add-lexical-binding-prop (file)
  "Add `lexical-binding: t' prop to FILE without disrupting open buffers."
  (let ((buffer (get-buffer (find-file-noselect file))))
    (with-current-buffer buffer
      (add-file-local-variable-prop-line 'lexical-binding t nil)
      (save-buffer))
    (unless (get-buffer-window buffer 'visible)
      (kill-buffer buffer))))

(defun org-babel-tangle-add-lexical-prop-to-el-tangled-files()
  (dolist (file (let ((source-list (org-babel-get-tangle-files-by-ext "el"))
                      (filter-list '(".dir-locals.el")))
                  (filter-list-any source-list filter-list)))
    (add-lexical-binding-prop file)))
#+end_src

* 11xx-org-functions-tangle-export-helpers.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-org-functions-tangle-export-helpers.el
:END:

#+begin_src emacs-lisp
;;; 11xx-org-functions-tangle-export-helpers.el --- Org babel tangle/export helpers  -*- lexical-binding: t -*-

;;; Code:
;;;###autoload
(defun org-babel-get-src-block-header-arg (header-arg)
  "Get the value of the header argument HEADER-ARG from the provided SRC-BLOCK-INFO.

First argument `org-babel-get-src-block-info' is set to `t'
because it will try to evaluate function in e.g. `:tangle' and if
for some reason that function refers to
`org-babel-get-src-block-info' it infinite loops."
  ;; This could be set as an optional arg? but then what's the point meh haha
  (let* ((src-block-info (org-babel-get-src-block-info t)) ; t for NO-EVAL, otherwise it will infinite loop
         (params (nth 2 src-block-info)))
    (assoc-default header-arg params)))
#+end_src

for [[file:~/.config/darkman/README.org]]
#+begin_src emacs-lisp
;;;###autoload
(defun darkmandir (shfile)
  "Evaluate to a filename in a directory from `XDG_DATA_HOME' that's either `light-mode.d' or `dark-mode.d'.

The string argument SHFILE is the target filename of the darkman script to be tangled.

Usage:
  Either set
  A header-arg \":theme light\" or \":theme dark\";
  A `org-set-property' called 'theme' with value \"dark\" or \"light\".

  Then using the function returns:
  (darkmandir \"script.sh\")
    => \"/home/user/.local/share/light-mode.d/script.sh\"
    or
    => \"/home/user/.local/share/dark-mode.d/script.sh\""
  (let* ((file (if shfile (string-trim shfile "/")))
         (dir-light (expand-file-name "light-mode.d/" (xdg-data-home)))
         (dir-dark (expand-file-name "dark-mode.d/" (xdg-data-home)))
         (out-path-light (expand-file-name file dir-light))
         (out-path-dark (expand-file-name file dir-dark)))
    (cond
     ((or (string= (org-babel-get-src-block-header-arg :theme) "light")
          (string= (org-entry-get nil "theme" t) "light"))
      out-path-light)
     ((or (string= (org-babel-get-src-block-header-arg :theme) "dark")
          (string= (org-entry-get nil "theme" t) "dark"))
      out-path-dark))))
#+end_src

#+begin_src emacs-lisp
(provide '11xx-org-functions-tangle-export-helpers)
;;; 11xx-org-functions-tangle-export-helpers.el ends here
#+end_src


* 11xx-dired.el
:PROPERTIES:
:CUSTOM_ID: orgid-wlgppl
:header-args:emacs-lisp+: :tangle lisp/11xx-dired.el
:END:

#+begin_src emacs-lisp
<<11xx-dired>>

(provide '11xx-dired)
#+end_src

** Dired
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-dired :tangle no
:END:

*** Dired functions

**** Single buffer dired
[[https://github.com/crocket/dired-single#recommended-keybindings][dired-single#recommended-keybindings]] | [[https://youtu.be/PMWwM8QJAtU?t=2182][Emacs From Scratch #10 - Effortless File Management with Dired@36:22]]

Or the later =(setq dired-kill-when-opening-new-dired-buffer t)= in Emacs 28.1+.

**** Dired up directory without opening new buffer
#+begin_src emacs-lisp
(defun dired-find-alternate-file-up ()
  "Sames as `dired-find-alternate-file' but go up one directory instead."
  (interactive)
  (find-alternate-file ".."))
#+end_src


**** dired open with external app
[[https://emacs.stackexchange.com/questions/21796/dired-alternative-to-openwith-how-to-open-file-per-extension/21808#21808][wizard]]
~launch~ is a script xdg alternative located in ~~.local/bin~.
#+begin_src emacs-lisp
(defun mu-open-in-external-app ()
  "Open the file where point is or the marked files in Dired in external app.

The app is chosen from your OS's preference."
  (interactive)
  (let* ((file-list
          (dired-get-marked-files)))
    (mapc
     (lambda (file-path)
       (let ((process-connection-type nil))
         (start-process "" nil "launch" file-path)))
     file-list)))
#+end_src

**** Open Terminal here
[[https://truongtx.me/2013/09/13/emacs-dired-new-terminal-window-at-current-directory-on-macos][wizard src]]
this gets the terminal name from the environment variable ~$TERMINAL~,
if not set edit the code accordinly. Don't forget to edit the call flags!
#+begin_src emacs-lisp
;; default terminal application path
(defvar 11xx--terminal (getenv "TERMINAL")
  "The default terminal as in the TERMINAL environment variable.")
;;; function to open new terminal window at current directory
(defun tmtxt/open-current-dir-in-terminal ()
  "Open current directory in 'dired-mode' in terminal application."
  (interactive)
  (shell-command (concat
                  (shell-quote-argument 11xx--terminal)
                  " "
                  "--working-directory"
                  " "
                  (shell-quote-argument (file-truename default-directory)))))

;; (define-key dired-mode-map (kbd "<f4>") 'tmtxt/open-current-dir-in-terminal) ;; was kmacro-end-or-call-macro
#+end_src

*** Dired setup

- [[https://writequit.org/denver-emacs/presentations/2016-05-24-elpy-and-dired.html][Using Dired as a file manager]]
- [[https://www.youtube.com/watch?v=PMWwM8QJAtU][Emacs From Scratch #10 - Effortless File Management with Dired]]
- [[https://github.com/Fuco1/dired-hacks#dired-rainbow][Dired-Rainbow]]
- [[help:dired-compress-files-alist][Add compression]]

NOTE: =dired-async= is provided by the =async= package.
#+begin_src emacs-lisp
(setup ls-lisp
  (setopt ls-lisp-use-insert-directory-program nil
          ls-lisp-dirs-first t
          ls-lisp-ignore-case t
          ls-lisp-use-string-collate nil
          dired-use-ls-dired nil
          dired-listing-switches "-lAhv"
          ;; dired-listing-switches "-l --almost-all --human-readable --group-directories-first --no-group --sort=version"
          ls-lisp-format-time-list '("%Y-%m-%d %H:%M" "%Y-%m-%d %H:%M")
          ls-lisp-use-localized-time-format t
          ))

(setup dired
  (:require dired-x dired-aux)
  (:hook auto-revert-mode)
  (:put-enable dired-find-alternate-file)

  (setopt
   dired-recursive-copies #'always
   dired-recursive-deletes #'always
   ;; Compress/Archive files
   dired-compress-directory-default-suffix ".tar.zst"
   dired-compress-file-alist '(("\\.zst\\'" . "zstd -qf -11 --rm -o %o %i"))
   dired-compress-files-alist '(("\\.tar\\.zst\\'" . "tar -cf - %i | zstd -11 -o %o"))
   ;; prompt
   dired-deletion-confirmer #'y-or-n-p
   dired-kill-when-opening-new-dired-buffer t ; emacs 28.1 dired-single
   dired-dwim-target t ; [[https://emacs.stackexchange.com/questions/5603/how-to-quickly-copy-move-file-in-emacs-dired/5604#5604][How to quickly copy/move file in Emacs Dired? - Emacs Stack Exchange]]
   dired-hide-details-hide-symlink-targets nil ; always show where symlink points to
   )

  (defun f/dired-find-home ()
    (interactive)
    (dired (getenv "HOME")))

  (:bind "RET" mu-open-in-external-app
         "/" dired-narrow-fuzzy
         "<tab>" dired-subtree-toggle
         "<remap> <dired-maybe-insert-subdir>" dired-subtree-toggle
         "<backtab>" dired-subtree-cycle
         "t" tmtxt/open-current-dir-in-terminal
         "f" dired-find-file
         "b" dired-up-directory

         "h" dired-up-directory        ;; was M-x describe-mode
         "j" dired-next-line           ;; was M-x dired-goto-file
         "k" dired-previous-line       ;; was M-x dired-do-kill-lines
         "l" dired-find-file

         "SPC" dired-mark
         "~" f/dired-find-home
         ))

(setup dired-hide-dotfiles
  (:elpaca dired-hide-dotfiles)
  (keymap-set dired-mode-map "." #'dired-hide-dotfiles-mode) ; was dired-clean-directory
  (setopt dired-hide-dotfiles-verbose nil))

(setup (:elpaca dired-narrow))
(setup (:elpaca dired-subtree))

(setup (:elpaca dired-efap)
  (:with-hook dired-mode
    (:require dired-efap))
  (:with-map dired-mode-map
    (:bind "r" dired-efap))
  (:with-hook dired-efap-mode-hooks
    (setq-local dirvish-hide-cursor nil))
  (setopt dired-efap-initial-filename-selection nil))

;; (setup (:elpaca all-the-icons-dired)
;;   (:load-after dired)
;;   ;; (all-the-icons-install-fonts t) ; on first run to fix missing icons
;;   (:hook-into dired-mode))

(setup (:elpaca diredfl)
  (:hook-into dired-mode))

(use-package dired-hl-line-mode
  :hook (dired-mode . dired-hl-line-mode))
#+end_src

**** TODO dirvish
#+begin_src emacs-lisp :tangle no :noweb-ref dummy
(setup (:elpaca dirvish)
  (dirvish-override-dired-mode)

  ;; Fixes for dired-efap and wdired
  (defun dirvish-hide-cursor--on ()
    "Browsing state: Enable buffer-local `dirvish-hide-cursor'."
    (setq-local dirvish-hide-cursor t
                cursor-type nil))
  (defun dirvish-hide-cursor--off ()
    "Editing state: show cursor, disable buffer-local `dirvish-hide-cursor'."
    (setq-local dirvish-hide-cursor nil
                cursor-type t))
  (add-hook   'dired-mode-hook                         #'dirvish-hide-cursor--on)
  (add-hook   'wdired-mode-hook                        #'dirvish-hide-cursor--off)
  (advice-add 'wdired-change-to-dired-mode      :after #'dirvish-hide-cursor--on)
  (advice-add 'dired-efap                       :after #'dirvish-hide-cursor--off)
  (advice-add 'dired-efap--change-to-dired-mode :after #'dirvish-hide-cursor--on)
  )
;; (setopt dirvish-attributes '(nerd-icons file-time file-size collapse subtree-state vc-state git-msg))
#+end_src

**** DONE Show current directory in Dired header line
#+begin_src emacs-lisp :tangle no :noweb-ref dummy
(defun f/dired-dir-header-line ()
  "Uses `header-line-format' to display the current directory."
  (interactive)
  (setq-local header-line-format
              '((:eval (abbreviate-file-name default-directory)))))
(add-hook 'dired-mode-hook 'f/dired-dir-header-line)
#+end_src

* Magit

** 11xx-magit.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-magit.el
:END:

- See
  + [[https://emacs.stackexchange.com/questions/15270/whats-the-magit-equivalent-of-git-add/15272#15272][What's the Magit equivalent of 'git add'? - Emacs Stack Exchange]]
  + [[https://emacs.stackexchange.com/questions/30602/use-nonstandard-git-directory-with-magit][use nonstandard `.git` directory with magit - Emacs Stack Exchange]]
  + [[https://gitlab.com/dwt1/dotfiles/-/blob/master/.emacs.d.gnu/config.org#magit][.emacs.d.gnu/config.org · master · Derek Taylor / Dotfiles · GitLab]]
  + [[https://gitlab.com/dwt1/dotfiles/-/commit/125f9d2630994911ad15425ff1cad69474bead7e][Merge branch 'emacs' into 'master' (125f9d26) · Commits · Derek Taylor / Dotfiles · GitLab]]
    # #wizard
  + Fix elpaca version mismatch
    * See [[https://github.com/progfolio/elpaca/issues/324][[Bug/Support]: Error installing magit · Issue #324 · progfolio/elpaca]]

#+begin_src emacs-lisp
(setup magit
  (:elpaca magit)

  ;; rely on autoloads from elpaca block so magit don't need to be required
  ;; inside `magit-status-bare.el'.
  (require 'magit-status-bare)

  ;; unbind default `magit-status' so g can be used as prefix
  (keymap-global-unset "C-x g")

  (keymap-global-set "C-x g g" #'magit-status-default) ; magit-status

  ;;; bare repos
  (magit-status-bare :git-dir "~/.local/dotfiles.git/"
                     :work-tree (getenv "HOME")
                     :key-bind "C-x g d")
  (dired-git-add-bare :git-dir "~/.local/dotfiles.git/"
                      :work-tree (getenv "HOME")
                      :key-bind "C-c g d a")

  (:with-feature dired
    (defun dired-git-add (&optional arg)
      "Execute 'git add' command for current or marked files in Dired mode.
With prefix ARG, prompt for additional arguments to pass to the command."
      (interactive "P")
      (let* ((files (dired-get-marked-files nil arg))
             (git-cmd "git")
             (output (mapconcat (lambda (file)
                                  (shell-command-to-string
                                   (concat git-cmd " add --verbose " (shell-quote-argument file))))
                                files
                                "\n")))
        (message "Git add command completed:\n%s" output)))
    (:bind "C-c g g a" dired-git-add))

  (require '11xx-vot))

(setup (:elpaca transient)
  (:load-after magit))

(provide '11xx-magit)
#+end_src

** magit-status-bare.el
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/magit-status-bare.el
:END:

#+begin_src emacs-lisp
;; NOTE: This requires lexical-binding = t
(require 'dired)
(require '11xx-functions) ; filter-list-any-string-prefix

;;;###autoload
(defun magit-status-default ()
  "Wrapper for `magit-status' without \"--git-dir\" or \"--work-tree\" CLI args.

Magit relies on `magit-git-global-arguments' for passing to git
command-line arguments, normally it's not necessary to customize
it but when invoking `magit-status' for a bare git repository is
desired `magit-git-global-arguments' needs to include the
`--git-dir=<dir>' and `--work-tree=<dir>' options. Though there's
a problem with this approach: Customizing
`magit-git-global-arguments' needs to change it globally because
even though `magit-status' may work when called inside a `let',
other commands inside the magit buffer will also read from the
same variable, but if the new values have not been set globally
commands like `magit-stage' will not work because they will be
missing `--git-dir' and `--work-tree'. A hacky way of doing it is
having a version for the bare git function calls that include the
custom flags, and this version that removes the custom
flags. Then replace the keybind for `magit-status'."
  (interactive)
  (setq magit-git-global-arguments (filter-list-any-string-prefix
                                    magit-git-global-arguments
                                    '("--git-dir" "--work-tree")))
  (call-interactively #'magit-status))

;;;###autoload
(defun magit-status-bare (&rest args)
  "Configure Magit to operate on a bare repository using ARGS.

ARGS is a property list that supports the following keys:
- `:git-dir'     (required) Path to a bare Git directory.
- `:work-tree'   (required) Path to the repository's worktree.
- `:key-bind'    (optional) Set a global key binding. If
  provided, the key binding is set, but the function is not
  executed."
  (interactive)
  (let* ((git-dir (plist-get args :git-dir))
         (work-tree (plist-get args :work-tree))
         (key-binding (plist-get args :key-bind))
         (git-dir-arg (concat "--git-dir=" (expand-file-name git-dir)))
         (work-tree-arg (concat "--work-tree=" (expand-file-name work-tree)))
         )
    (setq magit-git-global-arguments (append (eval (car (get 'magit-git-global-arguments 'standard-value)))
                                             (list git-dir-arg work-tree-arg)))

    (if (key-valid-p key-binding)
        (keymap-global-set key-binding
                           (let ((expanded-git-dir git-dir)
                                 (expanded-work-tree work-tree))
                             (lambda ()
                               (interactive)
                               (magit-status-bare :git-dir expanded-git-dir :work-tree expanded-work-tree))))
      (call-interactively 'magit-status))))

;;;###autoload
(defun dired-git-add-bare (&rest args)
  "Add files to a bare repository from Dired using ARGS.

ARGS is a property list that supports the following keys:
- `:git-dir'       (required) The absolute path to the bare Git directory.
- `:work-tree'     (required) The absolute path to the repository's worktree.
- `:key-bind'      (optional) Set a key binding to invoke this
  function in `dired-mode-map'. If provided, the key binding is
  set, but the function is not executed."
  (interactive)
  (let* ((git-dir (plist-get args :git-dir))
         (work-tree (plist-get args :work-tree))
         (key-binding (plist-get args :key-bind))
         (git-dir-arg (concat "--git-dir=" (expand-file-name git-dir)))
         (work-tree-arg (concat "--work-tree=" (expand-file-name work-tree))))

    (if (key-valid-p key-binding)
        ;; Set the key binding without executing the function
        (keymap-set dired-mode-map key-binding
                    (lambda (&optional arg)
                      (interactive "P")
                      (dired-git-add-bare :git-dir git-dir :work-tree work-tree)))
      ;; Execute the function
      (let* ((files (dired-get-marked-files nil nil))
             (git-cmd (mapconcat 'identity (list "git" git-dir-arg work-tree-arg) " "))
             (output (mapconcat (lambda (file)
                                  (shell-command-to-string
                                   (concat git-cmd " add --verbose " (shell-quote-argument file))))
                                files "\n")))
        (message "Git add command completed:\n%s" output)))))


(provide 'magit-status-bare)
#+end_src

* 11xx-completion.el: Completion frakework, Minibuffer
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-completion.el
:END:

#+begin_src emacs-lisp
<<11xx-completion>>

(provide '11xx-completion)
#+end_src


** def
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-completion :tangle no
:END:

- [[https://www.reddit.com/r/emacs/comments/qfrxgb/comment/hi6mfh7/?utm_source=share&utm_medium=web2x&context=3][what are Vertico, Consult, Marginalia, Embark]]

*** VERTico

- See
  + [[https://github.com/minad/vertico][VERTical Interactive COmpletion - GitHub]]
  + [[https://github.com/axelf4/hotfuzz][hotfuzz]]
  + [[https://www.youtube.com/watch?v=J0OaRy85MOo][Streamline Your Emacs Completions with Vertico]]
  + [[https://www.reddit.com/r/emacs/comments/qfrxgb/comment/hi6nxs11xx--?context=3][What these packages do migrating from ivy]]
  + [[https://stackoverflow.com/questions/6133799/delete-a-word-without-adding-it-to-the-kill-ring-in-emacs/6133921#6133921][Delete a word without adding it to the kill-ring in Emacs - Stack Overflow]]
  + https://systemcrafters.cc/live-streams/may-21-2021/
  # [2022-02-24 Thu 00:01:03]

#+begin_src emacs-lisp
(setup (:elpaca vertico)
  (defun f/minibuffer-backward-delete-word (arg)
    "Delete characters backward until encountering the beginning of a word.
With argument ARG, do this that many times."
    (interactive "p")
    (delete-region (point) (progn (backward-word arg) (point))))

  (defun f/minibuffer-delete-word (arg)
    "Delete characters forward until the end of a word.
Like `kill-word' but doesn't add deleted words to kill ring."
    (interactive "p")
    (delete-region (point) (progn (forward-word arg) (point))))

  (defun f/minibuffer-delete-line (arg)
    "Delete characters forward until the end of the line.
Like `kill-line' but doesn't add deleted characters to kill ring."
    (interactive "p")
    (delete-region (point) (progn (end-of-line arg) (point))))
  ;; prevent cursor on minibuffer
  (:with-hook minibuffer-setup-hook
    (:hook cursor-intangible-mode))

  (:with-map vertico-map
    (:bind "?" minibuffer-completion-help
           "M-RET" minibuffer-force-complete-and-exit
           "M-TAB" minibuffer-complete
           "M-<backspace>" f/minibuffer-backward-delete-word
           "M-D" f/minibuffer-backward-delete-word ; was down-list
           "C-M-d" backward-delete-char ; was down-list
           "M-d" f/minibuffer-delete-word
           "C-k" f/minibuffer-delete-line
           "C-M-k" kill-line
           ;; "M-h" dw/minibuffer-backward-kill

           ;; can be reversed because of `vertico-reverse-mode', but no:
           ;; "C-p" vertico-next
           ;; "C-n" vertico-previous
           ))
  (:option vertico-scroll-margin 4 ;; Different scroll margin
           ;;;; Show more candidates
           ;; setq vertico-count 20
           ;;;; Grow and shrink the Vertico minibuffer
           ;; vertico-resize t
           ;;;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
           vertico-cycle t)

  ;; vertico-minibuffer-settings
  ;; - Hide commands in M-x which do not work in the current mode.
  ;; # Emacs 28
  ;; - Vertico commands are hidden in normal buffers.
  (setopt read-extended-command-predicate #'command-completion-default-include-p
          enable-recursive-minibuffers t
          completion-cycle-threshold 3 ; TAB cycle if there are only few candidates
          ;; Do not allow the cursor in the minibuffer prompt
          minibuffer-prompt-properties '(read-only
                                         t
                                         cursor-intangible
                                         t face minibuffer-prompt))
  (:with-hook elpaca-after-init-hook
    (:hook vertico-mode)))
#+end_src

*** Savehist
See https://www.reddit.com/r/emacs/comments/ie7g17/emacs_clipboard_between_sessions/
[[https://help-gnu-emacs.gnu.narkive.com/LOddwNvQ/don-t-clear-kill-ring-when-restart-emacs][Don't clear kill-ring when restart emacs]]
# [2022-11-09 Wed 17:02:36 -03]

Have =M-x= commands history across sessions

#+begin_src emacs-lisp
;; Persist history over Emacs restarts. Vertico sorts by history position.
(setup savehist
  (:option savehist-additional-variables '(kill-ring
                                           compile-command
                                           search-ring
                                           regexp-search-ring)
           history-length 1000
           history-delete-duplicates t)

  ;; History lengths can also be limited:
  ;; See [[https://www.reddit.com/r/emacs/comments/i961nn/comment/g1d87tf/?context=3][Emacs dragged down by massive 'history' file : emacs#demosthenex]]
  ;; Found my savehist was HUGE and locking up emacs every 5 min
  (put 'savehist-minibuffer-history-variables 'history-length 1000)
  (put 'org-read-date-history                 'history-length 1000)
  (put 'read-expression-history               'history-length 1000)
  (put 'org-table-formula-history             'history-length 1000)
  (put 'extended-command-history              'history-length 1000)
  (put 'ido-file-history                      'history-length 1000)
  (put 'helm-M-x-input-history                'history-length 1000)
  (put 'minibuffer-history                    'history-length 1000)
  (put 'ido-buffer-history                    'history-length 1000)
  (put 'buffer-name-history                   'history-length 1000)
  (put 'file-name-history                     'history-length 1000)
  ;; # [2022-11-09 Wed 17:15:35 -03]

  (:hook-into elpaca-after-init-hook))
#+end_src

*** Orderless
[[https://github.com/oantolin/orderless#style-dispatchers][Style dispatchers]]
#+begin_src emacs-lisp
(setup (:elpaca orderless)
  (:option completion-category-defaults nil
           ;; served well completion-styles '(substring orderless flex)
           completion-styles '(orderless initials substring basic)
           completion-category-overrides '((file (styles basic partial-completion)))
           ;; completion-category-overrides '((command (styles orderless+initialism))
           ;;                                 (symbol (styles orderless+initialism))
           ;;                                 (variable (styles orderless+initialism)))
           ;; Integrate with company
           orderless-component-separator "[ &]"
           ;; Case matching
           orderless-smart-case t
           ;; completion-ignore-case t
           ;; read-file-name-completion-ignore-case t
           ;; read-buffer-completion-ignore-case t
           )

  (defun just-one-face (fn &rest args)
    (let ((orderless-match-faces [completions-common-part]))
      (apply fn args)))

  (:advise company-capf--candidates :around #'just-one-face)
  )
#+end_src

*** Marginalia
- [[https://github.com/minad/marginalia/][marginalia github]]
#+begin_src emacs-lisp
;; Enable richer annotations using the Marginalia package
(setup (:elpaca marginalia)
  (:hook-into elpaca-after-init-hook)
  ;; Either bind `marginalia-cycle` globally or only in the minibuffer
  ;; (:bind "M-A" marginalia-cycle)
  (:with-map minibuffer-local-map
    (:bind "M-A" marginalia-cycle))
  (setopt marginalia-align 'left
          marginalia-field-width 120))
#+end_src

*** Consult
[[https://github.com/minad/consult#use-package-example][Example configuration for Consult]]
#+begin_src emacs-lisp
(setup (:elpaca consult)
  (:global-set
   "C-s" consult-line ;; Was search-forward
   "C-x b" consult-buffer ;; Was switch-to-buffer
   "C-r" consult-history ;; #TODO-ithink was isearch-backward
   "C-c o s" consult-org-heading
   ))
;; note: consult-outline & consult-org-heading
#+end_src

https://github.com/minad/consult/issues/563#issuecomment-1186612641
#+begin_example emacs-lisp
(defun org-show-entry-consult-a (fn &rest args)
  (when-let ((pos (apply fn args)))
    (org-fold-show-entry)))

(advice-add 'consult-line :around #'org-show-entry-consult-a)
(advice-add 'consult-org-heading :around #'org-show-entry-consult-a)
(advice-add 'consult-org-heading :around #'consult--grep)
#+end_example

*** Embark
[[https://github.com/oantolin/embark#quick-start][Embark#Quick start]]
#+begin_src emacs-lisp
(setup (:elpaca embark)
       (:elpaca embark-consult)
  (:load-after consult)
  (:global-set
   "C-." embark-act
   ;; "C-;" embark-dwim
   "C-h B" embark-bindings)
  ;; Optionally replace the key help with a completing-read interface
  (setq prefix-help-command #'embark-prefix-help-command)

  ;; Hide the mode line of the Embark live/completions buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none))))
  ;; (:hook embark-collect-mode consult-preview-at-point-mode)
  )
#+end_src

*** Corfu
yoinked [[https://github.com/daviwil/dotfiles/blob/master/Emacs.org#completions-in-regions-with-corfu][daviwil/dotfiles/Emacs.org#completions-in-regions-with-corfu]]
#+begin_src emacs-lisp
(setup (:elpaca corfu)
  (:global-set "<tab>" completion-at-point)

  (:with-map corfu-map
    (:bind "M-SPC" corfu-insert-separator)
    (:unbind "C-n"
             "C-p"))
  (:option corfu-cycle t
           ;; corfu-auto t
           corfu-auto-delay 0.1
           corfu-auto-prefix 4
           ;; corfu-quit-at-boundary 'separator ; Using M-SPC will activate orderless-style matching with space-separated fields.
           ;; See [[https://www.reddit.com/r/emacs/comments/sh3lio/orderless_corfu_make_the_component_separator/][Orderless + Corfu: Make '*' the component separator? : emacs]]
           ;; lsp-completion-provider :none ; this otherwise conflicts with corfu
           corfu-preview-current nil)

  (:with-hook elpaca-after-init-hook
    (:hook global-corfu-mode))
  (global-corfu-mode 1)

  ;; enable corfu on minibuffers like eval-expression
  (defun corfu-enable-in-minibuffer ()
    "Enable Corfu in the minibuffer if `completion-at-point' is bound."
    (when (where-is-internal #'completion-at-point (list (current-local-map)))
      ;; (setq-local corfu-auto nil) ;; Enable/disable auto completion
      (setq-local corfu-echo-delay nil ;; Disable automatic echo and popup
                  corfu-popupinfo-delay nil)
      (corfu-mode 1)))
  (add-hook 'minibuffer-setup-hook #'corfu-enable-in-minibuffer))

(setup (:elpaca corfu-terminal)
  ;; https://codeberg.org/akib/emacs-corfu-terminal#headline-6
  (unless (display-graphic-p)
    (corfu-terminal-mode 1)))
#+end_src

#+begin_src emacs-lisp
(setup (:elpaca prescient)
       (:elpaca corfu-prescient)
  (:load-after corfu)
  (:with-hook corfu-mode-hook
    (:hook corfu-prescient-mode))
  (:option prescient-persist-mode t))
#+end_src

*** Cape: Completion extensions!
- [[https://github.com/minad/cape][minad/cape: 🦸cape.el - Completion At Point Extensions]]
- [[https://kisaragi-hiu.com/switching-to-corfu.html][Switching to Corfu - Kisaragi Hiu]].
# [2022-12-01 Thu 01:46:10 -03]
#+begin_src emacs-lisp
;; Add extensions
(setup (:elpaca cape)
  ;; Bind dedicated completion commands
  ;; Alternative prefix keys: C-c p, M-p, M-+, ...
  ;; (:global-set
  ;;  "C-c p p" completion-at-point ;; capf
  ;;  "C-c p t" complete-tag        ;; etags
  ;;  "C-c p d" cape-dabbrev        ;; or dabbrev-completion
  ;;  "C-c p h" cape-history
  ;;  "C-c p f" cape-file
  ;;  "C-c p k" cape-keyword
  ;;  "C-c p s" cape-elisp-symbol
  ;;  "C-c p e" cape-elisp-block
  ;;  "C-c p a" cape-abbrev
  ;;  "C-c p l" cape-line
  ;;  "C-c p w" cape-dict
  ;;  "C-c p :" cape-emoji
  ;;  "C-c p \\" cape-tex
  ;;  "C-c p _" cape-tex
  ;;  "C-c p ^" cape-tex
  ;;  "C-c p &" cape-sgml
  ;;  "C-c p r" cape-rfc1345)
  ;; Add to the global default value of `completion-at-point-functions' which is
  ;; used by `completion-at-point'.  The order of the functions matters, the
  ;; first function returning a result wins.  Note that the list of buffer-local
  ;; completion functions takes precedence over the global list.
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-file)
  (add-to-list 'completion-at-point-functions #'cape-elisp-block)
  ;;(add-to-list 'completion-at-point-functions #'cape-history)
  ;;(add-to-list 'completion-at-point-functions #'cape-keyword)
  ;;(add-to-list 'completion-at-point-functions #'cape-tex)
  ;;(add-to-list 'completion-at-point-functions #'cape-sgml)
  ;;(add-to-list 'completion-at-point-functions #'cape-rfc1345)
  ;;(add-to-list 'completion-at-point-functions #'cape-abbrev)
  ;;(add-to-list 'completion-at-point-functions #'cape-dict)
  ;;(add-to-list 'completion-at-point-functions #'cape-elisp-symbol)
  ;;(add-to-list 'completion-at-point-functions #'cape-line)
  )
#+end_src

*** TempEl
[[https://github.com/minad/tempel][minad/tempel: TempEl - Simple templates for Emacs]].
See the example template file: [[https://github.com/minad/tempel#template-file-format][minad/tempel: TempEl - Simple templates for Emacs]].
#+begin_src emacs-lisp
(setup (:elpaca tempel)

  ;; Require trigger prefix before template name when completing.
  ;; (:option tempel-trigger-prefix "<")
  (:global-set
   "M-+" tempel-complete ;; Alternative tempel-expand
   "M-*" tempel-insert)

  ;; Setup completion at point
  (defun tempel-setup-capf ()
    ;; Add the Tempel Capf to `completion-at-point-functions'.
    ;; `tempel-expand' only triggers on exact matches. Alternatively use
    ;; `tempel-complete' if you want to see all matches, but then you
    ;; should also configure `tempel-trigger-prefix', such that Tempel
    ;; does not trigger too often when you don't expect it. NOTE: We add
    ;; `tempel-expand' *before* the main programming mode Capf, such
    ;; that it will be tried first.
    (setq-local completion-at-point-functions
                (cons #'tempel-expand
                      completion-at-point-functions)))


  ;; Optionally make the Tempel templates available to Abbrev,
  ;; either locally or globally. `expand-abbrev' is bound to C-x '.
  ;; (add-hook 'prog-mode-hook #'tempel-abbrev-mode)
  ;; (global-tempel-abbrev-mode)
  (:with-hook prog-mode-hook text-mode-hook
              (:hook tempel-setup-capf)))
#+end_src

*** Language Server Protocols (LSP)
*Arch packages:*
- [[https://github.com/bash-lsp/bash-language-server][bash-language-server]]
- [[https://github.com/typescript-language-server/typescript-language-server][typescript-language-server]]
- [[https://github.com/haskell/haskell-language-server#readme][haskell-language-server]]

**** lsp-mode
# :PROPERTIES:
# :header-args:emacs-lisp: :noweb-ref dummy :tangle no
# :END:

- [[https://emacs-lsp.github.io/lsp-mode/page/performance/#use-plists-for-deserialization][Performance - LSP Mode - LSP support for Emacs#Use =plists= for deserialization]]
  + Set environment variable
    : export LSP_USE_PLISTS=true
    or call Emacs as =LSP_USE_PLISTS=true emacs=.
  + In the case of using =straight.el= delete all cloned files:
    : cd "${XDG_CONFIG_HOME}"/emacs && fd -td lsp -x echo rm -rf
    /(remove echo to make real changes)/
  + Set =(setq lsp-use-plists t)= /before/ installing =lsp-mode= packages
  + [[https://github.com/emacs-lsp/lsp-mode/issues/837][Moving cursor is very slow · Issue #837 · emacs-lsp/lsp-mode]]
#+begin_src emacs-lisp
(setq lsp-use-plists t)
;; (setup (:elpaca lsp-haskell))
(setup (:elpaca lsp-ui)
  ;; (:option lsp-ui-doc-show-with-cursor t
  ;;          lsp-ui-doc-delay 0.5)
  )
(setup (:elpaca lsp-mode)
  ;; LSP Language server starter packages
  (:option lsp-idle-delay 0.1 ; 0.5 ; 0.1
           lsp-keymap-prefix "C-c l"
           lsp-log-io nil)

  ;; (setq lsp-ui-doc-enable nil) ; set to nil for better performance
  ) ; "(setup lsp-mode..." ends here
(setup (:elpaca flycheck))
#+end_src

**** Eglot
[[https://github.com/joaotavora/eglot][joaotavora/eglot: A client for Language Server Protocol servers]].
#+begin_src emacs-lisp
(setup (:elpaca eldoc-box))
(setup eglot ; built-in since Emacs 29
  (:option eglot-send-changes-idle-time 0.01)
  (:with-feature eldoc ; eglot uses eldoc for ui documentation
    ;; (add-hook 'eglot-managed-mode-hook #'eldoc-box-hover-mode)
    (:option eldoc-idle-delay 0.01
             eldoc-echo-area-prefer-doc-buffer t) ; e.g. display doc on a second monitor
    (:with-feature eldoc-box
      ;; prefixes eldoc-box- to options
      (:option* doc-separator (concat "\n\n" (make-string 3 ?-) "\n\n") ; code \u2501
                clear-with-C-g t
                max-pixel-height 1400))
    (:with-feature whitespace
      ;; Disable `show-trailing-whitespace' in eldox box hover childframe
      (:with-hook (eldoc-box-buffer-hook)
        (:hook (lambda() (setq-local show-trailing-whitespace nil)))))))
#+end_src

***** Performance
See [[https://emacs-lsp.github.io/lsp-mode/page/performance/][Performance - LSP Mode - LSP support for Emacs]]
# [2022-05-27 Fri 11:00:30 -03]

**** TODO lsp-bridge
- To sandbox the pip dependencies do:
  + On Linux
    : ❯ python -m venv ./.python-venv
    : ❯ ./.python-ven11xx--bin/pip install epc orjson sexpdata six setuptools paramiko rapidfuzz
    then source the venv before launching Emacs:
    : ❯ source ./python-ven11xx--bin/activate
    : ❯ emacs
  # + On Windows (#TODO does it work on windows-nt?)
  #   : python -m venv .\.python-venv
  #   : .\.python-venv\Scripts\pip.exe install epc orjson sexpdata six setuptools paramiko rapidfuzz
  # + Install Now set the python venv root inside Emacs:
- Or on Arch Linux install:
  : pacman -S python-orjson python-six python-setuptools python-paramiko python-rapidfuzz --needed
  : paru -S python-epc python-sexpdata --needed

#+begin_src emacs-lisp :noweb-ref dummy :tangle no
(setup (:elpaca yasnippet))
(setup-elpaca (lsp-bridge :host github :repo "manateelazycat/lsp-bridge"
                          :files (:defaults "*.el" "*.py" "acm/*" "core/*" "langserver/*" "multiserver/*" "resources/*")
                          :build (:not compile))
  (global-lsp-bridge-mode)
  )
#+end_src

[[https://github.com/manateelazycat/lsp-bridge#installation][manateelazycat/lsp-bridge: A blazingly fast LSP client for Emacs]]
#+begin_src emacs-lisp :noweb-ref dummy :tangle no
(setup (:elpaca pyenv-mode))

(let (python-shell-virtualenv-root "./.python-venv")
  (pythonic-activate)
  (run-python "python pip --version"))

(use-package lsp-bridge
  :vc (:url "manateelazycat/lsp-bridge"))

(setup-elpaca (lsp-bridge :host github :repo "manateelazycat/lsp-bridge"))

(setup (:elpaca yasnippet))
(setup-elpaca (lsp-bridge :host github :repo "manateelazycat/lsp-bridge"
                          :files (:defaults "*.el" "*.py" "acm/*" "core/*" "langserver/*" "multiserver/*" "resources/*")
                          :build (:not compile))
  ;;(global-lsp-bridge-mode)
  )
(elpaca (lsp-bridge :host github :repo "manateelazycat/lsp-bridge"
                          :files (:defaults "*.el" "*.py" "acm/*" "core/*" "langserver/*" "multiserver/*" "resources/*")
                          :build (:not compile)))
;; ~/.config/emacs/elpaca/builds/lsp-bridge/

(package-vc-install '(lsp-bridge :url "https://github.com/manateelazycat/lsp-bridge"))

(setup (:elpaca lsp-bridge :host github :repo "manateelazycat/lsp-bridge"))
#+end_src
Before testing disable Corfu or any other completion.
Run with =lsp-bridge-mode=.

*** Prescient
[[https://github.com/raxod502/prescient.el][raxod502/prescient.el: ☄️ Simple but effective sorting and filtering for Emacs.]]
# [2022-04-27 Wed 22:45:04]
Remembers used completion items and put them up.

**** Prescient with Corfu
See [[*Corfu][Corfu]].

* 11xx-ui.el: User Interface settings
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-ui.el
:END:

#+begin_src emacs-lisp
<<11xx-ui>>

(provide '11xx-ui)
#+end_src


** User Interface
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-ui :tangle no
:END:

*** Change UI modes
#+begin_src emacs-lisp
;;; UI
(menu-bar-mode -1)    ; Disable menu bar
(tool-bar-mode -1)    ; Disable toolbar
;; (ALARM-EMACS27-conflict): scroll-bar-mode is void on emacs-nox
(scroll-bar-mode -1)  ; Disable scrolllbar

(blink-cursor-mode 1)
(setopt blink-cursor-blinks 1)

(column-number-mode 1) ; column number in mode-line
(line-number-mode 1) ; line number in mode-line
;; (global-hl-line-mode 1) ;; highlight current line
;; (visual-line-mode 1)
;; (toggle-truncate-lines -1)
#+end_src

*** Font
#+begin_src emacs-lisp
;; Font configuration
;; Check if on Windows and change font (Windows-NT)
(defvar 11xx--get-default-font
  (if (eq system-type 'windows-nt)
      ;; "Consolas"
      ;; "Literation Mono Nerd Font" on Linux or "LiterationMono Nerd Font" on (Windows-NT)
      "LiterationMono Nerd Font"
    "Literation Mono Nerd Font")
  "Sets the default font based on the system type.
To be used with `set-font'.")

(defvar 11xx--get-default-font-size
  (if (eq system-type 'windows-nt)
      11
    11)
  "Sets the default font size based on the system type.
To be used with `set-font'.")

(defun set-font (&rest args)
  "Set font face using `set-face-attribute' and keywords.
Available keywords are:

`:name' = a string with the font name like \"Liberation Mono\" or
\"DejaVu Sans Mono\". It defaults to the value from the helper
function `f/get-default-font' that returns a string.

`:size' = a number that is multiplied by 10 internally to pass as
\":height\" to `set-face-attribute'. It defaults to the value
from the helper function `f/get-default-font-size' that returns a
number."
  (let* ((font (or (plist-get args :name) 11xx--get-default-font))
         (size (or (plist-get args :size) 11xx--get-default-font-size)))
    (set-face-attribute 'default nil
                        :font font
                        :height (* size 10))))

(if (daemonp) ;; Load font after daemon frame is created/init hook
    (add-hook 'after-make-frame-functions
              (lambda (frame)
                (with-selected-frame frame
                  (set-font))))
  (add-hook 'elpaca-after-init-hook
            (lambda () (set-font))))
;; end set font
#+end_src

*** Options
#+begin_src emacs-lisp
(setopt cursor-type 'box
        ;; display-line-numbers-type 'relative
        linum-relative-current-symbol ""
        inhibit-startup-screen t
        auto-hscroll-mode 'current-line ; nano-like line horizontal scrolling ; https://emacs.stackexchange.com/questions/40864/scroll-only-current-line-when-truncating-lines
        use-dialog-box nil)
#+end_src

*** Display line numbers
#+begin_src emacs-lisp
(setup display-line-numbers
  (:disabled)
  ;; disable line numbers for some modes

  (:option* grow-only t) ;; prevents difference between 10s, 100s,
                         ;; etc, line numbers from ;; flicker-pushing
                         ;; content to the side.

  (:hook-into prog-mode text-mode html-mode)
  (:with-hook (term-mode-hook
               shell-mode-hook
               eshell-mode-hook
               org-mode-hook)
    (:hook (lambda() (display-line-numbers-mode -1)))))
#+end_src

*** Parens appearance
#+begin_src emacs-lisp
(setopt show-paren-mode t
        show-paren-delay 0.01
        show-paren-style 'parenthesis)

(setup (:elpaca rainbow-delimiters)
  (:hook-into emacs-lisp-mode))
#+end_src

*** Theme
#+begin_seealso
- [[#prevent-white-flashbang-on-startup][Prevent white flashbang on startup]]
- [[https://emacs.stackexchange.com/questions/2797/emacs-wont-load-theme-on-startup/19271#19271][init file - Emacs won't load theme on startup - Emacs Stack Exchange]]
- [[https://stackoverflow.com/questions/22977387/setting-the-emacs-theme-on-startup-without-the-interactive-mode][elisp - setting the emacs theme on startup without the interactive mode - Stack Overflow]]
- [[https://stackoverflow.com/questions/18904529/after-emacs-deamon-i-can-not-see-new-theme-in-emacsclient-frame-it-works-fr/23668935#23668935][After 'emacs --deamon' I can not see new theme in emacsclient frame. It works from 'emacs M-x server-start' - Stack Overflow]]
#+end_seealso

**** Load theme path
*NOTE:* Make sure to save a custom theme with the =-theme= suffix,
otherwise Emacs will ignore the file.
# My dumbass ignored this for two days of "troubleshooting" :s [2022-04-13 Wed 22:08:31]
#+begin_src emacs-lisp
(let ((themedir (expand-file-name "themes/" user-emacs-directory)))
  (add-to-list 'custom-theme-load-path themedir)
  (add-to-list 'load-path themedir))
#+end_src

**** Remove background color when opening from terminal
wizard [[https://stackoverflow.com/questions/19054228/emacs-disable-theme-background-color-in-terminal/20233611#20233611][Emacs: disable theme background color in terminal - Stack Overflow]]
Remove background face when on terminal
#+begin_src emacs-lisp
(defun on-after-init ()
  (unless (display-graphic-p (selected-frame))
    (set-face-background 'default "unspecified-bg" (selected-frame))))
(add-hook 'window-setup-hook #'on-after-init)
;; idk if the string "unspecified-bg" specifically has to be used but it works


;; [[https://stackoverflow.com/questions/19054228/emacs-disable-theme-background-color-in-terminal/33298750#33298750][Emacs: disable theme background color in terminal - Stack Overflow]]
(defun on-frame-open (&optional frame)
  "If the FRAME created in terminal don't load background color."
  (unless (display-graphic-p frame)
    (set-face-background 'default "unspecified-bg" frame)))
(add-hook 'after-make-frame-functions #'on-frame-open)
#+end_src
# [2022-12-03 Sat 00:26:02 -03]

**** Day/Night theme switch
Load theme based on Dark or Light system theme:
- Dependencies:
  + =xdg-desktop-portal=, there are multiple providers targeted for
    different Desktop Environments and Window Managers, install one
    and it should provide the dbus that =auto-dark= depends on.

- =auto-dark= Supports Linux/Mac/Windows
  + See [[https://github.com/LionyxML/auto-dark-emacs][GitHub - LionyxML/auto-dark-emacs: Auto-Dark-Emacs is an auto changer between 2 themes, dark/light, following MacOS, Linux or Windows Dark Mode settings]]
  + NOTE: for this package to work with =darkman= the file
    =~/.config/xdg-desktop-portal/portals.conf= has to override
    =org.freedesktop.impl.portal.Settings= to use darkman's
    implementation, e.g.:
    See [[file:~/.config/darkman/README.org::#orgid-ohmzyr][Making Darkman portal implementation work on minimal setups]].
    #+begin_example
    [preferred]
    org.freedesktop.impl.portal.Settings=darkman
    #+end_example

#+begin_src emacs-lisp
;; (elpaca (neron-themes :host codeberg
;;                       :repo "11xx/neron-themes"
;;                       :files ("neron-*.el")))
(elpaca (neron-themes :host codeberg :repo "~/clones/neron-themes" :files ("neron-*.el"))) ; dev

(setup (:elpaca auto-dark)
  (setopt auto-dark-themes '((neron-dark)
                             (neron-light)))
  (auto-dark-mode)
  (:hide-mode))
#+end_src

*** ibuffer mode
[[https://www.reddit.com/r/emacs/comments/19xwk3/comment/c8sg4rq/?utm_source=share&utm_medium=web2x&context=3][wizard src]] | [[http://martinowen.net/blog/2010/02/03/tips-for-emacs-ibuffer.html][Tips for using Emacs Ibuffer]]
#+begin_src emacs-lisp
(setup ibuffer
  (:option ibuffer-show-empty-filter-groups nil
           ibuffer-saved-filter-groups (quote
                                        (("default"
                                          ("shell"      (mode . shell-mode))
                                          ("dired"      (mode . dired-mode))
                                          ("org"        (mode . org-mode))
                                          ("emacs-lisp" (mode . emacs-lisp)))))
           ibuffer-expert t)
  (:hook (lambda() (ibuffer-switch-to-saved-filter-groups "default")))
  (:global-set "C-x C-b" ibuffer))
#+end_src

*** Ruler
#+begin_src emacs-lisp
(setup display-fill-column-indicator-mode
  (:hook-into prog-mode text-mode)
  (:option display-fill-column-indicator-column 79)
  (:with-hook prog-mode
    (:hook (lambda() (setq-local display-fill-column-indicator-column 120))))
  (display-fill-column-indicator-mode 1))
#+end_src

*** Modeline

**** Doom Modeline
[[https://github.com/daviwil/emacs-from-scratch/blob/master/Emacs.org#better-modeline][daviwil/emacs-from-scratch/Emacs.org#Better Modeline]]
# [2022-05-07 Sat 02:54:50]
[[https://github.com/seagle0128/doom-modeline#customize=][seagle0128/doom-modeline]]
# [2022-05-07 Sat 03:02:57]

and more examples [[https://www.reddit.com/r/emacs/comments/izksoi/2020_modelines_besides_doom/][2020 Modelines besides Doom? : emacs]]
# [2022-05-07 Sat 03:45:54]
#+begin_src emacs-lisp
(setup (:elpaca doom-modeline)
  (:hook-into elpaca-after-init-hook)
  (:option doom-modeline-height 15
           doom-modeline-buffer-encoding nil
           ;; display-time-format '%H:%M'
           doom-modeline-percent-position nil
           doom-modeline-icon nil
           doom-modeline-enable-word-count nil ; Performance
           doom-modeline-buffer-file-name-style 'relative-from-project
           ))
#+end_src

**** Window margin/padding
#+begin_src emacs-lisp
(set-window-margins nil 1)
#+end_src
- See
  [[https://emacs.stackexchange.com/questions/19022/adding-padding-to-the-left-of-text-in-buffer/19041#19041][linum mode - Adding padding to the left of text in buffer - Emacs Stack Exchange]]
  [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Margins.html][Display Margins (GNU Emacs Lisp Reference Manual)]]
  # [2023-06-06 07:35:53]

*** Fira Code ligatures minor mode
:PROPERTIES:
:header-args:emacs-lisp: :noweb-ref dummy :tangle no
:END:
[[https://melpa.org/#/fira-code-mode][fira-code-mode - MELPA]]

Display code ligatures using supported font symbols.

Install =otf-fira-code-symbol= from the AUR

The funciton =(fira-code-mode-set-font)= seems to be required having installed
Fira Code Symbol externally.
[[https://github.com/jming422/fira-code-mode#troubleshooting-common-issues][jming422/fira-code-mode:Troubleshooting Common Issues]]

[[https://github.com/microsoft/cascadia-code][microsoft/cascadia-code]]
[[https://github.com/tonsky/FiraCode/wiki/Emacs-instructions#using-prettify-symbols=][Emacs instructions · tonsky/FiraCode Wiki]]

# [2022-05-30 Mon 13:53:19 -03]
# b [2023-06-19 Mon 15:52:18 -03]

#+begin_src emacs-lisp
(setup (:elpaca fira-code-mode)
  (:hook-into prog-mode)
  (require 'fira-code-mode)
  (dolist (ligature '("-}"))
    (add-to-list 'fira-code-mode-disabled-ligatures ligature)))
#+end_src
- Note: It doesn't work properly on terminal

*** ligature.el
:PROPERTIES:
:header-args:emacs-lisp: :noweb-ref dummy :tangle no
:END:
# this doesnt work as "secondary" just for ligatures, or i couldn't figure out
- [[https://github.com/tonsky/FiraCode/wiki/Emacs-instructions#using-ligatureel][Emacs instructions · tonsky/FiraCode Wiki]]
#+begin_src emacs-lisp
(setup (:elpaca ligature)
  ;; Enable the www ligature in every possible major mode
  (ligature-set-ligatures 't '("www"))

  ;; Enable ligatures in programming modes
  (ligature-set-ligatures 'prog-mode '("www" "**" "***" "**/" "*>" "*/" "\\\\" "\\\\\\" "{-" "::"
                                       ":::" ":=" "!!" "!=" "!==" "-}" "----" "-->" "->" "->>"
                                       "-<" "-<<" "-~" "#{" "#[" "##" "###" "####" "#(" "#?" "#_"
                                       "#_(" ".-" ".=" ".." "..<" "..." "?=" "??" ";;" "/*" "/**"
                                       "/=" "/==" "/>" "//" "///" "&&" "||" "||=" "|=" "|>" "$>" "^="
                                       "++" "+++" "+>" "=:=" "==" "===" "==>" "=>" "=>>" "<="
                                       "=<<" "=/=" ">-" ">=" ">=>" ">>" ">>-" ">>=" ">>>" "<*"
                                       "<*>" "<|" "<|>" "<$" "<$>" "<!--" "<-" "<--" "<->" "<+"
                                       "<+>" "<=" "<==" "<=>" "<=<" "<>" "<<" "<<-" "<<=" "<<<"
                                       "<~" "<~~" "</" "</>" "~@" "~-" "~>" "~~" "~~>" "%%"))

  (global-ligature-mode t))
#+end_src

* 11xx-half-scroll.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-half-scroll.el :noweb-ref 11xx-half-scroll
:END:

Scroll half-page hack: [[https://www.emacswiki.org/emacs/HalfScrolling][emacswiki.org/Half Scrolling]]
#+begin_src emacs-lisp
;; source https://www.emacswiki.org/emacs/HalfScrolling
(defun window-half-height ()
  (max 1 (/ (1- (window-height (selected-window))) 2)))

(cl-defun window-div-height (&optional (n 2))
  (max 1 (/ (1- (window-height (selected-window))) n)))

(defun scroll-up-half ()
  (interactive)
  (scroll-up (window-half-height)))

(defun scroll-down-half ()
  (interactive)
  (scroll-down (window-half-height)))

;;;###autoload
(defun scroll-up-div ()
  (interactive)
  (scroll-up (window-div-height 10)))

;;;###autoload
(defun scroll-down-div ()
  (interactive)
  (scroll-down (window-div-height 10)))

(keymap-global-set "<remap> <scroll-up-command>" #'scroll-up-div)
(keymap-global-set "<remap> <scroll-down-command>" #'scroll-down-div)

(provide '11xx-half-scroll)
#+end_src
# ;; [next] good-scroll-up-full-screen
# ;; [prior] good-scroll-down-full-screen
# ;; Scroll
# ;; "<remap> <scroll-up-command>" scroll-up-half
# ;; "<remap> <scroll-down-command>" scroll-down-half
# ;; "<remap> <scroll-up-command>" pixel-scroll-up
# ;; "<remap> <scroll-down-command>" pixel-scroll-down
* 11xx-pixel-scroll.el: Smooth scrolling
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-pixel-scroll.el :noweb-ref 11xx-pixel-scroll
:END:
- See
  + [[https://www.emacswiki.org/emacs/SmoothScrolling#h5o-1][EmacsWiki: Smooth Scrolling]]
  + [[https://stackoverflow.com/questions/1128927/how-to-scroll-line-by-line-in-gnu-emacs/1128948#1128948][How to scroll line by line in GNU Emacs? - Stack Overflow]]

#+begin_src emacs-lisp
(setup pixel-scroll
  ;; (:only-if (display-graphic-p))
  (pixel-scroll-precision-mode)
  (:hook-into elpaca-after-init-hook)
  (:option pixel-scroll-precision-use-momentum t
           pixel-scroll-precision-large-scroll-height 5.0
           mouse-wheel-scroll-amount '(1 ((shift) . 1)) ; one line at a time
           mouse-wheel-progressive-speed nil ; don't accelerate scrolling
           mouse-wheel-follow-mouse 't)) ; scroll window under mouse

(provide '11xx-pixel-scroll)
#+end_src

* 11xx-navigation.el: Controlling Emacs
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-navigation.el
:END:

#+begin_src emacs-lisp
<<11xx-navigation>>

(provide '11xx-navigation)
#+end_src

** def
:PROPERTIES:
:header-args:emacs-lisp+: :noweb-ref 11xx-navigation :tangle no
:END:

*** Navigation

**** Window movement with ace-window
[[https://www.admiralbumblebee.com/programming/2020/01/04/Six-months-VS-Code.html#window-management][Window Management with ace-window src]]

Packages for enhanced Emacs minibuffers and better completions/matches
https://youtu.be/43Dg5zYPHTU

**** Rotate frames
wizard [[https://emacs.stackexchange.com/questions/5371/how-to-change-emacs-windows-from-vertical-split-to-horizontal-split/5372#5372][How to change Emacs windows from vertical split to horizontal split? - Emacs Stack Exchange]]
# [2022-12-02 Fri 23:34:18 -03]

Use the package =transpose-frame= (see [[https://www.emacswiki.org/emacs/TransposeFrame][EmacsWiki: Transpose Frame]]):
#+begin_src emacs-lisp
(setup (:elpaca transpose-frame)
  (defun f/rotate-frame-clockwise-or-default ()
    "Rotate frame clockwise if more than one frame exists; otherwise, execute default command."
    (interactive)
    (if (window-parent)
        (rotate-frame-clockwise)
      ;; Default command:
      (call-interactively #'move-to-window-line-top-bottom)))

  (defun f/rotate-frame-anticlockwise-or-default ()
    "Rotate frame anticlockwise if more than one frame exists; otherwise, execute default command."
    (interactive)
    (if (window-parent)
        (rotate-frame-anticlockwise)
      ;; Default command:
      (call-interactively #'move-to-window-line-top-bottom)))

  (:global-set
   "M-r" #'f/rotate-frame-clockwise-or-default ;; was #'move-to-window-line-top-bottom
   "M-S-r" #'f/rotate-frame-anticlockwise-or-default ;; was #'move-to-window-line-top-bottom
   ))
#+end_src

*** Multiple Cursors
~multiple-cursors~
#+begin_src emacs-lisp
(setup (:elpaca multiple-cursors)
  (:global-set
   "C-S-c C-S-c" mc/edit-lines
   "C-<" mc/mark-previous-like-this
   "C->" mc/mark-next-like-this
   "C-c C-<" mc/mark-all-like-this))
#+end_src


* llm-ai-assistants.el: Large Language Models (LLM) AI Assistants
:PROPERTIES:
:header-args:emacs-lisp: :tangle lisp/llm-ai-assistants.el
:END:

#+begin_src emacs-lisp
;;; llm-ai-assistants.el --- AI assistant features config -*- lexical-binding: t -*-

;;; Code
#+end_src

** gptel
- See
  + [[https://www.reddit.com/r/emacs/comments/14glmqc/use_emacs_as_a_chatgpt_app/][Use emacs as a ChatGPT app : emacs]]
    that links [[https://www.armindarvish.com/en/post/use_emacs_as_a_chatgpt_client/][Use Emacs as a ChatGPT App from Anywhere on Your System | /\r|\/|i|\|]]
  + [[https://github.com/karthink/gptel][karthink/gptel: A no-frills ChatGPT client for Emacs]]
  + ChatGPT API keys can be generated from
    https://platform.openai.com/account/api-keys
# [2023-06-23 Fri 13:14:22 -03]
#+begin_src emacs-lisp
(setup gptel
  (:elpaca gptel)
  (setopt gptel-model 'gpt-5.4-nano
          gptel-default-mode 'org-mode)

  (with-eval-after-load 'gptel-openai
    (dolist (model
             ;; info from 20260327 https://developers.openai.com/api/docs/models
             '((gpt-5.4-mini
                :description "Strong mini model for coding, computer use, and subagents"
                :capabilities (media tool-use json url)
                :mime-types ("image/jpeg" "image/png" "image/gif" "image/webp")
                :context-window 400
                :input-cost 0.75
                :output-cost 4.5
                :cutoff-date "2025-08")
               (gpt-5.4-nano
                :description "Cheapest GPT-5.4-class model for simple high-volume tasks"
                :capabilities (media tool-use json url)
                :mime-types ("image/jpeg" "image/png" "image/gif" "image/webp")
                :context-window 400
                :input-cost 0.2
                :output-cost 1.25
                :cutoff-date "2025-08")))
      (setq gptel--openai-models
            (assq-delete-all (car model) gptel--openai-models))
      (setq gptel--openai-models
            (append gptel--openai-models (list model))))
    (setopt gptel-backend (gptel-make-openai "ChatGPT"
                            :stream t
                            :models gptel--openai-models)))

  (gptel-make-gemini "Gemini"
    :stream t
    :key (gptel-api-key-from-auth-source "generativelanguage.googleapis.com"))
  (gptel-make-anthropic "Claude"
    :stream t
    :key (gptel-api-key-from-auth-source "api.anthropic.com"))

  (gptel-make-ollama "Ollama"
    :host "localhost:11434"
    :stream t
    :models '(qwen3.5:9b
              qwen2.5-coder:14b
              ))

  (with-eval-after-load 'org
    (add-to-list 'org-use-property-inheritance "GPTEL_MODEL")
    (add-to-list 'org-use-property-inheritance "GPTEL_BACKEND")
    (add-to-list 'org-use-property-inheritance "GPTEL_SYSTEM")
    (add-to-list 'org-use-property-inheritance "GPTEL_TEMPERATURE"))
  )

(use-package ob-gptel
  :after gptel
  :load-path "~/clones/11xx-ob-gptel/"
  :config
  (add-to-list 'org-babel-load-languages '(gptel . t))
  (defun ob-gptel-setup-completions ()
    (add-hook 'completion-at-point-functions
              'ob-gptel-capf nil t))

  (add-to-list 'org-structure-template-alist '("gp" . "src gptel"))

  :hook (org-mode . ob-gptel-setup-completions))

(with-eval-after-load 'gptel
  (defun gptel--append-response-footer (beg end)
    "Append a footer after a completed gptel response."
    (when (> end beg)
      (save-excursion
        (goto-char end)
        (insert
         (pcase major-mode
           ('markdown-mode
            (concat "\n\n[comment]: <> (Responded: "
                    (format-time-string "%Y-%m-%d %a %H:%M:%S %:::z")
                    ")"))
           ('org-mode
            (concat "\n\n# Responded: "
                    (format-time-string "%Y-%m-%d %a %H:%M:%S %:::z")))
           (_ ""))))))

  (add-hook 'gptel-post-response-functions #'gptel--append-response-footer))

(use-package gptel-titler
  :after gptel
  :load-path "~/code/emacs/gptel-titler/")
#+end_src

mcp
#+begin_src emacs-lisp
(elpaca mcp
  (use-package mcp
    :init
    (setopt mcp-hub-servers
            '(("searxng-isokoliuk" . (:command "podman"
                                               :args ("run" "--rm" "-i"
                                                      "--network" "host"
                                                      "-e" "SEARXNG_URL=http://127.0.0.1:32768"
                                                      "isokoliuk/mcp-searxng:latest")))
              ("searxng-icewreck" . (:command "podman"
                                              :args ("run" "--rm" "-i"
                                                     "--network" "host"
                                                     "-e" "SEARXNG_URL=http://127.0.0.1:32768"
                                                     "docker.io/icewreck/searxng-mcp-server:latest")))))
    ))

(use-package gptel-integrations
  :after mcp)
#+end_src

** chat file helper
#+begin_src emacs-lisp
(defun new-ai-chat-file (&optional new-file)
  (interactive)
  (let* ((defoutfile (expand-file-name (concat (time-stamp-string "%Y%m%dT%H%M%S") ".org") "~/ai/chats/"))
         (outfile (file-truename (or new-file defoutfile))))
    (find-file outfile)))
#+end_src


** provide pseudo-package
#+begin_src emacs-lisp
(provide 'llm-ai-assistants)
;;; llm-ai-assistants.el ends here
#+end_src


* 11xx-pdf-viewer.el
- [[https://www.reddit.com/r/emacs/comments/opkzxm/view_pdf_in_dark_mode_with_pdftools/][View PDF in dark mode with pdf-tools : r/emacs]]
- [[https://github.com/vedang/pdf-tools][vedang/pdf-tools: Emacs support library for PDF files.]]
#+begin_src emacs-lisp :noweb-ref dummy :tangle lisp/11xx-pdf-viewer.el
(setup (:elpaca org-pdftools))
(setup (:elpaca pdf-tools)
  ;; (pdf-tools-install)
  (:with-map pdf-view-mode-map
    (:bind "j" pdf-view-next-line-or-next-page
           "k" pdf-view-previous-line-or-previous-page
           ))
  (:with-hook pdf-view-mode-hook
    (:hook pdf-view-themed-minor-mode)))

(provide '11xx-pdf-viewer)
#+end_src

** Troubleshooting
Getting =[...]: pdf-info-epdfinfo-program is not executable= means
epdfinfo was not built. Having installed from MELPA or NonGNU ELPA it
should be available but running =pdf-tools-install= may be necessary:
: M-x pdf-tools-install
or eval =(pdf-tools-install)=, it returns nil if it successfully detects
a working executable.
- See [[https://github.com/politza/pdf-tools/issues/288][pdf-info-check-epdfinfo: pdf-info-epdfinfo-program is not executable · Issue #288 · politza/pdf-tools]]

* 11xx-latex.el: LaTeX config
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/11xx-latex.el
:END:

- See [[https://abode.karthinks.com/org-latex-preview/][org-latex-preview: Set up and troubleshooting]]
  # [2024-09-18 Wed 19:39:19 -03] @ak

For math and chemestry equations and notations.
# [2022-12-07 Wed 09:15:05 -03]

=tex-mode.el= provides =latex-mode=:
#+begin_src emacs-lisp
(setup tex-mode
#+end_src

Install auctex for a better, faster backend:
[[https://karthinks.com/software/fast-latex-previews-in-org-mode/][Fast Latex previews in Org-mode | Karthinks]]
#+begin_src emacs-lisp
(:elpaca auctex)
#+end_src

*** Customize LaTeX preview image size
#wizard [[https://emacs.stackexchange.com/questions/19880/font-size-control-of-latex-previews-in-org-files/33992#33992][org mode - Font size control of LateX previews in Org files - Emacs Stack Exchange]]
#+begin_src emacs-lisp :tangle no
(:option org-format-latex-options (plist-put org-format-latex-options :scale 1.5))
#+end_src

Export sizes of LaTeX in HTML, from Org Mode
[[https://emacs.stackexchange.com/questions/59174/properly-exporting-latex-to-html-from-org-mode-using-dvisvgm-dvipng/59184#59184][Properly exporting latex to HTML from org-mode using dvisvgm / dvipng - Emacs Stack Exchange]]
#+begin_src emacs-lisp
(with-eval-after-load 'ox-html
  (setq org-html-head
        (replace-regexp-in-string
         ".org-svg { width: 90%; }"
         ".org-svg { width: auto; }"
         org-html-style-default)))
#+end_src
end of ~setup tex-mode~:
#+begin_src emacs-lisp
) ; end of (setup tex-mode
#+end_src

LaTeX preview in org-mode:
- [[https://github.com/io12/org-fragtog][io12/org-fragtog: Automatically toggle Org mode LaTeX fragment previews as the cursor enters and exits them]]
- See "=LaTeX previews=" heading: [[https://lucidmanager.org/productivity/ricing-org-mode/][Ricing Org Mode: A Beautiful Writing Environment]]
#+begin_src emacs-lisp
(setup (:elpaca org-fragtog))
#+end_src

* dired-hl-line-mode.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/dired-hl-line-mode.el
:END:

#+begin_src emacs-lisp
;;; dired-hl-line-mode.el --- Hide block cursor and highlights current line with hl-line -*- lexical-binding: t -*-

;;; Commentary
;; Minor mode for Dired that hides the block cursor and enables `hl-line'.
;; Automatically transitions in/out when entering wdired or dired-efap for editing.

;;; Code

(require 'hl-line)

(defun dired-hl-line-mode--on ()
  "Enable hl-line and hide cursor."
  (hl-line-mode 1)
  (setq-local cursor-type nil))

(defun dired-hl-line-mode--off ()
  "Disable hl-line and restore cursor."
  (hl-line-mode -1)
  (setq-local cursor-type t))

(defun dired-hl-line-mode--maybe-on (&rest _)
  "Re-enable if mode is active in this buffer."
  (when dired-hl-line-mode
    (dired-hl-line-mode--on)))

(defun dired-hl-line-mode--maybe-off (&rest _)
  "Disable if mode is active in this buffer."
  (when dired-hl-line-mode
    (dired-hl-line-mode--off)))

(define-minor-mode dired-hl-line-mode
  "Toggle hl-line + hidden cursor for read-only Dired browsing."
  :lighter " HlC"
  :group 'dired
  (if dired-hl-line-mode
      (progn
        (add-hook 'wdired-mode-hook #'dired-hl-line-mode--maybe-off nil t)
        (advice-add 'wdired-change-to-dired-mode      :after #'dired-hl-line-mode--maybe-on)
        (advice-add 'dired-efap                       :after #'dired-hl-line-mode--maybe-off)
        (advice-add 'dired-efap--change-to-dired-mode :after #'dired-hl-line-mode--maybe-on)
        (dired-hl-line-mode--on))
    (remove-hook 'wdired-mode-hook                   #'dired-hl-line-mode--maybe-off t)
    (advice-remove 'wdired-change-to-dired-mode      #'dired-hl-line-mode--maybe-on)
    (advice-remove 'dired-efap                       #'dired-hl-line-mode--maybe-off)
    (advice-remove 'dired-efap--change-to-dired-mode #'dired-hl-line-mode--maybe-on)
    (dired-hl-line-mode--off)))

(provide 'dired-hl-line-mode)
;;; dired-hl-line-mode.el ends here
#+end_src


* org-bitwarden.el
:PROPERTIES:
:header-args:emacs-lisp+: :tangle lisp/org-bitwarden.el :noweb no
:END:

#+begin_src emacs-lisp
;;; org-bitwarden.el --- Bitwarden secret helper for Org Babel -*- lexical-binding: t -*-

;; Author: 11xx
;; Version: 20260313
;; Package-Requires: ((emacs "27.1") (org "9.7"))
;; Keywords: org, babel, bitwarden, secrets

;;; Commentary:
;; Registers a `bw' named block in the Org Library of Babel so any org
;; file can retrieve Bitwarden secrets via noweb references:
;;
;;   <<bw(uuid="3e8a1f42-dc4b-4f2a-b7e1-0c9a3d7b2e15")>>
;;   <<bw(uuid="3e8a1f42-dc4b-4f2a-b7e1-0c9a3d7b2e15", field="username")>>
;;
;; Setup — add to init.el:
;;   (require 'org-bitwarden)
;;
;; Selecting a backend:
;;   (setq org-bitwarden-backend 'rbw)   ; default
;;   (setq org-bitwarden-backend 'bw)    ; official Bitwarden CLI
;;
;; Registering a custom backend:
;;   (org-bitwarden-register-backend 'my-backend #'my-getter-fn)
;;   ;; my-getter-fn signature: (uuid-or-name field) -> string
;;
;; Suppress confirmation prompts in an org file by adding at the bottom:
;;   # Local Variables:
;;   # org-confirm-babel-evaluate: nil
;;   # End:

;;; Code:

(require 'ob-lob)


(defgroup org-bitwarden nil
  "Bitwarden secret retrieval for Org Babel."
  :group 'org-babel
  :prefix "org-bitwarden-")


(defvar org-bitwarden--backends '()
  "Alist of (SYMBOL . FUNCTION) backend entries.
Each function must accept (uuid-or-name field) and return a string.
Use `org-bitwarden-register-backend' to add entries.")

(defcustom org-bitwarden-backend 'rbw
  "Backend used to retrieve Bitwarden secrets.

Built-in values:
  `rbw'  — unofficial Rust client with background daemon (recommended)
  `bw'   — official Bitwarden Node.js CLI

Custom backends can be added via `org-bitwarden-register-backend'."
  :type '(symbol)
  :group 'org-bitwarden)

(defun org-bitwarden-register-backend (name fn)
  "Register a Bitwarden retrieval backend.

NAME is a symbol identifying the backend (e.g. \\='my-backend).
FN is a function of two string arguments (UUID-OR-NAME FIELD)
that returns the secret as a string, or signals an error.

Example:
  (org-bitwarden-register-backend
   \\='my-backend
   (lambda (uuid field)
     (my-vault-get uuid field)))

After registering, select it with:
  (setq org-bitwarden-backend \\='my-backend)"
  (unless (symbolp name)
    (error "org-bitwarden: backend name must be a symbol, got %S" name))
  (unless (functionp fn)
    (error "org-bitwarden: backend function must be callable, got %S" fn))
  (setf (alist-get name org-bitwarden--backends) fn))

(defun org-bitwarden--rbw-get (uuid field)
  "Retrieve FIELD from Bitwarden item UUID-OR-NAME using rbw."
  (unless (executable-find "rbw")
    (error "org-bitwarden: `rbw' not found in PATH"))
  (string-trim
   (shell-command-to-string
    (format "rbw get --field %s %s"
            (shell-quote-argument field)
            (shell-quote-argument uuid)))))

(defun org-bitwarden--bw-get (uuid field)
  "Retrieve FIELD from Bitwarden item UUID-OR-NAME using the official bw CLI."
  (unless (executable-find "bw")
    (error "org-bitwarden: `bw' not found in PATH"))
  (unless (getenv "BW_SESSION")
    (error (concat "org-bitwarden: BW_SESSION not set — "
                   "run `bw unlock' and export the session token")))
  ;; bw uses positional subcommands, not --field, for standard fields
  (let* ((subcmd (if (member field '("password" "username" "uri" "notes" "name"))
                     field
                   ;; custom fields require --raw + jq; fall back to a
                   ;; clear error since bw has no --field flag
                   (error (concat "org-bitwarden: `bw' backend does not support "
                                  "custom field %S — use `rbw' instead")
                          field)))
         (val (string-trim
               (shell-command-to-string
                (format "bw get %s %s"
                        (shell-quote-argument subcmd)
                        (shell-quote-argument uuid))))))
    val))

(org-bitwarden-register-backend 'rbw #'org-bitwarden--rbw-get)
(org-bitwarden-register-backend 'bw  #'org-bitwarden--bw-get)

;; retrieval
(defun org-bitwarden-get (uuid field)
  "Retrieve FIELD from Bitwarden item UUID-OR-NAME using `org-bitwarden-backend'.

UUID is a Bitwarden item UUID (preferred) or item name.
FIELD is the field name: \"password\" (default), \"username\",
or any custom field name defined on the item.

Signals an error if the result is empty or the backend fails."
  (let ((fn (alist-get org-bitwarden-backend org-bitwarden--backends)))
    (unless fn
      (error "org-bitwarden: unknown backend `%s' — register it with \
`org-bitwarden-register-backend'" org-bitwarden-backend))
    (let ((val (funcall fn uuid field)))
      (cond
       ((not (stringp val))
        (error "org-bitwarden: backend returned non-string %S" val))
       ((string-empty-p val)
        (error "org-bitwarden: empty result — uuid=%s field=%s" uuid field))
       (t val)))))

;; Library of Babel
(defconst org-bitwarden--lob-source
  "
,#+NAME: bw
,#+begin_src emacs-lisp :var uuid=\"\" field=\"password\" :tangle no :exports none
(org-bitwarden-get uuid field)
,#+end_src
"
  "Org source for the `bw' Library of Babel block.
Calls `org-bitwarden-get' which dispatches to `org-bitwarden-backend'.")

(defun org-bitwarden-lob-ingest ()
  "Idempotently register the `bw' block in the Org Library of Babel."
  (unless (assq 'bw org-babel-library-of-babel)
    (with-temp-buffer
      (insert org-bitwarden--lob-source)
      (org-mode)
      (org-babel-lob-ingest))))

(defun org-bitwarden-unload-function ()
  "Clean up LOB entry when package is unloaded via `unload-feature'."
  (setq org-babel-library-of-babel
        (assq-delete-all 'bw org-babel-library-of-babel))
  nil)

;; Init
(org-bitwarden-lob-ingest)

(provide 'org-bitwarden)
;;; org-bitwarden.el ends here

#+end_src


* File Local Variables                                             :noexport:
- [[https://www.reddit.com/r/orgmode/comments/jy8fuc/orgbabeltangle_on_save/][org-babel-tangle on save? : r/orgmode]]
- [[https://gitlab.com/joseph8th/literatemacs/-/blob/master/README.org?ref_type=heads&plain=1#L1915][README.org · master · Joseph E. Edwards VIII / literatemacs · GitLab]]
- [[https://web.archive.org/web/20230117073433/https://github.com/joseph8th/literatemacs#conclusion][GitHub - joseph8th/literatemacs: My literate Emacs config]]

#+begin_comment
# Local Variables:
# eval: (add-hook 'org-babel-tangle-finished-hook #'org-babel-tangle-add-lexical-prop-to-el-tangled-files nil nil)
# End:
#+end_comment
