#+TITLE: darkman: Dark/Light switcher by D-Bus API, scripts & IPCs

# originally used 2021-10-27, back # [2023-06-03 Sat 08:25:12 -03]
# moved # [2024-02-17 Sat 17:42:40 -03] @ak

# Export as HTML

Check =XDG_DATA_DIRS=, where darkman searches for directories
=light-mode.d= and =dark-mode.d= (defaults to =~/.local/share= for users).

* =config.yaml=: Darkman's config file
:PROPERTIES:
:header-args:yaml: :tangle config.yaml
:END:
- To get the latitude and longitude of a city go to Google Maps and
  + On PC: Right click on a general region and click the first item in
    the context menu.
  + On the phone app: Long press somewhere and the lat and long number
    appear in the search bar.
  + Latitude and longitude numbers can be negative and only one
    decimal number is enough.
# São Paulo / Brazil
#+begin_src yaml
lat: -23.5
lng: -46.6
#+end_src

* Darkman setup notes
** GTK & QT: Uniform look and live theme change
:PROPERTIES:
:CUSTOM_ID: orgid-tjunht
:END:

- To allow dynamic/live theme changes for running
  applications/programs, specially for Qt on minimal setups, see:
  + [[#orgid-tqgntk][Qt live theme change outside KDE]].

- The GTK setup is more straightforward and better supported outside
  of GNOME, see
  + [[#orgid-rzourk][GTK live theme change outside GNOME]]

- There's more settings done by the shell regarding this setup, see:
  + [[file:~/.config/shell/README.org::#orgid-twrkwj][shell: GTK & Qt: Uniform look & live theme change]]

*** Qt live theme change outside KDE
:PROPERTIES:
:CUSTOM_ID: orgid-tqgntk
:END:

- The Qt live theme change setup is divided in two:
  + [[#plasma-workspace-mothod-note][Plasma Workspace method]]
  + [[#qgnomeplatform-mothod-note][QGnomePlatform method]]

**** Plasma Workspace method
:PROPERTIES:
:CUSTOM_ID: plasma-workspace-mothod-note
:END:

This is the preferred and better supported method for live theme
changes with Qt.

Install the following packages to get KDE Plasma's functionality
outside of the DE:
- =plasma-workspace=: provides =plasma-apply-colorscheme= which allows for
  setting the env. var. ~QT_QPA_PLATFORMTHEME=kde~ and applying =kvantum=
  themes, (this package also provides =lookandfeeltool= but it doesn't
  seem to recognize kvantum themes).
- =kvantum=: Normally used by setting the
  env. var. =QT_STYLE_OVERRIDE=kvantum= but in this setup only the
  provided "=Kv*=" Qt themes are used, no overrides necessary.

Export the env. var. =QT_QPA_PLATFORMTHEME=kde=, this makes Qt apps (not
all though) use Plasma's backend leaving them susceptible to
=plasma-workspace='s CLI tools "=plasma-apply-colorscheme=" and
"=lookandfeeltool=" allowing live theme changes.

With a running Qt app running run the following command to see if it
changes the theme live:
: plasma-apply-colorscheme KvGnome
or
: plasma-apply-colorscheme KvGnomeDark
Note that when running from an environment that has a different or
unset =DISPLAY= or =WAYLAND_DISPLAY= env. var. the target Qt app may be
unreachable making it necessary to use the option "=--platform
offscreen=" (required when running from systemd for example), though
"=offscreen=" is not the only available choice, for a normal desktop
setup it should be enough.

**** QGnomePlatform method
:PROPERTIES:
:CUSTOM_ID: qgnomeplatform-mothod-note
:END:
Install the following packages:
- =qgnomeplatform-qt5=, =qgnomeplatform-qt6=, =qgnomeplatform-common=
  (provided by =qgnomeplatform= group package).
- =adwaita-qt5=, =adwaita-qt6=: dependencies for =qgnomeplatform=.
 # * =qt5-wayland= and =qt6-wayland= should be pulled by packages as
 #   dependencies.
Though [[https://github.com/FedoraQt/QGnomePlatform?tab=readme-ov-file#qgnomeplatform-project-is-unmaintained-a-no-longer-actively-developed][QGnomePlatform isn't maintained anymore]] it works for Qt apps
that are older and/or that only expect theme settings from a config
file or env. var. It should work when apps won't respect
~QT_QPA_PLATFORMTHEME=kde~ for live changes. Note that since it requires
the same env. var. as the [[#plasma-workspace-mothod-note][Plasma Workspace method]] but with the value
~QT_QPA_PLATFORMTHEME=gnome~ instead, unfortunately apps that will only
live change with QGnomePlatform need to be wrapped manually, providing
~QT_QPA_PLATFORMTHEME=gnome~.
- To make sure the wrappers take precedence over the main ~PATH~
  binaries and remain isolated not polluting any other directory in
  PATH, create a new one
  e.g. =~/.local/share/qt-platform-theme-wrappers/= and;
  + *NOTE*: This directory /cannot/ be inside another one already in
    PATH. For example if "=~/.local/bin=" is in PATH using
    "=~/.local/bin/qt-wrappers=" won't work because when the shell
    indexes executables from "=~/.local/bin=" into =hash= any other
    executable inside it will /NOT/ take precedence over other
    executables exclusively on their own top-evel directory, even if
    it comes first in the PATH scalar list.
    # [2024-09-04 Wed 16:45:34 -03] @ak
- Place the wrappers there with contents e.g.:
  #+begin_src shell :tangle no :noweb-ref dummy
  #!/usr/bin/env bash
  QT_QPA_PLATFORMTHEME=gnome program "$@"
  #+end_src
  where the only thing that need to change across files will be the
  program name, in this example is "=picard=". The filename should be
  the same name as the program since it's supposed to take precedence
  over existing ones.
  + Note: The shebang can be dropped to let the current shell execute
    it instead, since it's just setting an env. var., and make sure
    it's executable (permissions 755/+x).
- Then /PREpend/ the directory =~/.local/share/qt-platform-theme-wrappers=
  to =PATH= by adding it prior in the list, specially before system
  directories, e.g.:
  : PATH=$HOME/.local/share/qt-platform-theme-wrappers:$PATH

- /Though cumbersome this method should only be necessary for a few
  applications./

  The reason for script wrappers instead of something like aliases is
  that this should also work with GUI program launchers such as
  dmenu-like launchers or Window Manager keybinds, though an extra
  step may be required for =.desktop= files but since this is a minimal
  setup the =.desktop= files are never really used.
  # [2024-09-04 Wed 11:01:44 -03] @ak

- See [[#orgid-jwzzky][QGnomePlatform environment variable wrappers]] for the tangled
  files.

*** GTK live theme change outside GNOME
:PROPERTIES:
:CUSTOM_ID: orgid-rzourk
:END:

Modern GTK apps should listen to =dconf='s key-based configuration
system which is a backend for =gsettings= but also works through a D-Bus
interface. For theming and color schemes it exposes the
schema/namespace "=org.gnome.desktop.interface=" which, among others,
stores the keys "=gtk-theme=" and "=color-scheme=".
- Get the current values with:
  : gsettings get org.gnome.desktop.interface gtk-theme
  : gsettings get org.gnome.desktop.interface color-scheme
- and to set new ones run e.g.:
  : gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
  : gsettings set org.gnome.desktop.interface color-scheme prefer-dark
  where the last argument's possible values are:
  + =gtk-theme=: a GTK theme name, which should be the same as a
    directory name from =/usr/share/themes/= or
    =~/.local/share/themes=.
  + =color-scheme=: one of =default=, =prefer-dark= or =prefer-dark=.

- Discover available schemas, keys and values for keys with:
  : gsettings list-schemas
  To list configurable schemas, optional flag =--print-paths=.

  : gsettings list-keys org.gnome.desktop.interface
  To list available configurable keys within schemas.

  : gsettings range org.gnome.desktop.interface color-scheme
  To list documented supported values from schema keys. This pulls
  documentation from XML files, in this case from
  =/usr/share/glib-2.0/schemas/org.gnome.desktop.interface.gschema.xml=.

- In case =gsettings= didn't work, see:
  + [[gsettings-not-working-note][GSettings not working note]]
  + [[xsettingsd-setup-note][XSETTINGS setup note]]

<<gsettings-not-working-note>>
If there's an issue where =gsettings= doesn't seem to set theme
settings, check if:
- GTK config files are present in =~/config/gtk-*= or =~/.gtkrc*=;
- The =GTK_THEME= environment variable is set.
- In case of GTK 4/libadwaita apps setting it may be necessary to
  the set the env. var. ~ADW_DISABLE_PORTAL=1~.
  See [[https://wiki.archlinux.org/title/GTK#GTK_3_and_GTK_4][ArchWiki/GTK#GTK 3 and GTK 4]].
These "hard" settings take precedence over =dconf= / =gsettings= / =D-Bus=
and prevent it from changing the theme live/on-demand.

<<xsettingsd-setup-note>>
For older GTK <3 programs XSETTINGS is used instead. To use XSETTINGS:
- Install =xsettingsd= for the most minimal (and manual) approach. This
  is the "=d="aemon for XSETTINGS and it reads settings from
  =~/.config/xsettingsd/xsettingsd.conf=. The theme option is:
  : Net/ThemeName "Adwaita-dark"
  where the string is a GTK theme name. For the live theme change
  effect, if e.g. the theme option =Net/ThemeName= in the config file
  has been changed to something else, to make =xsettingsd= pick up the
  new config file changes send a =-HUP= signal to it, e.g.:
  : killall -HUP xsettingsd
  or
  : pkill -HUP xsettingsd
  # [2024-09-04 Wed 15:15:12 -03] @ak
  + The signal "=HUP=" should be code "=1=" in "kill/send-signal"
    utilities.

- Note: even if =xsettingsd= is launched /after/ the GTK <3 application,
  launching it should then trigger the app to update to new changes.
- See
  + [[https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland][GTK 3 settings on Wayland · swaywm/sway Wiki]]
  + [[https://apple.stackexchange.com/questions/103610/what-does-hup-do-when-used-with-killall][macos - What does -HUP do when used with killall? - Ask Different]]
# [2023-06-04 Sun 09:49:26 -03]
*** Make GTK applications use KDE's (or other) file picker
Set the environment variable ~GTK_USE_PORTAL=1~, then if e.g. the
current desktop portal is =xdg-desktop-portal-kde= it should use
KDE's/Dolphin file picker.
- *NOTE*: Using ~GTK_USE_PORTAL=1~ may break how some GTK <3 apps read
  their settings making e.g. font rendering uglier. To fix this make
  sure =xdg-desktop-portal-gtk= is also installed to serve as fallback
  for them. The order of priority for =x-d-p= implementations /not/ always
  are overriden by the =portal.conf= file. See note in
  [[file:~/.config/xdg-desktop-portal/README.org::#orgid-uxoxxl][GTK apps lost font rendering, cursor theme or other settings]].

  An alternative to this is to use wrapper that set ~GTK_USE_PORTAL=1~
  for individual apps.

Another way to force a specific file picker from a desktop portal that
implements it is to e.g. set the option
~org.freedesktop.impl.portal.FileChooser=kde~ on
=~/.config/xdg-desktop-portal/portals.conf=. See an example:
[[file:~/.config/xdg-desktop-portal/README.org::#orgid-rhgutk][Hyprland-specific overrides]].
# [2024-09-06 Fri 20:14:08 -03] @ak

**** Application-specific settings to use XDG Desktop Portal
:PROPERTIES:
:CUSTOM_ID: orgid-sqomyz
:END:
Programs that provide settings to use the portal's file picker instead
of using environment variables or overrides in =portals.conf=.

***** Firefox
In =about:config= set =widget.use-xdg-desktop-portal.file-picker= to =1=.
# [2024-09-07 Sat 14:42:26 -03] @ak
- See
  + Example using a =user.js= file: [[file:~/.mozilla/README.org::#orgid-jryihm][firefox: XDG Desktop Portal integration]]
  + [[https://www.reddit.com/r/kde/comments/pz2y0m/comment/heyem8r/][#comment@r/kde/Firefox and GTK_USE_PORTAL=1 vs Firefox not detected as default browser]]
*** Blur with kvantum (specially Dolphin)
- [[https://github.com/tsujan/Kvantum/blob/master/Kvantum/INSTALL.md#desktop-environments][Kvantum/Kvantum/INSTALL.md at master · tsujan/Kvantum]]
- [[https://forum.endeavouros.com/t/transparencies-in-kvantum-eos-kde/56168/5][Transparencies in Kvantum EOS KDE - Desktop Environments / Plasma - EndeavourOS]]

Make sure to set /either/ kvantum-dark or qt6ct on =plasma-open-settings=
> =Colors & Thems= > =Application Style=.
# [2024-09-10 Tue 13:22:26 -03] @ak
*** pcmanfm-qt doesn't show icons
- [[https://forum.endeavouros.com/t/pcmanfm-qt-doesnt-show-icons/4854/8][Pcmanfm-qt doesn't show icons - Desktop Environments / Lxqt - EndeavourOS]]

install qt5ct/qt6ct and change icon there
# [2024-09-10 Tue 13:23:27 -03] @ak


** Making Darkman portal implementation work on minimal setups
:PROPERTIES:
:CUSTOM_ID: orgid-ohmzyr
:END:

- See
  + [[https://www.reddit.com/r/archlinux/comments/17bkz58/comment/kh51tnc/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button][Dark mode (darkman) and xdg-desktop-portal* driving me nuts : r/archlinux]]
  + Discussion: [[https://github.com/keepassxreboot/keepassxc/issues/9892][System theme not followed - sway · Issue #9892 · keepassxreboot/keepassxc]]
  + [[https://github.com/flatpak/xdg-desktop-portal/issues/1017#issuecomment-1731712470][Settings portals should not be provided unconditionally · Issue #1017 · flatpak/xdg-desktop-portal]]
  + [[https://darkman.whynothugo.nl/#DEBUGGING][darkman(1)#DEBUGGING]] example on how to get current "color-scheme"
    from the freedesktop bus, if it's working. See note below for why.
  + [[https://github.com/LionyxML/auto-dark-emacs/blob/045472a5a28a16216d4ec74f1382003e8f7d1cdc/auto-dark.el#L125][LionyxML/auto-dark-emacs/auto-dark.el#L125]]
  + [[https://man.archlinux.org/man/extra/xdg-desktop-portal/portals.conf.5.en][portals.conf(5) — Arch manual pages]]
  + Extra reference for the discussion on implementing overrides with
    =~/.config/xdg-desktop-portal/portals.conf=:
    * [[https://github.com/flatpak/xdg-desktop-portal/issues/906#issuecomment-1302217878][Issue #906 · flatpak/xdg-desktop-portal]]
    * [[https://github.com/flatpak/xdg-desktop-portal/pull/955][Pull Request #955 · flatpak/xdg-desktop-portal]]
  + [[https://wiki.archlinux.org/title/XDG_Desktop_Portal][XDG Desktop Portal - ArchWiki]]
  + [[https://dbus.freedesktop.org/doc/dbus-tutorial.html][D-Bus Tutorial]]
Desktop Environments standard for getting changes to the color scheme
is to use the D-Bus =org.freedesktop.portal.Desktop= with interface
=org.freedesktop.portal.Settings= provided by a =xdg-desktop-portal-*=
implementation and exposed by =xdg-desktop-portal=:
- Try running this command:
  #+begin_src shell :tangle no :noweb-ref dummy
  dbus-send --type=method_call --print-reply \
            --dest='org.freedesktop.portal.Desktop' \
            '/org/freedesktop/portal/desktop' \
            'org.freedesktop.portal.Settings.Read' \
            string:'org.freedesktop.appearance' \
            string:'color-scheme'
  #+end_src
  Example (working) output:
  #+begin_example
  method return time=1708524466.520474 sender=:1.265 -> destination=:1.268 serial=60 reply_serial=2
    variant       variant          uint32 2
  #+end_example
  + Where, in the last column after "variant", +afaik+:
    * 0 = light, being a fallback default;
    * 1 = dark;
    * 2 = light.
    * See a working example from [[https://github.com/LionyxML/auto-dark-emacs/blob/045472a5a28a16216d4ec74f1382003e8f7d1cdc/auto-dark.el#L224C53-L224C63][auto-dark-emacs]].
  But if the following error is returned:
  : Error org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
  instead of the variant information, the running =xdg-desktop-portal-*=
  implementation is not exposing the =org.freedesktop.portal.Settings=
  interface. Darkman provides an alternative for it but it needs to be
  enabled in the =portals.conf= file provided or read by the current
  =xdg-desktop-portal-*= implementation. For example when using Hyprland
  and the recommended =xdg-desktop-portal-hyprland= it by default won't
  read the =Settings= interface so after installing Hyprland's desktop
  portal, to make it read the D-Bus interface for color scheme
  changes, expose that interface explicitly in the =portal.conf= file
  read by the portal implementation:
  : org.freedesktop.impl.portal.Settings=darkman

- SOLUTION: create the file =~/.config/xdg-desktop-portal/portals.conf=
  with an override for =org.freedesktop.portal.Settings= that uses
  =darkman=:
  #+begin_src conf :tangle no :noweb-ref dummy
  [preferred]
  default=kde
  org.freedesktop.impl.portal.Settings=darkman
  #+end_src

* Darkman Scripts
:PROPERTIES:
:header-args:bash: :mkdirp yes :shebang #!/usr/bin/env bash :noweb no-export
:header-args:shell: :mkdirp yes :shebang #!/usr/bin/env sh :noweb no-export
:END:

# (mainly Wayland)

# update this se #TODO # [2024-02-22 Thu 23:11:48 -03] @ak
- There are two versions of every script. They usually share a header
  of helper functions and setup.

- Notes:
  + Darkman will hang on long running processes until that process
    exits or is sent to the background.

- The tangled scripts are at
  + [[file:~/.local/share/light-mode.d]]
  + [[file:~/.local/share/dark-mode.d]]

Helper functions for checking and setup
#+NAME: darkman-helper-functions
#+begin_src shell
check_file() {
    [ -f "$1" ] && return 0
    printf 'The file "%s" does not exist, aborting...\n' "$1"
    exit 1
}

check_cmd() {
    ! command -v "$1" > /dev/null && exit 1
}

running_check() {
    pgrep -ixU "$(id -u)" "$1" > /dev/null
}

running_check_killall() {
    running_check "$1" && killall "$1" --quiet
}
#+end_src

** GTK and Qt

- Light
#+begin_src shell :tangle (darkmandir "gtk-qt.sh") :theme light
gsettings set org.gnome.desktop.interface gtk-theme Adwaita
gsettings set org.gnome.desktop.interface color-scheme prefer-light

# icon theme too ?

# `--platform offscreen' is necessary since this script will be run by systemd
plasma-apply-colorscheme --platform offscreen KvGnome
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "gtk-qt.sh") :theme dark
gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
gsettings set org.gnome.desktop.interface color-scheme prefer-dark

plasma-apply-colorscheme --platform offscreen KvGnomeDark
#+end_src

*** QGnomePlatform environment variable wrappers
:PROPERTIES:
:tangle-dir: (expand-file-name "qt-platform-theme-wrappers" (xdg-data-home))
:header-args:bash: :tangle-mode o775 :mkdirp yes
:header-args:python: :tangle-mode o775 :mkdirp yes
:CUSTOM_ID: orgid-jwzzky
:END:

- picard: MusicBrainz Picard's launcher is just a Python script, NOTE:
  *do not* try to wrap the system provided one using a shell script or
  it will cause an infinite loop of processes spawning (though they do
  nothing). Instead set the environment variable in Python and just
  copy over rest of the launcher script.
  #+begin_src python :tangle (tdir "picard")
  #!/usr/bin/python3
  import os
  os.environ['QT_QPA_PLATFORMTHEME'] = 'gnome'

  # rest is the same from /usr/bin/picard:
  try:
      from picard.tagger import main
      main('/usr/share/locale', True)
  except SystemExit:
      raise  # Just continue with a normal application exit
  except:  # noqa: E722,F722 # pylint: disable=bare-except
      from picard import crash_handler
      crash_handler()
      raise
  #+end_src


** Dunst: Notification server
The themed versions of =dunstrc= are named =dunstrc-dark= and
=dunstrc-light= and should be present in the same directory.
#+NAME: dunst-setup
#+begin_src shell
«darkman-helper-functions»

check_cmd dunst

dunstrc="${XDG_CONFIG_HOME}"/dunst/dunstrc
dunstrcLight="${dunstrc}"-light
dunstrcDark="${dunstrc}"-dark

check_file "${dunstrcLight}"
check_file "${dunstrcDark}"

running_check_killall dunst
trap 'running_check dunst || dunst &' EXIT INT

override_dunstrc() {
    # use full path to cp to skip any aliases
    /usr/bin/cp --force "$1" "${dunstrc}"
}
#+end_src

- Light
#+begin_src shell :tangle (darkmandir "dunst.sh") :theme light
«dunst-setup»

override_dunstrc "${dunstrcLight}"
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "dunst.sh") :theme dark
«dunst-setup»

override_dunstrc "${dunstrcDark}"
#+end_src

** Mako: Notification daemon

- See [[file:~/.config/mako/README.org::#orgid-gnpzww][Theme (mode) settings]] for the mako modes the scripts change here

#+NAME: mako-setup
#+begin_src shell :tangle no
«darkman-helper-functions»

check_cmd mako
check_cmd busctl

# Using busctl directly since makoctl is a script and it's buggy 2024-09-04
mako_set_mode() {
    busctl --user call \
           org.freedesktop.Notifications \
           /fr/emersion/Mako \
           fr.emersion.Mako \
           -- \
           SetMode s "$1"
}

mako_reload() {
    busctl --user call org.freedesktop.Notifications /fr/emersion/Mako fr.emersion.Mako -- Reload
}

makoDir=${XDG_CONFIG_HOME}/mako

# mako themes
light=light-mode
dark=dark-mode

check_file "${makoDir}"/"${light}"
check_file "${makoDir}"/"${dark}"

mako_source_theme() {
    case "$1" in
        dark) themeFile="${dark}" ;;
        light) themeFile="${light}" ;;
    esac

    sed -E -i "s,^(include=)(~/.config/mako|${makoDir})/(${light}|${dark}),\1\2/${themeFile}," \
        "${makoDir}"/config
}

trap 'mako_reload' EXIT INT
#+end_src

- Light
#+begin_src shell :tangle (darkmandir "mako.sh") :theme light
«mako-setup»

mako_set_mode light
mako_source_theme light
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "mako.sh") :theme dark
«mako-setup»

mako_set_mode dark
mako_source_theme dark
#+end_src

** Wallpaper
# - =lightordark-wallpaper= is a script. Instead changed to using
# - Wayland-specific swaybg explicitly because the script wasn't
# - working # inside systemd.

#+NAME: wallpaper-setup
#+begin_src shell
«darkman-helper-functions»

check_cmd swaybg

running_check_killall swaybg
# swaybg --color '#eeeeee' &
swaybg_fork() {
    # Setting the wayland display because systemd would not recognize it otherwise. #TODO-Workarounds?
    WAYLAND_DISPLAY=wayland-1 swaybg --color "$@" &
    # IMPORTANT: fork this process because otherwise darkman will not
    # execute the other scripts, waiting for this one to finish.
}
#+end_src

- Light
#+begin_src shell :tangle (darkmandir "wallpaper.sh") :theme light
«wallpaper-setup»

swaybg_fork '#eeeeee'
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "wallpaper.sh") :theme dark
«wallpaper-setup»

swaybg_fork '#382738'
#+end_src

** Hyprland
:PROPERTIES:
:CUSTOM_ID: orgid-xivkrg
:END:
This method relies on an 'import' in =hyprland.conf=, a file containing
only relevant color theme definitions for border colors (and any other
customization made within Hyprland) is sourced so that any changes do
that file makes only those settings update. Instead of using the IPC
this makes changes last even if the configuration is reloaded, since
it sources a written file.

- The setup is:
  + =themes/= directory inside =$XDG_CONFIG_HOME/hypr=
  + =themes.conf= file containing /only/ a =source= to a standard dark or
    light filename, =00-dark-theme.conf= or =00-light-theme.conf=. e.g the
    line:
    : source = themes/00-light-theme.conf

  + both the =00-dark-theme.conf= or =00-light-theme.conf= files can
    contain either =hyprland.conf= settings directly or another =source=
    of a (final) specific theme.
  + Nesting sources like this, though more abstract, allows for easier
    maintanance/changing of themes with scripts.

Actual theming done & prepared withing Hyprland's directory.
#+NAME: hyprland-setup
#+begin_src shell
«darkman-helper-functions»

hyprDir=${XDG_CONFIG_HOME}/hypr
themeConfFile=${hyprDir}/themes/theme.conf

lightFile=00-light-theme.conf
darkFile=00-dark-theme.conf

check_file "${themeConfFile}"
check_file "${themeConfFile%/*}/${lightFile}"
check_file "${themeConfFile%/*}/${darkFile}"

hyprland_source_theme() {
    case "$1" in
        dark) themeFile=${darkFile} ;;
        light) themeFile=${lightFile} ;;
    esac

    sed -Ei "s,^source([[:blank:]]+|)=([[:blank:]]+|)(${lightFile}|${darkFile})$,source = ${themeFile}," "${themeConfFile}"
}
#+end_src

- Light
#+begin_src shell :tangle (darkmandir "/hyprland.sh") :theme light
«hyprland-setup»

hyprland_source_theme light
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "/hyprland.sh") :theme dark
«hyprland-setup»

hyprland_source_theme dark
#+end_src

** Eww
Setup that will be used in both scripts:
#+NAME: darkman-eww-mainbar-setup
#+begin_src shell
«darkman-helper-functions»


ewwDir=${XDG_CONFIG_HOME}/eww

# files containing css variables, the eww.scss file have to use them properly
light=light-colors.scss
dark=dark-colors.scss

# check if the scss files exist
check_file "${ewwDir}"/"${light}"
check_file "${ewwDir}"/"${dark}"

eww_scss_source_theme() {
    case "$1" in
        dark) themeFile="${dark}" ;;
        light) themeFile="${light}" ;;
    esac

    sed -i "s/^\(@import\) *\"\(${light}\|${dark}\)\".*/\1 \"${themeFile}\";/" \
        "${ewwDir}"/eww.scss
}
#+end_src

This approach uses a prepared =eww.scss= file with defined color
variables that have two versions, a light and a dark, separated into
two files. The one being used in the moment is sourced with a css
import, e.g.: =@import "light-colors.scss";=.

The scripts replace that line with the alternative.

- Light
#+begin_src shell :tangle (darkmandir "/eww-mainbar.sh") :theme light
«darkman-eww-mainbar-setup»

eww_scss_source_theme light
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "/eww-mainbar.sh") :theme dark
«darkman-eww-mainbar-setup»

eww_scss_source_theme dark
#+end_src

** Alacritty

Shared setup functions:
#+NAME: darkman-alacritty-colors-replace
#+begin_src shell :tangle no
replace_theme_import() {
    sed -i -E "s|^(import = \[ \"~/.config/alacritty/themes/)(.*)(\.toml.*)|\1$1\3|" \
        "$2"
}

replace_theme_import "${theme}" "${XDG_CONFIG_HOME}"/alacritty/alacritty.toml
#+end_src

- Light
Using toml import where =$theme= is the filename of them theme without
extension.
#+begin_src shell :tangle (darkmandir "/alacritty.sh") :theme light
theme=neron-light

«darkman-alacritty-colors-replace»
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "/alacritty.sh") :theme dark
theme=neron-dark

«darkman-alacritty-colors-replace»
#+end_src

** tofi

#+NAME: darkman-tofi-setup
#+begin_src shell
«darkman-helper-functions»

tofiDir=${XDG_CONFIG_HOME}/tofi

check_file "${tofiDir}"/config
check_file "${tofiDir}"/center-box

tofi_replace_include_theme() {
    cd "${tofiDir}" || exit 1
    sed -Ei 's/^(include=)((\.\/)?(center-box-|def-)).*/\1\2'$theme'/' config center-box
}
#+end_src

- Light
#+begin_src shell :tangle (darkmandir "/tofi.sh") :theme light
«darkman-tofi-setup»

theme=light

tofi_replace_include_theme
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "/tofi.sh") :theme dark
«darkman-tofi-setup»

theme=dark

tofi_replace_include_theme
#+end_src


** xsettingsd: XSETTINGS daemon
#+NAME: darkman-xsettingsd-setup
#+begin_src shell
«darkman-helper-functions»

xsettingsdConf=${XDG_CONFIG_HOME:-$HOME/.config}/xsettingsd/xsettingsd.conf

check_file "${xsettingsdConf}"

trap 'running_check xsettingsd && killall -HUP xsettingsd' EXIT INT
#+end_src

- Light
#+begin_src shell :tangle (darkmandir "/xsettingsd.sh") :theme light
«darkman-xsettingsd-setup»

themeName=Adwaita

sed -i "s|^\(Net/ThemeName\).*|\1 \"${themeName}\"|" "${xsettingsdConf}"
#+end_src

- Dark
#+begin_src shell :tangle (darkmandir "/xsettingsd.sh") :theme dark
«darkman-xsettingsd-setup»

themeName=Adwaita-dark

sed -i "s|^\(Net/ThemeName\).*|\1 \"${themeName}\"|" "${xsettingsdConf}"
#+end_src
