---
galaxy_info:
  role_name: containers
  author: Ansible User
  description: Configure rootless Podman containers on Raspberry Pi OS
  company:
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - containers
    - podman
    - podman-compose
    - rootless
    - raspberry-pi
