# Theme & Icon theme

# [[file:README.org::*Theme & Icon theme][Theme & Icon theme:1]]
Net/ThemeName "Adwaita-dark"

Net/IconThemeName "Papirus"
Gtk/CursorThemeName "simp1e-amber"
# Theme & Icon theme:1 ends here

# Font config

# [[file:README.org::*Font config][Font config:1]]
Xft/Antialias 1
Xft/HintStyle "hintfull"
Xft/Hinting 1
Xft/RGBA "rgb"

# Values other than "none" makes GDK fonts look horrible, at least for me.
# Set lcddefault on 'Xresources' and/or 'fontconfig/fonts.conf' instead.
Xft/lcdfilter "none"
# Font config:1 ends here

# Sounds

# [[file:README.org::*Sounds][Sounds:1]]
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
# Sounds:1 ends here
