# Theme & Icon theme

# [[file:README.org::*Theme & Icon theme][Theme & Icon theme:1]]
Net/ThemeName "Adwaita"
# Theme & Icon theme:1 ends here



# # bogs out with new GTK sutff [2022-04-11 Mon 04:09:36]
# # Net/IconThemeName "hicolor"
# # Net/IconThemeName "Adwaita"

#   =Xft/DPI 100352=
#   DPI = (Width*Height) / (Screen Inch Size, e.g. 24)
#   =Xft/DPI 155217=
#   =Xft/DPI 116412=
#   =Xft/DPI 117651=
#   =Xft/DPI 156868=

# [[file:README.org::*Theme & Icon theme][Theme & Icon theme:2]]
Xft/Antialias 1
Xft/HintStyle "hintfull"
Xft/Hinting 1
Xft/RGBA "none"

# Values other than "none" makes GDK fonts look horrible, at least for me.
# Set lcddefault on 'Xresources' and/or 'fontconfig/fonts.conf' instead.
Xft/lcdfilter "none"
# Theme & Icon theme:2 ends here
