[colors.primary]
background = "#ffffff"
bright_foreground = "#8f8c8c"
foreground = "#5a5d5c"

[colors.normal]
black = "#5a5d5c"
blue = "#1e5ca8" # #0656c6
cyan = "#006861"
green = "#316900"
magenta = "#b30071"
red = "#ba0d0d"
white = "#5e5c5a"
yellow = "#755800"

[colors.bright] # halved so 3.33
black = "#908c8c"
blue = "#4c8ee5"
cyan = "#009d9d"
green = "#49a000" # "#1c6b00"
magenta = "#ff30b0"
red = "#f35656"
white = "#8f8c8c"
yellow = "#b28600"

[colors.dim] # 6.16
black = "#5c6360"
blue = "#1f61b2"
cyan = "#006e63"
green = "#326f00" # "#529f05" # #376647
magenta = "#bc0078"
red = "#c40d0e"
white = "#636160"
yellow = "#7b5d00"


[colors.cursor]
cursor = "#3d5a9e"
text = "#ffffff"

[colors.selection]
background = "#5a30f3"
text = "#ffffff"
