#+TITLE: Firefox configurable files

# [2024-03-01 Fri 03:14:16 -03] @ak

* user.js
:PROPERTIES:
:header-args:typescript: :tangle firefox-user.js
:END:

The =user.js= can easily be transferred between backups. It is a file
override of settings from =about:config=.

Since Firefox really doesn't like having a custom profile folder
(though one can be set, see [[#orgid-kjzvnx][Set custom profile directory]]), this file
will remain here stored. It will need to be moved/copied/linked to
inside the current profile folder manually.

Link to appropriate place e.g.
: ln -sf ~/.mozilla/firefox-user.js ~/.mozilla/firefox/profile-folder/user.js

- See this readme for more info on user.js
  + [[https://github.com/pyllyukko/user.js][GitHub - pyllyukko/user.js: user.js -- Firefox configuration hardening]]

** Disable alt menu
#+begin_src typescript
user_pref("ui.key.menuAccessKeyFocuses", false);
#+end_src

** Wayland libva VA-API NVIDIA video decode
#+begin_src typescript
user_pref("media.ffmpeg.vaapi.enabled", true);
user_pref("media.hardware-video-decoding.force-enabled", true);
user_pref("media.rdd-ffmpeg.enabled", true);
user_pref("media.av1.enabled", true); // You may skip this if your GPU does not support AV1
user_pref("gfx.x11-egl.force-enabled", true);
user_pref("widget.dmabuf.force-enabled", true);
#+end_src

** UI
- also enable options from https://github.com/Bali10050/FirefoxCSS/blob/main/user.js
- https://www.reddit.com/r/FirefoxCSS/comments/myc578/svg_icon_contextfill_resolves_to_black/
#+begin_src typescript
// enable userChrome.css
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("svg.context-properties.content.enabled", true);
user_pref("layout.css.has-selector.enabled", true);
#+end_src

** XDG Desktop Portal integration
:PROPERTIES:
:CUSTOM_ID: orgid-jryihm
:END:
- See
  + [[file:~/.config/darkman/README.org::#orgid-sqomyz][Application-specific settings to use XDG Desktop Portal]]
    # linked here
#+begin_src typescript
user_pref("widget.use-xdg-desktop-portal.file-picker", 1);
user_pref("widget.use-xdg-desktop-portal.location", 1);
user_pref("widget.use-xdg-desktop-portal.mime-handler", 1);
user_pref("widget.use-xdg-desktop-portal.open-uri", 1);
user_pref("widget.use-xdg-desktop-portal.settings", 1);
#+end_src

** Performance
- *NOTE*: =dom.ipc.processCount.extension= set to more than 1 (default)
  disables extensions.
  + See
    * [[https://bugzilla.mozilla.org/show_bug.cgi?id=1419341][1419341 - Firefox web extensions disabled by dom.ipc.processCount.extension > 1]]
    * [[https://searchfox.org/mozilla-central/rev/919dce54f43356c22d6ff6b81c07ef412b1bf933/toolkit/components/extensions/Extension.jsm#1047-1049][Extension.jsm - mozsearch]]
#+begin_src typescript
user_pref("gfx.webrender.all", true);
user_pref("browser.preferences.defaultPerformanceSettings.enabled", false);
// setting all the following dom.ipc to higher values made a noticeable difference
user_pref("dom.ipc.processCount", 8); // was 8 by default
user_pref("dom.ipc.processCount.extension", 1); // default is 1 and CANNOT be changed otherwise it will disable extensions.
user_pref("dom.ipc.processCount.file", 8); // was 1
user_pref("dom.ipc.processCount.privilegedabout", 8); // was 1
user_pref("dom.ipc.processCount.privilegedmozilla", 8); // was 1
user_pref("dom.ipc.processCount.webIsolated", 8); // was 4

// store cache in xdg_runtime_dir's tmpfs
user_pref("browser.cache.disk.parent_directory", "/run/user/1000/firefox"); // update UID if it's not 1000
user_pref("browser.sessionstore.interval", 60000); // in milliseconds
#+end_src

** Custom Defaults
#+begin_src typescript
user_pref("browser.startup.page", 3);  // 3 = Open previous windows and tabs
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.preferences.defaultPerformanceSettings.enabled", false);
user_pref("layers.acceleration.disabled", false);
#+end_src

** Zen user.js
imported from zen's user.js
#+begin_src typescript
user_pref("app.normandy.api_url", "");
user_pref("app.update.checkInstallTime", false);
user_pref("app.update.disabledForTesting", true);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.newtabpage.activity-stream.asrouter.providers.cfr", "null");
user_pref("browser.newtabpage.activity-stream.asrouter.providers.cfr-fxa", "null");
user_pref("browser.newtabpage.activity-stream.asrouter.providers.message-groups", "null");
user_pref("browser.newtabpage.activity-stream.asrouter.providers.messaging-experiments", "null");
user_pref("browser.newtabpage.activity-stream.asrouter.providers.snippets", "null");
user_pref("browser.newtabpage.activity-stream.asrouter.providers.whats-new-panel", "null");
user_pref("browser.newtabpage.activity-stream.discoverystream.config", "[]");
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.system.topstories", false);
user_pref("browser.newtabpage.activity-stream.fxaccounts.endpoint", "");
user_pref("browser.newtabpage.activity-stream.tippyTop.service.endpoint", "");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
// user_pref("browser.startup.page", 0);
user_pref("browser.uitour.enabled", false);
user_pref("browser.warnOnQuit", false);
user_pref("browser.webapps.checkForUpdates", 0);
user_pref("datareporting.healthreport.documentServerURI", "http://%(server)s/dummy/healthreport/");
user_pref("datareporting.healthreport.logging.consoleEnabled", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("datareporting.healthreport.service.firstRun", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyBypassNotification", true);
user_pref("devtools.console.stdout.chrome", true);
user_pref("dom.ipc.reportProcessHangs", false);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
// user_pref("focusmanager.testmode", true);
user_pref("general.useragent.updates.enabled", false);
user_pref("geo.provider.testing", true);
user_pref("geo.wifi.scan", false);
user_pref("hangmonitor.timeout", 0);
user_pref("idle.lastDailyNotification", -1);
user_pref("marionette.port", 0);
user_pref("media.gmp-manager.updateEnabled", false);
user_pref("media.sanity-test.disabled", true);
user_pref("network.manage-offline-status", false);
user_pref("network.sntp.pools", "%(server)s");
user_pref("remote.active-protocols", 1);
user_pref("remote.log.level", "Info");
user_pref("security.certerrors.mitm.priming.enabled", false);
user_pref("services.settings.server", "data:,#remote-settings-dummy/v1");
// user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("toolkit.startup.max_resumed_crashes", -1);
#+end_src




* User css
- See
  + [[https://firefoxcss-store.github.io/][FirefoxCSS Store]]
  + [[https://www.userchrome.org/][userChrome.css for Customizing Firefox]]
  + [[https://www.userchrome.org/what-is-userchrome-css.html][What is userChrome.css? What can it do?]]
  + [[https://www.userchrome.org/how-create-userchrome-css.html][How to Create a userChrome.css File]]
  + [[https://www.reddit.com/r/FirefoxCSS/comments/myc578/svg_icon_contextfill_resolves_to_black/][svg icon context-fill resolves to black : r/FirefoxCSS]]
  + [[https://mrotherguy.github.io/ToyfoCSS/][ToyfoCSS - CSS Intro]]

Setup for css
: cd ~/.mozilla
: ln -sf ../../chromecss-default firefox/profile-folder/chrome
: ln -sf jarnotmaciej-essence-firefoxcss chromecss-default
so only =chromecss-default= has to be changed.

- NOTE: if =chrome= was a link already give =ln= the =-T= flag.

* Firefox Notes
# moved from arch-linux.org # [2024-03-01 Fri 03:18:06 -03] @ak
** Get current profile directory
Go to the page =about:support= on Firefox, down in the table there is a
row named =Profile Directory= with the directory path.

** Set custom profile directory
:PROPERTIES:
:CUSTOM_ID: orgid-kjzvnx
:END:
- See
  [[*Get current profile directory][Get current profile directory]]
  [[https://support.mozilla.org/en-US/questions/1196116][is it possible to change the location of the FF profile folder? - Mozilla Support]]

The command
: firefox --profile /path/to/profiledir
allow Firefox to use a custom profile. If it complains about using an
older Firefox version with a profile from a newer version the flag
=--allow-downgrade= can also be used.

Having a profile directory backed-up, to continue using it, setting it
as default:
- Go to page: =about:profiles=
- "=Create a New Profile=";
  + choose a name for the profile;
  + click =Choose Folder...= and point to the backed-up profile dir.

This can also be used for renaming a profile directory.

** user.js vs autoconfig.js aka userChrome.js
- [[https://www.reddit.com/r/FirefoxCSS/comments/x04k1b/what_is_the_difference_between_userjs_and/][What is the difference between user.js and userChrome.js? : r/FirefoxCSS]]
# [2024-08-30 Fri 12:30:23 -03] @ak

=user.js= is for =user_pref=. =autoconfig.js= is for injection.

** Recommendations
- [[https://github.com/arkenfox/user.js/wiki/4.1-Extensions][4.1 Extensions · arkenfox/user.js Wiki]]
  # [2026-03-13 Fri 18:55:55 -03] @ak

* TODO AutoConfig                                         :ignore:noexport:
:PROPERTIES:
:header-args:typescript: :tangle no
:END:

- https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig

Set up firefox to read a js file called =custom-firefox.cfg= placed at
the top level of the installation directory:
# #+begin_src typescript :tangle /usr/lib/firefox/defaults/pref/autoconfig.js
pref("general.config.filename", "11xx-custom-firefox.cfg");
pref("general.config.obscure_value", 0);
#+end_src


# #+begin_src typescript :tangle /usr/lib/firefox/11xx-custom-firefox.cfg
// IMPORTANT: Start your code on the 2nd line
let { classes: Cc, interfaces: Ci, manager: Cm  } = Components;
const {Services} = Components.utils.import('resource://gre/modules/Services.jsm');
function ConfigJS() { Services.obs.addObserver(this, 'chrome-document-global-created', false); }
ConfigJS.prototype = {
  observe: function (aSubject) { aSubject.addEventListener('DOMContentLoaded', this, {once: true}); },
  handleEvent: function (aEvent) {
    let document = aEvent.originalTarget;
    let window = document.defaultView;
    let location = window.location;
    if (/^(chrome:(?!\/\/(global\/content\/commonDialog|browser\/content\/webext-panels)\.x?html)|about:(?!blank))/i.test(location.href)) {
      if (window._gBrowser) {
        let keys = ["key_close","key_closeWindow"];
        for (var i=0; i < keys.length; i++) {
          let keyCommand = window.document.getElementById(keys[i]);
          if (keyCommand != undefined) {
            keyCommand.removeAttribute("command");
            keyCommand.removeAttribute("key");
            keyCommand.removeAttribute("modifiers");
            keyCommand.removeAttribute("oncommand");
            keyCommand.removeAttribute("data-l10n-id");
          }
        }
      }
    }
  }
};
#+end_src

