---
gak_prowlarr_dir: "{{ ansible_facts['user_dir'] }}/services/prowlarr"
# Image release metadata: 2.3.5.5327-ls144
gak_prowlarr_image: lscr.io/linuxserver/prowlarr@sha256:b4204e18666179472225935b443a99cf6c66dcb7bbc2d35034427a3851f13135
gak_prowlarr_port: 8888
